In [2]:
import sys
import pandas as pd

sys.path.append("/var/www/python/Qingcheng/nighthawk/")
from nighthawk.util import sql_functions
from nighthawk.data.pipeline.common_functions.load import Load
from nighthawk.data.pipeline.common_functions.wind import Wind
from nighthawk.data.pipeline.common_functions.solar import Solar
from nighthawk.data.pipeline.common_functions.genoutage import GenOutage
from nighthawk.data.pipeline.var_handler.fuel_type import FuelType

START = "2026-04-01"
END   = "2026-04-01"
BAA_ZONES = ["E", "W"]

load     = Load("SPP")
wind     = Wind("SPP")
solar    = Solar("SPP")
genout   = GenOutage("SPP")
fueltype = FuelType("SPP")
print(f"Objects created for SPP  |  {START} → {END}")

Objects created for SPP  |  2026-04-01 → 2026-04-01

## 1. Total Load

In [2]:
df_total = load.get_total_load(START, END, var_spec=['f', 'a'])
print(df_total.shape)
df_total

(24, 4)

            dt  hr  spp_load_total_forecast_f  spp_load_total_actual_a
0   2026-04-01   1                    32440.0                  30110.0
1   2026-04-01   2                    31585.0                  31552.0
2   2026-04-01   3                    31124.0                  30860.0
3   2026-04-01   4                    30883.0                  30524.0
4   2026-04-01   5                    31120.0                  30709.0
5   2026-04-01   6                    32023.0                  31673.0
6   2026-04-01   7                    33790.0                  33342.0
7   2026-04-01   8                    35016.0                  34568.0
8   2026-04-01   9                    35513.0                  35212.0
9   2026-04-01  10                    35851.0                  35849.0
10  2026-04-01  11                    36356.0                  36323.0
11  2026-04-01  12                    36814.0                  36720.0
12  2026-04-01  13                    37247.0                  36997.0
13  2026-04-01  14                    37877.0                  37170.0
14  2026-04-01  15                    38289.0                  37311.0
15  2026-04-01  16                    38766.0                  37475.0
16  2026-04-01  17                    39267.0                  37785.0
17  2026-04-01  18                    39499.0                  37907.0
18  2026-04-01  19                    39288.0                  37920.0
19  2026-04-01  20                    38807.0                  37772.0
20  2026-04-01  21                    38370.0                  37816.0
21  2026-04-01  22                    37430.0                  36992.0
22  2026-04-01  23                    35670.0                  35368.0
23  2026-04-01  24                    33618.0                  33771.0

## 2. BAA Zonal Load (E and W)

In [3]:
df_baa = load.get_baa_zonal_load(START, END, baa_zones=BAA_ZONES, var_spec=['f', 'a'])
print(df_baa.shape)
df_baa

(48, 5)

,dt,hr,baa_zone,spp_baa_zonal_load_forecast_f,spp_baa_zonal_load_actual_a
0,2026-04-01,1,E,29713.0,27477.0
1,2026-04-01,1,W,2727.0,2633.0
2,2026-04-01,2,E,28966.0,29008.0
3,2026-04-01,2,W,2619.0,2544.0
4,2026-04-01,3,E,28563.0,28359.0
5,2026-04-01,3,W,2561.0,2501.0
6,2026-04-01,4,E,28340.0,28048.0
7,2026-04-01,4,W,2543.0,2476.0
8,2026-04-01,5,E,28571.0,28264.0
9,2026-04-01,5,W,2549.0,2445.0
10,2026-04-01,6,E,29422.0,29175.0
11,2026-04-01,6,W,2601.0,2498.0
12,2026-04-01,7,E,31084.0,30732.0
13,2026-04-01,7,W,2706.0,2610.0
14,2026-04-01,8,E,32134.0,31813.0
15,2026-04-01,8,W,2882.0,2755.0
16,2026-04-01,9,E,32550.0,32315.0
17,2026-04-01,9,W,2963.0,2897.0
18,2026-04-01,10,E,32893.0,32945.0
19,2026-04-01,10,W,2958.0,2904.0
20,2026-04-01,11,E,33413.0,33421.0
21,2026-04-01,11,W,2943.0,2902.0
22,2026-04-01,12,E,33870.0,33837.0
23,2026-04-01,12,W,2944.0,2883.0
24,2026-04-01,13,E,34342.0,34124.0
25,2026-04-01,13,W,2905.0,2873.0
26,2026-04-01,14,E,34992.0,34328.0
27,2026-04-01,14,W,2885.0,2842.0
28,2026-04-01,15,E,35380.0,34488.0
29,2026-04-01,15,W,2909.0,2823.0
30,2026-04-01,16,E,35858.0,34485.0
31,2026-04-01,16,W,2908.0,2795.0
32,2026-04-01,17,E,36311.0,NaN
33,2026-04-01,17,W,2956.0,NaN
34,2026-04-01,18,E,36494.0,NaN
35,2026-04-01,18,W,3005.0,NaN
36,2026-04-01,19,E,36215.0,NaN
37,2026-04-01,19,W,3073.0,NaN
38,2026-04-01,20,E,35684.0,NaN
39,2026-04-01,20,W,3123.0,NaN
40,2026-04-01,21,E,35193.0,NaN
41,2026-04-01,21,W,3177.0,NaN
42,2026-04-01,22,E,34270.0,NaN
43,2026-04-01,22,W,3160.0,NaN
44,2026-04-01,23,E,32611.0,NaN
45,2026-04-01,23,W,3059.0,NaN
46,2026-04-01,24,E,30799.0,NaN
47,2026-04-01,24,W,2819.0,NaN

## 3. Broadzonal Load

In [4]:
df_broadzonal = load.get_broadzonal_load(START, END, var_spec=['f', 'a'])
print(df_broadzonal.shape)
df_broadzonal

(72, 5)

,dt,hr,broadzone,spp_broadzonal_load_forecast_f,spp_broadzonal_load_actual_a
0,2026-04-01,1,NORTH,7650.74,7650.74
1,2026-04-01,1,SOUTH,21333.99,21333.99
2,2026-04-01,1,WEST,0.00,0.00
3,2026-04-01,2,NORTH,7579.01,7579.01
4,2026-04-01,2,SOUTH,20855.13,20855.13
...,...,...,...,...,...
67,2026-04-01,23,SOUTH,24017.62,NaN
68,2026-04-01,23,WEST,0.00,NaN
69,2026-04-01,24,NORTH,7796.01,NaN
70,2026-04-01,24,SOUTH,22593.36,NaN
71,2026-04-01,24,WEST,0.00,NaN

## 4. Zonal Load

In [5]:
df_zonal = load.get_zonal_load(START, END, var_spec=['f', 'a'])
print(df_zonal.shape)
df_zonal

/var/www/python/Prod/nighthawk/nighthawk/data/pipeline/common_functions/load.py:1588: UserWarning: No zonal load forecast available for zone(s) ['PSCO', 'WACM', 'WAUW']; using actual load as forecast.
  warnings.warn(

(480, 5)

             dt  hr  zone  spp_zonal_load_forecast_f  spp_zonal_load_actual_a
0    2026-04-01   1  CSWS                    4658.57                  4658.57
1    2026-04-01   1   EDE                     448.35                   448.35
2    2026-04-01   1  GRDA                     987.37                   987.37
3    2026-04-01   1  INDN                      79.79                    79.79
4    2026-04-01   1  KACY                     218.90                   218.90
..          ...  ..   ...                        ...                      ...
475  2026-04-01  24  WACM                        NaN                      NaN
476  2026-04-01  24  WAUE                    3911.98                      NaN
477  2026-04-01  24  WAUW                        NaN                      NaN
478  2026-04-01  24  WFEC                     977.51                      NaN
479  2026-04-01  24    WR                    3149.16                      NaN

[480 rows x 5 columns]

## 5. Reserve Zonal Load

In [6]:
df_res = load.get_res_zonal_load(START, END, var_spec=['f', 'a'])
print(df_res.shape)
df_res

(144, 5)

,dt,hr,ReserveZone,spp_res_zonal_load_forecast_f,spp_res_zonal_load_actual_a
0,2026-04-01,1,1,3660.03,3660.03
1,2026-04-01,1,2,657.00,657.00
2,2026-04-01,1,3,4096.22,4096.22
3,2026-04-01,1,4,16580.77,16580.77
4,2026-04-01,1,5,3990.71,3990.71
...,...,...,...,...,...
139,2026-04-01,24,2,680.42,NaN
140,2026-04-01,24,3,4173.73,NaN
141,2026-04-01,24,4,17739.21,NaN
142,2026-04-01,24,5,3911.98,NaN
143,2026-04-01,24,21,NaN,NaN

## 6. Load Error

In [103]:
df_load_error = load.get_load_error(START, END, var_spec=['f', 'a'])
print(df_load_error.shape)
df_load_error

(24, 4)

            dt  hr  spp_load_error_f  spp_load_error_a
0   2026-04-01   1         -75.89660           -2330.0
1   2026-04-01   2        -145.97000             -33.0
2   2026-04-01   3        -116.74600            -264.0
3   2026-04-01   4         -80.73860            -359.0
4   2026-04-01   5        -117.05800            -411.0
5   2026-04-01   6         156.23500            -350.0
6   2026-04-01   7         228.36400            -448.0
7   2026-04-01   8         186.54900            -448.0
8   2026-04-01   9          26.12560            -301.0
9   2026-04-01  10         -41.49000              -2.0
10  2026-04-01  11         -93.29190             -33.0
11  2026-04-01  12         -36.79660             -94.0
12  2026-04-01  13           6.20715            -250.0
13  2026-04-01  14           8.79481            -707.0
14  2026-04-01  15          84.15330            -978.0
15  2026-04-01  16          72.89820           -1291.0
16  2026-04-01  17         387.72500           -1482.0
17  2026-04-01  18         218.38800           -1592.0
18  2026-04-01  19         263.02100           -1368.0
19  2026-04-01  20         231.58500           -1035.0
20  2026-04-01  21         123.80700            -554.0
21  2026-04-01  22         109.20100            -438.0
22  2026-04-01  23          79.88970            -302.0
23  2026-04-01  24           6.28078             153.0

## 7. BAA Zonal Load Error (E and W)

In [8]:
df_baa_error = load.get_baa_zonal_load_error(START, END, baa_zones=BAA_ZONES, var_spec=['f', 'a'])
print(df_baa_error.shape)
df_baa_error

(48, 5)

/var/www/python/Prod/nighthawk/nighthawk/data/pipeline/common_functions/load.py:2150: UserWarning: No model-predicted BAA-zonal load error forecast available for zone(s) ['W']; using actual load error as forecast.
  warnings.warn(

,dt,hr,baa_zone,spp_baa_zonal_load_error_a,spp_baa_zonal_load_error_f
0,2026-04-01,1,E,-2236.0,-158.31000
1,2026-04-01,1,W,-94.0,-94.00000
2,2026-04-01,2,E,42.0,-203.91600
3,2026-04-01,2,W,-75.0,-75.00000
4,2026-04-01,3,E,-204.0,-204.09600
5,2026-04-01,3,W,-60.0,-60.00000
6,2026-04-01,4,E,-292.0,-141.91500
7,2026-04-01,4,W,-67.0,-67.00000
8,2026-04-01,5,E,-307.0,-179.26300
9,2026-04-01,5,W,-104.0,-104.00000
10,2026-04-01,6,E,-247.0,143.59000
11,2026-04-01,6,W,-103.0,-103.00000
12,2026-04-01,7,E,-352.0,197.03500
13,2026-04-01,7,W,-96.0,-96.00000
14,2026-04-01,8,E,-321.0,131.98600
15,2026-04-01,8,W,-127.0,-127.00000
16,2026-04-01,9,E,-235.0,63.54950
17,2026-04-01,9,W,-66.0,-66.00000
18,2026-04-01,10,E,52.0,-72.55100
19,2026-04-01,10,W,-54.0,-54.00000
20,2026-04-01,11,E,8.0,-193.79400
21,2026-04-01,11,W,-41.0,-41.00000
22,2026-04-01,12,E,-33.0,-129.17100
23,2026-04-01,12,W,-61.0,-61.00000
24,2026-04-01,13,E,-218.0,-85.92140
25,2026-04-01,13,W,-32.0,-32.00000
26,2026-04-01,14,E,-664.0,-88.25000
27,2026-04-01,14,W,-43.0,-43.00000
28,2026-04-01,15,E,-892.0,37.18520
29,2026-04-01,15,W,-86.0,-86.00000
30,2026-04-01,16,E,-1373.0,8.10015
31,2026-04-01,16,W,-113.0,-113.00000
32,2026-04-01,17,E,NaN,265.16700
33,2026-04-01,17,W,NaN,NaN
34,2026-04-01,18,E,NaN,167.45300
35,2026-04-01,18,W,NaN,NaN
36,2026-04-01,19,E,NaN,197.94100
37,2026-04-01,19,W,NaN,NaN
38,2026-04-01,20,E,NaN,193.51700
39,2026-04-01,20,W,NaN,NaN
40,2026-04-01,21,E,NaN,56.61560
41,2026-04-01,21,W,NaN,NaN
42,2026-04-01,22,E,NaN,11.54570
43,2026-04-01,22,W,NaN,NaN
44,2026-04-01,23,E,NaN,39.52530
45,2026-04-01,23,W,NaN,NaN
46,2026-04-01,24,E,NaN,-150.98900
47,2026-04-01,24,W,NaN,NaN

---
## WIND

### 8. Total Wind

In [3]:
df_wind_total = wind.get_total_wind(START, END, var_spec=['f', 'a'])
print(df_wind_total.shape)
df_wind_total

(24, 4)

            dt  hr  spp_wind_total_forecast_f  spp_wind_total_actual_a
0   2026-04-01   1                   19661.68                 17018.20
1   2026-04-01   2                   18941.02                 16073.57
2   2026-04-01   3                   18526.22                 15514.78
3   2026-04-01   4                   18392.06                 14693.56
4   2026-04-01   5                   18447.30                 13884.95
5   2026-04-01   6                   18251.26                 13138.94
6   2026-04-01   7                   17755.26                 12729.71
7   2026-04-01   8                   17281.17                 11809.35
8   2026-04-01   9                   16633.53                  9874.16
9   2026-04-01  10                   16403.86                  8009.48
10  2026-04-01  11                   17154.66                  7061.17
11  2026-04-01  12                   18484.05                  6885.44
12  2026-04-01  13                   20099.78                  7508.45
13  2026-04-01  14                   21484.89                  9344.62
14  2026-04-01  15                   22766.49                 11324.18
15  2026-04-01  16                   24159.63                 13980.73
16  2026-04-01  17                   25247.81                 15484.05
17  2026-04-01  18                   25709.12                 15125.89
18  2026-04-01  19                   25788.08                 15387.12
19  2026-04-01  20                   25905.19                 15893.35
20  2026-04-01  21                   26462.58                 16819.22
21  2026-04-01  22                   27181.59                 18486.04
22  2026-04-01  23                   28076.37                 18787.17
23  2026-04-01  24                   26422.09                 19292.60

### 9. BAA Zonal Wind (E and W)

In [4]:
df_wind_baa = wind.get_baa_zonal_wind(START, END, baa_zones=BAA_ZONES, var_spec=['f', 'a'])
print(df_wind_baa.shape)
df_wind_baa

(48, 5)

,dt,hr,baa_zone,spp_baa_zonal_wind_forecast_f,spp_baa_zonal_wind_actual_a
0,2026-04-01,1,E,18820.52,16197.00
1,2026-04-01,1,W,841.16,821.20
2,2026-04-01,2,E,18101.49,15325.80
3,2026-04-01,2,W,839.53,747.77
4,2026-04-01,3,E,17711.71,14835.12
5,2026-04-01,3,W,814.51,679.66
6,2026-04-01,4,E,17604.79,14035.19
7,2026-04-01,4,W,787.27,658.37
8,2026-04-01,5,E,17679.20,13225.89
9,2026-04-01,5,W,768.10,659.06
10,2026-04-01,6,E,17492.74,12491.20
11,2026-04-01,6,W,758.52,647.74
12,2026-04-01,7,E,17002.22,12092.82
13,2026-04-01,7,W,753.04,636.89
14,2026-04-01,8,E,16545.44,11198.60
15,2026-04-01,8,W,735.73,610.75
16,2026-04-01,9,E,15917.99,9254.99
17,2026-04-01,9,W,715.54,619.17
18,2026-04-01,10,E,15698.94,7438.47
19,2026-04-01,10,W,704.92,571.01
20,2026-04-01,11,E,16442.00,6474.50
21,2026-04-01,11,W,712.66,586.67
22,2026-04-01,12,E,17759.29,6322.80
23,2026-04-01,12,W,724.76,562.64
24,2026-04-01,13,E,19371.73,6936.46
25,2026-04-01,13,W,728.05,571.99
26,2026-04-01,14,E,20772.87,8806.61
27,2026-04-01,14,W,712.02,538.01
28,2026-04-01,15,E,22084.69,10817.26
29,2026-04-01,15,W,681.80,506.92
30,2026-04-01,16,E,23513.51,13465.08
31,2026-04-01,16,W,646.12,515.65
32,2026-04-01,17,E,24641.19,14990.82
33,2026-04-01,17,W,606.62,493.23
34,2026-04-01,18,E,25147.98,14659.22
35,2026-04-01,18,W,561.14,466.67
36,2026-04-01,19,E,25248.40,14964.64
37,2026-04-01,19,W,539.68,422.48
38,2026-04-01,20,E,25366.46,15505.78
39,2026-04-01,20,W,538.73,387.57
40,2026-04-01,21,E,25941.80,16492.95
41,2026-04-01,21,W,520.78,326.27
42,2026-04-01,22,E,26665.94,18233.11
43,2026-04-01,22,W,515.65,252.93
44,2026-04-01,23,E,27557.02,18631.62
45,2026-04-01,23,W,519.35,155.55
46,2026-04-01,24,E,25899.26,19162.22
47,2026-04-01,24,W,522.83,130.38

### 10. Reserve Zonal Wind

In [18]:
df_wind_res = wind.get_res_zonal_wind(START, END, var_spec=['f', 'a'])
display(df_wind_res.head(10))
df_wind_res

,dt,hr,ReserveZone,spp_res_zonal_wind_forecast_f,spp_res_zonal_wind_actual_a
0,2026-04-01,1,1,1907.53,1641.80
1,2026-04-01,1,2,3762.81,3894.99
2,2026-04-01,1,3,1125.62,921.67
3,2026-04-01,1,4,9296.98,7498.03
4,2026-04-01,1,5,2727.58,2160.04
5,2026-04-01,1,21,841.16,819.10
6,2026-04-01,2,1,1809.51,1570.33
7,2026-04-01,2,2,3436.82,3491.59
8,2026-04-01,2,3,995.66,591.17
9,2026-04-01,2,4,9127.73,7483.80

,dt,hr,ReserveZone,spp_res_zonal_wind_forecast_f,spp_res_zonal_wind_actual_a
0,2026-04-01,1,1,1907.53,1641.80
1,2026-04-01,1,2,3762.81,3894.99
2,2026-04-01,1,3,1125.62,921.67
3,2026-04-01,1,4,9296.98,7498.03
4,2026-04-01,1,5,2727.58,2160.04
...,...,...,...,...,...
139,2026-04-01,24,2,5785.92,4455.42
140,2026-04-01,24,3,2009.54,1653.04
141,2026-04-01,24,4,13878.44,9536.89
142,2026-04-01,24,5,2635.36,2611.94
143,2026-04-01,24,21,522.83,133.55

### 11. Wind Error

In [6]:
df_wind_error = wind.get_wind_error(START, END, var_spec=['f', 'a'])
print(df_wind_error.shape)
df_wind_error

(24, 4)

            dt  hr  spp_wind_error_f  spp_wind_error_a
0   2026-04-01   1          639.7140       2453.836674
1   2026-04-01   2          639.7140       2695.469547
2   2026-04-01   3          639.7140       2991.373332
3   2026-04-01   4          634.2130       3698.455000
4   2026-04-01   5          616.3100       4562.114167
5   2026-04-01   6          600.6570       5110.630000
6   2026-04-01   7          600.6570       5024.201667
7   2026-04-01   8          606.1580       5448.957501
8   2026-04-01   9          606.1580       6757.455000
9   2026-04-01  10          600.7200       8370.631667
10  2026-04-01  11          595.6800      10091.783333
11  2026-04-01  12          590.1790      11585.775000
12  2026-04-01  13          610.5930      12547.593332
13  2026-04-01  14          634.8350      12065.083332
14  2026-04-01  15          612.6970      11431.046667
15  2026-04-01  16          571.6480       9945.954993
16  2026-04-01  17          103.2400       9591.787496
17  2026-04-01  18           32.5311      10485.188336
18  2026-04-01  19           66.2004      10183.221673
19  2026-04-01  20          238.4210       9637.673344
20  2026-04-01  21          649.2300       8942.115859
21  2026-04-01  22          743.4560       6742.820020
22  2026-04-01  23          944.4660       6410.349963
23  2026-04-01  24          760.3070       3337.896738

### 12. BAA Zonal Wind Error (E and W)

In [7]:
df_wind_baa_error = wind.get_baa_zonal_wind_error(START, END, baa_zones=BAA_ZONES, var_spec=['f', 'a'])
print(df_wind_baa_error.shape)
df_wind_baa_error

(48, 5)

/var/www/python/Prod/nighthawk/nighthawk/data/pipeline/common_functions/wind.py:1593: UserWarning: No model-predicted BAA-zonal wind error forecast available for zone(s) ['W']; using actual wind error as forecast.
  warnings.warn(

,dt,hr,baa_zone,spp_baa_zonal_wind_error_a,spp_baa_zonal_wind_error_f
0,2026-04-01,1,E,2433.876674,639.714000
1,2026-04-01,1,W,19.960000,19.960000
2,2026-04-01,2,E,2614.815000,639.714000
3,2026-04-01,2,W,80.654546,80.654546
4,2026-04-01,3,E,2858.216667,639.714000
5,2026-04-01,3,W,133.156667,133.156667
6,2026-04-01,4,E,3569.600000,634.213000
7,2026-04-01,4,W,128.855000,128.855000
8,2026-04-01,5,E,4453.074167,616.310000
9,2026-04-01,5,W,109.040000,109.040000
10,2026-04-01,6,E,5000.228333,600.657000
11,2026-04-01,6,W,110.401667,110.401667
12,2026-04-01,7,E,4908.295000,600.657000
13,2026-04-01,7,W,115.906667,115.906667
14,2026-04-01,8,E,5346.840000,606.158000
15,2026-04-01,8,W,102.117501,102.117501
16,2026-04-01,9,E,6661.609167,606.158000
17,2026-04-01,9,W,95.845833,95.845833
18,2026-04-01,10,E,8258.920000,600.720000
19,2026-04-01,10,W,111.711666,111.711666
20,2026-04-01,11,E,9967.120833,595.680000
21,2026-04-01,11,W,124.662500,124.662500
22,2026-04-01,12,E,11428.370834,590.179000
23,2026-04-01,12,W,157.404167,157.404167
24,2026-04-01,13,E,12405.571666,610.593000
25,2026-04-01,13,W,142.021667,142.021667
26,2026-04-01,14,E,11901.989164,634.835000
27,2026-04-01,14,W,163.094167,163.094167
28,2026-04-01,15,E,11258.168334,612.697000
29,2026-04-01,15,W,172.878333,172.878333
30,2026-04-01,16,E,9816.422493,571.648000
31,2026-04-01,16,W,129.532500,129.532500
32,2026-04-01,17,E,9481.580007,103.240000
33,2026-04-01,17,W,110.207500,110.207500
34,2026-04-01,18,E,10394.310835,32.531100
35,2026-04-01,18,W,90.877500,90.877500
36,2026-04-01,19,E,10066.039160,66.200400
37,2026-04-01,19,W,117.182500,117.182500
38,2026-04-01,20,E,9489.516670,238.421000
39,2026-04-01,20,W,148.156667,148.156667
40,2026-04-01,21,E,8754.919183,649.230000
41,2026-04-01,21,W,187.196666,187.196666
42,2026-04-01,22,E,6480.100020,743.456000
43,2026-04-01,22,W,262.720000,262.720000
44,2026-04-01,23,E,6048.200110,944.466000
45,2026-04-01,23,W,362.150000,362.150000
46,2026-04-01,24,E,2948.744102,760.307000
47,2026-04-01,24,W,389.152500,389.152500

### 13. VER Curtailment

In [8]:
df_ver = wind.get_ver_curtailment(START, END, var_spec=['f', 'a'])
print(df_ver.shape)
df_ver

(24, 4)

,dt,hr,spp_ver_curtailments_forecast_f,spp_ver_curtailments_actual_a
0,2026-04-01,1,1811.040,189.643326
1,2026-04-01,2,1759.060,171.980453
2,2026-04-01,3,1525.740,20.066668
3,2026-04-01,4,1517.030,0.045000
4,2026-04-01,5,1510.380,0.235833
5,2026-04-01,6,1184.470,1.690000
6,2026-04-01,7,1122.280,1.348333
7,2026-04-01,8,1101.870,22.862499
8,2026-04-01,9,647.363,1.915000
9,2026-04-01,10,532.968,23.748333
10,2026-04-01,11,766.187,1.706667
11,2026-04-01,12,990.603,12.835000
12,2026-04-01,13,1160.860,43.736668
13,2026-04-01,14,1637.470,75.186668
14,2026-04-01,15,1896.170,11.263333
15,2026-04-01,16,2420.880,232.945007
16,2026-04-01,17,2434.320,171.972504
17,2026-04-01,18,2470.160,98.041664
18,2026-04-01,19,2509.170,217.738327
19,2026-04-01,20,2605.400,374.166656
20,2026-04-01,21,3927.390,701.244141
21,2026-04-01,22,4463.950,1952.729980
22,2026-04-01,23,6058.580,2878.850037
23,2026-04-01,24,6847.820,3791.593262

### 14. BAA Zonal VER Curtailment (E and W)

In [26]:
df_ver_baa = wind.get_baa_zonal_ver_curtailment('2026-04-03', '2026-04-03', baa_zones=BAA_ZONES, var_spec=['f', 'a'])
print(df_ver_baa.shape)
df_ver_baa

(24, 5)

/var/www/python/Prod/nighthawk/nighthawk/data/pipeline/common_functions/wind.py:1799: UserWarning: No BAA-zonal VER curtailment forecast available for zone(s) ['W']; using actual curtailment as forecast.
  warnings.warn(

,dt,hr,baa_zone,spp_baa_zonal_ver_curtailments_forecast_f,spp_baa_zonal_ver_curtailments_actual_a
0,2026-04-03,1,E,6153.24,NaN
1,2026-04-03,2,E,6430.88,NaN
2,2026-04-03,3,E,6702.76,NaN
3,2026-04-03,4,E,6808.07,NaN
4,2026-04-03,5,E,6626.88,NaN
5,2026-04-03,6,E,5765.97,NaN
6,2026-04-03,7,E,5497.78,NaN
7,2026-04-03,8,E,5065.83,NaN
8,2026-04-03,9,E,4994.91,NaN
9,2026-04-03,10,E,3866.38,NaN
10,2026-04-03,11,E,3776.04,NaN
11,2026-04-03,12,E,3629.12,NaN
12,2026-04-03,13,E,3004.48,NaN
13,2026-04-03,14,E,2119.15,NaN
14,2026-04-03,15,E,1635.34,NaN
15,2026-04-03,16,E,1612.35,NaN
16,2026-04-03,17,E,1552.89,NaN
17,2026-04-03,18,E,1503.65,NaN
18,2026-04-03,19,E,1084.86,NaN
19,2026-04-03,20,E,1090.95,NaN
20,2026-04-03,21,E,1443.53,NaN
21,2026-04-03,22,E,1759.99,NaN
22,2026-04-03,23,E,3047.26,NaN
23,2026-04-03,24,E,3906.19,NaN

---
## SOLAR

### 15. Total Solar

In [10]:
df_solar_total = solar.get_total_solar(START, END, var_spec=['f', 'a'])
print(df_solar_total.shape)
df_solar_total

(24, 4)

            dt  hr  spp_solar_total_forecast_f  spp_solar_total_actual_a
0   2026-04-01   1                        0.00                      0.60
1   2026-04-01   2                        0.00                      0.60
2   2026-04-01   3                        0.00                      0.60
3   2026-04-01   4                        0.00                      0.60
4   2026-04-01   5                        0.00                      0.60
5   2026-04-01   6                        0.00                      0.60
6   2026-04-01   7                        0.05                      0.60
7   2026-04-01   8                       53.81                     22.74
8   2026-04-01   9                      422.77                    363.38
9   2026-04-01  10                      827.84                    744.52
10  2026-04-01  11                     1040.28                    762.78
11  2026-04-01  12                     1231.59                    976.17
12  2026-04-01  13                     1346.48                   1173.30
13  2026-04-01  14                     1354.77                   1224.14
14  2026-04-01  15                     1277.63                   1211.61
15  2026-04-01  16                     1127.67                    965.83
16  2026-04-01  17                      931.52                    836.92
17  2026-04-01  18                      782.86                    559.63
18  2026-04-01  19                      520.74                    290.63
19  2026-04-01  20                      150.00                    113.35
20  2026-04-01  21                        5.79                     12.04
21  2026-04-01  22                        0.00                      0.01
22  2026-04-01  23                        0.00                      0.01
23  2026-04-01  24                        0.00                      0.00

### 16. BAA Zonal Solar (E and W)

In [11]:
df_solar_baa = solar.get_baa_zonal_solar(START, END, baa_zones=BAA_ZONES, var_spec=['f', 'a'])
print(df_solar_baa.shape)
df_solar_baa

(48, 5)

,dt,hr,baa_zone,spp_baa_zonal_solar_forecast_f,spp_baa_zonal_solar_actual_a
0,2026-04-01,1,E,0.60,0.60
1,2026-04-01,1,W,0.00,0.00
2,2026-04-01,2,E,0.60,0.60
3,2026-04-01,2,W,0.00,0.00
4,2026-04-01,3,E,0.60,0.60
5,2026-04-01,3,W,0.00,0.00
6,2026-04-01,4,E,0.60,0.60
7,2026-04-01,4,W,0.00,0.00
8,2026-04-01,5,E,0.60,0.60
9,2026-04-01,5,W,0.00,0.00
10,2026-04-01,6,E,0.60,0.60
11,2026-04-01,6,W,0.00,0.00
12,2026-04-01,7,E,0.05,0.60
13,2026-04-01,7,W,0.00,0.00
14,2026-04-01,8,E,52.76,22.62
15,2026-04-01,8,W,1.05,0.12
16,2026-04-01,9,E,385.00,335.76
17,2026-04-01,9,W,37.77,27.62
18,2026-04-01,10,E,685.76,660.14
19,2026-04-01,10,W,142.08,84.38
20,2026-04-01,11,E,799.30,619.88
21,2026-04-01,11,W,240.98,142.90
22,2026-04-01,12,E,908.31,767.67
23,2026-04-01,12,W,323.28,208.50
24,2026-04-01,13,E,977.99,792.99
25,2026-04-01,13,W,368.49,380.31
26,2026-04-01,14,E,960.44,848.17
27,2026-04-01,14,W,394.33,375.97
28,2026-04-01,15,E,877.78,802.78
29,2026-04-01,15,W,399.85,408.83
30,2026-04-01,16,E,748.08,545.89
31,2026-04-01,16,W,379.59,419.94
32,2026-04-01,17,E,597.14,423.29
33,2026-04-01,17,W,334.38,413.63
34,2026-04-01,18,E,466.37,241.52
35,2026-04-01,18,W,316.49,318.11
36,2026-04-01,19,E,243.19,142.71
37,2026-04-01,19,W,277.55,147.92
38,2026-04-01,20,E,38.57,42.42
39,2026-04-01,20,W,111.43,70.93
40,2026-04-01,21,E,0.19,1.09
41,2026-04-01,21,W,5.60,10.95
42,2026-04-01,22,E,0.00,0.00
43,2026-04-01,22,W,0.01,0.01
44,2026-04-01,23,E,0.00,0.00
45,2026-04-01,23,W,0.01,0.01
46,2026-04-01,24,E,0.00,0.00
47,2026-04-01,24,W,0.00,0.00

### 17. Reserve Zonal Solar

In [25]:
df_solar_res = solar.get_res_zonal_solar(START, END, var_spec=['f', 'a'])
print(df_solar_res.shape)
df_solar_res.sort_values(['dt','hr','ReserveZone'])[:10]

(144, 5)

,dt,hr,ReserveZone,spp_res_zonal_solar_forecast_f,spp_res_zonal_solar_actual_a
0,2026-04-01,1,1,0.0,0.00
24,2026-04-01,1,2,0.0,0.00
48,2026-04-01,1,3,0.0,-0.03
72,2026-04-01,1,4,0.0,0.60
96,2026-04-01,1,5,0.0,0.00
120,2026-04-01,1,21,0.0,0.00
1,2026-04-01,2,1,0.0,0.00
25,2026-04-01,2,2,0.0,0.00
49,2026-04-01,2,3,0.0,0.05
73,2026-04-01,2,4,0.0,0.60

---
## GEN OUTAGE

### 18. Gen Outage — Total SPP

In [13]:
df_genout_total = genout.get_genoutage_by_level(START, END, area_list=['SPP'], var_spec=['f', 'a'])
print(df_genout_total.shape)
df_genout_total

(24, 5)

            dt  hr baa_zone  spp_genoutage_forecast_f  spp_genoutage_actual_a
0   2026-04-01   1      SPP                   25715.9                 25197.9
1   2026-04-01   2      SPP                   25728.3                 25198.1
2   2026-04-01   3      SPP                   25878.9                 25348.7
3   2026-04-01   4      SPP                   25878.9                 25348.7
4   2026-04-01   5      SPP                   25712.9                 25182.7
5   2026-04-01   6      SPP                   25612.9                 25182.7
6   2026-04-01   7      SPP                   25897.1                 25171.9
7   2026-04-01   8      SPP                   25907.1                 25179.9
8   2026-04-01   9      SPP                   25907.1                 25180.5
9   2026-04-01  10      SPP                   25907.7                 25183.5
10  2026-04-01  11      SPP                   25182.9                 25794.4
11  2026-04-01  12      SPP                   25180.6                 25792.1
12  2026-04-01  13      SPP                   25258.3                 25888.2
13  2026-04-01  14      SPP                   25152.3                 25286.2
14  2026-04-01  15      SPP                   25272.4                 25314.3
15  2026-04-01  16      SPP                   25265.0                 25306.9
16  2026-04-01  17      SPP                   25264.8                 25306.7
17  2026-04-01  18      SPP                   25264.8                 25349.7
18  2026-04-01  19      SPP                   25805.3                 25882.4
19  2026-04-01  20      SPP                   25806.5                 25883.9
20  2026-04-01  21      SPP                   25753.5                 25830.9
21  2026-04-01  22      SPP                   25755.8                 25833.2
22  2026-04-01  23      SPP                   25713.0                 25790.4
23  2026-04-01  24      SPP                   25714.3                 25791.7

### 19. Gen Outage — BAA Zonal (E and W)

In [1]:
import sys
import pandas as pd

sys.path.append("/var/www/python/Qingcheng/nighthawk/")
from nighthawk.util import sql_functions
from nighthawk.data.pipeline.common_functions.load import Load
from nighthawk.data.pipeline.common_functions.wind import Wind
from nighthawk.data.pipeline.common_functions.solar import Solar
from nighthawk.data.pipeline.common_functions.genoutage import GenOutage
from nighthawk.data.pipeline.var_handler.fuel_type import FuelType

START = "2026-04-01"
END   = "2026-04-01"
BAA_ZONES = ["E", "W"]

load     = Load("SPP")
wind     = Wind("SPP")
solar    = Solar("SPP")
genout   = GenOutage("SPP")
fueltype = FuelType("SPP")
print(f"Objects created for SPP  |  {START} → {END}")

df_genout_baa = genout.get_genoutage_by_level('2026-04-07', '2026-04-07', area_list=['E', 'W'], var_spec=['f', 'a'])
print(df_genout_baa.shape)
display(df_genout_baa)

df_outage_fuel = fueltype.get_genoutage_fuel_type('2026-04-07', '2026-04-07', var_spec=['f', 'a'])
print(df_outage_fuel.shape)

# df_outage_fuel['total_f'] = df_outage_fuel.filter(regex='_f$').sum(axis=1)
# df_outage_fuel['total_a'] = df_outage_fuel.filter(regex='_a$').sum(axis=1)
# df_outage_fuel

fueltype.get_genoutage_fuel_type('2026-04-07', '2026-04-07', var_spec=['f', 'a'])

Objects created for SPP  |  2026-04-01 → 2026-04-01
(48, 5)

            dt  hr baa_zone  spp_genoutage_forecast_f  spp_genoutage_actual_a
0   2026-04-07   1        E                   26588.4                 27190.4
1   2026-04-07   1        W                    1739.1                  1858.0
2   2026-04-07   2        E                   26790.4                 27392.4
3   2026-04-07   2        W                    1739.1                  1858.0
4   2026-04-07   3        E                   26790.4                 27392.4
5   2026-04-07   3        W                    1858.0                  1858.0
6   2026-04-07   4        E                   26790.4                 27392.4
7   2026-04-07   4        W                    1858.0                  1858.0
8   2026-04-07   5        E                   27392.4                 26613.2
9   2026-04-07   5        W                    1858.0                  1939.6
10  2026-04-07   6        E                   27531.9                 27026.9
11  2026-04-07   6        W                    1858.0                  1939.6
12  2026-04-07   7        E                   27543.8                 27040.2
13  2026-04-07   7        W                    1858.0                  1939.6
14  2026-04-07   8        E                   27738.8                 27694.0
15  2026-04-07   8        W                    1858.0                  1939.6
16  2026-04-07   9        E                   28331.9                 28297.7
17  2026-04-07   9        W                    1858.0                  1939.6
18  2026-04-07  10        E                   28333.5                 28293.1
19  2026-04-07  10        W                    1858.0                  1939.6
20  2026-04-07  11        E                   28333.3                 28292.9
21  2026-04-07  11        W                    1858.0                  1939.6
22  2026-04-07  12        E                   28333.3                 28292.9
23  2026-04-07  12        W                    1858.0                  1939.6
24  2026-04-07  13        E                   28337.4                 28297.0
25  2026-04-07  13        W                    1858.0                  1930.6
26  2026-04-07  14        E                   28338.9                 28298.5
27  2026-04-07  14        W                    1858.0                  1930.6
28  2026-04-07  15        E                   28339.9                 28299.5
29  2026-04-07  15        W                    1858.0                  1930.6
30  2026-04-07  16        E                   28342.2                     NaN
31  2026-04-07  16        W                    1858.0                     NaN
32  2026-04-07  17        E                   28344.4                     NaN
33  2026-04-07  17        W                    1858.0                     NaN
34  2026-04-07  18        E                   28336.7                     NaN
35  2026-04-07  18        W                    1858.0                     NaN
36  2026-04-07  19        E                   28328.1                     NaN
37  2026-04-07  19        W                    1858.0                     NaN
38  2026-04-07  20        E                   28328.3                     NaN
39  2026-04-07  20        W                    1858.0                     NaN
40  2026-04-07  21        E                   28328.7                     NaN
41  2026-04-07  21        W                    1858.0                     NaN
42  2026-04-07  22        E                   28478.7                     NaN
43  2026-04-07  22        W                    1858.0                     NaN
44  2026-04-07  23        E                   28479.7                     NaN
45  2026-04-07  23        W                    1858.0                     NaN
46  2026-04-07  24        E                   28479.7                     NaN
47  2026-04-07  24        W                    1858.0                     NaN

,spp_fuelmixoutage_coal_forecast_f,spp_fuelmixoutage_dieselfueloil_forecast_f,spp_fuelmixoutage_hydro_forecast_f,spp_fuelmixoutage_naturalgas_forecast_f,spp_fuelmixoutage_solar_forecast_f,spp_fuelmixoutage_wind_forecast_f,dt,hr,spp_fuelmixoutage_coal_actual_a,spp_fuelmixoutage_dieselfueloil_actual_a,spp_fuelmixoutage_hydro_actual_a,spp_fuelmixoutage_naturalgas_actual_a,spp_fuelmixoutage_solar_actual_a,spp_fuelmixoutage_wind_actual_a
0,9532.8,75.8,1620.3,14487.3,820.5,263.0,2026-04-05,19,8995.8,75.8,1620.3,13875.3,820.5,263.0
1,9532.8,75.8,1620.3,14487.3,820.5,263.0,2026-04-05,20,8995.8,75.8,1620.3,13875.3,820.5,263.0
2,9532.8,75.8,1620.3,14487.3,820.5,263.0,2026-04-05,21,8995.8,75.8,1620.3,13875.3,820.5,263.0
3,9532.8,75.8,1620.3,14487.3,970.5,263.0,2026-04-05,22,8995.8,75.8,1620.3,13875.3,970.5,263.0
4,9532.8,75.8,1620.3,14487.3,970.5,263.0,2026-04-05,23,8995.8,75.8,1620.3,13875.3,970.5,263.0
5,9532.8,75.8,1620.3,14487.3,970.5,263.0,2026-04-05,24,8995.8,75.8,1620.3,13875.3,970.5,263.0
6,9685.8,75.8,1620.3,14934.2,970.5,263.0,2026-04-06,1,9774.8,75.8,1620.3,14253.7,970.5,263.0
7,9823.8,75.8,1620.3,14934.2,970.5,263.0,2026-04-06,2,9986.8,75.8,1620.3,14253.7,970.5,263.0
8,9942.7,75.8,1685.3,14934.2,970.5,263.0,2026-04-06,3,10105.7,75.8,1685.3,14253.7,970.5,263.0
9,9942.7,75.8,1698.1,14934.2,970.5,263.0,2026-04-06,4,10105.7,75.8,1698.1,14253.7,970.5,263.0
10,10105.7,75.8,1698.1,14253.7,970.5,263.0,2026-04-06,5,10810.7,75.8,1703.1,14486.3,970.5,263.0
11,10105.7,75.8,1698.1,14269.2,970.5,263.0,2026-04-06,6,10810.7,75.8,1703.1,14501.8,970.5,263.0
12,10105.7,119.8,1698.1,14497.2,970.5,263.0,2026-04-06,7,10810.7,119.8,1690.3,14729.8,970.5,263.0
13,10105.7,119.8,1698.1,14506.2,820.5,263.0,2026-04-06,8,10810.7,119.8,1690.3,14738.8,820.5,263.0
14,10105.7,119.8,1698.1,14506.2,1077.5,283.0,2026-04-06,9,10810.7,119.8,1690.3,14738.8,1077.5,283.0
15,10105.7,119.8,1628.1,14506.2,1077.5,283.0,2026-04-06,10,10810.7,119.8,1633.1,14738.8,1077.5,283.0
16,10105.7,119.8,1628.1,14506.2,1077.5,283.0,2026-04-06,11,10810.7,119.8,1633.1,14738.8,1077.5,283.0
17,10105.7,119.8,1628.1,14506.2,1077.5,283.0,2026-04-06,12,10810.7,119.8,1633.1,14738.8,1077.5,283.0
18,10105.7,119.8,1628.1,14506.2,1077.5,283.0,2026-04-06,13,10810.7,119.8,1633.1,14738.8,1077.5,283.0
19,10105.7,119.8,1628.1,14506.2,1077.5,283.0,2026-04-06,14,10810.7,119.8,1633.1,14738.8,1077.5,283.0

,dt,hr,spp_fuelmixoutage_coal_forecast_f,spp_fuelmixoutage_dieselfueloil_forecast_f,spp_fuelmixoutage_hydro_forecast_f,spp_fuelmixoutage_naturalgas_forecast_f,spp_fuelmixoutage_solar_forecast_f,spp_fuelmixoutage_wind_forecast_f,spp_fuelmixoutage_coal_actual_a,spp_fuelmixoutage_dieselfueloil_actual_a,spp_fuelmixoutage_hydro_actual_a,spp_fuelmixoutage_naturalgas_actual_a,spp_fuelmixoutage_solar_actual_a,spp_fuelmixoutage_wind_actual_a
0,2026-04-07,1,9912.8,119.8,1656.1,14793.8,1247.5,283.0,10736.7,119.8,1656.1,14688.8,1247.5,283.0
1,2026-04-07,2,9912.8,119.8,1656.1,14995.8,1247.5,283.0,10736.7,119.8,1656.1,14890.8,1247.5,283.0
2,2026-04-07,3,10031.7,119.8,1656.1,14995.8,1247.5,283.0,10736.7,119.8,1656.1,14890.8,1247.5,283.0
3,2026-04-07,4,10031.7,119.8,1656.1,14995.8,1247.5,283.0,10736.7,119.8,1656.1,14890.8,1247.5,283.0
4,2026-04-07,5,10736.7,119.8,1656.1,14890.8,1247.5,283.0,9990.8,119.8,1656.1,14925.4,1255.0,283.0
5,2026-04-07,6,10736.7,119.8,1656.1,15031.8,1247.5,283.0,10265.8,119.8,1656.1,15066.4,1255.0,283.0
6,2026-04-07,7,10736.7,119.8,1676.1,15031.8,1247.5,283.0,10265.8,119.8,1676.1,15066.4,1255.0,283.0
7,2026-04-07,8,10736.7,119.8,1676.1,15377.8,1097.5,283.0,10265.8,119.8,1676.1,15870.4,1105.0,283.0
8,2026-04-07,9,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
9,2026-04-07,10,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
10,2026-04-07,11,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
11,2026-04-07,12,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
12,2026-04-07,13,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
13,2026-04-07,14,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
14,2026-04-07,15,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
15,2026-04-07,16,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15825.4,1105.0,878.0
16,2026-04-07,17,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15723.4,1105.0,878.0
17,2026-04-07,18,10736.7,119.8,1676.1,15368.8,1097.5,878.0,10265.8,119.8,1676.1,15714.4,1105.0,878.0
18,2026-04-07,19,10736.7,119.8,1676.1,15359.8,1097.5,878.0,10265.8,119.8,1648.1,15705.4,1105.0,858.0
19,2026-04-07,20,10736.7,119.8,1676.1,15359.8,1097.5,878.0,10265.8,119.8,1648.1,15705.4,1105.0,858.0

,dt,hr,spp_fuelmixoutage_coal_forecast_f,spp_fuelmixoutage_dieselfueloil_forecast_f,spp_fuelmixoutage_hydro_forecast_f,spp_fuelmixoutage_naturalgas_forecast_f,spp_fuelmixoutage_solar_forecast_f,spp_fuelmixoutage_wind_forecast_f,spp_fuelmixoutage_coal_actual_a,spp_fuelmixoutage_dieselfueloil_actual_a,spp_fuelmixoutage_hydro_actual_a,spp_fuelmixoutage_naturalgas_actual_a,spp_fuelmixoutage_solar_actual_a,spp_fuelmixoutage_wind_actual_a
0,2026-04-07,1,9912.8,119.8,1656.1,14793.8,1247.5,283.0,10736.7,119.8,1656.1,14688.8,1247.5,283.0
1,2026-04-07,2,9912.8,119.8,1656.1,14995.8,1247.5,283.0,10736.7,119.8,1656.1,14890.8,1247.5,283.0
2,2026-04-07,3,10031.7,119.8,1656.1,14995.8,1247.5,283.0,10736.7,119.8,1656.1,14890.8,1247.5,283.0
3,2026-04-07,4,10031.7,119.8,1656.1,14995.8,1247.5,283.0,10736.7,119.8,1656.1,14890.8,1247.5,283.0
4,2026-04-07,5,10736.7,119.8,1656.1,14890.8,1247.5,283.0,9990.8,119.8,1656.1,14925.4,1255.0,283.0
5,2026-04-07,6,10736.7,119.8,1656.1,15031.8,1247.5,283.0,10265.8,119.8,1656.1,15066.4,1255.0,283.0
6,2026-04-07,7,10736.7,119.8,1676.1,15031.8,1247.5,283.0,10265.8,119.8,1676.1,15066.4,1255.0,283.0
7,2026-04-07,8,10736.7,119.8,1676.1,15377.8,1097.5,283.0,10265.8,119.8,1676.1,15870.4,1105.0,283.0
8,2026-04-07,9,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
9,2026-04-07,10,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
10,2026-04-07,11,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
11,2026-04-07,12,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
12,2026-04-07,13,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
13,2026-04-07,14,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
14,2026-04-07,15,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
15,2026-04-07,16,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15825.4,1105.0,878.0
16,2026-04-07,17,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15723.4,1105.0,878.0
17,2026-04-07,18,10736.7,119.8,1676.1,15368.8,1097.5,878.0,10265.8,119.8,1676.1,15714.4,1105.0,878.0
18,2026-04-07,19,10736.7,119.8,1676.1,15359.8,1097.5,878.0,10265.8,119.8,1648.1,15705.4,1105.0,858.0
19,2026-04-07,20,10736.7,119.8,1676.1,15359.8,1097.5,878.0,10265.8,119.8,1648.1,15705.4,1105.0,858.0

(24, 14)

,spp_fuelmixoutage_coal_forecast_f,spp_fuelmixoutage_dieselfueloil_forecast_f,spp_fuelmixoutage_hydro_forecast_f,spp_fuelmixoutage_naturalgas_forecast_f,spp_fuelmixoutage_solar_forecast_f,spp_fuelmixoutage_wind_forecast_f,dt,hr,spp_fuelmixoutage_coal_actual_a,spp_fuelmixoutage_dieselfueloil_actual_a,spp_fuelmixoutage_hydro_actual_a,spp_fuelmixoutage_naturalgas_actual_a,spp_fuelmixoutage_solar_actual_a,spp_fuelmixoutage_wind_actual_a
0,9532.8,75.8,1620.3,14487.3,820.5,263.0,2026-04-05,19,8995.8,75.8,1620.3,13875.3,820.5,263.0
1,9532.8,75.8,1620.3,14487.3,820.5,263.0,2026-04-05,20,8995.8,75.8,1620.3,13875.3,820.5,263.0
2,9532.8,75.8,1620.3,14487.3,820.5,263.0,2026-04-05,21,8995.8,75.8,1620.3,13875.3,820.5,263.0
3,9532.8,75.8,1620.3,14487.3,970.5,263.0,2026-04-05,22,8995.8,75.8,1620.3,13875.3,970.5,263.0
4,9532.8,75.8,1620.3,14487.3,970.5,263.0,2026-04-05,23,8995.8,75.8,1620.3,13875.3,970.5,263.0
5,9532.8,75.8,1620.3,14487.3,970.5,263.0,2026-04-05,24,8995.8,75.8,1620.3,13875.3,970.5,263.0
6,9685.8,75.8,1620.3,14934.2,970.5,263.0,2026-04-06,1,9774.8,75.8,1620.3,14253.7,970.5,263.0
7,9823.8,75.8,1620.3,14934.2,970.5,263.0,2026-04-06,2,9986.8,75.8,1620.3,14253.7,970.5,263.0
8,9942.7,75.8,1685.3,14934.2,970.5,263.0,2026-04-06,3,10105.7,75.8,1685.3,14253.7,970.5,263.0
9,9942.7,75.8,1698.1,14934.2,970.5,263.0,2026-04-06,4,10105.7,75.8,1698.1,14253.7,970.5,263.0
10,10105.7,75.8,1698.1,14253.7,970.5,263.0,2026-04-06,5,10810.7,75.8,1703.1,14486.3,970.5,263.0
11,10105.7,75.8,1698.1,14269.2,970.5,263.0,2026-04-06,6,10810.7,75.8,1703.1,14501.8,970.5,263.0
12,10105.7,119.8,1698.1,14497.2,970.5,263.0,2026-04-06,7,10810.7,119.8,1690.3,14729.8,970.5,263.0
13,10105.7,119.8,1698.1,14506.2,820.5,263.0,2026-04-06,8,10810.7,119.8,1690.3,14738.8,820.5,263.0
14,10105.7,119.8,1698.1,14506.2,1077.5,283.0,2026-04-06,9,10810.7,119.8,1690.3,14738.8,1077.5,283.0
15,10105.7,119.8,1628.1,14506.2,1077.5,283.0,2026-04-06,10,10810.7,119.8,1633.1,14738.8,1077.5,283.0
16,10105.7,119.8,1628.1,14506.2,1077.5,283.0,2026-04-06,11,10810.7,119.8,1633.1,14738.8,1077.5,283.0
17,10105.7,119.8,1628.1,14506.2,1077.5,283.0,2026-04-06,12,10810.7,119.8,1633.1,14738.8,1077.5,283.0
18,10105.7,119.8,1628.1,14506.2,1077.5,283.0,2026-04-06,13,10810.7,119.8,1633.1,14738.8,1077.5,283.0
19,10105.7,119.8,1628.1,14506.2,1077.5,283.0,2026-04-06,14,10810.7,119.8,1633.1,14738.8,1077.5,283.0

,dt,hr,spp_fuelmixoutage_coal_forecast_f,spp_fuelmixoutage_dieselfueloil_forecast_f,spp_fuelmixoutage_hydro_forecast_f,spp_fuelmixoutage_naturalgas_forecast_f,spp_fuelmixoutage_solar_forecast_f,spp_fuelmixoutage_wind_forecast_f,spp_fuelmixoutage_coal_actual_a,spp_fuelmixoutage_dieselfueloil_actual_a,spp_fuelmixoutage_hydro_actual_a,spp_fuelmixoutage_naturalgas_actual_a,spp_fuelmixoutage_solar_actual_a,spp_fuelmixoutage_wind_actual_a
0,2026-04-07,1,9912.8,119.8,1656.1,14793.8,1247.5,283.0,10736.7,119.8,1656.1,14688.8,1247.5,283.0
1,2026-04-07,2,9912.8,119.8,1656.1,14995.8,1247.5,283.0,10736.7,119.8,1656.1,14890.8,1247.5,283.0
2,2026-04-07,3,10031.7,119.8,1656.1,14995.8,1247.5,283.0,10736.7,119.8,1656.1,14890.8,1247.5,283.0
3,2026-04-07,4,10031.7,119.8,1656.1,14995.8,1247.5,283.0,10736.7,119.8,1656.1,14890.8,1247.5,283.0
4,2026-04-07,5,10736.7,119.8,1656.1,14890.8,1247.5,283.0,9990.8,119.8,1656.1,14925.4,1255.0,283.0
5,2026-04-07,6,10736.7,119.8,1656.1,15031.8,1247.5,283.0,10265.8,119.8,1656.1,15066.4,1255.0,283.0
6,2026-04-07,7,10736.7,119.8,1676.1,15031.8,1247.5,283.0,10265.8,119.8,1676.1,15066.4,1255.0,283.0
7,2026-04-07,8,10736.7,119.8,1676.1,15377.8,1097.5,283.0,10265.8,119.8,1676.1,15870.4,1105.0,283.0
8,2026-04-07,9,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
9,2026-04-07,10,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
10,2026-04-07,11,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
11,2026-04-07,12,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
12,2026-04-07,13,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
13,2026-04-07,14,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
14,2026-04-07,15,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
15,2026-04-07,16,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15825.4,1105.0,878.0
16,2026-04-07,17,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15723.4,1105.0,878.0
17,2026-04-07,18,10736.7,119.8,1676.1,15368.8,1097.5,878.0,10265.8,119.8,1676.1,15714.4,1105.0,878.0
18,2026-04-07,19,10736.7,119.8,1676.1,15359.8,1097.5,878.0,10265.8,119.8,1648.1,15705.4,1105.0,858.0
19,2026-04-07,20,10736.7,119.8,1676.1,15359.8,1097.5,878.0,10265.8,119.8,1648.1,15705.4,1105.0,858.0

,dt,hr,spp_fuelmixoutage_coal_forecast_f,spp_fuelmixoutage_dieselfueloil_forecast_f,spp_fuelmixoutage_hydro_forecast_f,spp_fuelmixoutage_naturalgas_forecast_f,spp_fuelmixoutage_solar_forecast_f,spp_fuelmixoutage_wind_forecast_f,spp_fuelmixoutage_coal_actual_a,spp_fuelmixoutage_dieselfueloil_actual_a,spp_fuelmixoutage_hydro_actual_a,spp_fuelmixoutage_naturalgas_actual_a,spp_fuelmixoutage_solar_actual_a,spp_fuelmixoutage_wind_actual_a
0,2026-04-07,1,9912.8,119.8,1656.1,14793.8,1247.5,283.0,10736.7,119.8,1656.1,14688.8,1247.5,283.0
1,2026-04-07,2,9912.8,119.8,1656.1,14995.8,1247.5,283.0,10736.7,119.8,1656.1,14890.8,1247.5,283.0
2,2026-04-07,3,10031.7,119.8,1656.1,14995.8,1247.5,283.0,10736.7,119.8,1656.1,14890.8,1247.5,283.0
3,2026-04-07,4,10031.7,119.8,1656.1,14995.8,1247.5,283.0,10736.7,119.8,1656.1,14890.8,1247.5,283.0
4,2026-04-07,5,10736.7,119.8,1656.1,14890.8,1247.5,283.0,9990.8,119.8,1656.1,14925.4,1255.0,283.0
5,2026-04-07,6,10736.7,119.8,1656.1,15031.8,1247.5,283.0,10265.8,119.8,1656.1,15066.4,1255.0,283.0
6,2026-04-07,7,10736.7,119.8,1676.1,15031.8,1247.5,283.0,10265.8,119.8,1676.1,15066.4,1255.0,283.0
7,2026-04-07,8,10736.7,119.8,1676.1,15377.8,1097.5,283.0,10265.8,119.8,1676.1,15870.4,1105.0,283.0
8,2026-04-07,9,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
9,2026-04-07,10,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
10,2026-04-07,11,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
11,2026-04-07,12,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
12,2026-04-07,13,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
13,2026-04-07,14,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
14,2026-04-07,15,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
15,2026-04-07,16,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15825.4,1105.0,878.0
16,2026-04-07,17,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15723.4,1105.0,878.0
17,2026-04-07,18,10736.7,119.8,1676.1,15368.8,1097.5,878.0,10265.8,119.8,1676.1,15714.4,1105.0,878.0
18,2026-04-07,19,10736.7,119.8,1676.1,15359.8,1097.5,878.0,10265.8,119.8,1648.1,15705.4,1105.0,858.0
19,2026-04-07,20,10736.7,119.8,1676.1,15359.8,1097.5,878.0,10265.8,119.8,1648.1,15705.4,1105.0,858.0

,dt,hr,spp_fuelmixoutage_coal_forecast_f,spp_fuelmixoutage_dieselfueloil_forecast_f,spp_fuelmixoutage_hydro_forecast_f,spp_fuelmixoutage_naturalgas_forecast_f,spp_fuelmixoutage_solar_forecast_f,spp_fuelmixoutage_wind_forecast_f,spp_fuelmixoutage_coal_actual_a,spp_fuelmixoutage_dieselfueloil_actual_a,spp_fuelmixoutage_hydro_actual_a,spp_fuelmixoutage_naturalgas_actual_a,spp_fuelmixoutage_solar_actual_a,spp_fuelmixoutage_wind_actual_a
0,2026-04-07,1,9912.8,119.8,1656.1,14793.8,1247.5,283.0,10736.7,119.8,1656.1,14688.8,1247.5,283.0
1,2026-04-07,2,9912.8,119.8,1656.1,14995.8,1247.5,283.0,10736.7,119.8,1656.1,14890.8,1247.5,283.0
2,2026-04-07,3,10031.7,119.8,1656.1,14995.8,1247.5,283.0,10736.7,119.8,1656.1,14890.8,1247.5,283.0
3,2026-04-07,4,10031.7,119.8,1656.1,14995.8,1247.5,283.0,10736.7,119.8,1656.1,14890.8,1247.5,283.0
4,2026-04-07,5,10736.7,119.8,1656.1,14890.8,1247.5,283.0,9990.8,119.8,1656.1,14925.4,1255.0,283.0
5,2026-04-07,6,10736.7,119.8,1656.1,15031.8,1247.5,283.0,10265.8,119.8,1656.1,15066.4,1255.0,283.0
6,2026-04-07,7,10736.7,119.8,1676.1,15031.8,1247.5,283.0,10265.8,119.8,1676.1,15066.4,1255.0,283.0
7,2026-04-07,8,10736.7,119.8,1676.1,15377.8,1097.5,283.0,10265.8,119.8,1676.1,15870.4,1105.0,283.0
8,2026-04-07,9,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
9,2026-04-07,10,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
10,2026-04-07,11,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
11,2026-04-07,12,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
12,2026-04-07,13,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
13,2026-04-07,14,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
14,2026-04-07,15,10736.7,119.8,1676.1,15377.8,1097.5,878.0,10265.8,119.8,1688.1,15870.4,1105.0,878.0
15,2026-04-07,16,10736.7,119.8,1676.1,15377.8,1097.5,878.0,NaN,NaN,NaN,NaN,NaN,NaN
16,2026-04-07,17,10736.7,119.8,1676.1,15377.8,1097.5,878.0,NaN,NaN,NaN,NaN,NaN,NaN
17,2026-04-07,18,10736.7,119.8,1676.1,15368.8,1097.5,878.0,NaN,NaN,NaN,NaN,NaN,NaN
18,2026-04-07,19,10736.7,119.8,1676.1,15359.8,1097.5,878.0,NaN,NaN,NaN,NaN,NaN,NaN
19,2026-04-07,20,10736.7,119.8,1676.1,15359.8,1097.5,878.0,NaN,NaN,NaN,NaN,NaN,NaN
20,2026-04-07,21,10736.7,119.8,1676.1,15359.8,1097.5,878.0,NaN,NaN,NaN,NaN,NaN,NaN
21,2026-04-07,22,10736.7,119.8,1676.1,15359.8,1247.5,878.0,NaN,NaN,NaN,NaN,NaN,NaN
22,2026-04-07,23,10736.7,119.8,1676.1,15359.8,1247.5,878.0,NaN,NaN,NaN,NaN,NaN,NaN
23,2026-04-07,24,10736.7,119.8,1676.1,15359.8,1247.5,878.0,NaN,NaN,NaN,NaN,NaN,NaN

---
## GEN MIX (FUEL TYPE)

### 20. All 5 GenMix Nighthawk Functions — 2026-04-01

| # | Function | Table | Fuel types | Zones | a/f |
|---|---|---|---|---|---|
| 1 | `get_gen_fuel_type` | `GenMixHourly` | Hydro, Nuclear, NaturalGas | SPP total | both |
| 2 | `get_gen_fuel_actual` | `GenMixHourly` | all 10 | SPP total | actual only |
| 3 | `get_baa_zonal_gen_fuel_type` | `BAAZonalGenMixHourly` | Hydro, Nuclear, NaturalGas | E + W | both |
| 4 | `get_baa_zonal_gen_fuel_actual` | `BAAZonalGenMixHourly` | all 10 | E + W | actual only |
| 5 | `get_spp_gas_output` *(deprecated)* | `GenMixHourly` | NaturalGas only | SPP total | both |

In [1]:
import sys
sys.path.append("/var/www/python/Qingcheng/nighthawk/")
from nighthawk.data.pipeline.var_handler.fuel_type import FuelType
from nighthawk.data.pipeline.var_handler.spp_specific.gas_price_effect import get_spp_gas_output

ft = FuelType('SPP')
D = '2026-04-01'

# ── 1. get_gen_fuel_type ─────────────────────────────────────────────────────
# GenMixHourly → Hydro, Nuclear, NaturalGas only; forecast = 1-day shift of actual
df1 = ft.get_gen_fuel_type(D, D, var_spec=['a', 'f']) 
print('1. get_gen_fuel_type:', df1.shape)
print('   columns:', df1.columns.tolist())
display(df1)

# ── 2. get_gen_fuel_actual ───────────────────────────────────────────────────
# GenMixHourly → all 10 fuel types; actual only, melted format
df2 = ft.get_gen_fuel_actual(D, D)
print('2. get_gen_fuel_actual:', df2.shape)
print('   fuel types:', df2['fuel_type'].unique().tolist() if 'fuel_type' in df2.columns else df2.columns.tolist())
display(df2)

# ── 3. get_baa_zonal_gen_fuel_type ───────────────────────────────────────────
# BAAZonalGenMixHourly → Hydro, Nuclear, NaturalGas; E and W; forecast = 1-day shift per zone
df3 = ft.get_baa_zonal_gen_fuel_type(D, D, baa_zones=['E', 'W'], var_spec=['a', 'f'])
print('3. get_baa_zonal_gen_fuel_type:', df3.shape)
print('   columns:', df3.columns.tolist())
display(df3)

# ── 4. get_baa_zonal_gen_fuel_actual ─────────────────────────────────────────
# BAAZonalGenMixHourly → all 10 fuel types; E and W; actual only, melted format
df4 = ft.get_baa_zonal_gen_fuel_actual(D, D, baa_zones=['E', 'W'])
print('4. get_baa_zonal_gen_fuel_actual:', df4.shape)
print('   fuel types:', df4['fuel_type'].unique().tolist() if 'fuel_type' in df4.columns else df4.columns.tolist())
display(df4)

# ── 5. get_spp_gas_output (deprecated) ───────────────────────────────────────
# GenMixHourly → NaturalGasTotal only; actual + forecast (1-day shift)
df5 = get_spp_gas_output(D, D, var_spec=['a', 'f'])
print('5. get_spp_gas_output (deprecated):', df5.shape)
print('   columns:', df5.columns.tolist())
display(df5)

1. get_gen_fuel_type: (24, 8)
   columns: ['dt', 'hr', 'spp_fuelmix_hydro_forecast_f', 'spp_fuelmix_nuclear_forecast_f', 'spp_fuelmix_naturalgas_forecast_f', 'spp_fuelmix_hydro_actual_a', 'spp_fuelmix_nuclear_actual_a', 'spp_fuelmix_naturalgas_actual_a']

,dt,hr,spp_fuelmix_hydro_forecast_f,spp_fuelmix_nuclear_forecast_f,spp_fuelmix_naturalgas_forecast_f,spp_fuelmix_hydro_actual_a,spp_fuelmix_nuclear_actual_a,spp_fuelmix_naturalgas_actual_a
0,2026-04-01,1,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-04-01,2,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-04-01,3,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-04-01,4,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-04-01,5,NaN,NaN,NaN,NaN,NaN,NaN
5,2026-04-01,6,NaN,NaN,NaN,NaN,NaN,NaN
6,2026-04-01,7,NaN,NaN,NaN,NaN,NaN,NaN
7,2026-04-01,8,NaN,NaN,NaN,NaN,NaN,NaN
8,2026-04-01,9,NaN,NaN,NaN,NaN,NaN,NaN
9,2026-04-01,10,NaN,NaN,NaN,1637.7,2022.2,14074.2
10,2026-04-01,11,NaN,NaN,NaN,1684.1,2023.1,14188.4
11,2026-04-01,12,NaN,NaN,NaN,1602.4,2020.8,13116.7
12,2026-04-01,13,NaN,NaN,NaN,1659.3,2022.6,11788.0
13,2026-04-01,14,NaN,NaN,NaN,1743.4,2022.8,11707.5
14,2026-04-01,15,NaN,NaN,NaN,1751.6,2022.0,9968.8
15,2026-04-01,16,NaN,NaN,NaN,1780.2,2021.9,9644.6
16,2026-04-01,17,NaN,NaN,NaN,1968.5,2021.4,9400.1
17,2026-04-01,18,NaN,NaN,NaN,2009.2,2022.3,9109.9
18,2026-04-01,19,NaN,NaN,NaN,2102.5,2021.2,9192.6
19,2026-04-01,20,NaN,NaN,NaN,1981.0,2021.5,8646.0
20,2026-04-01,21,NaN,NaN,NaN,1889.1,2019.6,7293.1
21,2026-04-01,22,NaN,NaN,NaN,1463.8,2020.0,6865.2
22,2026-04-01,23,NaN,NaN,NaN,1276.8,2019.5,6285.3
23,2026-04-01,24,NaN,NaN,NaN,802.8,2019.5,5630.1

2. get_gen_fuel_actual: (15, 12)
   fuel types: ['dt', 'hr', 'spp_gen_coal_mw', 'spp_gen_dieselfueloil_mw', 'spp_gen_hydro_mw', 'spp_gen_naturalgas_mw', 'spp_gen_nuclear_mw', 'spp_gen_other_mw', 'spp_gen_solar_mw', 'spp_gen_wastedisposalservices_mw', 'spp_gen_wasteheat_mw', 'spp_gen_wind_mw']

,dt,hr,spp_gen_coal_mw,spp_gen_dieselfueloil_mw,spp_gen_hydro_mw,spp_gen_naturalgas_mw,spp_gen_nuclear_mw,spp_gen_other_mw,spp_gen_solar_mw,spp_gen_wastedisposalservices_mw,spp_gen_wasteheat_mw,spp_gen_wind_mw
0,2026-04-01,10,8277.2,70.2,1637.7,14074.2,2022.2,81.7,772.8,7.0,0.0,7332.9
1,2026-04-01,11,8448.3,124.1,1684.1,14188.4,2023.1,117.3,963.5,7.8,0.0,7052.8
2,2026-04-01,12,8019.9,190.0,1602.4,13116.7,2020.8,42.8,1152.7,7.8,0.0,7547.7
3,2026-04-01,13,7712.1,229.9,1659.3,11788.0,2022.6,44.7,1247.4,7.7,0.0,9298.3
4,2026-04-01,14,7478.9,218.9,1743.4,11707.5,2022.8,57.2,1212.8,7.8,0.0,11275.6
5,2026-04-01,15,7150.5,165.4,1751.6,9968.8,2022.0,70.9,991.6,7.8,0.0,13926.5
6,2026-04-01,16,7259.8,122.4,1780.2,9644.6,2021.9,68.2,854.0,7.9,0.0,15508.1
7,2026-04-01,17,7674.2,72.5,1968.5,9400.1,2021.4,56.2,607.3,7.9,0.0,15249.4
8,2026-04-01,18,7579.6,27.8,2009.2,9109.9,2022.3,50.1,361.8,7.9,0.0,15471.2
9,2026-04-01,19,7865.9,40.8,2102.5,9192.6,2021.2,56.8,118.0,6.7,0.0,15949.2
10,2026-04-01,20,7997.3,74.7,1981.0,8646.0,2021.5,52.1,17.3,6.3,0.0,16883.6
11,2026-04-01,21,7401.8,121.9,1889.1,7293.1,2019.6,38.7,0.2,6.3,0.0,18233.7
12,2026-04-01,22,6157.5,100.8,1463.8,6865.2,2020.0,37.9,0.2,6.4,0.0,18638.9
13,2026-04-01,23,5013.5,88.0,1276.8,6285.3,2019.5,36.0,0.3,6.4,0.0,18955.1
14,2026-04-01,24,4473.2,131.6,802.8,5630.1,2019.5,30.5,0.2,6.3,0.0,19826.3

3. get_baa_zonal_gen_fuel_type: (48, 9)
   columns: ['dt', 'hr', 'baa_zone', 'spp_baa_zonal_fuelmix_hydro_actual_a', 'spp_baa_zonal_fuelmix_hydro_forecast_f', 'spp_baa_zonal_fuelmix_nuclear_actual_a', 'spp_baa_zonal_fuelmix_nuclear_forecast_f', 'spp_baa_zonal_fuelmix_naturalgas_actual_a', 'spp_baa_zonal_fuelmix_naturalgas_forecast_f']

,dt,hr,baa_zone,spp_baa_zonal_fuelmix_hydro_actual_a,spp_baa_zonal_fuelmix_hydro_forecast_f,spp_baa_zonal_fuelmix_nuclear_actual_a,spp_baa_zonal_fuelmix_nuclear_forecast_f,spp_baa_zonal_fuelmix_naturalgas_actual_a,spp_baa_zonal_fuelmix_naturalgas_forecast_f
0,2026-04-01,1,E,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-04-01,1,W,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-04-01,2,E,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-04-01,2,W,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-04-01,3,E,NaN,NaN,NaN,NaN,NaN,NaN
5,2026-04-01,3,W,NaN,NaN,NaN,NaN,NaN,NaN
6,2026-04-01,4,E,NaN,NaN,NaN,NaN,NaN,NaN
7,2026-04-01,4,W,NaN,NaN,NaN,NaN,NaN,NaN
8,2026-04-01,5,E,NaN,NaN,NaN,NaN,NaN,NaN
9,2026-04-01,5,W,NaN,NaN,NaN,NaN,NaN,NaN
10,2026-04-01,6,E,NaN,NaN,NaN,NaN,NaN,NaN
11,2026-04-01,6,W,NaN,NaN,NaN,NaN,NaN,NaN
12,2026-04-01,7,E,NaN,NaN,NaN,NaN,NaN,NaN
13,2026-04-01,7,W,NaN,NaN,NaN,NaN,NaN,NaN
14,2026-04-01,8,E,NaN,NaN,NaN,NaN,NaN,NaN
15,2026-04-01,8,W,NaN,NaN,NaN,NaN,NaN,NaN
16,2026-04-01,9,E,NaN,NaN,NaN,NaN,NaN,NaN
17,2026-04-01,9,W,NaN,NaN,NaN,NaN,NaN,NaN
18,2026-04-01,10,E,1145.2,NaN,2022.2,NaN,13432.7,NaN
19,2026-04-01,10,W,492.5,NaN,0.0,NaN,641.5,NaN
20,2026-04-01,11,E,1248.4,NaN,2023.1,NaN,13560.0,NaN
21,2026-04-01,11,W,435.7,NaN,0.0,NaN,628.3,NaN
22,2026-04-01,12,E,1171.2,NaN,2020.8,NaN,12634.2,NaN
23,2026-04-01,12,W,431.2,NaN,0.0,NaN,482.6,NaN
24,2026-04-01,13,E,1222.9,NaN,2022.6,NaN,11442.4,NaN
25,2026-04-01,13,W,436.4,NaN,0.0,NaN,345.6,NaN
26,2026-04-01,14,E,1287.3,NaN,2022.8,NaN,11296.4,NaN
27,2026-04-01,14,W,456.1,NaN,0.0,NaN,411.0,NaN
28,2026-04-01,15,E,1305.1,NaN,2022.0,NaN,9643.5,NaN
29,2026-04-01,15,W,446.5,NaN,0.0,NaN,325.3,NaN
30,2026-04-01,16,E,1316.9,NaN,2021.9,NaN,9317.1,NaN
31,2026-04-01,16,W,463.3,NaN,0.0,NaN,327.6,NaN
32,2026-04-01,17,E,1488.5,NaN,2021.4,NaN,8994.1,NaN
33,2026-04-01,17,W,480.0,NaN,0.0,NaN,406.0,NaN
34,2026-04-01,18,E,1500.2,NaN,2022.3,NaN,8658.2,NaN
35,2026-04-01,18,W,508.9,NaN,0.0,NaN,451.7,NaN
36,2026-04-01,19,E,1507.8,NaN,2021.2,NaN,8650.7,NaN
37,2026-04-01,19,W,594.7,NaN,0.0,NaN,541.9,NaN
38,2026-04-01,20,E,1359.2,NaN,2021.5,NaN,8079.5,NaN
39,2026-04-01,20,W,621.8,NaN,0.0,NaN,566.5,NaN
40,2026-04-01,21,E,1275.5,NaN,2019.6,NaN,6687.8,NaN
41,2026-04-01,21,W,613.5,NaN,0.0,NaN,605.3,NaN
42,2026-04-01,22,E,887.9,NaN,2020.0,NaN,6239.4,NaN
43,2026-04-01,22,W,575.8,NaN,0.0,NaN,625.8,NaN
44,2026-04-01,23,E,751.0,NaN,2019.5,NaN,5670.4,NaN
45,2026-04-01,23,W,525.8,NaN,0.0,NaN,614.9,NaN
46,2026-04-01,24,E,340.9,NaN,2019.5,NaN,4912.4,NaN
47,2026-04-01,24,W,462.0,NaN,0.0,NaN,717.8,NaN

4. get_baa_zonal_gen_fuel_actual: (15, 22)
   fuel types: ['dt', 'hr', 'e_spp_baa_zonal_gen_coal_mw', 'e_spp_baa_zonal_gen_dieselfueloil_mw', 'e_spp_baa_zonal_gen_hydro_mw', 'e_spp_baa_zonal_gen_naturalgas_mw', 'e_spp_baa_zonal_gen_nuclear_mw', 'e_spp_baa_zonal_gen_other_mw', 'e_spp_baa_zonal_gen_solar_mw', 'e_spp_baa_zonal_gen_wastedisposalservices_mw', 'e_spp_baa_zonal_gen_wasteheat_mw', 'e_spp_baa_zonal_gen_wind_mw', 'w_spp_baa_zonal_gen_coal_mw', 'w_spp_baa_zonal_gen_dieselfueloil_mw', 'w_spp_baa_zonal_gen_hydro_mw', 'w_spp_baa_zonal_gen_naturalgas_mw', 'w_spp_baa_zonal_gen_nuclear_mw', 'w_spp_baa_zonal_gen_other_mw', 'w_spp_baa_zonal_gen_solar_mw', 'w_spp_baa_zonal_gen_wastedisposalservices_mw', 'w_spp_baa_zonal_gen_wasteheat_mw', 'w_spp_baa_zonal_gen_wind_mw']

,dt,hr,e_spp_baa_zonal_gen_coal_mw,e_spp_baa_zonal_gen_dieselfueloil_mw,e_spp_baa_zonal_gen_hydro_mw,e_spp_baa_zonal_gen_naturalgas_mw,e_spp_baa_zonal_gen_nuclear_mw,e_spp_baa_zonal_gen_other_mw,e_spp_baa_zonal_gen_solar_mw,e_spp_baa_zonal_gen_wastedisposalservices_mw,...,w_spp_baa_zonal_gen_coal_mw,w_spp_baa_zonal_gen_dieselfueloil_mw,w_spp_baa_zonal_gen_hydro_mw,w_spp_baa_zonal_gen_naturalgas_mw,w_spp_baa_zonal_gen_nuclear_mw,w_spp_baa_zonal_gen_other_mw,w_spp_baa_zonal_gen_solar_mw,w_spp_baa_zonal_gen_wastedisposalservices_mw,w_spp_baa_zonal_gen_wasteheat_mw,w_spp_baa_zonal_gen_wind_mw
0,2026-04-01,10,7352.8,1.6,1145.2,13432.7,2022.2,77.0,633.7,7.0,...,924.4,68.6,492.5,641.5,0.0,4.7,139.2,0.0,0.0,597.4
1,2026-04-01,11,7422.4,45.5,1248.4,13560.0,2023.1,111.8,771.1,7.8,...,1025.9,78.6,435.7,628.3,0.0,5.6,192.4,0.0,0.0,581.4
2,2026-04-01,12,7193.6,144.7,1171.2,12634.2,2020.8,38.2,798.1,7.8,...,826.3,45.2,431.2,482.6,0.0,4.6,354.6,0.0,0.0,585.5
3,2026-04-01,13,6943.8,147.6,1222.9,11442.4,2022.6,39.9,882.9,7.7,...,768.3,82.4,436.4,345.6,0.0,4.8,364.5,0.0,0.0,543.9
4,2026-04-01,14,6652.1,147.5,1287.3,11296.4,2022.8,52.6,825.8,7.8,...,826.8,71.3,456.1,411.0,0.0,4.7,387.0,0.0,0.0,526.6
5,2026-04-01,15,6304.0,141.7,1305.1,9643.5,2022.0,66.2,569.6,7.8,...,846.4,23.7,446.5,325.3,0.0,4.7,422.0,0.0,0.0,532.3
6,2026-04-01,16,6472.7,96.4,1316.9,9317.1,2021.9,63.5,439.5,7.9,...,787.1,26.0,463.3,327.6,0.0,4.7,414.4,0.0,0.0,514.8
7,2026-04-01,17,6749.8,44.8,1488.5,8994.1,2021.4,51.5,256.2,7.9,...,924.5,27.7,480.0,406.0,0.0,4.7,351.1,0.0,0.0,486.7
8,2026-04-01,18,6593.0,1.6,1500.2,8658.2,2022.3,45.4,157.5,7.9,...,986.6,26.2,508.9,451.7,0.0,4.7,204.4,0.0,0.0,433.2
9,2026-04-01,19,6809.4,1.5,1507.8,8650.7,2021.2,52.1,49.4,6.7,...,1056.5,39.3,594.7,541.9,0.0,4.7,68.6,0.0,0.0,410.0
10,2026-04-01,20,6919.8,1.4,1359.2,8079.5,2021.5,47.4,2.2,6.3,...,1077.5,73.3,621.8,566.5,0.0,4.7,15.2,0.0,0.0,353.1
11,2026-04-01,21,6231.9,1.4,1275.5,6687.8,2019.6,33.8,0.2,6.3,...,1169.9,120.5,613.5,605.3,0.0,4.9,0.0,0.0,0.0,274.5
12,2026-04-01,22,4911.7,1.2,887.9,6239.4,2020.0,31.6,0.2,6.4,...,1245.8,99.6,575.8,625.8,0.0,6.3,0.0,0.0,0.0,175.4
13,2026-04-01,23,3880.4,1.2,751.0,5670.4,2019.5,31.4,0.3,6.4,...,1133.1,86.9,525.8,614.9,0.0,4.6,0.0,0.0,0.0,140.9
14,2026-04-01,24,3310.8,1.2,340.9,4912.4,2019.5,23.5,0.2,6.3,...,1162.5,130.4,462.0,717.8,0.0,7.0,0.0,0.0,0.0,191.3

5. get_spp_gas_output (deprecated): (24, 4)
   columns: ['dt', 'hr', 'spp_fuelmix_naturalgas_actual_a', 'spp_fuelmix_naturalgas_forecast_f']

/tmp/ipykernel_2635545/3805136757.py:39: DeprecationWarning: Call to deprecated function get_spp_gas_output.
  df5 = get_spp_gas_output(D, D, var_spec=['a', 'f'])

,dt,hr,spp_fuelmix_naturalgas_actual_a,spp_fuelmix_naturalgas_forecast_f
0,2026-04-01,1,NaN,NaN
1,2026-04-01,2,NaN,NaN
2,2026-04-01,3,NaN,NaN
3,2026-04-01,4,NaN,NaN
4,2026-04-01,5,NaN,NaN
5,2026-04-01,6,NaN,NaN
6,2026-04-01,7,NaN,NaN
7,2026-04-01,8,NaN,NaN
8,2026-04-01,9,NaN,NaN
9,2026-04-01,10,NaN,NaN
10,2026-04-01,11,14074.2,14074.2
11,2026-04-01,12,14188.4,14188.4
12,2026-04-01,13,13116.7,13116.7
13,2026-04-01,14,11788.0,11788.0
14,2026-04-01,15,11707.5,11707.5
15,2026-04-01,16,9968.8,9968.8
16,2026-04-01,17,9644.6,9644.6
17,2026-04-01,18,9400.1,9400.1
18,2026-04-01,19,9109.9,9109.9
19,2026-04-01,20,9192.6,9192.6
20,2026-04-01,21,8646.0,8646.0
21,2026-04-01,22,7293.1,7293.1
22,2026-04-01,23,6865.2,6865.2
23,2026-04-01,24,6285.3,6285.3

### 21. Gen Outage by Fuel Type

In [3]:
df_genout_total = genout.get_genoutage_by_level(START, END, area_list=['SPP'], var_spec=['f', 'a'])
print(df_genout_total.shape)
df_genout_total

(24, 5)

            dt  hr baa_zone  spp_genoutage_forecast_f  spp_genoutage_actual_a
0   2026-04-01   1      SPP                   25897.1                 25171.9
1   2026-04-01   2      SPP                   25907.1                 25179.9
2   2026-04-01   3      SPP                   25907.1                 25180.5
3   2026-04-01   4      SPP                   25907.7                 25183.5
4   2026-04-01   5      SPP                   25182.9                 25794.4
5   2026-04-01   6      SPP                   25180.6                 25792.1
6   2026-04-01   7      SPP                   25258.3                 25888.2
7   2026-04-01   8      SPP                   25152.3                 25286.2
8   2026-04-01   9      SPP                   25272.4                 25314.3
9   2026-04-01  10      SPP                   25265.0                 25306.9
10  2026-04-01  11      SPP                   25264.8                 25306.7
11  2026-04-01  12      SPP                   25264.8                 25349.7
12  2026-04-01  13      SPP                   25805.3                 25882.4
13  2026-04-01  14      SPP                   25806.5                 25883.9
14  2026-04-01  15      SPP                   25753.5                 25830.9
15  2026-04-01  16      SPP                   25755.8                 25833.2
16  2026-04-01  17      SPP                   25713.0                 25790.4
17  2026-04-01  18      SPP                   25714.3                 25791.7
18  2026-04-01  19      SPP                   25634.3                 25784.6
19  2026-04-01  20      SPP                   25634.6                 25784.8
20  2026-04-01  21      SPP                   25635.2                 25935.2
21  2026-04-01  22      SPP                   25635.2                 25935.2
22  2026-04-01  23      SPP                   25636.2                 25936.2
23  2026-04-01  24      SPP                   25636.2                 25936.2

In [4]:
df_outage_fuel = fueltype.get_genoutage_fuel_type('2026-04-01', '2026-04-01', var_spec=['f', 'a'])
print(df_outage_fuel.shape)

df_outage_fuel['total_f'] = df_outage_fuel.filter(regex='_f$').sum(axis=1)
df_outage_fuel['total_a'] = df_outage_fuel.filter(regex='_a$').sum(axis=1)
df_outage_fuel

(24, 14)

,dt,hr,spp_fuelmixoutage_coal_forecast_f,spp_fuelmixoutage_dieselfueloil_forecast_f,spp_fuelmixoutage_hydro_forecast_f,spp_fuelmixoutage_naturalgas_forecast_f,spp_fuelmixoutage_solar_forecast_f,spp_fuelmixoutage_wind_forecast_f,spp_fuelmixoutage_coal_actual_a,spp_fuelmixoutage_dieselfueloil_actual_a,spp_fuelmixoutage_hydro_actual_a,spp_fuelmixoutage_naturalgas_actual_a,spp_fuelmixoutage_solar_actual_a,spp_fuelmixoutage_wind_actual_a,total_f,total_a
0,2026-04-01,1,8488.8,72.0,936.0,14325.5,1155.7,625.5,8488.8,72.0,890.0,13752.5,1003.5,705.5,25603.5,24912.3
1,2026-04-01,2,8488.8,72.0,936.0,14335.5,1155.7,625.5,8488.8,72.0,890.0,13762.5,1003.5,705.5,25613.5,24922.3
2,2026-04-01,3,8488.8,72.0,936.0,14335.5,1155.7,625.5,8488.8,72.0,890.0,13762.5,1003.5,705.5,25613.5,24922.3
3,2026-04-01,4,8488.8,72.0,936.0,14335.5,1155.7,625.5,8488.8,72.0,890.0,13762.5,1003.5,705.5,25613.5,24922.3
4,2026-04-01,5,8488.8,72.0,890.0,13762.5,1003.5,705.5,8938.8,72.0,890.0,13973.9,781.5,824.5,24922.3,25480.7
5,2026-04-01,6,8488.8,72.0,890.0,13762.5,1003.5,705.5,8938.8,72.0,890.0,13973.9,781.5,824.5,24922.3,25480.7
6,2026-04-01,7,8488.8,72.0,890.0,13847.5,1003.5,705.5,8938.8,72.0,890.0,14077.2,781.5,824.5,25007.3,25584.0
7,2026-04-01,8,8488.8,72.0,890.0,13892.5,853.5,705.5,8488.8,72.0,890.0,14074.2,631.5,824.5,24902.3,24981.0
8,2026-04-01,9,8488.8,266.0,890.0,13892.5,781.5,705.5,8488.8,266.0,890.0,14109.9,631.5,625.5,25024.3,25011.7
9,2026-04-01,10,8488.8,266.0,890.0,13892.5,781.5,705.5,8488.8,266.0,890.0,14109.9,631.5,625.5,25024.3,25011.7
10,2026-04-01,11,8488.8,266.0,890.0,13892.5,781.5,705.5,8488.8,266.0,890.0,14109.9,631.5,625.5,25024.3,25011.7
11,2026-04-01,12,8488.8,266.0,890.0,13892.5,781.5,705.5,8488.8,266.0,890.0,14152.9,631.5,625.5,25024.3,25054.7
12,2026-04-01,13,9024.8,266.0,890.0,13892.5,781.5,705.5,9025.8,266.0,890.0,14150.5,631.5,625.5,25560.3,25589.3
13,2026-04-01,14,9024.8,266.0,890.0,13892.5,781.5,705.5,9025.8,266.0,890.0,14150.5,631.5,625.5,25560.3,25589.3
14,2026-04-01,15,9024.8,212.0,890.0,13892.5,781.5,705.5,9025.8,212.0,890.0,14150.5,631.5,625.5,25506.3,25535.3
15,2026-04-01,16,9024.8,212.0,890.0,13892.5,781.5,705.5,9025.8,212.0,890.0,14150.5,631.5,625.5,25506.3,25535.3
16,2026-04-01,17,9024.8,212.0,890.0,13847.5,781.5,705.5,9025.8,212.0,890.0,14105.5,631.5,625.5,25461.3,25490.3
17,2026-04-01,18,9024.8,212.0,890.0,13847.5,781.5,705.5,9025.8,212.0,890.0,14105.5,631.5,625.5,25461.3,25490.3
18,2026-04-01,19,9024.8,212.0,890.0,13847.5,781.5,625.5,9025.8,212.0,890.0,14096.5,631.5,625.5,25381.3,25481.3
19,2026-04-01,20,9024.8,212.0,890.0,13847.5,781.5,625.5,9025.8,212.0,890.0,14096.5,631.5,625.5,25381.3,25481.3
20,2026-04-01,21,9024.8,212.0,890.0,13847.5,781.5,625.5,9025.8,212.0,890.0,14096.5,781.5,625.5,25381.3,25631.3
21,2026-04-01,22,9024.8,212.0,890.0,13847.5,781.5,625.5,9025.8,212.0,890.0,14096.5,781.5,625.5,25381.3,25631.3
22,2026-04-01,23,9024.8,212.0,890.0,13847.5,781.5,625.5,9025.8,212.0,890.0,14096.5,781.5,625.5,25381.3,25631.3
23,2026-04-01,24,9024.8,212.0,890.0,13847.5,781.5,625.5,9025.8,212.0,890.0,14096.5,781.5,625.5,25381.3,25631.3

In [5]:
# ── DIAGNOSTIC: why fuel-type sum != GeneratorOutageNew total ──────────────
import pandas as pd
from nighthawk.util import connections, sql_functions

# 1. Raw GeneratorOutageNew — dt/hr already in SPP market time
df_gon = sql_functions.download_df_from_sql_db(
    "SELECT dt, hr, ForecastOutage, ActualOutage "
    "FROM spp_physical.GeneratorOutageNew "
    "WHERE dt = '2026-04-01' ORDER BY hr"
)
df_gon['dt'] = df_gon['dt'].astype(str)
print('GeneratorOutageNew columns:', df_gon.columns.tolist())
print('Rows:', len(df_gon))
display(df_gon)

# 2. Raw fuel-type tables — dthr is UTC hour-ending
#    nighthawk converts: tz_localize(UTC) -> tz_convert(US/Central) - 1h, then hr = local_hour + 1
fuel_cols = ['CoalMW','DieselFuelOilMW','HydroMW','NaturalGasMW','SolarMW','WindMW']

df_ftype_f = sql_functions.download_df_from_sql_db(
    "SELECT dthr, CoalMW, DieselFuelOilMW, HydroMW, NaturalGasMW, SolarMW, WindMW "
    "FROM spp_physical.GenOutagebyFuelTypeForecast "
    "WHERE DATE(dthr) >= DATE_SUB('2026-04-01', INTERVAL 1 DAY) "
    "  AND DATE(dthr) <= DATE_ADD('2026-04-01', INTERVAL 1 DAY) ORDER BY dthr"
)
df_ftype_a = sql_functions.download_df_from_sql_db(
    "SELECT dthr, CoalMW, DieselFuelOilMW, HydroMW, NaturalGasMW, SolarMW, WindMW "
    "FROM spp_physical.GenOutagebyFuelTypeActual "
    "WHERE DATE(dthr) >= DATE_SUB('2026-04-01', INTERVAL 1 DAY) "
    "  AND DATE(dthr) <= DATE_ADD('2026-04-01', INTERVAL 1 DAY) ORDER BY dthr"
)

for df, tag in [(df_ftype_f, 'Forecast'), (df_ftype_a, 'Actual')]:
    df['dthr'] = pd.to_datetime(df['dthr']).dt.tz_localize('UTC').dt.tz_convert('US/Central') - pd.Timedelta('1h')
    df['dt']   = df['dthr'].dt.strftime('%Y-%m-%d')
    df['hr']   = df['dthr'].dt.hour + 1
    df.drop(columns=['dthr'], inplace=True)
    df['fuel_sum'] = df[fuel_cols].sum(axis=1)
    print(f'GenOutagebyFuelType{tag} rows after tz-convert:', len(df))
    display(df[df['dt'] == '2026-04-01'][['dt','hr','fuel_sum'] + fuel_cols])

# 3. Side-by-side on target date
df_f_day = df_ftype_f[df_ftype_f['dt'] == '2026-04-01'][['dt','hr','fuel_sum']].rename(columns={'fuel_sum':'fuel_sum_f'})
df_a_day = df_ftype_a[df_ftype_a['dt'] == '2026-04-01'][['dt','hr','fuel_sum']].rename(columns={'fuel_sum':'fuel_sum_a'})
df_gon_day = df_gon[df_gon['dt'] == '2026-04-01'][['dt','hr','ForecastOutage','ActualOutage']]

cmp = df_gon_day.merge(df_f_day, on=['dt','hr'], how='outer').merge(df_a_day, on=['dt','hr'], how='outer')
cmp['diff_f'] = cmp['ForecastOutage'] - cmp['fuel_sum_f']
cmp['diff_a'] = cmp['ActualOutage']   - cmp['fuel_sum_a']
print('\n=== Comparison: GeneratorOutageNew vs fuel_type_sum ===')
display(cmp)
print('Max |diff_f|:', cmp['diff_f'].abs().max(), '  Max |diff_a|:', cmp['diff_a'].abs().max())
print('Hours with diff_f != 0:', (cmp['diff_f'].abs() > 0.01).sum())
print('Hours with diff_a != 0:', (cmp['diff_a'].abs() > 0.01).sum())

# 4. Inspect all columns of GeneratorOutageNew (may reveal extra fuel type fields)
df_raw = sql_functions.download_df_from_sql_db("SELECT * FROM spp_physical.GeneratorOutageNew WHERE dt = '2026-04-01' LIMIT 3")
print('\nAll columns in GeneratorOutageNew:', df_raw.columns.tolist())
display(df_raw)

GeneratorOutageNew columns: ['dt', 'hr', 'ForecastOutage', 'ActualOutage']
Rows: 24

            dt  hr  ForecastOutage  ActualOutage
0   2026-04-01   1         25715.9       25197.9
1   2026-04-01   2         25728.3       25198.1
2   2026-04-01   3         25878.9       25348.7
3   2026-04-01   4         25878.9       25348.7
4   2026-04-01   5         25712.9       25182.7
5   2026-04-01   6         25612.9       25182.7
6   2026-04-01   7         25897.1       25171.9
7   2026-04-01   8         25907.1       25179.9
8   2026-04-01   9         25907.1       25180.5
9   2026-04-01  10         25907.7       25183.5
10  2026-04-01  11         25182.9       25794.4
11  2026-04-01  12         25180.6       25792.1
12  2026-04-01  13         25258.3       25888.2
13  2026-04-01  14         25152.3       25286.2
14  2026-04-01  15         25272.4       25314.3
15  2026-04-01  16         25265.0       25306.9
16  2026-04-01  17         25264.8       25306.7
17  2026-04-01  18         25264.8       25349.7
18  2026-04-01  19         25805.3       25882.4
19  2026-04-01  20         25806.5       25883.9
20  2026-04-01  21         25753.5       25830.9
21  2026-04-01  22         25755.8       25833.2
22  2026-04-01  23         25713.0       25790.4
23  2026-04-01  24         25714.3       25791.7

GenOutagebyFuelTypeForecast rows after tz-convert: 72

,dt,hr,fuel_sum,CoalMW,DieselFuelOilMW,HydroMW,NaturalGasMW,SolarMW,WindMW
30,2026-04-01,1,25603.5,8488.8,72.0,936.0,14325.5,1155.7,625.5
31,2026-04-01,2,25613.5,8488.8,72.0,936.0,14335.5,1155.7,625.5
32,2026-04-01,3,25613.5,8488.8,72.0,936.0,14335.5,1155.7,625.5
33,2026-04-01,4,25613.5,8488.8,72.0,936.0,14335.5,1155.7,625.5
34,2026-04-01,5,24922.3,8488.8,72.0,890.0,13762.5,1003.5,705.5
35,2026-04-01,6,24922.3,8488.8,72.0,890.0,13762.5,1003.5,705.5
36,2026-04-01,7,25007.3,8488.8,72.0,890.0,13847.5,1003.5,705.5
37,2026-04-01,8,24902.3,8488.8,72.0,890.0,13892.5,853.5,705.5
38,2026-04-01,9,25024.3,8488.8,266.0,890.0,13892.5,781.5,705.5
39,2026-04-01,10,25024.3,8488.8,266.0,890.0,13892.5,781.5,705.5
40,2026-04-01,11,25024.3,8488.8,266.0,890.0,13892.5,781.5,705.5
41,2026-04-01,12,25024.3,8488.8,266.0,890.0,13892.5,781.5,705.5
42,2026-04-01,13,25560.3,9024.8,266.0,890.0,13892.5,781.5,705.5
43,2026-04-01,14,25560.3,9024.8,266.0,890.0,13892.5,781.5,705.5
44,2026-04-01,15,25506.3,9024.8,212.0,890.0,13892.5,781.5,705.5
45,2026-04-01,16,25506.3,9024.8,212.0,890.0,13892.5,781.5,705.5
46,2026-04-01,17,25461.3,9024.8,212.0,890.0,13847.5,781.5,705.5
47,2026-04-01,18,25461.3,9024.8,212.0,890.0,13847.5,781.5,705.5
48,2026-04-01,19,25381.3,9024.8,212.0,890.0,13847.5,781.5,625.5
49,2026-04-01,20,25381.3,9024.8,212.0,890.0,13847.5,781.5,625.5
50,2026-04-01,21,25381.3,9024.8,212.0,890.0,13847.5,781.5,625.5
51,2026-04-01,22,25381.3,9024.8,212.0,890.0,13847.5,781.5,625.5
52,2026-04-01,23,25381.3,9024.8,212.0,890.0,13847.5,781.5,625.5
53,2026-04-01,24,25381.3,9024.8,212.0,890.0,13847.5,781.5,625.5

GenOutagebyFuelTypeActual rows after tz-convert: 72

,dt,hr,fuel_sum,CoalMW,DieselFuelOilMW,HydroMW,NaturalGasMW,SolarMW,WindMW
30,2026-04-01,1,24912.3,8488.8,72.0,890.0,13752.5,1003.5,705.5
31,2026-04-01,2,24922.3,8488.8,72.0,890.0,13762.5,1003.5,705.5
32,2026-04-01,3,24922.3,8488.8,72.0,890.0,13762.5,1003.5,705.5
33,2026-04-01,4,24922.3,8488.8,72.0,890.0,13762.5,1003.5,705.5
34,2026-04-01,5,25480.7,8938.8,72.0,890.0,13973.9,781.5,824.5
35,2026-04-01,6,25480.7,8938.8,72.0,890.0,13973.9,781.5,824.5
36,2026-04-01,7,25584.0,8938.8,72.0,890.0,14077.2,781.5,824.5
37,2026-04-01,8,24981.0,8488.8,72.0,890.0,14074.2,631.5,824.5
38,2026-04-01,9,25011.7,8488.8,266.0,890.0,14109.9,631.5,625.5
39,2026-04-01,10,25011.7,8488.8,266.0,890.0,14109.9,631.5,625.5
40,2026-04-01,11,25011.7,8488.8,266.0,890.0,14109.9,631.5,625.5
41,2026-04-01,12,25054.7,8488.8,266.0,890.0,14152.9,631.5,625.5
42,2026-04-01,13,25589.3,9025.8,266.0,890.0,14150.5,631.5,625.5
43,2026-04-01,14,25589.3,9025.8,266.0,890.0,14150.5,631.5,625.5
44,2026-04-01,15,25535.3,9025.8,212.0,890.0,14150.5,631.5,625.5
45,2026-04-01,16,25535.3,9025.8,212.0,890.0,14150.5,631.5,625.5
46,2026-04-01,17,25490.3,9025.8,212.0,890.0,14105.5,631.5,625.5
47,2026-04-01,18,25490.3,9025.8,212.0,890.0,14105.5,631.5,625.5
48,2026-04-01,19,25481.3,9025.8,212.0,890.0,14096.5,631.5,625.5
49,2026-04-01,20,25481.3,9025.8,212.0,890.0,14096.5,631.5,625.5
50,2026-04-01,21,25631.3,9025.8,212.0,890.0,14096.5,781.5,625.5
51,2026-04-01,22,25631.3,9025.8,212.0,890.0,14096.5,781.5,625.5
52,2026-04-01,23,25631.3,9025.8,212.0,890.0,14096.5,781.5,625.5
53,2026-04-01,24,25631.3,9025.8,212.0,890.0,14096.5,781.5,625.5

=== Comparison: GeneratorOutageNew vs fuel_type_sum ===

,dt,hr,ForecastOutage,ActualOutage,fuel_sum_f,fuel_sum_a,diff_f,diff_a
0,2026-04-01,1,25715.9,25197.9,25603.5,24912.3,112.4,285.6
1,2026-04-01,2,25728.3,25198.1,25613.5,24922.3,114.8,275.8
2,2026-04-01,3,25878.9,25348.7,25613.5,24922.3,265.4,426.4
3,2026-04-01,4,25878.9,25348.7,25613.5,24922.3,265.4,426.4
4,2026-04-01,5,25712.9,25182.7,24922.3,25480.7,790.6,-298.0
5,2026-04-01,6,25612.9,25182.7,24922.3,25480.7,690.6,-298.0
6,2026-04-01,7,25897.1,25171.9,25007.3,25584.0,889.8,-412.1
7,2026-04-01,8,25907.1,25179.9,24902.3,24981.0,1004.8,198.9
8,2026-04-01,9,25907.1,25180.5,25024.3,25011.7,882.8,168.8
9,2026-04-01,10,25907.7,25183.5,25024.3,25011.7,883.4,171.8
10,2026-04-01,11,25182.9,25794.4,25024.3,25011.7,158.6,782.7
11,2026-04-01,12,25180.6,25792.1,25024.3,25054.7,156.3,737.4
12,2026-04-01,13,25258.3,25888.2,25560.3,25589.3,-302.0,298.9
13,2026-04-01,14,25152.3,25286.2,25560.3,25589.3,-408.0,-303.1
14,2026-04-01,15,25272.4,25314.3,25506.3,25535.3,-233.9,-221.0
15,2026-04-01,16,25265.0,25306.9,25506.3,25535.3,-241.3,-228.4
16,2026-04-01,17,25264.8,25306.7,25461.3,25490.3,-196.5,-183.6
17,2026-04-01,18,25264.8,25349.7,25461.3,25490.3,-196.5,-140.6
18,2026-04-01,19,25805.3,25882.4,25381.3,25481.3,424.0,401.1
19,2026-04-01,20,25806.5,25883.9,25381.3,25481.3,425.2,402.6
20,2026-04-01,21,25753.5,25830.9,25381.3,25631.3,372.2,199.6
21,2026-04-01,22,25755.8,25833.2,25381.3,25631.3,374.5,201.9
22,2026-04-01,23,25713.0,25790.4,25381.3,25631.3,331.7,159.1
23,2026-04-01,24,25714.3,25791.7,25381.3,25631.3,333.0,160.4

Max |diff_f|: 1004.7999999999993   Max |diff_a|: 782.7000000000044
Hours with diff_f != 0: 24
Hours with diff_a != 0: 24

All columns in GeneratorOutageNew: ['dt', 'hr', 'ActualOutage', 'ForecastOutage']

           dt  hr  ActualOutage  ForecastOutage
0  2026-04-01   1       25197.9         25715.9
1  2026-04-01   2       25198.1         25728.3
2  2026-04-01   3       25348.7         25878.9

### 21b. get_genoutage_fuel_type — market-total outage by fuel type

SPP only. Reads `spp_physical.GenOutagebyFuelTypeForecast` and `GenOutagebyFuelTypeActual`.

In [7]:
df_outage_fuel = fueltype.get_genoutage_fuel_type('2026-04-01', '2026-04-01', var_spec=['f', 'a'])
print(df_outage_fuel)

            dt  hr  spp_fuelmixoutage_coal_forecast_f  \
0   2026-04-01   1                             8488.8
1   2026-04-01   2                             8488.8
2   2026-04-01   3                             8488.8
3   2026-04-01   4                             8488.8
4   2026-04-01   5                             8488.8
5   2026-04-01   6                             8488.8
6   2026-04-01   7                             8488.8
7   2026-04-01   8                             8488.8
8   2026-04-01   9                             8488.8
9   2026-04-01  10                             8488.8
10  2026-04-01  11                             8488.8
11  2026-04-01  12                             8488.8
12  2026-04-01  13                             9024.8
13  2026-04-01  14                             9024.8
14  2026-04-01  15                             9024.8
15  2026-04-01  16                             9024.8
16  2026-04-01  17                             9024.8
17  2026-04-01  18                             9024.8
18  2026-04-01  19                             9024.8
19  2026-04-01  20                             9024.8
20  2026-04-01  21                             9024.8
21  2026-04-01  22                             9024.8
22  2026-04-01  23                             9024.8
23  2026-04-01  24                             9024.8

    spp_fuelmixoutage_dieselfueloil_forecast_f  \
0                                         72.0
1                                         72.0
2                                         72.0
3                                         72.0
4                                         72.0
5                                         72.0
6                                         72.0
7                                         72.0
8                                        266.0
9                                        266.0
10                                       266.0
11                                       266.0
12                                       266.0
13                                       266.0
14                                       212.0
15                                       212.0
16                                       212.0
17                                       212.0
18                                       212.0
19                                       212.0
20                                       212.0
21                                       212.0
22                                       212.0
23                                       212.0

    spp_fuelmixoutage_hydro_forecast_f  \
0                                936.0
1                                936.0
2                                936.0
3                                936.0
4                                890.0
5                                890.0
6                                890.0
7                                890.0
8                                890.0
9                                890.0
10                               890.0
11                               890.0
12                               890.0
13                               890.0
14                               890.0
15                               890.0
16                               890.0
17                               890.0
18                               890.0
19                               890.0
20                               890.0
21                               890.0
22                               890.0
23                               890.0

    spp_fuelmixoutage_naturalgas_forecast_f  \
0                                   14325.5
1                                   14335.5
2                                   14335.5
3                                   14335.5
4                                   13762.5
5                                   13762.5
6                                   13847.5
7                                   13892.5
8                                   13892.5
9                                   13892.5
10                                  13892.5
11                                  13892.5
12                                  13892.5
13                                  13892.5
14                                  13892.5
15                                  13892.5
16                                  13847.5
17                                  13847.5
18                                  13847.5
19                                  13847.5
20                                  13847.5
21                                  13847.5
22                                  13847.5
23                                  13847.5

    spp_fuelmixoutage_solar_forecast_f  spp_fuelmixoutage_wind_forecast_f  \
0                               1155.7                              625.5
1                               1155.7                              625.5
2                               1155.7                              625.5
3                               1155.7                              625.5
4                               1003.5                              705.5
5                               1003.5                              705.5
6                               1003.5                              705.5
7                                853.5                              705.5
8                                781.5                              705.5
9                                781.5                              705.5
10                               781.5                              705.5
11                               781.5                              705.5
12                               781.5                              705.5
13                               781.5                              705.5
14                               781.5                              705.5
15                               781.5                              705.5
16                               781.5                              705.5
17                               781.5                              705.5
18                               781.5                              625.5
19                               781.5                              625.5
20                               781.5                              625.5
21                               781.5                              625.5
22                               781.5                              625.5
23                               781.5                              625.5

    spp_fuelmixoutage_coal_actual_a  spp_fuelmixoutage_dieselfueloil_actual_a  \
0                            8488.8                                      72.0
1                            8488.8                                      72.0
2                            8488.8                                      72.0
3                            8488.8                                      72.0
4                            8938.8                                      72.0
5                            8938.8                                      72.0
6                            8938.8                                      72.0
7                            8488.8                                      72.0
8                            8488.8                                     266.0
9                            8488.8                                     266.0
10                           8488.8                                     266.0
11                           8488.8                                     266.0
12                           9025.8                                     266.0
13                           9025.8                                     266.0
14                           9025.8                                     212.0
15                           9025.8                                     212.0
16                           9025.8                                     212.0
17                           9025.8                                     212.0
18                           9025.8                                     212.0
19                           9025.8                                     212.0
20                           9025.8                                     212.0
21                           9025.8                                     212.0
22                           9025.8                                     212.0
23                           9025.8                                     212.0

    spp_fuelmixoutage_hydro_actual_a  spp_fuelmixoutage_naturalgas_actual_a  \
0                              890.0                                13752.5
1                              890.0                                13762.5
2                              890.0                                13762.5
3                              890.0                                13762.5
4                              890.0                                13973.9
5                              890.0                                13973.9
6                              890.0                                14077.2
7                              890.0                                14074.2
8                              890.0                                14109.9
9                              890.0                                14109.9
10                             890.0                                14109.9
11                             890.0                                14152.9
12                             890.0                                14150.5
13                             890.0                                14150.5
14                             890.0                                14150.5
15                             890.0                                14150.5
16                             890.0                                14105.5
17                             890.0                                14105.5
18                             890.0                                14096.5
19                             890.0                                14096.5
20                             890.0                                14096.5
21                             890.0                                14096.5
22                             890.0                                14096.5
23                             890.0                                14096.5

    spp_fuelmixoutage_solar_actual_a  spp_fuelmixoutage_wind_actual_a
0                             1003.5                            705.5
1                             1003.5                            705.5
2                             1003.5                            705.5
3                             1003.5                            705.5
4                              781.5                            824.5
5                              781.5                            824.5
6                              781.5                            824.5
7                              631.5                            824.5
8                              631.5                            625.5
9                              631.5                            625.5
10                             631.5                            625.5
11                             631.5                            625.5
12                             631.5                            625.5
13                             631.5                            625.5
14                             631.5                            625.5
15                             631.5                            625.5
16                             631.5                            625.5
17                             631.5                            625.5
18                             631.5                            625.5
19                             631.5                            625.5
20                             781.5                            625.5
21                             781.5                            625.5
22                             781.5                            625.5
23                             781.5                            625.5

### 21c. get_baa_zonal_genoutage_fuel_type — BAA-zonal outage by fuel type

SPP only. Reads `spp_physical.BAAZonalGenOutagebyFuelTypeForecast` and `BAAZonalGenOutagebyFuelTypeActual`.

In [8]:
df_baa_outage_fuel = fueltype.get_baa_zonal_genoutage_fuel_type('2026-04-01', '2026-04-01', baa_zones=['E', 'W'], var_spec=['f', 'a'])
print(df_baa_outage_fuel.shape)
print(df_baa_outage_fuel.columns.tolist())
display(df_baa_outage_fuel)

(48, 15)
['dt', 'hr', 'baa_zone', 'spp_baa_zonal_fuelmixoutage_coal_forecast_f', 'spp_baa_zonal_fuelmixoutage_dieselfueloil_forecast_f', 'spp_baa_zonal_fuelmixoutage_hydro_forecast_f', 'spp_baa_zonal_fuelmixoutage_naturalgas_forecast_f', 'spp_baa_zonal_fuelmixoutage_solar_forecast_f', 'spp_baa_zonal_fuelmixoutage_wind_forecast_f', 'spp_baa_zonal_fuelmixoutage_coal_actual_a', 'spp_baa_zonal_fuelmixoutage_dieselfueloil_actual_a', 'spp_baa_zonal_fuelmixoutage_hydro_actual_a', 'spp_baa_zonal_fuelmixoutage_naturalgas_actual_a', 'spp_baa_zonal_fuelmixoutage_solar_actual_a', 'spp_baa_zonal_fuelmixoutage_wind_actual_a']

,dt,hr,baa_zone,spp_baa_zonal_fuelmixoutage_coal_forecast_f,spp_baa_zonal_fuelmixoutage_dieselfueloil_forecast_f,spp_baa_zonal_fuelmixoutage_hydro_forecast_f,spp_baa_zonal_fuelmixoutage_naturalgas_forecast_f,spp_baa_zonal_fuelmixoutage_solar_forecast_f,spp_baa_zonal_fuelmixoutage_wind_forecast_f,spp_baa_zonal_fuelmixoutage_coal_actual_a,spp_baa_zonal_fuelmixoutage_dieselfueloil_actual_a,spp_baa_zonal_fuelmixoutage_hydro_actual_a,spp_baa_zonal_fuelmixoutage_naturalgas_actual_a,spp_baa_zonal_fuelmixoutage_solar_actual_a,spp_baa_zonal_fuelmixoutage_wind_actual_a
0,2026-04-01,1,E,8488.8,72.0,936.0,14325.5,1155.7,625.5,8488.8,72.0,890.0,13752.5,1003.5,705.5
1,2026-04-01,1,W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-04-01,2,E,8488.8,72.0,936.0,14335.5,1155.7,625.5,8488.8,72.0,890.0,13762.5,1003.5,705.5
3,2026-04-01,2,W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-04-01,3,E,8488.8,72.0,936.0,14335.5,1155.7,625.5,8488.8,72.0,890.0,13762.5,1003.5,705.5
5,2026-04-01,3,W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2026-04-01,4,E,8488.8,72.0,936.0,14335.5,1155.7,625.5,8488.8,72.0,890.0,13762.5,1003.5,705.5
7,2026-04-01,4,W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2026-04-01,5,E,8488.8,72.0,890.0,13762.5,1003.5,705.5,8938.8,72.0,890.0,13973.9,781.5,824.5
9,2026-04-01,5,W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2026-04-01,6,E,8488.8,72.0,890.0,13762.5,1003.5,705.5,8938.8,72.0,890.0,13973.9,781.5,824.5
11,2026-04-01,6,W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2026-04-01,7,E,8488.8,72.0,890.0,13847.5,1003.5,705.5,8938.8,72.0,890.0,14077.2,781.5,824.5
13,2026-04-01,7,W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2026-04-01,8,E,8488.8,72.0,890.0,13892.5,853.5,705.5,8488.8,72.0,890.0,14074.2,631.5,824.5
15,2026-04-01,8,W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2026-04-01,9,E,8488.8,266.0,890.0,13892.5,781.5,705.5,8488.8,266.0,890.0,14109.9,631.5,625.5
17,2026-04-01,9,W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2026-04-01,10,E,8488.8,266.0,890.0,13892.5,781.5,705.5,8488.8,266.0,890.0,14109.9,631.5,625.5
19,2026-04-01,10,W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2026-04-01,11,E,8488.8,266.0,890.0,13892.5,781.5,705.5,8488.8,266.0,890.0,14109.9,631.5,625.5
21,2026-04-01,11,W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2026-04-01,12,E,8488.8,266.0,890.0,13892.5,781.5,705.5,8488.8,266.0,890.0,14152.9,631.5,625.5
23,2026-04-01,12,W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2026-04-01,13,E,9024.8,266.0,890.0,13892.5,781.5,705.5,9025.8,266.0,890.0,14150.5,631.5,625.5
25,2026-04-01,13,W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2026-04-01,14,E,9024.8,266.0,890.0,13892.5,781.5,705.5,9025.8,266.0,890.0,14150.5,631.5,625.5
27,2026-04-01,14,W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2026-04-01,15,E,9024.8,212.0,890.0,13892.5,781.5,705.5,9025.8,212.0,890.0,14150.5,631.5,625.5
29,2026-04-01,15,W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,2026-04-01,16,E,9024.8,212.0,890.0,13892.5,781.5,705.5,9025.8,212.0,890.0,14150.5,631.5,625.5
31,2026-04-01,16,W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,2026-04-01,17,E,9024.8,212.0,890.0,13847.5,781.5,705.5,9025.8,212.0,890.0,14105.5,631.5,625.5
33,2026-04-01,17,W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,2026-04-01,18,E,9024.8,212.0,890.0,13847.5,781.5,705.5,9025.8,212.0,890.0,14105.5,631.5,625.5
35,2026-04-01,18,W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,2026-04-01,19,E,9024.8,212.0,890.0,13847.5,781.5,625.5,9025.8,212.0,890.0,14096.5,631.5,625.5
37,2026-04-01,19,W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,2026-04-01,20,E,9024.8,212.0,890.0,13847.5,781.5,625.5,9025.8,212.0,890.0,14096.5,631.5,625.5
39,2026-04-01,20,W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,2026-04-01,21,E,9024.8,212.0,890.0,13847.5,781.5,625.5,9025.8,212.0,890.0,14096.5,781.5,625.5
41,2026-04-01,21,W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,2026-04-01,22,E,9024.8,212.0,890.0,13847.5,781.5,625.5,9025.8,212.0,890.0,14096.5,781.5,625.5
43,2026-04-01,22,W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,2026-04-01,23,E,9024.8,212.0,890.0,13847.5,781.5,625.5,9025.8,212.0,890.0,14096.5,781.5,625.5
45,2026-04-01,23,W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,2026-04-01,24,E,9024.8,212.0,890.0,13847.5,781.5,625.5,9025.8,212.0,890.0,14096.5,781.5,625.5
47,2026-04-01,24,W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 21d. get_data_and_mapping_for_genoutage_fuel_type — wrapper with node mapping

Same as `get_genoutage_fuel_type` but returns `(data, mapping)` keyed by node.

In [9]:
from nighthawk.data.pipeline.var_handler.fuel_type import get_data_and_mapping_for_genoutage_fuel_type

data_goft, mapping_goft = get_data_and_mapping_for_genoutage_fuel_type(
    node_list=[636], opexchange='SPP',
    start_dt='2026-04-01', end_dt='2026-04-01',
    fuel_type=['Coal', 'DieselFuelOil', 'Hydro', 'NaturalGas', 'Solar', 'Wind'],
    impute=True
)
print('data shape:', data_goft.shape)
print('mapping shape:', mapping_goft.shape)
display(data_goft)
display(mapping_goft)

             dt  hr  spp_fuelmixoutage_coal_forecast_f  \
0 0  2026-04-01   1                             8488.8
1 1  2026-04-01   2                             8488.8
2 2  2026-04-01   3                             8488.8
3 3  2026-04-01   4                             8488.8
4 4  2026-04-01   5                             8488.8

     spp_fuelmixoutage_dieselfueloil_forecast_f  \
0 0                                        72.0
1 1                                        72.0
2 2                                        72.0
3 3                                        72.0
4 4                                        72.0

     spp_fuelmixoutage_hydro_forecast_f  \
0 0                               936.0
1 1                               936.0
2 2                               936.0
3 3                               936.0
4 4                               890.0

     spp_fuelmixoutage_naturalgas_forecast_f  \
0 0                                  14325.5
1 1                                  14335.5
2 2                                  14335.5
3 3                                  14335.5
4 4                                  13762.5

     spp_fuelmixoutage_solar_forecast_f  spp_fuelmixoutage_wind_forecast_f  \
0 0                              1155.7                              625.5
1 1                              1155.7                              625.5
2 2                              1155.7                              625.5
3 3                              1155.7                              625.5
4 4                              1003.5                              705.5

     spp_fuelmixoutage_coal_actual_a  \
0 0                           8488.8
1 1                           8488.8
2 2                           8488.8
3 3                           8488.8
4 4                           8938.8

     spp_fuelmixoutage_dieselfueloil_actual_a  \
0 0                                      72.0
1 1                                      72.0
2 2                                      72.0
3 3                                      72.0
4 4                                      72.0

     spp_fuelmixoutage_hydro_actual_a  spp_fuelmixoutage_naturalgas_actual_a  \
0 0                             890.0                                13752.5
1 1                             890.0                                13762.5
2 2                             890.0                                13762.5
3 3                             890.0                                13762.5
4 4                             890.0                                13973.9

     spp_fuelmixoutage_solar_actual_a  spp_fuelmixoutage_wind_actual_a
0 0                            1003.5                            705.5
1 1                            1003.5                            705.5
2 2                            1003.5                            705.5
3 3                            1003.5                            705.5
4 4                             781.5                            824.5
             dt  hr  spp_fuelmixoutage_coal_forecast_f  \
0 0  2026-04-01   1                             8488.8
1 1  2026-04-01   2                             8488.8
2 2  2026-04-01   3                             8488.8
3 3  2026-04-01   4                             8488.8
4 4  2026-04-01   5                             8488.8

     spp_fuelmixoutage_coal_actual_a  \
0 0                           8488.8
1 1                           8488.8
2 2                           8488.8
3 3                           8488.8
4 4                           8938.8

     spp_fuelmixoutage_dieselfueloil_forecast_f  \
0 0                                        72.0
1 1                                        72.0
2 2                                        72.0
3 3                                        72.0
4 4                                        72.0

     spp_fuelmixoutage_dieselfueloil_actual_a  \
0 0                                      72.0
1 1                                      72.0
2 2                                      72.0
3 3                                      72.0
4 4                                      72.0

     spp_fuelmixoutage_hydro_forecast_f  spp_fuelmixoutage_hydro_actual_a  \
0 0                               936.0                             890.0
1 1                               936.0                             890.0
2 2                               936.0                             890.0
3 3                               936.0                             890.0
4 4                               890.0                             890.0

     spp_fuelmixoutage_naturalgas_forecast_f  \
0 0                                  14325.5
1 1                                  14335.5
2 2                                  14335.5
3 3                                  14335.5
4 4                                  13762.5

     spp_fuelmixoutage_naturalgas_actual_a  \
0 0                                13752.5
1 1                                13762.5
2 2                                13762.5
3 3                                13762.5
4 4                                13973.9

     spp_fuelmixoutage_solar_forecast_f  spp_fuelmixoutage_solar_actual_a  \
0 0                              1155.7                            1003.5
1 1                              1155.7                            1003.5
2 2                              1155.7                            1003.5
3 3                              1155.7                            1003.5
4 4                              1003.5                             781.5

     spp_fuelmixoutage_wind_forecast_f  spp_fuelmixoutage_wind_actual_a
0 0                              625.5                            705.5
1 1                              625.5                            705.5
2 2                              625.5                            705.5
3 3                              625.5                            705.5
4 4                              705.5                            824.5
             dt  hr  spp_fuelmixoutage_coal_forecast_f  \
0 0  2026-04-01   1                             8488.8
1 1  2026-04-01   2                             8488.8
2 2  2026-04-01   3                             8488.8
3 3  2026-04-01   4                             8488.8
4 4  2026-04-01   5                             8488.8

     spp_fuelmixoutage_coal_actual_a  \
0 0                           8488.8
1 1                           8488.8
2 2                           8488.8
3 3                           8488.8
4 4                           8938.8

     spp_fuelmixoutage_dieselfueloil_forecast_f  \
0 0                                        72.0
1 1                                        72.0
2 2                                        72.0
3 3                                        72.0
4 4                                        72.0

     spp_fuelmixoutage_dieselfueloil_actual_a  \
0 0                                      72.0
1 1                                      72.0
2 2                                      72.0
3 3                                      72.0
4 4                                      72.0

     spp_fuelmixoutage_hydro_forecast_f  spp_fuelmixoutage_hydro_actual_a  \
0 0                               936.0                             890.0
1 1                               936.0                             890.0
2 2                               936.0                             890.0
3 3                               936.0                             890.0
4 4                               890.0                             890.0

     spp_fuelmixoutage_naturalgas_forecast_f  \
0 0                                  14325.5
1 1                                  14335.5
2 2                                  14335.5
3 3                                  14335.5
4 4                                  13762.5

     spp_fuelmixoutage_naturalgas_actual_a  \
0 0                                13752.5
1 1                                13762.5
2 2                                13762.5
3 3                                13762.5
4 4                                13973.9

     spp_fuelmixoutage_solar_forecast_f  spp_fuelmixoutage_solar_actual_a  \
0 0                              1155.7                            1003.5
1 1                              1155.7                            1003.5
2 2                              1155.7                            1003.5
3 3                              1155.7                            1003.5
4 4                              1003.5                             781.5

     spp_fuelmixoutage_wind_forecast_f  spp_fuelmixoutage_wind_actual_a
0 0                              625.5                            705.5
1 1                              625.5                            705.5
2 2                              625.5                            705.5
3 3                              625.5                            705.5
4 4                              705.5                            824.5
data shape: (24, 14)
mapping shape: (12, 2)

,,dt,hr,spp_fuelmixoutage_coal_forecast_f,spp_fuelmixoutage_coal_actual_a,spp_fuelmixoutage_dieselfueloil_forecast_f,spp_fuelmixoutage_dieselfueloil_actual_a,spp_fuelmixoutage_hydro_forecast_f,spp_fuelmixoutage_hydro_actual_a,spp_fuelmixoutage_naturalgas_forecast_f,spp_fuelmixoutage_naturalgas_actual_a,spp_fuelmixoutage_solar_forecast_f,spp_fuelmixoutage_solar_actual_a,spp_fuelmixoutage_wind_forecast_f,spp_fuelmixoutage_wind_actual_a
0,0,2026-04-01,1,8488.8,8488.8,72.0,72.0,936.0,890.0,14325.5,13752.5,1155.7,1003.5,625.5,705.5
1,1,2026-04-01,2,8488.8,8488.8,72.0,72.0,936.0,890.0,14335.5,13762.5,1155.7,1003.5,625.5,705.5
2,2,2026-04-01,3,8488.8,8488.8,72.0,72.0,936.0,890.0,14335.5,13762.5,1155.7,1003.5,625.5,705.5
3,3,2026-04-01,4,8488.8,8488.8,72.0,72.0,936.0,890.0,14335.5,13762.5,1155.7,1003.5,625.5,705.5
4,4,2026-04-01,5,8488.8,8938.8,72.0,72.0,890.0,890.0,13762.5,13973.9,1003.5,781.5,705.5,824.5
5,5,2026-04-01,6,8488.8,8938.8,72.0,72.0,890.0,890.0,13762.5,13973.9,1003.5,781.5,705.5,824.5
6,6,2026-04-01,7,8488.8,8938.8,72.0,72.0,890.0,890.0,13847.5,14077.2,1003.5,781.5,705.5,824.5
7,7,2026-04-01,8,8488.8,8488.8,72.0,72.0,890.0,890.0,13892.5,14074.2,853.5,631.5,705.5,824.5
8,8,2026-04-01,9,8488.8,8488.8,266.0,266.0,890.0,890.0,13892.5,14109.9,781.5,631.5,705.5,625.5
9,9,2026-04-01,10,8488.8,8488.8,266.0,266.0,890.0,890.0,13892.5,14109.9,781.5,631.5,705.5,625.5
10,10,2026-04-01,11,8488.8,8488.8,266.0,266.0,890.0,890.0,13892.5,14109.9,781.5,631.5,705.5,625.5
11,11,2026-04-01,12,8488.8,8488.8,266.0,266.0,890.0,890.0,13892.5,14152.9,781.5,631.5,705.5,625.5
12,12,2026-04-01,13,9024.8,9025.8,266.0,266.0,890.0,890.0,13892.5,14150.5,781.5,631.5,705.5,625.5
13,13,2026-04-01,14,9024.8,9025.8,266.0,266.0,890.0,890.0,13892.5,14150.5,781.5,631.5,705.5,625.5
14,14,2026-04-01,15,9024.8,9025.8,212.0,212.0,890.0,890.0,13892.5,14150.5,781.5,631.5,705.5,625.5
15,15,2026-04-01,16,9024.8,9025.8,212.0,212.0,890.0,890.0,13892.5,14150.5,781.5,631.5,705.5,625.5
16,16,2026-04-01,17,9024.8,9025.8,212.0,212.0,890.0,890.0,13847.5,14105.5,781.5,631.5,705.5,625.5
17,17,2026-04-01,18,9024.8,9025.8,212.0,212.0,890.0,890.0,13847.5,14105.5,781.5,631.5,705.5,625.5
18,18,2026-04-01,19,9024.8,9025.8,212.0,212.0,890.0,890.0,13847.5,14096.5,781.5,631.5,625.5,625.5
19,19,2026-04-01,20,9024.8,9025.8,212.0,212.0,890.0,890.0,13847.5,14096.5,781.5,631.5,625.5,625.5
20,20,2026-04-01,21,9024.8,9025.8,212.0,212.0,890.0,890.0,13847.5,14096.5,781.5,781.5,625.5,625.5
21,21,2026-04-01,22,9024.8,9025.8,212.0,212.0,890.0,890.0,13847.5,14096.5,781.5,781.5,625.5,625.5
22,22,2026-04-01,23,9024.8,9025.8,212.0,212.0,890.0,890.0,13847.5,14096.5,781.5,781.5,625.5,625.5
23,23,2026-04-01,24,9024.8,9025.8,212.0,212.0,890.0,890.0,13847.5,14096.5,781.5,781.5,625.5,625.5

    node_num                                    var_name
0        636           spp_fuelmixoutage_coal_forecast_f
1        636             spp_fuelmixoutage_coal_actual_a
2        636  spp_fuelmixoutage_dieselfueloil_forecast_f
3        636    spp_fuelmixoutage_dieselfueloil_actual_a
4        636          spp_fuelmixoutage_hydro_forecast_f
5        636            spp_fuelmixoutage_hydro_actual_a
6        636     spp_fuelmixoutage_naturalgas_forecast_f
7        636       spp_fuelmixoutage_naturalgas_actual_a
8        636          spp_fuelmixoutage_solar_forecast_f
9        636            spp_fuelmixoutage_solar_actual_a
10       636           spp_fuelmixoutage_wind_forecast_f
11       636             spp_fuelmixoutage_wind_actual_a

### 21e. get_data_and_mapping_for_baa_zonal_genoutage_fuel_type — BAA-zonal wrapper with node mapping

In [10]:
from nighthawk.data.pipeline.var_handler.fuel_type import get_data_and_mapping_for_baa_zonal_genoutage_fuel_type

data_bgoft, mapping_bgoft = get_data_and_mapping_for_baa_zonal_genoutage_fuel_type(
    node_list=[636], opexchange='SPP',
    start_dt='2026-04-01', end_dt='2026-04-01',
    fuel_type=['All'],
    impute=True
)
print('data shape:', data_bgoft.shape)
print('mapping shape:', mapping_bgoft.shape)
display(data_bgoft)
display(mapping_bgoft)

data shape: (24, 14)
mapping shape: (12, 2)

,dt,hr,e_spp_baa_zonal_fuelmixoutage_coal_actual_a,e_spp_baa_zonal_fuelmixoutage_coal_forecast_f,e_spp_baa_zonal_fuelmixoutage_dieselfueloil_actual_a,e_spp_baa_zonal_fuelmixoutage_dieselfueloil_forecast_f,e_spp_baa_zonal_fuelmixoutage_hydro_actual_a,e_spp_baa_zonal_fuelmixoutage_hydro_forecast_f,e_spp_baa_zonal_fuelmixoutage_naturalgas_actual_a,e_spp_baa_zonal_fuelmixoutage_naturalgas_forecast_f,e_spp_baa_zonal_fuelmixoutage_solar_actual_a,e_spp_baa_zonal_fuelmixoutage_solar_forecast_f,e_spp_baa_zonal_fuelmixoutage_wind_actual_a,e_spp_baa_zonal_fuelmixoutage_wind_forecast_f
0,2026-04-01,1,8488.8,8488.8,72.0,72.0,890.0,936.0,13752.5,14325.5,1003.5,1155.7,705.5,625.5
1,2026-04-01,2,8488.8,8488.8,72.0,72.0,890.0,936.0,13762.5,14335.5,1003.5,1155.7,705.5,625.5
2,2026-04-01,3,8488.8,8488.8,72.0,72.0,890.0,936.0,13762.5,14335.5,1003.5,1155.7,705.5,625.5
3,2026-04-01,4,8488.8,8488.8,72.0,72.0,890.0,936.0,13762.5,14335.5,1003.5,1155.7,705.5,625.5
4,2026-04-01,5,8938.8,8488.8,72.0,72.0,890.0,890.0,13973.9,13762.5,781.5,1003.5,824.5,705.5
5,2026-04-01,6,8938.8,8488.8,72.0,72.0,890.0,890.0,13973.9,13762.5,781.5,1003.5,824.5,705.5
6,2026-04-01,7,8938.8,8488.8,72.0,72.0,890.0,890.0,14077.2,13847.5,781.5,1003.5,824.5,705.5
7,2026-04-01,8,8488.8,8488.8,72.0,72.0,890.0,890.0,14074.2,13892.5,631.5,853.5,824.5,705.5
8,2026-04-01,9,8488.8,8488.8,266.0,266.0,890.0,890.0,14109.9,13892.5,631.5,781.5,625.5,705.5
9,2026-04-01,10,8488.8,8488.8,266.0,266.0,890.0,890.0,14109.9,13892.5,631.5,781.5,625.5,705.5
10,2026-04-01,11,8488.8,8488.8,266.0,266.0,890.0,890.0,14109.9,13892.5,631.5,781.5,625.5,705.5
11,2026-04-01,12,8488.8,8488.8,266.0,266.0,890.0,890.0,14152.9,13892.5,631.5,781.5,625.5,705.5
12,2026-04-01,13,9025.8,9024.8,266.0,266.0,890.0,890.0,14150.5,13892.5,631.5,781.5,625.5,705.5
13,2026-04-01,14,9025.8,9024.8,266.0,266.0,890.0,890.0,14150.5,13892.5,631.5,781.5,625.5,705.5
14,2026-04-01,15,9025.8,9024.8,212.0,212.0,890.0,890.0,14150.5,13892.5,631.5,781.5,625.5,705.5
15,2026-04-01,16,9025.8,9024.8,212.0,212.0,890.0,890.0,14150.5,13892.5,631.5,781.5,625.5,705.5
16,2026-04-01,17,9025.8,9024.8,212.0,212.0,890.0,890.0,14105.5,13847.5,631.5,781.5,625.5,705.5
17,2026-04-01,18,9025.8,9024.8,212.0,212.0,890.0,890.0,14105.5,13847.5,631.5,781.5,625.5,705.5
18,2026-04-01,19,9025.8,9024.8,212.0,212.0,890.0,890.0,14096.5,13847.5,631.5,781.5,625.5,625.5
19,2026-04-01,20,9025.8,9024.8,212.0,212.0,890.0,890.0,14096.5,13847.5,631.5,781.5,625.5,625.5
20,2026-04-01,21,9025.8,9024.8,212.0,212.0,890.0,890.0,14096.5,13847.5,781.5,781.5,625.5,625.5
21,2026-04-01,22,9025.8,9024.8,212.0,212.0,890.0,890.0,14096.5,13847.5,781.5,781.5,625.5,625.5
22,2026-04-01,23,9025.8,9024.8,212.0,212.0,890.0,890.0,14096.5,13847.5,781.5,781.5,625.5,625.5
23,2026-04-01,24,9025.8,9024.8,212.0,212.0,890.0,890.0,14096.5,13847.5,781.5,781.5,625.5,625.5

    node_num                                           var_name
0        636        e_spp_baa_zonal_fuelmixoutage_coal_actual_a
1        636      e_spp_baa_zonal_fuelmixoutage_coal_forecast_f
2        636  e_spp_baa_zonal_fuelmixoutage_dieselfueloil_ac...
3        636  e_spp_baa_zonal_fuelmixoutage_dieselfueloil_fo...
4        636       e_spp_baa_zonal_fuelmixoutage_hydro_actual_a
5        636     e_spp_baa_zonal_fuelmixoutage_hydro_forecast_f
6        636  e_spp_baa_zonal_fuelmixoutage_naturalgas_actual_a
7        636  e_spp_baa_zonal_fuelmixoutage_naturalgas_forec...
8        636       e_spp_baa_zonal_fuelmixoutage_solar_actual_a
9        636     e_spp_baa_zonal_fuelmixoutage_solar_forecast_f
10       636        e_spp_baa_zonal_fuelmixoutage_wind_actual_a
11       636      e_spp_baa_zonal_fuelmixoutage_wind_forecast_f

---
## GEN MIX RAW TABLES

### 22. GenMix 5-min (spp_physical.GenMix)

In [9]:
df_genmix = sql_functions.download_df_from_sql_db(
    "SELECT IntervalEnd, GMTIntervalEnd, CoalTotal, WindTotal, SolarTotal, NaturalGasTotal, AverageActualLoad "
    "FROM spp_physical.GenMix "
    "WHERE DATE(IntervalEnd) = '2026-04-03' ORDER BY IntervalEnd")
print(df_genmix.shape)
# spot check: rows should be ~288 (5-min intervals * 24hr)
df_genmix.tail(10)

(108, 7)

,IntervalEnd,GMTIntervalEnd,CoalTotal,WindTotal,SolarTotal,NaturalGasTotal,AverageActualLoad
98,2026-04-03 08:10:00,2026-04-03 13:10:00,5456.2,20804.9,108.1,5611.3,33914.0
99,2026-04-03 08:15:00,2026-04-03 13:15:00,5513.1,20716.8,133.0,5740.2,34431.3
100,2026-04-03 08:20:00,2026-04-03 13:20:00,5541.2,20800.6,174.1,5700.4,34162.5
101,2026-04-03 08:25:00,2026-04-03 13:25:00,5633.1,20924.8,226.1,5633.5,34231.8
102,2026-04-03 08:30:00,2026-04-03 13:30:00,5689.0,20713.1,270.4,5768.1,34704.9
103,2026-04-03 08:35:00,2026-04-03 13:35:00,5768.0,20494.4,262.8,5922.1,34320.7
104,2026-04-03 08:40:00,2026-04-03 13:40:00,5804.2,20453.4,309.1,5830.4,34332.5
105,2026-04-03 08:45:00,2026-04-03 13:45:00,5828.2,20454.6,315.8,5910.4,34833.5
106,2026-04-03 08:50:00,2026-04-03 13:50:00,5830.0,20347.7,471.5,5949.8,34488.7
107,2026-04-03 08:55:00,2026-04-03 13:55:00,5804.3,20208.6,487.8,5969.1,34634.3

### 23. GenMixHourly (spp_physical.GenMixHourly)

In [83]:
df_genmixhr = sql_functions.download_df_from_sql_db(
    "SELECT * "
    "FROM spp_physical.GenMixHourly "
    "WHERE dt = '2026-04-01' ORDER BY hr")
print(df_genmixhr.shape)
pd.set_option('display.max_columns', None)  # show all columns
pd.set_option('display.max_rows', None)     # show all rows
pd.set_option('display.width', None)
display(df_genmixhr)

(14, 33)

,dt,hr,CoalMarket,CoalSelf,CoalTotal,DieselFuelOilMarket,DieselFuelOilSelf,DieselFuelOilTotal,HydroMarket,HydroSelf,HydroTotal,NaturalGasMarket,NaturalGasSelf,NaturalGasTotal,NuclearMarket,NuclearSelf,NuclearTotal,SolarMarket,SolarSelf,SolarTotal,WasteDisposalServicesMarket,WasteDisposalServicesSelf,WasteDisposalServicesTotal,WindMarket,WindSelf,WindTotal,WasteHeatMarket,WasteHeatSelf,WasteHeatTotal,OtherMarket,OtherSelf,OtherTotal,AverageActualLoad
0,2026-04-01,10,3564.0,4713.2,8277.2,0.0,70.2,70.2,79.8,1557.9,1637.7,12165.6,1908.7,14074.2,0.0,2022.2,2022.2,0.0,772.8,772.8,1.5,5.5,7.0,0.0,7332.9,7332.9,0.0,0.0,0.0,43.4,38.2,81.7,35172.4
1,2026-04-01,11,3566.4,4881.9,8448.3,37.6,86.6,124.1,2.4,1681.7,1684.1,12274.8,1913.6,14188.4,0.0,2023.1,2023.1,0.0,963.5,963.5,1.5,6.3,7.8,0.0,7052.8,7052.8,0.0,0.0,0.0,79.2,38.1,117.3,35616.7
2,2026-04-01,12,3497.6,4522.4,8019.9,143.2,46.8,190.0,2.4,1600.0,1602.4,11582.3,1534.5,13116.7,0.0,2020.8,2020.8,0.0,1152.7,1152.7,1.5,6.2,7.8,0.0,7547.7,7547.7,0.0,0.0,0.0,7.3,35.5,42.8,35874.3
3,2026-04-01,13,3324.2,4387.9,7712.1,146.0,83.9,229.9,6.1,1653.2,1659.3,10518.3,1269.7,11788.0,0.0,2022.6,2022.6,0.0,1247.4,1247.4,1.5,6.2,7.7,0.0,9298.3,9298.3,0.0,0.0,0.0,11.6,33.1,44.7,36047.3
4,2026-04-01,14,3221.3,4257.6,7478.9,146.0,72.9,218.9,6.4,1737.0,1743.4,10148.7,1558.7,11707.5,0.0,2022.8,2022.8,0.0,1212.8,1212.8,1.5,6.2,7.8,0.0,11275.6,11275.6,0.0,0.0,0.0,25.4,31.8,57.2,36238.6
5,2026-04-01,15,3119.9,4030.6,7150.5,140.2,25.2,165.4,9.6,1742.0,1751.6,8090.6,1878.1,9968.8,0.0,2022.0,2022.0,0.0,991.6,991.6,1.5,6.2,7.8,0.0,13926.5,13926.5,0.0,0.0,0.0,12.6,58.3,70.9,36344.5
6,2026-04-01,16,3130.6,4129.2,7259.8,94.8,27.6,122.4,20.3,1759.8,1780.2,7719.1,1925.6,9644.6,0.0,2021.9,2021.9,0.0,854.0,854.0,1.5,6.3,7.9,0.0,15508.1,15508.1,0.0,0.0,0.0,38.9,29.2,68.2,36643.9
7,2026-04-01,17,3309.6,4364.6,7674.2,43.3,29.2,72.5,32.6,1935.9,1968.5,8024.9,1375.3,9400.1,0.0,2021.4,2021.4,0.0,607.3,607.3,1.6,6.4,7.9,0.0,15249.4,15249.4,0.0,0.0,0.0,27.0,29.2,56.2,36818.3
8,2026-04-01,18,3238.3,4341.3,7579.6,0.0,27.8,27.8,52.2,1957.0,2009.2,7727.6,1382.3,9109.9,0.0,2022.3,2022.3,0.0,361.8,361.8,1.5,6.4,7.9,0.0,15471.2,15471.2,0.0,0.0,0.0,20.9,29.2,50.1,36795.3
9,2026-04-01,19,3296.8,4569.1,7865.9,0.0,40.8,40.8,52.6,2049.8,2102.5,7704.4,1488.1,9192.6,0.0,2021.2,2021.2,0.0,118.0,118.0,0.4,6.4,6.7,0.0,15949.2,15949.2,0.0,0.0,0.0,27.6,29.2,56.8,36578.6
10,2026-04-01,20,3409.4,4587.9,7997.3,0.0,74.7,74.7,33.5,1947.5,1981.0,7120.8,1525.1,8646.0,0.0,2021.5,2021.5,0.0,17.3,17.3,0.0,6.3,6.3,0.0,16883.6,16883.6,0.0,0.0,0.0,23.0,29.1,52.1,36681.5
11,2026-04-01,21,3132.4,4269.4,7401.8,0.0,121.9,121.9,33.6,1855.5,1889.1,5533.1,1760.0,7293.1,0.0,2019.6,2019.6,0.0,0.2,0.2,0.0,6.3,6.3,0.0,18233.7,18233.7,0.0,0.0,0.0,7.6,31.2,38.7,35910.5
12,2026-04-01,22,2407.0,3750.5,6157.5,0.0,100.8,100.8,33.7,1430.0,1463.8,4844.0,2021.1,6865.2,0.0,2020.0,2020.0,0.0,0.2,0.2,0.0,6.4,6.4,0.0,18638.9,18638.9,0.0,0.0,0.0,7.5,30.3,37.9,34300.7
13,2026-04-01,23,1860.3,3153.2,5013.5,64.4,23.6,88.0,12.3,1264.5,1276.8,4373.3,1911.9,6285.3,0.0,2019.5,2019.5,0.0,0.3,0.3,0.0,6.4,6.4,0.0,18955.1,18955.1,0.0,0.0,0.0,7.4,28.6,36.0,32663.4

In [ ]:
df_genmixhr = sql_functions.download_df_from_sql_db(
    "SELECT * "
    "FROM spp_physical.GenMixHourly "
    "WHERE dt = '2026-04-01' ORDER BY hr")
print(df_genmixhr.shape)
pd.set_option('display.max_columns', None)  # show all columns
pd.set_option('display.max_rows', None)     # show all rows
pd.set_option('display.width', None)
display(df_genmixhr)

(14, 33)

,dt,hr,CoalMarket,CoalSelf,CoalTotal,DieselFuelOilMarket,DieselFuelOilSelf,DieselFuelOilTotal,HydroMarket,HydroSelf,HydroTotal,NaturalGasMarket,NaturalGasSelf,NaturalGasTotal,NuclearMarket,NuclearSelf,NuclearTotal,SolarMarket,SolarSelf,SolarTotal,WasteDisposalServicesMarket,WasteDisposalServicesSelf,WasteDisposalServicesTotal,WindMarket,WindSelf,WindTotal,WasteHeatMarket,WasteHeatSelf,WasteHeatTotal,OtherMarket,OtherSelf,OtherTotal,AverageActualLoad
0,2026-04-01,10,3564.0,4713.2,8277.2,0.0,70.2,70.2,79.8,1557.9,1637.7,12165.6,1908.7,14074.2,0.0,2022.2,2022.2,0.0,772.8,772.8,1.5,5.5,7.0,0.0,7332.9,7332.9,0.0,0.0,0.0,43.4,38.2,81.7,35172.4
1,2026-04-01,11,3566.4,4881.9,8448.3,37.6,86.6,124.1,2.4,1681.7,1684.1,12274.8,1913.6,14188.4,0.0,2023.1,2023.1,0.0,963.5,963.5,1.5,6.3,7.8,0.0,7052.8,7052.8,0.0,0.0,0.0,79.2,38.1,117.3,35616.7
2,2026-04-01,12,3497.6,4522.4,8019.9,143.2,46.8,190.0,2.4,1600.0,1602.4,11582.3,1534.5,13116.7,0.0,2020.8,2020.8,0.0,1152.7,1152.7,1.5,6.2,7.8,0.0,7547.7,7547.7,0.0,0.0,0.0,7.3,35.5,42.8,35874.3
3,2026-04-01,13,3324.2,4387.9,7712.1,146.0,83.9,229.9,6.1,1653.2,1659.3,10518.3,1269.7,11788.0,0.0,2022.6,2022.6,0.0,1247.4,1247.4,1.5,6.2,7.7,0.0,9298.3,9298.3,0.0,0.0,0.0,11.6,33.1,44.7,36047.3
4,2026-04-01,14,3221.3,4257.6,7478.9,146.0,72.9,218.9,6.4,1737.0,1743.4,10148.7,1558.7,11707.5,0.0,2022.8,2022.8,0.0,1212.8,1212.8,1.5,6.2,7.8,0.0,11275.6,11275.6,0.0,0.0,0.0,25.4,31.8,57.2,36238.6
5,2026-04-01,15,3119.9,4030.6,7150.5,140.2,25.2,165.4,9.6,1742.0,1751.6,8090.6,1878.1,9968.8,0.0,2022.0,2022.0,0.0,991.6,991.6,1.5,6.2,7.8,0.0,13926.5,13926.5,0.0,0.0,0.0,12.6,58.3,70.9,36344.5
6,2026-04-01,16,3130.6,4129.2,7259.8,94.8,27.6,122.4,20.3,1759.8,1780.2,7719.1,1925.6,9644.6,0.0,2021.9,2021.9,0.0,854.0,854.0,1.5,6.3,7.9,0.0,15508.1,15508.1,0.0,0.0,0.0,38.9,29.2,68.2,36643.9
7,2026-04-01,17,3309.6,4364.6,7674.2,43.3,29.2,72.5,32.6,1935.9,1968.5,8024.9,1375.3,9400.1,0.0,2021.4,2021.4,0.0,607.3,607.3,1.6,6.4,7.9,0.0,15249.4,15249.4,0.0,0.0,0.0,27.0,29.2,56.2,36818.3
8,2026-04-01,18,3238.3,4341.3,7579.6,0.0,27.8,27.8,52.2,1957.0,2009.2,7727.6,1382.3,9109.9,0.0,2022.3,2022.3,0.0,361.8,361.8,1.5,6.4,7.9,0.0,15471.2,15471.2,0.0,0.0,0.0,20.9,29.2,50.1,36795.3
9,2026-04-01,19,3296.8,4569.1,7865.9,0.0,40.8,40.8,52.6,2049.8,2102.5,7704.4,1488.1,9192.6,0.0,2021.2,2021.2,0.0,118.0,118.0,0.4,6.4,6.7,0.0,15949.2,15949.2,0.0,0.0,0.0,27.6,29.2,56.8,36578.6
10,2026-04-01,20,3409.4,4587.9,7997.3,0.0,74.7,74.7,33.5,1947.5,1981.0,7120.8,1525.1,8646.0,0.0,2021.5,2021.5,0.0,17.3,17.3,0.0,6.3,6.3,0.0,16883.6,16883.6,0.0,0.0,0.0,23.0,29.1,52.1,36681.5
11,2026-04-01,21,3132.4,4269.4,7401.8,0.0,121.9,121.9,33.6,1855.5,1889.1,5533.1,1760.0,7293.1,0.0,2019.6,2019.6,0.0,0.2,0.2,0.0,6.3,6.3,0.0,18233.7,18233.7,0.0,0.0,0.0,7.6,31.2,38.7,35910.5
12,2026-04-01,22,2407.0,3750.5,6157.5,0.0,100.8,100.8,33.7,1430.0,1463.8,4844.0,2021.1,6865.2,0.0,2020.0,2020.0,0.0,0.2,0.2,0.0,6.4,6.4,0.0,18638.9,18638.9,0.0,0.0,0.0,7.5,30.3,37.9,34300.7
13,2026-04-01,23,1860.3,3153.2,5013.5,64.4,23.6,88.0,12.3,1264.5,1276.8,4373.3,1911.9,6285.3,0.0,2019.5,2019.5,0.0,0.3,0.3,0.0,6.4,6.4,0.0,18955.1,18955.1,0.0,0.0,0.0,7.4,28.6,36.0,32663.4

In [ ]:
df_genmixhr = sql_functions.download_df_from_sql_db(
    "SELECT * "
    "FROM spp_physical.GenMixHourly "
    "WHERE dt = '2026-04-01' ORDER BY hr")
print(df_genmixhr.shape)
pd.set_option('display.max_columns', None)  # show all columns
pd.set_option('display.max_rows', None)     # show all rows
pd.set_option('display.width', None)
display(df_genmixhr)

(14, 33)

,dt,hr,CoalMarket,CoalSelf,CoalTotal,DieselFuelOilMarket,DieselFuelOilSelf,DieselFuelOilTotal,HydroMarket,HydroSelf,HydroTotal,NaturalGasMarket,NaturalGasSelf,NaturalGasTotal,NuclearMarket,NuclearSelf,NuclearTotal,SolarMarket,SolarSelf,SolarTotal,WasteDisposalServicesMarket,WasteDisposalServicesSelf,WasteDisposalServicesTotal,WindMarket,WindSelf,WindTotal,WasteHeatMarket,WasteHeatSelf,WasteHeatTotal,OtherMarket,OtherSelf,OtherTotal,AverageActualLoad
0,2026-04-01,10,3564.0,4713.2,8277.2,0.0,70.2,70.2,79.8,1557.9,1637.7,12165.6,1908.7,14074.2,0.0,2022.2,2022.2,0.0,772.8,772.8,1.5,5.5,7.0,0.0,7332.9,7332.9,0.0,0.0,0.0,43.4,38.2,81.7,35172.4
1,2026-04-01,11,3566.4,4881.9,8448.3,37.6,86.6,124.1,2.4,1681.7,1684.1,12274.8,1913.6,14188.4,0.0,2023.1,2023.1,0.0,963.5,963.5,1.5,6.3,7.8,0.0,7052.8,7052.8,0.0,0.0,0.0,79.2,38.1,117.3,35616.7
2,2026-04-01,12,3497.6,4522.4,8019.9,143.2,46.8,190.0,2.4,1600.0,1602.4,11582.3,1534.5,13116.7,0.0,2020.8,2020.8,0.0,1152.7,1152.7,1.5,6.2,7.8,0.0,7547.7,7547.7,0.0,0.0,0.0,7.3,35.5,42.8,35874.3
3,2026-04-01,13,3324.2,4387.9,7712.1,146.0,83.9,229.9,6.1,1653.2,1659.3,10518.3,1269.7,11788.0,0.0,2022.6,2022.6,0.0,1247.4,1247.4,1.5,6.2,7.7,0.0,9298.3,9298.3,0.0,0.0,0.0,11.6,33.1,44.7,36047.3
4,2026-04-01,14,3221.3,4257.6,7478.9,146.0,72.9,218.9,6.4,1737.0,1743.4,10148.7,1558.7,11707.5,0.0,2022.8,2022.8,0.0,1212.8,1212.8,1.5,6.2,7.8,0.0,11275.6,11275.6,0.0,0.0,0.0,25.4,31.8,57.2,36238.6
5,2026-04-01,15,3119.9,4030.6,7150.5,140.2,25.2,165.4,9.6,1742.0,1751.6,8090.6,1878.1,9968.8,0.0,2022.0,2022.0,0.0,991.6,991.6,1.5,6.2,7.8,0.0,13926.5,13926.5,0.0,0.0,0.0,12.6,58.3,70.9,36344.5
6,2026-04-01,16,3130.6,4129.2,7259.8,94.8,27.6,122.4,20.3,1759.8,1780.2,7719.1,1925.6,9644.6,0.0,2021.9,2021.9,0.0,854.0,854.0,1.5,6.3,7.9,0.0,15508.1,15508.1,0.0,0.0,0.0,38.9,29.2,68.2,36643.9
7,2026-04-01,17,3309.6,4364.6,7674.2,43.3,29.2,72.5,32.6,1935.9,1968.5,8024.9,1375.3,9400.1,0.0,2021.4,2021.4,0.0,607.3,607.3,1.6,6.4,7.9,0.0,15249.4,15249.4,0.0,0.0,0.0,27.0,29.2,56.2,36818.3
8,2026-04-01,18,3238.3,4341.3,7579.6,0.0,27.8,27.8,52.2,1957.0,2009.2,7727.6,1382.3,9109.9,0.0,2022.3,2022.3,0.0,361.8,361.8,1.5,6.4,7.9,0.0,15471.2,15471.2,0.0,0.0,0.0,20.9,29.2,50.1,36795.3
9,2026-04-01,19,3296.8,4569.1,7865.9,0.0,40.8,40.8,52.6,2049.8,2102.5,7704.4,1488.1,9192.6,0.0,2021.2,2021.2,0.0,118.0,118.0,0.4,6.4,6.7,0.0,15949.2,15949.2,0.0,0.0,0.0,27.6,29.2,56.8,36578.6
10,2026-04-01,20,3409.4,4587.9,7997.3,0.0,74.7,74.7,33.5,1947.5,1981.0,7120.8,1525.1,8646.0,0.0,2021.5,2021.5,0.0,17.3,17.3,0.0,6.3,6.3,0.0,16883.6,16883.6,0.0,0.0,0.0,23.0,29.1,52.1,36681.5
11,2026-04-01,21,3132.4,4269.4,7401.8,0.0,121.9,121.9,33.6,1855.5,1889.1,5533.1,1760.0,7293.1,0.0,2019.6,2019.6,0.0,0.2,0.2,0.0,6.3,6.3,0.0,18233.7,18233.7,0.0,0.0,0.0,7.6,31.2,38.7,35910.5
12,2026-04-01,22,2407.0,3750.5,6157.5,0.0,100.8,100.8,33.7,1430.0,1463.8,4844.0,2021.1,6865.2,0.0,2020.0,2020.0,0.0,0.2,0.2,0.0,6.4,6.4,0.0,18638.9,18638.9,0.0,0.0,0.0,7.5,30.3,37.9,34300.7
13,2026-04-01,23,1860.3,3153.2,5013.5,64.4,23.6,88.0,12.3,1264.5,1276.8,4373.3,1911.9,6285.3,0.0,2019.5,2019.5,0.0,0.3,0.3,0.0,6.4,6.4,0.0,18955.1,18955.1,0.0,0.0,0.0,7.4,28.6,36.0,32663.4

In [ ]:
df_genmixhr = sql_functions.download_df_from_sql_db(
    "SELECT * "
    "FROM spp_physical.GenMixHourly "
    "WHERE dt = '2026-04-01' ORDER BY hr")
print(df_genmixhr.shape)
pd.set_option('display.max_columns', None)  # show all columns
pd.set_option('display.max_rows', None)     # show all rows
pd.set_option('display.width', None)
display(df_genmixhr)

(14, 33)

,dt,hr,CoalMarket,CoalSelf,CoalTotal,DieselFuelOilMarket,DieselFuelOilSelf,DieselFuelOilTotal,HydroMarket,HydroSelf,HydroTotal,NaturalGasMarket,NaturalGasSelf,NaturalGasTotal,NuclearMarket,NuclearSelf,NuclearTotal,SolarMarket,SolarSelf,SolarTotal,WasteDisposalServicesMarket,WasteDisposalServicesSelf,WasteDisposalServicesTotal,WindMarket,WindSelf,WindTotal,WasteHeatMarket,WasteHeatSelf,WasteHeatTotal,OtherMarket,OtherSelf,OtherTotal,AverageActualLoad
0,2026-04-01,10,3564.0,4713.2,8277.2,0.0,70.2,70.2,79.8,1557.9,1637.7,12165.6,1908.7,14074.2,0.0,2022.2,2022.2,0.0,772.8,772.8,1.5,5.5,7.0,0.0,7332.9,7332.9,0.0,0.0,0.0,43.4,38.2,81.7,35172.4
1,2026-04-01,11,3566.4,4881.9,8448.3,37.6,86.6,124.1,2.4,1681.7,1684.1,12274.8,1913.6,14188.4,0.0,2023.1,2023.1,0.0,963.5,963.5,1.5,6.3,7.8,0.0,7052.8,7052.8,0.0,0.0,0.0,79.2,38.1,117.3,35616.7
2,2026-04-01,12,3497.6,4522.4,8019.9,143.2,46.8,190.0,2.4,1600.0,1602.4,11582.3,1534.5,13116.7,0.0,2020.8,2020.8,0.0,1152.7,1152.7,1.5,6.2,7.8,0.0,7547.7,7547.7,0.0,0.0,0.0,7.3,35.5,42.8,35874.3
3,2026-04-01,13,3324.2,4387.9,7712.1,146.0,83.9,229.9,6.1,1653.2,1659.3,10518.3,1269.7,11788.0,0.0,2022.6,2022.6,0.0,1247.4,1247.4,1.5,6.2,7.7,0.0,9298.3,9298.3,0.0,0.0,0.0,11.6,33.1,44.7,36047.3
4,2026-04-01,14,3221.3,4257.6,7478.9,146.0,72.9,218.9,6.4,1737.0,1743.4,10148.7,1558.7,11707.5,0.0,2022.8,2022.8,0.0,1212.8,1212.8,1.5,6.2,7.8,0.0,11275.6,11275.6,0.0,0.0,0.0,25.4,31.8,57.2,36238.6
5,2026-04-01,15,3119.9,4030.6,7150.5,140.2,25.2,165.4,9.6,1742.0,1751.6,8090.6,1878.1,9968.8,0.0,2022.0,2022.0,0.0,991.6,991.6,1.5,6.2,7.8,0.0,13926.5,13926.5,0.0,0.0,0.0,12.6,58.3,70.9,36344.5
6,2026-04-01,16,3130.6,4129.2,7259.8,94.8,27.6,122.4,20.3,1759.8,1780.2,7719.1,1925.6,9644.6,0.0,2021.9,2021.9,0.0,854.0,854.0,1.5,6.3,7.9,0.0,15508.1,15508.1,0.0,0.0,0.0,38.9,29.2,68.2,36643.9
7,2026-04-01,17,3309.6,4364.6,7674.2,43.3,29.2,72.5,32.6,1935.9,1968.5,8024.9,1375.3,9400.1,0.0,2021.4,2021.4,0.0,607.3,607.3,1.6,6.4,7.9,0.0,15249.4,15249.4,0.0,0.0,0.0,27.0,29.2,56.2,36818.3
8,2026-04-01,18,3238.3,4341.3,7579.6,0.0,27.8,27.8,52.2,1957.0,2009.2,7727.6,1382.3,9109.9,0.0,2022.3,2022.3,0.0,361.8,361.8,1.5,6.4,7.9,0.0,15471.2,15471.2,0.0,0.0,0.0,20.9,29.2,50.1,36795.3
9,2026-04-01,19,3296.8,4569.1,7865.9,0.0,40.8,40.8,52.6,2049.8,2102.5,7704.4,1488.1,9192.6,0.0,2021.2,2021.2,0.0,118.0,118.0,0.4,6.4,6.7,0.0,15949.2,15949.2,0.0,0.0,0.0,27.6,29.2,56.8,36578.6
10,2026-04-01,20,3409.4,4587.9,7997.3,0.0,74.7,74.7,33.5,1947.5,1981.0,7120.8,1525.1,8646.0,0.0,2021.5,2021.5,0.0,17.3,17.3,0.0,6.3,6.3,0.0,16883.6,16883.6,0.0,0.0,0.0,23.0,29.1,52.1,36681.5
11,2026-04-01,21,3132.4,4269.4,7401.8,0.0,121.9,121.9,33.6,1855.5,1889.1,5533.1,1760.0,7293.1,0.0,2019.6,2019.6,0.0,0.2,0.2,0.0,6.3,6.3,0.0,18233.7,18233.7,0.0,0.0,0.0,7.6,31.2,38.7,35910.5
12,2026-04-01,22,2407.0,3750.5,6157.5,0.0,100.8,100.8,33.7,1430.0,1463.8,4844.0,2021.1,6865.2,0.0,2020.0,2020.0,0.0,0.2,0.2,0.0,6.4,6.4,0.0,18638.9,18638.9,0.0,0.0,0.0,7.5,30.3,37.9,34300.7
13,2026-04-01,23,1860.3,3153.2,5013.5,64.4,23.6,88.0,12.3,1264.5,1276.8,4373.3,1911.9,6285.3,0.0,2019.5,2019.5,0.0,0.3,0.3,0.0,6.4,6.4,0.0,18955.1,18955.1,0.0,0.0,0.0,7.4,28.6,36.0,32663.4

### 24. BAAZonalGenMix (spp_physical.BAAZonalGenMix) — E and W

In [75]:
df_baa_genmix = sql_functions.download_df_from_sql_db(
    "SELECT IntervalEnd, BAA, CoalTotal, WindTotal, SolarTotal, NaturalGasTotal, AverageActualLoad "
    "FROM spp_physical.BAAZonalGenMix "
    "WHERE DATE(IntervalEnd) = '2026-04-06' ORDER BY IntervalEnd DESC, BAA")
print(df_baa_genmix.shape)
# spot check: E + W rows; WindTotal_E + WindTotal_W should ≈ GenMix WindTotal
df_baa_genmix.head(10)

(264, 7)

,IntervalEnd,BAA,CoalTotal,WindTotal,SolarTotal,NaturalGasTotal,AverageActualLoad
0,2026-04-06 10:55:00,E,4139.9,12061.9,1681.8,8962.5,30808.5
1,2026-04-06 10:55:00,W,619.5,278.6,360.2,802.3,2342.3
2,2026-04-06 10:50:00,E,4200.8,11979.4,1690.8,8980.7,30880.1
3,2026-04-06 10:50:00,W,631.6,273.1,380.9,822.6,2346.4
4,2026-04-06 10:45:00,E,4261.3,11928.1,1659.3,9034.6,31079.2
5,2026-04-06 10:45:00,W,649.3,307.6,446.7,846.5,2771.5
6,2026-04-06 10:40:00,E,4312.2,11886.3,1666.2,9134.4,31005.6
7,2026-04-06 10:40:00,W,636.4,303.5,436.5,846.8,2518.8
8,2026-04-06 10:35:00,E,4389.7,11800.5,1666.4,9189.7,31081.7
9,2026-04-06 10:35:00,W,648.4,318.2,445.9,847.1,2533.6

### 25. BAAZonalGenMixHourly (spp_physical.BAAZonalGenMixHourly) — E + W sum vs GenMixHourly

In [85]:
df_baa_hr = sql_functions.download_df_from_sql_db(
    "SELECT * "
    "FROM spp_physical.BAAZonalGenMixHourly "
    "WHERE dt = '2026-04-01' ORDER BY hr, BAA")
print(df_baa_hr.shape)
# spot check: E + W rows; WindTotal_E + WindTotal_W should ≈ GenMix WindTotal
df_baa_hr.head(10)

(28, 34)

,dt,hr,BAA,CoalMarket,CoalSelf,CoalTotal,DieselFuelOilMarket,DieselFuelOilSelf,DieselFuelOilTotal,HydroMarket,HydroSelf,HydroTotal,NaturalGasMarket,NaturalGasSelf,NaturalGasTotal,NuclearMarket,NuclearSelf,NuclearTotal,SolarMarket,SolarSelf,SolarTotal,WasteDisposalServicesMarket,WasteDisposalServicesSelf,WasteDisposalServicesTotal,WindMarket,WindSelf,WindTotal,WasteHeatMarket,WasteHeatSelf,WasteHeatTotal,OtherMarket,OtherSelf,OtherTotal,AverageActualLoad
0,2026-04-01,10,E,3564.0,3788.8,7352.8,0.0,1.6,1.6,79.8,1065.4,1145.2,12165.6,1267.2,13432.7,0.0,2022.2,2022.2,0.0,633.7,633.7,1.5,5.5,7.0,0.0,6735.6,6735.6,0.0,0.0,0.0,43.4,33.5,77.0,32438.6
1,2026-04-01,10,W,0.0,924.4,924.4,0.0,68.6,68.6,0.0,492.5,492.5,0.0,641.5,641.5,0.0,0.0,0.0,0.0,139.2,139.2,0.0,0.0,0.0,0.0,597.4,597.4,0.0,0.0,0.0,0.0,4.7,4.7,2733.8
2,2026-04-01,11,E,3566.4,3856.0,7422.4,37.6,7.9,45.5,2.4,1246.0,1248.4,12274.8,1285.3,13560.0,0.0,2023.1,2023.1,0.0,771.1,771.1,1.5,6.3,7.8,0.0,6471.4,6471.4,0.0,0.0,0.0,79.2,32.5,111.8,32887.3
3,2026-04-01,11,W,0.0,1025.9,1025.9,0.0,78.6,78.6,0.0,435.7,435.7,0.0,628.3,628.3,0.0,0.0,0.0,0.0,192.4,192.4,0.0,0.0,0.0,0.0,581.4,581.4,0.0,0.0,0.0,0.0,5.6,5.6,2729.4
4,2026-04-01,12,E,3497.6,3696.1,7193.6,143.2,1.6,144.7,2.4,1168.8,1171.2,11582.3,1051.9,12634.2,0.0,2020.8,2020.8,0.0,798.1,798.1,1.5,6.2,7.8,0.0,6962.3,6962.3,0.0,0.0,0.0,7.3,30.9,38.2,33195.4
5,2026-04-01,12,W,0.0,826.3,826.3,0.0,45.2,45.2,0.0,431.2,431.2,0.0,482.6,482.6,0.0,0.0,0.0,0.0,354.6,354.6,0.0,0.0,0.0,0.0,585.5,585.5,0.0,0.0,0.0,0.0,4.6,4.6,2678.9
6,2026-04-01,13,E,3324.2,3619.6,6943.8,146.0,1.6,147.6,6.1,1216.8,1222.9,10518.3,924.2,11442.4,0.0,2022.6,2022.6,0.0,882.9,882.9,1.5,6.2,7.7,0.0,8754.4,8754.4,0.0,0.0,0.0,11.6,28.3,39.9,33370.2
7,2026-04-01,13,W,0.0,768.3,768.3,0.0,82.4,82.4,0.0,436.4,436.4,0.0,345.6,345.6,0.0,0.0,0.0,0.0,364.5,364.5,0.0,0.0,0.0,0.0,543.9,543.9,0.0,0.0,0.0,0.0,4.8,4.8,2677.1
8,2026-04-01,14,E,3221.3,3430.8,6652.1,146.0,1.5,147.5,6.4,1280.9,1287.3,10148.7,1147.7,11296.4,0.0,2022.8,2022.8,0.0,825.8,825.8,1.5,6.2,7.8,0.0,10749.1,10749.1,0.0,0.0,0.0,25.4,27.1,52.6,33584.4
9,2026-04-01,14,W,0.0,826.8,826.8,0.0,71.3,71.3,0.0,456.1,456.1,0.0,411.0,411.0,0.0,0.0,0.0,0.0,387.0,387.0,0.0,0.0,0.0,0.0,526.6,526.6,0.0,0.0,0.0,0.0,4.7,4.7,2654.2

---
## TIE FLOWS

### 26. TieFlows (spp_physical.TieFlows)

In [18]:
df_tieflow = sql_functions.download_df_from_sql_db(
    "SELECT * FROM spp_physical.TieFlows "
    "WHERE DATE(GMTTime) = '2026-04-01' ORDER BY MarketTime LIMIT 100")
print(df_tieflow.shape)
print('Columns:', df_tieflow.columns.tolist())
df_tieflow.head(10)

(100, 30)
Columns: ['MarketTime', 'GMTTime', 'SPPNSI', 'DPC', 'MCWEST', 'CLEC', 'SPC', 'AMRN', 'OTP', 'GRE', 'MDU', 'SOUC', 'SPA', 'SGE', 'AECI', 'ERCOTN', 'WAUE', 'EDDY', 'ERCOTE', 'BLKW', 'LAMAR', 'MEC', 'SPPNAI', 'RCEAST', 'EES', 'NSP', 'SCSE', 'ALTW', 'TVA', 'SIKE']

,MarketTime,GMTTime,SPPNSI,DPC,MCWEST,CLEC,SPC,AMRN,OTP,GRE,...,LAMAR,MEC,SPPNAI,RCEAST,EES,NSP,SCSE,ALTW,TVA,SIKE
0,2026-03-31 19:00:00,2026-04-01 00:00:00,398.6,31.5,20.6,80.9,-34.5,287.1,347.1,229.3,...,0.6,-934.2,389.4,102.7,253.6,-263.3,0.0,-123.4,-49.9,0.0
1,2026-03-31 19:01:00,2026-04-01 00:01:00,410.1,31.5,20.7,80.1,-27.5,284.2,350.1,229.9,...,0.4,-962.2,356.6,108.8,244.7,-265.5,0.0,-123.4,-49.5,0.0
2,2026-03-31 19:02:00,2026-04-01 00:02:00,435.5,31.5,20.4,75.6,-26.1,282.4,356.6,232.0,...,0.4,-977.9,334.9,114.9,213.4,-260.2,0.0,-120.8,-49.9,0.0
3,2026-03-31 19:03:00,2026-04-01 00:03:00,446.4,32.0,20.5,76.9,-20.6,279.8,370.2,234.4,...,0.6,-961.1,365.2,121.5,196.9,-264.2,0.0,-117.2,-49.5,0.0
4,2026-03-31 19:04:00,2026-04-01 00:04:00,464.0,32.1,20.6,74.0,-13.4,275.5,378.9,236.4,...,-0.1,-941.0,348.6,127.2,138.9,-261.8,0.0,-114.0,-48.8,0.0
5,2026-03-31 19:05:00,2026-04-01 00:05:00,489.5,32.4,20.5,71.8,-13.3,271.7,381.2,237.9,...,1.3,-971.8,349.8,133.6,137.9,-259.3,0.0,-111.7,-47.2,0.0
6,2026-03-31 19:06:00,2026-04-01 00:06:00,434.5,32.7,20.3,75.9,-22.3,267.5,388.6,238.4,...,0.6,-1004.6,298.4,134.0,141.4,-268.9,0.0,-112.5,-46.1,0.0
7,2026-03-31 19:07:00,2026-04-01 00:07:00,435.4,32.5,20.5,78.2,-39.7,265.0,387.8,238.2,...,0.9,-1108.9,141.3,134.0,118.6,-273.9,0.0,-114.1,-43.4,0.0
8,2026-03-31 19:08:00,2026-04-01 00:08:00,452.7,32.6,20.6,84.9,-55.1,266.5,396.2,238.6,...,0.6,-1092.5,239.5,134.0,174.1,-272.6,0.0,-117.7,-43.0,0.0
9,2026-03-31 19:09:00,2026-04-01 00:09:00,440.2,32.5,20.6,92.3,-50.2,274.6,399.2,247.7,...,0.4,-1071.1,302.6,134.0,193.4,-264.4,0.0,-115.1,-42.2,0.0

---
## RNU RATE

### 27. RNU Rate (spp_virtual.rnu_rate)

In [15]:
df_rnu = sql_functions.download_df_from_sql_db(
    "SELECT * FROM spp_virtual.rnu_rate "
    "ORDER BY dt DESC LIMIT 50")
print(df_rnu.shape)
df_rnu.head(10)

(50, 5)

           dt Run_Type  RT_RNU_Dist_Rate  RNU_Rate_Forecast      source
0  2026-04-07    Frcst           -0.4716            -0.4716  ForecastV1
1  2026-04-06    Frcst           -0.4716            -0.4716  ForecastV1
2  2026-04-05    Frcst           -0.4716            -0.4716  ForecastV1
3  2026-04-04    Frcst           -0.4716            -0.4716  ForecastV1
4  2026-04-03    Frcst           -0.4716            -0.4716  ForecastV1
5  2026-04-02    Frcst           -0.4716            -0.4716  ForecastV1
6  2026-04-01    Frcst           -0.4716            -0.4716  ForecastV1
7  2026-03-31    Frcst           -0.4716            -0.4716  ForecastV1
8  2026-03-30    Frcst           -0.4716            -0.4716  ForecastV1
9  2026-03-29    Frcst           -0.4716            -0.4716  ForecastV1

### 28. RNU Rate Detailed (spp_virtual.rnu_rate_detailed)

In [16]:
df_rnu_det = sql_functions.download_df_from_sql_db(
    "SELECT * FROM spp_virtual.rnu_rate_detailed "
    "ORDER BY dt DESC LIMIT 50")
print(df_rnu_det.shape)
df_rnu_det.head(10)

(50, 14)

,auto_id,dt,Run_Type,DA_Inadequacy,RT_Inadequacy,RT_Out_of_Merit,RT_Reg_Dep_ADJ,RT_JOA,RT_Net_Inadvertent,RT_Congestion,RT_RNU_Dist_Qty,RT_RNU_Dist_Rate,RT_RNU_Hrly_Amt,source
0,8936,2026-03-17,S7,35.39,-2434280.0,-235974.00,-48091.50,536581.0,5114.84,-2429240.0,2091530.0,-1.0431,2181670.0,ftp
1,8937,2026-03-16,S7,14.77,-166803.0,-29995.60,-11438.60,680046.0,27075.60,-139809.0,2081520.0,0.2267,-471884.0,ftp
2,8938,2026-03-15,S7,21.30,-1430000.0,-1044.56,-23408.40,772266.0,3073.29,-1427000.0,1915030.0,-0.3562,682137.0,ftp
3,8939,2026-03-14,S7,-45.05,-713455.0,-654.43,9132.07,335411.0,-6809.07,-720302.0,1781430.0,-0.2075,369636.0,ftp
4,8940,2026-03-13,S7,-16.25,378596.0,-952.92,-23912.30,205847.0,-579785.00,-201210.0,1797160.0,0.3114,-559623.0,ftp
5,8941,2026-03-12,S7,10.95,-455971.0,0.00,-26191.30,224016.0,11495.50,-444514.0,1959210.0,-0.1318,258230.0,ftp
6,8942,2026-03-11,S7,-26.16,-1970000.0,0.00,-12929.10,640875.0,-8588.67,-1978680.0,1941920.0,-0.6911,1342080.0,ftp
7,8901,2026-03-10,S7,2.74,-1023470.0,-39491.90,-19734.50,530062.0,827.45,-1022670.0,1912100.0,-0.2890,552619.0,ftp
8,8902,2026-03-09,S7,13.30,-549151.0,-12234.50,-37190.70,309633.0,19538.00,-529687.0,1800350.0,-0.1605,288942.0,ftp
9,8903,2026-03-08,S7,18.32,-635888.0,-1673.46,-2075.56,79495.2,-8633.87,-644632.0,1707120.0,-0.3281,560107.0,ftp

---
## OP CHARGES (MWP)

### 29. Op Reserve and Fees (spp_virtual.v3_op_reserve_and_fees)

In [105]:
df_opcharge = sql_functions.download_df_from_sql_db(
    "SELECT * FROM spp_virtual.v3_op_reserve_and_fees "
    "ORDER BY dt DESC LIMIT 100")
print(df_opcharge.shape)
print('Columns:', df_opcharge.columns.tolist())
df_opcharge.head(20)

(100, 4)
Columns: ['dt', 'daMwpDistRate', 'rtMwpDistRate', 'source']

            dt  daMwpDistRate  rtMwpDistRate      source
0   2026-04-11         0.3993         0.9525  forecastV2
1   2026-04-10         0.2057         1.1162  forecastV2
2   2026-04-09         0.4258         1.3488  forecastV2
3   2026-04-08         0.4790         1.0496  forecastV2
4   2026-04-07         0.3690         0.9374  forecastV2
5   2026-04-06         0.2423         0.8814  forecastV2
6   2026-04-05         0.1645         0.9928  forecastV2
7   2026-04-04         0.2818         0.8553  forecastV2
8   2026-04-03         0.4005         1.0808  forecastV2
9   2026-04-02         0.3155         0.9194  forecastV2
10  2026-04-01         0.3386         1.0200  forecastV2
11  2026-03-31         0.4006         0.9613  forecastV2
12  2026-03-30         0.3880         0.9131  forecastV2
13  2026-03-29         0.3701         0.6972  forecastV2
14  2026-03-28         0.3564         0.7763  forecastV2
15  2026-03-27         0.3707         0.8524  forecastV2
16  2026-03-26         0.4693         1.2303  forecastV2
17  2026-03-25         0.2733         1.0809  forecastV2
18  2026-03-24         0.4735         2.2306         ftp
19  2026-03-23         0.3011         0.8059         ftp

---
## CONSTRAINTS

### 30. DA Constraint Congestion (spp_constraints.congestion_da_hourly_v3)

Raw table — downloaded by `SPP_download_DA_Constraints_v20170324.php`. Tracks DA binding constraint shadow prices (M-values) per hour.

In [8]:
df_da_cong = sql_functions.download_df_from_sql_db(
    "SELECT * "
    "FROM spp_constraints.congestion_da_hourly_v3 "
    "WHERE dt = '{}' "
    "ORDER BY mvalue DESC LIMIT 20".format(START)
)
print(df_da_cong.shape)
display(df_da_cong.head(20))

(20, 4)

            dt  hr  ConstraintNum  MValue
0   2026-04-01   9         830532 -0.0068
1   2026-04-01   2         830532 -0.0375
2   2026-04-01   4         830532 -0.0487
3   2026-04-01   6         830532 -0.0532
4   2026-04-01   3         830532 -0.0575
5   2026-04-01   5         830532 -0.1058
6   2026-04-01  10         830535 -0.1146
7   2026-04-01   1         830532 -0.1230
8   2026-04-01   3         511187 -0.1318
9   2026-04-01   8         830532 -0.1457
10  2026-04-01  16         867601 -0.1627
11  2026-04-01   7         830532 -0.1627
12  2026-04-01  14         568501 -0.2780
13  2026-04-01  11         830535 -0.3823
14  2026-04-01  20            544 -0.4258
15  2026-04-01  18            731 -0.4837
16  2026-04-01  19         287069 -0.6748
17  2026-04-01   9         566138 -0.6853
18  2026-04-01  17         785959 -0.7285
19  2026-04-01  18         862424 -0.7630

### 31. DA Constraint M-Values via nighthawk `Constraint.get_mvalues()`

Reads from `congestion_da_hourly_v3`. Returns M-values (shadow prices × MW) for all constraints. Use `granularity='hourly'` for hour-by-hour breakdown.

In [9]:
from nighthawk.data.network.constraint import Constraint

constraint_spp = Constraint(oops_constraint_num_df=None, market='SPP')
df_da_mval = constraint_spp.get_mvalues(START, END, type='DA', granularity='hourly')
print(df_da_mval.shape)
display(df_da_mval.sort_values('mvalue', ascending=False).head(20))

(462, 4)

     oops_constraint_num          dt  hr  mvalue
95                830532  2026-04-01   9 -0.0068
17                830532  2026-04-01   2 -0.0375
37                830532  2026-04-01   4 -0.0487
62                830532  2026-04-01   6 -0.0532
27                830532  2026-04-01   3 -0.0575
49                830532  2026-04-01   5 -0.1058
110               830535  2026-04-01  10 -0.1146
8                 830532  2026-04-01   1 -0.1230
22                511187  2026-04-01   3 -0.1318
82                830532  2026-04-01   8 -0.1457
73                830532  2026-04-01   7 -0.1627
232               867601  2026-04-01  16 -0.1627
168               568501  2026-04-01  14 -0.2780
123               830535  2026-04-01  11 -0.3823
325                  544  2026-04-01  20 -0.4258
267                  731  2026-04-01  18 -0.4837
296               287069  2026-04-01  19 -0.6748
91                566138  2026-04-01   9 -0.6853
257               785959  2026-04-01  17 -0.7285
289               862424  2026-04-01  18 -0.7630

### 32. DA Constraint Family M-Values via `ConstraintFamily.get_mvalues()`

Reads `congestion_da_hourly_v3` + `ConstraintFamilyMaster_v3`. Groups constraints by monitored facility name.

In [12]:
from nighthawk.data.network.constraint_family import ConstraintFamily

cf_spp = ConstraintFamily(constraint_family_num_df=None, opexchange='SPP')
df_cf_mval = cf_spp.get_mvalues(START, END, type='DA', granularity='daily')
print(df_cf_mval.shape)
display(df_cf_mval.sort_values('mvalue', ascending=False).head(20))

(63, 3)

    constraintFamilyNum          dt   mvalue
49              1223658  2026-04-01  -0.1627
51              1223737  2026-04-01  -0.2780
60              1802563  2026-04-01  -0.7409
23                 6299  2026-04-01  -1.9271
58              1722555  2026-04-01  -2.0716
38               498407  2026-04-01  -2.0750
53              1224367  2026-04-01  -3.1680
22                 1037  2026-04-01  -4.9182
9                   648  2026-04-01  -7.1712
55              1357050  2026-04-01  -8.2805
4                   299  2026-04-01  -8.5963
13                  799  2026-04-01  -8.6984
35               334398  2026-04-01  -9.8629
50              1223676  2026-04-01 -14.2566
40               510053  2026-04-01 -23.8229
15                  902  2026-04-01 -28.1484
36               390730  2026-04-01 -34.3760
45               792695  2026-04-01 -37.3206
59              1802562  2026-04-01 -39.3891
48              1156298  2026-04-01 -43.2658

### 33. RT Constraint Congestion Hourly (spp_constraints.congestion_rt_hourly_v3)

Aggregated from 5-min intervals. Same structure as DA but for RTBM.

In [ ]:
df_rt_cong_hr = sql_functions.download_df_from_sql_db(
    "SELECT *"
    "FROM spp_constraints.congestion_rt_hourly_v3 "
    "WHERE dt = '{}' "
    "ORDER BY mvalue DESC LIMIT 20".format(START)
)
print(df_rt_cong_hr.shape)
display(df_rt_cong_hr.head(20))

(20, 4)

            dt  hr  ConstraintNum  MValue
0   2026-04-01  24         433608 -0.0576
1   2026-04-01  12         867609 -0.3901
2   2026-04-01  12         867791 -0.4408
3   2026-04-01   3         634003 -0.5508
4   2026-04-01  15         867609 -0.8661
5   2026-04-01  20         819280 -0.9176
6   2026-04-01  24         351341 -1.2380
7   2026-04-01  23         634003 -1.6817
8   2026-04-01  14         867609 -2.2330
9   2026-04-01  22         634003 -2.6842
10  2026-04-01  24         867861 -2.7792
11  2026-04-01  19         674432 -2.8292
12  2026-04-01   7         800833 -3.1850
13  2026-04-01  19         819280 -3.4163
14  2026-04-01  10         800833 -4.4150
15  2026-04-01  21         829637 -6.0045
16  2026-04-01   9         543835 -6.9511
17  2026-04-01  18         867609 -7.5031
18  2026-04-01  19         762555 -7.5129
19  2026-04-01  18         867861 -7.7585

### 34. RT Constraint Congestion 5-min (spp_constraints.congestion_rt_5_min_v3)

Highest-frequency constraint data — used by the contour map for real-time display.

In [61]:
df_rt_cong_5m = sql_functions.download_df_from_sql_db(
    "SELECT * "
    "FROM spp_constraints.congestion_rt_hourly_v3 "
    "WHERE dt >= '2026-04-01' "
    "ORDER BY dt "
    "LIMIT 20"
)

print(df_rt_cong_5m.shape)
display(df_rt_cong_5m.head(40))

(20, 4)

            dt  hr  ConstraintNum     MValue
0   2026-04-01   1         653411  -305.6833
1   2026-04-01   1         825657  -135.7030
2   2026-04-01   2         653411  -836.1967
3   2026-04-01   2         681335   -47.6150
4   2026-04-01   3         351341   -25.2826
5   2026-04-01   3         634003    -0.5508
6   2026-04-01   3         653411  -145.4984
7   2026-04-01   3         681335   -19.4162
8   2026-04-01   4         351341   -34.5707
9   2026-04-01   5         351341   -56.5493
10  2026-04-01   6         351341   -62.8231
11  2026-04-01   7         351341   -46.6060
12  2026-04-01   7         800833    -3.1850
13  2026-04-01   7         863216  -783.3210
14  2026-04-01   8         351341   -32.3053
15  2026-04-01   8         800833    -9.9458
16  2026-04-01   8         863216 -1381.4667
17  2026-04-01   9         351341   -23.2036
18  2026-04-01   9         499254   -52.0536
19  2026-04-01   9         543835    -6.9511

### 35. RT Constraint M-Values via nighthawk `Constraint.get_mvalues(type='RT')`

In [57]:
df_rt_mval = constraint_spp.get_mvalues(START, END, type='RT', granularity='hourly')
print(df_rt_mval.shape)
display(df_rt_mval.sort_values('mvalue', ascending=False))
display(df_rt_mval[df_rt_mval['hr']==1])

(178, 4)

     oops_constraint_num          dt  hr     mvalue
168               433608  2026-04-01  24    -0.0576
42                867609  2026-04-01  12    -0.3901
43                867791  2026-04-01  12    -0.4408
5                 634003  2026-04-01   3    -0.5508
69                867609  2026-04-01  15    -0.8661
..                   ...         ...  ..        ...
119               653411  2026-04-01  20 -1256.0846
161               653411  2026-04-01  23 -1270.3324
133               653411  2026-04-01  21 -1330.6849
16                863216  2026-04-01   8 -1381.4667
60                867791  2026-04-01  14 -1422.4462

[178 rows x 4 columns]

   oops_constraint_num          dt  hr    mvalue
0               653411  2026-04-01   1 -305.6833
1               825657  2026-04-01   1 -135.7030

### 36. Constraint Rolling Summaries (7D / 30D / 365D)

Pre-computed rolling M-value aggregates for trend analysis.

In [22]:
df_7d = sql_functions.download_df_from_sql_db(
    "SELECT * FROM spp_constraints.congestion_rt_7D_v3  LIMIT 10"
)
df_30d = sql_functions.download_df_from_sql_db(
    "SELECT * FROM spp_constraints.congestion_rt_30D_v3  LIMIT 10"
)
df_365d = sql_functions.download_df_from_sql_db(
    "SELECT * FROM spp_constraints.congestion_rt_365D_v3  LIMIT 10"
)
print('7D:', df_7d.shape)
display(df_7d)
print('30D:', df_30d.shape)
display(df_30d)
print('365D:', df_365d.shape)
display(df_365d)

7D: (0, 7)

Empty DataFrame
Columns: [ConstraintNum, TotalOn, TotalOff, OnHrs, OffHrs, OnAvg, OffAvg]
Index: []

30D: (0, 4)

Empty DataFrame
Columns: [dt, hr, ConstraintNum, MValue]
Index: []

365D: (0, 4)

Empty DataFrame
Columns: [dt, hr, ConstraintNum, MValue]
Index: []

---
## LMP (SETTLEMENT LOCATION PRICES)

**Nighthawk entry point:** `Node(node_nums=[...], market='SPP').get_price()`  
**Source tables:**
- DA hourly → `spp_lmp.settlement_location_da_hourly` (`da_value`, `congestional_value`, `marginalloss_value`)
- RT hourly → `spp_lmp.settlement_location_rt_hourly` (`rt_value`, `congestional_value`, `marginalloss_value`)
- RT daily summary → `spp_lmp.sl_rt_daily_summary` (`daily`, `on_peak`, `off_peak`, `daily_congestion`, ...)
- DA daily summary → `spp_lmp.sl_da_daily_summary`

**Note:** `rt_hrly_from_5min_table` for SPP points to the same `settlement_location_rt_hourly` (no separate fallback table).  
**Reprice:** `settlement_location_da_hourly_reprice` is written weekly; 0 rows for 2026-04-01 is expected.

### 37. DA Hourly LMP — Raw (spp_lmp.settlement_location_da_hourly)

Written by `download_LMP_from_CSV_to_DB3.php` via `REPLACE INTO`.  
**Columns:** `dt, hr, node_num, da_value (LMP), congestional_value (MCC), marginalloss_value (MLC)`  
**Expected for 2026-04-01:** 1580 nodes × 24 hrs = **37,920 rows**

In [62]:
# SPP North Hub node_num=635 — use as reference node
HUB_NODE = 635

df_da_lmp = sql_functions.download_df_from_sql_db(
    "SELECT dt, hr, node_num, da_value, congestional_value, marginalloss_value "
    "FROM spp_lmp.settlement_location_da_hourly "
    "WHERE dt='2026-04-01' AND node_num=635 "
    "ORDER BY hr"
)
# Check LMP = MCC + MLC + Slack (energy component)
df_da_lmp['implied_slack'] = df_da_lmp['da_value'] - df_da_lmp['congestional_value'] - df_da_lmp['marginalloss_value']
print('DA hourly shape:', df_da_lmp.shape, '  expected (24, 6)')
print('LMP decomp check (MCC+MLC+Slack should = LMP):')
display(df_da_lmp)

DA hourly shape: (24, 7)   expected (24, 6)
LMP decomp check (MCC+MLC+Slack should = LMP):

,dt,hr,node_num,da_value,congestional_value,marginalloss_value,implied_slack
0,2026-04-01,1,635,20.5748,-2.3471,-0.1380,23.0599
1,2026-04-01,2,635,16.8729,-0.4388,-0.1371,17.4488
2,2026-04-01,3,635,16.9680,-0.5097,-0.2124,17.6901
3,2026-04-01,4,635,17.2085,-0.2966,-0.3332,17.8383
4,2026-04-01,5,635,16.7601,-0.8054,-0.3227,17.8882
5,2026-04-01,6,635,21.5390,-0.4000,-0.4260,22.3650
6,2026-04-01,7,635,30.6228,-1.7332,-0.4494,32.8054
7,2026-04-01,8,635,30.5674,-1.8568,-0.3425,32.7667
8,2026-04-01,9,635,33.4855,-3.9063,-0.5511,37.9429
9,2026-04-01,10,635,43.5319,5.9016,-0.6434,38.2737
10,2026-04-01,11,635,38.3389,9.5046,-0.4206,29.2549
11,2026-04-01,12,635,30.3103,5.7453,-0.4222,24.9872
12,2026-04-01,13,635,23.6611,2.2835,-0.4037,21.7813
13,2026-04-01,14,635,18.7365,-0.2930,-0.3728,19.4023
14,2026-04-01,15,635,19.3938,-2.1171,-0.5317,22.0426
15,2026-04-01,16,635,17.3649,-1.2884,-0.5633,19.2166
16,2026-04-01,17,635,18.1596,-4.4051,-0.6992,23.2639
17,2026-04-01,18,635,25.1353,1.5826,-0.6098,24.1625
18,2026-04-01,19,635,19.1629,-2.9177,-0.5784,22.6590
19,2026-04-01,20,635,23.0055,-0.0533,-0.2141,23.2729
20,2026-04-01,21,635,20.3994,-0.8413,-0.2019,21.4426
21,2026-04-01,22,635,6.4973,-6.1654,-0.2261,12.8888
22,2026-04-01,23,635,3.6945,-1.0721,-0.1342,4.9008
23,2026-04-01,24,635,-0.4070,1.3519,0.0524,-1.8113

### 38. Row count check — DA 2026-04-01 should have exactly 37,920 rows

In [63]:
df_da_cnt = sql_functions.download_df_from_sql_db(
    "SELECT COUNT(DISTINCT node_num) as nodes, COUNT(DISTINCT hr) as hrs, COUNT(*) as total "
    "FROM spp_lmp.settlement_location_da_hourly WHERE dt='2026-04-01'"
)
print('DA 2026-04-01 count:', df_da_cnt.to_string(index=False))
assert df_da_cnt['total'][0] == 37920, f"Expected 37920, got {df_da_cnt['total'][0]}"
print('PASS: 1580 nodes x 24 hrs = 37920')

DA 2026-04-01 count:  nodes  hrs  total
  1580   24  37920
PASS: 1580 nodes x 24 hrs = 37920

### 39. DA LMP Reprice (spp_lmp.settlement_location_da_hourly_reprice)

Written by `spp_dataDownload_da_lmp_reprice.py` — runs **weekly**, not daily.  
0 rows for a given date is **normal** unless that date was repriced.  
Columns: `dt, hr, node_num, Revision, Reason, da_value, marginalloss_value, congestional_value, Modified_Date`

In [65]:
df_reprice = sql_functions.download_df_from_sql_db(
    "SELECT dt, hr, node_num, Revision, Reason, da_value, Modified_Date "
    "FROM spp_lmp.settlement_location_da_hourly_reprice "
    "WHERE dt='2026-04-01' "
    "ORDER BY hr, Revision"
)
print('Reprice rows for 2026-04-01 hub node:', df_reprice.shape[0])
print('(0 rows expected — reprice runs weekly and only if SPP re-publishes the file)')
display(df_reprice)

Reprice rows for 2026-04-01 hub node: 0
(0 rows expected — reprice runs weekly and only if SPP re-publishes the file)

Empty DataFrame
Columns: [dt, hr, node_num, Revision, Reason, da_value, Modified_Date]
Index: []

### 40. RT 5-min LMP — Raw (spp_lmp.sl_rt_5_min)

Written by `SPP_download_DART_LMP.php` (mode=rt) and gap-filled by `SPPLMPDailyCheck_5min.py`.  
**Columns:** `forecast_time (interval end datetime), dt, hr, node_num, rt_value, congestional_value, marginalloss_value`  
**Expected:** 12 intervals per hr × 24 hrs × ~1580 nodes

In [66]:
df_rt_5m = sql_functions.download_df_from_sql_db(
    "SELECT forecast_time, dt, hr, node_num, rt_value, congestional_value, marginalloss_value "
    "FROM spp_lmp.sl_rt_5_min "
    "WHERE dt='2026-04-01' AND hr=10 AND node_num=635 "
    "ORDER BY forecast_time"
)
print('RT 5-min for hub node hr=10:', df_rt_5m.shape, '  expected (12, 7)')
display(df_rt_5m)

RT 5-min for hub node hr=10: (12, 7)   expected (12, 7)

,forecast_time,dt,hr,node_num,rt_value,congestional_value,marginalloss_value
0,2026-04-01 09:05:00,2026-04-01,10,635,26.0402,-0.7913,-1.2187
1,2026-04-01 09:10:00,2026-04-01,10,635,31.9450,-0.6733,-1.4542
2,2026-04-01 09:15:00,2026-04-01,10,635,32.5124,-0.8039,-1.5158
3,2026-04-01 09:20:00,2026-04-01,10,635,38.3603,-0.8446,-1.7496
4,2026-04-01 09:25:00,2026-04-01,10,635,43.7941,-0.5941,-2.0328
5,2026-04-01 09:30:00,2026-04-01,10,635,51.5973,-1.2350,-2.2882
6,2026-04-01 09:35:00,2026-04-01,10,635,49.4960,-1.1183,-2.1351
7,2026-04-01 09:40:00,2026-04-01,10,635,66.9718,-1.6028,-2.8926
8,2026-04-01 09:45:00,2026-04-01,10,635,75.6710,-2.1242,-3.3331
9,2026-04-01 09:50:00,2026-04-01,10,635,77.8271,-1.9417,-3.6093
10,2026-04-01 09:55:00,2026-04-01,10,635,77.9529,-1.9706,-3.8188
11,2026-04-01 10:00:00,2026-04-01,10,635,79.9657,-5.5639,-4.0238

### 41. RT Hourly LMP — Raw (spp_lmp.settlement_location_rt_hourly)

Derived from `sl_rt_5_min` by `AVG(rt_value) GROUP BY (dt, hr, node_num)`.  
**Expected for 2026-04-01:** up to 37,920 rows — actual is **37,622** (298 gaps expected due to RTBM timing)

In [67]:
df_rt_lmp = sql_functions.download_df_from_sql_db(
    "SELECT dt, hr, node_num, rt_value, congestional_value, marginalloss_value "
    "FROM spp_lmp.settlement_location_rt_hourly "
    "WHERE dt='2026-04-01' AND node_num=635 "
    "ORDER BY hr"
)
print('RT hourly shape:', df_rt_lmp.shape, '  expected (24, 6)')
display(df_rt_lmp)

RT hourly shape: (24, 6)   expected (24, 6)

            dt  hr  node_num  rt_value  congestional_value  marginalloss_value
0   2026-04-01   1       635   11.3352             -2.3271             -0.6324
1   2026-04-01   2       635   11.2304             -2.0801             -0.5788
2   2026-04-01   3       635   18.0865             -0.3879             -0.6114
3   2026-04-01   4       635   19.3214              0.1538             -0.6777
4   2026-04-01   5       635   25.7622              0.2508             -0.8960
5   2026-04-01   6       635   36.3466              0.2727             -1.6857
6   2026-04-01   7       635   33.4603             -0.4688             -1.4933
7   2026-04-01   8       635   48.6189             -1.0068             -1.7959
8   2026-04-01   9       635  145.2658             -0.5969             -6.0424
9   2026-04-01  10       635   54.3445             -1.6053             -2.5060
10  2026-04-01  11       635  228.6487             -5.3207            -13.7183
11  2026-04-01  12       635  617.3986             -7.5591            -36.8743
12  2026-04-01  13       635   26.7379             -1.3428             -1.7101
13  2026-04-01  14       635   20.5922             -4.4347             -1.3271
14  2026-04-01  15       635   22.7319             -3.1869             -1.1310
15  2026-04-01  16       635   17.6549             -0.7463             -0.5553
16  2026-04-01  17       635   35.2014             -2.2482             -0.8418
17  2026-04-01  18       635   52.2118              5.1268             -1.6157
18  2026-04-01  19       635   41.2100             10.9938             -1.1211
19  2026-04-01  20       635   52.8241             12.6954             -1.5639
20  2026-04-01  21       635   28.7835             -0.3284             -1.0716
21  2026-04-01  22       635    3.0427             -7.4002             -0.5428
22  2026-04-01  23       635    1.0771             -8.6286             -0.3900
23  2026-04-01  24       635   -7.0416             -8.4476             -0.0382

### 42. Node.get_price() — nighthawk function (DA + RT hourly)

**SPP DA path:** reads `settlement_location_da_hourly` directly  
**SPP RT path:** reads `settlement_location_rt_hourly`; if end_dt > max(dt), falls back to same table  
**Column mapping:**
- `da_value` → `da_total` (LMP)
- `congestional_value` → `da_congestion` (MCC)
- `marginalloss_value` → `da_loss` (MLC)
- `da_value - congestional_value - marginalloss_value` → `da_slack`

In [86]:
from nighthawk.data.network.node import Node

node_spp = Node(node_nums=[635], market='SPP')

# DA hourly
df_node_da = node_spp.get_price('2026-04-01', '2026-04-01',
                                component=['LMP','MCC','MLC','Slack'], type=['DA'], granularity='hourly')
print('Node DA hourly:', df_node_da.shape)
display(df_node_da)

# RT hourly
df_node_rt = node_spp.get_price('2026-04-01', '2026-04-01',
                                component=['LMP','MCC','MLC','Slack'], type=['RT'], granularity='hourly')
print('Node RT hourly:', df_node_rt.shape)
display(df_node_rt)

Node DA hourly: (24, 7)

            dt  hr  node_num   da_total  da_congestion  da_loss   da_slack
0   2026-04-01   1       635  20.574800        -2.3471  -0.1380  23.059900
1   2026-04-01   2       635  16.872900        -0.4388  -0.1371  17.448799
2   2026-04-01   3       635  16.968000        -0.5097  -0.2124  17.690100
3   2026-04-01   4       635  17.208500        -0.2966  -0.3332  17.838301
4   2026-04-01   5       635  16.760099        -0.8054  -0.3227  17.888201
5   2026-04-01   6       635  21.539000        -0.4000  -0.4260  22.365000
6   2026-04-01   7       635  30.622801        -1.7332  -0.4494  32.805401
7   2026-04-01   8       635  30.567400        -1.8568  -0.3425  32.766701
8   2026-04-01   9       635  33.485500        -3.9063  -0.5511  37.942902
9   2026-04-01  10       635  43.531898         5.9016  -0.6434  38.273701
10  2026-04-01  11       635  38.338902         9.5046  -0.4206  29.254900
11  2026-04-01  12       635  30.310301         5.7453  -0.4222  24.987200
12  2026-04-01  13       635  23.661100         2.2835  -0.4037  21.781300
13  2026-04-01  14       635  18.736500        -0.2930  -0.3728  19.402300
14  2026-04-01  15       635  19.393801        -2.1171  -0.5317  22.042601
15  2026-04-01  16       635  17.364901        -1.2884  -0.5633  19.216600
16  2026-04-01  17       635  18.159599        -4.4051  -0.6992  23.263901
17  2026-04-01  18       635  25.135300         1.5826  -0.6098  24.162500
18  2026-04-01  19       635  19.162901        -2.9177  -0.5784  22.659000
19  2026-04-01  20       635  23.005501        -0.0533  -0.2141  23.272900
20  2026-04-01  21       635  20.399401        -0.8413  -0.2019  21.442600
21  2026-04-01  22       635   6.497300        -6.1654  -0.2261  12.888800
22  2026-04-01  23       635   3.694500        -1.0721  -0.1342   4.900800
23  2026-04-01  24       635  -0.407000         1.3519   0.0524  -1.811300

Node RT hourly: (24, 7)

            dt  hr  node_num    rt_total  rt_congestion    rt_loss    rt_slack
0   2026-04-01   1       635   11.335200        -2.3271  -0.632400   14.294700
1   2026-04-01   2       635   11.230400        -2.0801  -0.578800   13.889300
2   2026-04-01   3       635   18.086500        -0.3879  -0.611400   19.085800
3   2026-04-01   4       635   19.321400         0.1538  -0.677700   19.845301
4   2026-04-01   5       635   25.762199         0.2508  -0.896000   26.407400
5   2026-04-01   6       635   36.346600         0.2727  -1.685700   37.759602
6   2026-04-01   7       635   33.460300        -0.4688  -1.493300   35.422401
7   2026-04-01   8       635   48.618900        -1.0068  -1.795900   51.421600
8   2026-04-01   9       635  145.265793        -0.5969  -6.042400  151.905106
9   2026-04-01  10       635   54.344501        -1.6053  -2.506000   58.455799
10  2026-04-01  11       635  228.648697        -5.3207 -13.718300  247.687698
11  2026-04-01  12       635  617.398621        -7.5591 -36.874298  661.831970
12  2026-04-01  13       635   26.737900        -1.3428  -1.710100   29.790800
13  2026-04-01  14       635   20.592199        -4.4347  -1.327100   26.354000
14  2026-04-01  15       635   22.731899        -3.1869  -1.131000   27.049801
15  2026-04-01  16       635   17.654900        -0.7463  -0.555300   18.956499
16  2026-04-01  17       635   35.201401        -2.2482  -0.841800   38.291401
17  2026-04-01  18       635   52.211800         5.1268  -1.615700   48.700699
18  2026-04-01  19       635   41.209999        10.9938  -1.121100   31.337299
19  2026-04-01  20       635   52.824100        12.6954  -1.563900   41.692600
20  2026-04-01  21       635   28.783501        -0.3284  -1.071600   30.183500
21  2026-04-01  22       635    3.042700        -7.4002  -0.542800   10.985700
22  2026-04-01  23       635    1.077100        -8.6286  -0.390000   10.095700
23  2026-04-01  24       635   -7.041600        -8.4476  -0.038200    1.444200

### 43. Cross-check: Node.get_price() vs raw table — values must match

In [87]:
# DA: congestional_value in raw == da_congestion in nighthawk
merge_da = df_da_lmp[['dt','hr','congestional_value']].merge(
    df_node_da[['dt','hr','da_congestion']], on=['dt','hr'], how='outer'
)
merge_da['dt'] = merge_da['dt'].astype(str)
merge_da['diff'] = (merge_da['congestional_value'] - merge_da['da_congestion']).abs()
print('DA MCC diff (max should be ~0):', merge_da['diff'].max())

# RT: rt_value in raw == rt_total in nighthawk
merge_rt = df_rt_lmp[['dt','hr','rt_value']].merge(
    df_node_rt[['dt','hr','rt_total']], on=['dt','hr'], how='outer'
)
merge_rt['dt'] = merge_rt['dt'].astype(str)
merge_rt['diff'] = (merge_rt['rt_value'] - merge_rt['rt_total']).abs()
print('RT LMP diff (max should be ~0):', merge_rt['diff'].max())

DA MCC diff (max should be ~0): 4.2877197259372224e-07
RT LMP diff (max should be ~0): 2.0605468762369128e-05

### 44. Last-30-Day Rolling Tables (sl_da_hourly_last30days / sl_rt_hourly_last30days)

Same schema as core hourly tables. Used by nighthawk for faster recent-date queries.  
Written by OOPSify after each DA/RT download.

In [88]:
df_da_30d = sql_functions.download_df_from_sql_db(
    "SELECT dt, hr, node_num, da_value, congestional_value "
    "FROM spp_lmp.sl_da_hourly_last30days "
    "WHERE dt='2026-04-01' AND node_num=635 ORDER BY hr"
)
df_rt_30d = sql_functions.download_df_from_sql_db(
    "SELECT dt, hr, node_num, rt_value, congestional_value "
    "FROM spp_lmp.sl_rt_hourly_last30days "
    "WHERE dt='2026-04-01' AND node_num=635 ORDER BY hr"
)
print('DA last30d:', df_da_30d.shape, '  RT last30d:', df_rt_30d.shape)
display(df_da_30d)

DA last30d: (24, 5)   RT last30d: (24, 5)

            dt  hr  node_num  da_value  congestional_value
0   2026-04-01   1       635   20.5748             -2.3471
1   2026-04-01   2       635   16.8729             -0.4388
2   2026-04-01   3       635   16.9680             -0.5097
3   2026-04-01   4       635   17.2085             -0.2966
4   2026-04-01   5       635   16.7601             -0.8054
5   2026-04-01   6       635   21.5390             -0.4000
6   2026-04-01   7       635   30.6228             -1.7332
7   2026-04-01   8       635   30.5674             -1.8568
8   2026-04-01   9       635   33.4855             -3.9063
9   2026-04-01  10       635   43.5319              5.9016
10  2026-04-01  11       635   38.3389              9.5046
11  2026-04-01  12       635   30.3103              5.7453
12  2026-04-01  13       635   23.6611              2.2835
13  2026-04-01  14       635   18.7365             -0.2930
14  2026-04-01  15       635   19.3938             -2.1171
15  2026-04-01  16       635   17.3649             -1.2884
16  2026-04-01  17       635   18.1596             -4.4051
17  2026-04-01  18       635   25.1353              1.5826
18  2026-04-01  19       635   19.1629             -2.9177
19  2026-04-01  20       635   23.0055             -0.0533
20  2026-04-01  21       635   20.3994             -0.8413
21  2026-04-01  22       635    6.4973             -6.1654
22  2026-04-01  23       635    3.6945             -1.0721
23  2026-04-01  24       635   -0.4070              1.3519

### 45. Daily Summary LMP (sl_rt_daily_summary / sl_da_daily_summary)

Written by OOPSify. Used by `Node.get_price(..., granularity='daily')`.  
**Columns:** `dt, node_num, daily, on_peak, off_peak, daily_congestion, on_peak_congestion, off_peak_congestion, daily_marginloss, ...`  
**Expected for 2026-04-01:** 1,580 rows (one per node)

In [89]:
df_rt_daily = sql_functions.download_df_from_sql_db(
    "SELECT * FROM spp_lmp.sl_rt_daily_summary "
    "WHERE dt='2026-04-01' AND node_num=635"
)
print('RT daily summary (node 635):', df_rt_daily.shape)
display(df_rt_daily)

# Row count check
df_rt_daily_cnt = sql_functions.download_df_from_sql_db(
    "SELECT COUNT(*) as total FROM spp_lmp.sl_rt_daily_summary WHERE dt='2026-04-01'"
)
print('Total RT daily rows:', df_rt_daily_cnt['total'][0], ' expected ~1580')

RT daily summary (node 635): (1, 11)

,dt,node_num,on_peak,off_peak,daily,on_peak_congestion,off_peak_congestion,daily_congestion,on_peak_marginloss,off_peak_marginloss,daily_marginloss
0,2026-04-01,635,1428.73,116.118,1544.84,-7.4291,-21.194,-28.6231,-73.9106,-5.5102,-79.4208

Total RT daily rows: 1580  expected ~1580

### 46. Node.get_price() daily granularity — reads sl_rt_daily_summary

In [ ]:
df_node_daily = node_spp.get_price('2026-04-01', '2026-04-01',
                                   component=['LMP','MCC','MLC'], type=['DA','RT'], granularity='daily')
print('Node daily (DA+RT):', df_node_daily.shape)
display(df_node_daily)

### 47. RT 5-min Slack Last 2 Years — settlement_location_rt_5min_slack_last2years
> Script `spp_dataDownload_rt_slack_last2years.py` is **deprecated** (2026-03-12); table is now refreshed by `spp_update_lmp_summary.py` (`update_rt_5min_slack_last2years`).

In [97]:
df_rt_slack = sql_functions.download_df_from_sql_db(
    "SELECT * FROM spp_lmp.settlement_location_rt_5min_slack_last2years where dt = '2026-04-01' and hr = 1"
)

print('RT 5-min slack last-2yr:', df_rt_slack.shape)
display(df_rt_slack)

df_rt_slack_cnt = sql_functions.download_df_from_sql_db(
    "SELECT COUNT(*) as total, MIN(dt) as min_dt, MAX(dt) as max_dt "
    "FROM spp_lmp.settlement_location_rt_5min_slack_last2years"
)

display(df_rt_slack_cnt)

RT 5-min slack last-2yr: (6, 4)

             Interval          dt  hr    slack
0 2026-04-01 00:35:00  2026-04-01   1  14.1196
1 2026-04-01 00:40:00  2026-04-01   1  14.0267
2 2026-04-01 00:45:00  2026-04-01   1  18.4962
3 2026-04-01 00:50:00  2026-04-01   1  11.6634
4 2026-04-01 00:55:00  2026-04-01   1  13.5899
5 2026-04-01 01:00:00  2026-04-01   1  13.8722

    total      min_dt      max_dt
0  209234  2024-04-06  2026-04-06

### 48. Multi-Day LMP Forecast — settlement_location_multi_day_forecast

In [98]:
df_mdfc = sql_functions.download_df_from_sql_db(
    "SELECT * FROM spp_lmp.settlement_location_multi_day_forecast "
    "ORDER BY as_of_dt DESC, dt, hr LIMIT 5"
)
print('Multi-day forecast (all):', df_mdfc.shape)
display(df_mdfc)

df_mdfc_virt = sql_functions.download_df_from_sql_db(
    "SELECT * FROM spp_lmp.settlement_location_multi_day_forecast_virtual "
    "ORDER BY dt DESC, hr LIMIT 5"
)
print('Multi-day forecast (virtual):', df_mdfc_virt.shape)
display(df_mdfc_virt)

Multi-day forecast (all): (5, 8)

,as_of_dt,dt,hr,node_num,LMP,MLC,MCC,MEC
0,2026-04-04 18:31:39,2026-04-05,1,993,19.8918,0.6763,0.0814,19.1341
1,2026-04-04 18:31:39,2026-04-05,1,2,20.1957,0.9712,0.0904,19.1341
2,2026-04-04 18:31:39,2026-04-05,1,7,19.6284,0.4126,0.0816,19.1342
3,2026-04-04 18:31:39,2026-04-05,1,6,20.4058,1.1749,0.0967,19.1342
4,2026-04-04 18:31:39,2026-04-05,1,1,20.1589,0.8906,0.1342,19.1341

Multi-day forecast (virtual): (5, 7)

           dt  hr  node_num      LMP     MLC     MCC      MEC
0  2026-04-07   1         2  14.6243  0.6407  2.9938  10.9898
1  2026-04-07   1         8  20.4103  0.7280  8.6926  10.9897
2  2026-04-07   1         7  12.6757  0.3130  1.3730  10.9897
3  2026-04-07   1         1  12.8881  0.5707  1.3277  10.9897
4  2026-04-07   1         6  13.2877  0.7454  1.5526  10.9897

### 49. DA MCP Zonal Hourly — reserve_mcp_da_zonal_hourly

In [99]:
df_da_mcp = sql_functions.download_df_from_sql_db(
    "SELECT * FROM spp_lmp.reserve_mcp_da_zonal_hourly "
    "ORDER BY dt DESC, hr, Reserve_Zone LIMIT 5"
)
print('DA MCP zonal hourly:', df_da_mcp.shape)
display(df_da_mcp)

df_da_mcp_cnt = sql_functions.download_df_from_sql_db(
    "SELECT COUNT(*) as total, MIN(dt) as min_dt, MAX(dt) as max_dt "
    "FROM spp_lmp.reserve_mcp_da_zonal_hourly"
)
display(df_da_mcp_cnt)

DA MCP zonal hourly: (5, 10)

,dt,hr,Reserve_Zone,RegUP,RegDN,RampUP,RampDN,Spin,Supp,UncUP
0,2026-04-06,1,1,5.2983,3.8823,0.0,0.0,2.0001,0.449,0.0
1,2026-04-06,1,2,5.2983,3.8823,0.0,0.0,2.0001,0.449,0.0
2,2026-04-06,1,3,5.2983,3.8823,0.0,0.0,2.0001,0.449,0.0
3,2026-04-06,1,4,5.2983,3.8823,0.0,0.0,2.0001,0.449,0.0
4,2026-04-06,1,5,5.2983,3.8823,0.0,0.0,2.0001,0.449,0.0

    total      min_dt      max_dt
0  371117  2013-07-01  2026-04-06

### 50. DA Market Clearing — spp_virtual.market_clearing

In [100]:
df_mc = sql_functions.download_df_from_sql_db(
    "SELECT * FROM spp_virtual.market_clearing "
    "ORDER BY dt DESC, hr LIMIT 5"
)
print('DA market clearing:', df_mc.shape)
display(df_mc)

df_mc_cnt = sql_functions.download_df_from_sql_db(
    "SELECT COUNT(*) as total, MIN(dt) as min_dt, MAX(dt) as max_dt "
    "FROM spp_virtual.market_clearing"
)
display(df_mc_cnt)

DA market clearing: (5, 25)

,dt,hr,baa_zone,Generation,Cleared_DR,Cleared_Demand_Bid,Cleared_Fixed_Demand_Bid,Cleared_Virtual_Bid,Cleared_Virtual_Offer,Total_Demand,NSI,SMP,Min_LMP,Max_LMP,RegUP,RegDN,RampUP,RampDN,Spin,Supp,UncUP,Capacity_Available,Curtailed_Fixed_Demand_Bid,Net_Capacity,Fixed_Obligation
0,2026-04-06,1,E,24068.80,0.0,32.0,25724.70,2060.99,5131.420,27817.7,597.975,10.879,-122.398,248.430,360.0,473.0,584.0,852.0,713.0,713.0,273.0,50646.0,0,24339,26307
1,2026-04-06,1,W,3017.33,0.0,0.0,2546.22,219.70,14.421,2765.9,257.337,23.020,18.272,24.667,76.0,86.0,40.0,147.0,87.0,87.0,0.0,4172.0,0,1626,2546
2,2026-04-06,2,E,23278.80,0.0,32.0,25363.60,1834.27,5319.290,27229.9,543.764,9.143,-101.533,202.729,359.0,391.0,563.0,652.0,713.0,713.0,1214.0,50660.0,0,24772,25888
3,2026-04-06,2,W,2931.48,0.0,0.0,2472.30,245.70,8.421,2718.0,226.220,21.676,19.475,23.161,72.0,78.0,54.0,154.0,82.0,82.0,20.0,4081.0,0,1609,2472
4,2026-04-06,3,E,23925.40,0.0,32.0,25281.10,2187.14,4884.670,27500.2,544.110,10.960,-94.718,197.412,388.0,357.0,620.0,634.0,713.0,713.0,1119.0,50261.0,0,24519,25742

   total      min_dt      max_dt
0  55049  2020-01-01  2026-04-06

### 51. DA Virtual Clearing by MOA — spp_virtual.moa_virtual_clearing

In [ ]:
df_moa = sql_functions.download_df_from_sql_db(
    "SELECT * FROM spp_virtual.moa_virtual_clearing "
    "ORDER BY dt DESC, hr, moa LIMIT 5"
)
print('MOA virtual clearing:', df_moa.shape)
display(df_moa)

df_moa_cnt = sql_functions.download_df_from_sql_db(
    "SELECT COUNT(*) as total, MIN(dt) as min_dt, MAX(dt) as max_dt "
    "FROM spp_virtual.moa_virtual_clearing"
)
display(df_moa_cnt)

MOA virtual clearing: (5, 6)

           dt  hr BAA   moa  cleared_virtual_bid  cleared_virtual_offer
0  2026-04-06   1   E  CSWS              146.481                200.567
1  2026-04-06   1   E   EDE               67.887                104.628
2  2026-04-06   1   E  GRDA               32.114                 13.225
3  2026-04-06   1   E  INDN               10.400                 54.200
4  2026-04-06   1   E  KACY               25.048                  5.450

     total      min_dt      max_dt
0  1600301  2015-07-03  2026-04-06

### 52. Hourly Available Outage Maintenance Margin — `get_data_and_mapping_for_avail_maintenance_margin()`
> Source tables: `spp_physical.hourly_available_outage_maintenance_margin_virtual` (forecast) and `hourly_available_outage_maintenance_margin_latest` (actual). SWPW tables not used in nighthawk.

In [102]:
from nighthawk.data.pipeline.var_handler.avail_maint_margin import (
    get_data_and_mapping_for_avail_maintenance_margin
)

data_amm, mapping_amm = get_data_and_mapping_for_avail_maintenance_margin(
    node_list=[635],
    opexchange='SPP',
    start_dt=START,
    end_dt=END,
    var_spec=['f', 'a'],
)
print('data shape:', data_amm.shape)
print('columns:', data_amm.columns.tolist())
display(data_amm)

print('\nmapping:')
display(mapping_amm)

data shape: (24, 4)
columns: ['dt', 'hr', 'spp_total_avail_maintenance_margin_f', 'spp_total_avail_maintenance_margin_a']

,dt,hr,spp_total_avail_maintenance_margin_f,spp_total_avail_maintenance_margin_a
0,2026-04-01,1,13031.0,9221.0
1,2026-04-01,2,13987.0,9706.0
2,2026-04-01,3,14088.0,8781.0
3,2026-04-01,4,13854.0,8706.0
4,2026-04-01,5,15135.0,8548.0
5,2026-04-01,6,14792.0,7217.0
6,2026-04-01,7,13106.0,4150.0
7,2026-04-01,8,11829.0,2068.0
8,2026-04-01,9,10983.0,1248.0
9,2026-04-01,10,10251.0,1411.0
10,2026-04-01,11,10987.0,1467.0
11,2026-04-01,12,11727.0,1238.0
12,2026-04-01,13,11878.0,1545.0
13,2026-04-01,14,12204.0,2650.0
14,2026-04-01,15,12076.0,4549.0
15,2026-04-01,16,12397.0,5929.0
16,2026-04-01,17,12726.0,6415.0
17,2026-04-01,18,13487.0,5350.0
18,2026-04-01,19,13765.0,6289.0
19,2026-04-01,20,14140.0,6783.0
20,2026-04-01,21,15144.0,8257.0
21,2026-04-01,22,15114.0,10166.0
22,2026-04-01,23,17440.0,12361.0
23,2026-04-01,24,19232.0,15159.0

mapping:

   node_num                              var_name
0       635  spp_total_avail_maintenance_margin_f
1       635  spp_total_avail_maintenance_margin_a