In [5]:
import sys
import pandas as pd

sys.path.append("/var/www/python/Prod/nighthawk/")
from nighthawk.util import sql_functions
from nighthawk.data.pipeline.common_functions.load import Load
from nighthawk.data.pipeline.common_functions.wind import Wind
from nighthawk.data.pipeline.common_functions.solar import Solar
from nighthawk.data.pipeline.common_functions.genoutage import GenOutage
from nighthawk.data.pipeline.var_handler.fuel_type import FuelType

START = "2026-04-01"
END   = "2026-04-01"
BAA_ZONES = ["E", "W"]

load     = Load("SPP")
wind     = Wind("SPP")
solar    = Solar("SPP")
genout   = GenOutage("SPP")
fueltype = FuelType("SPP")
print(f"Objects created for SPP  |  {START} → {END}")

Objects created for SPP  |  2026-04-01 → 2026-04-01

## 1. Total Load

In [2]:
df_total = load.get_total_load(START, END, var_spec=['f', 'a'])
print(df_total.shape)
df_total

(24, 4)

            dt  hr  spp_load_total_forecast_f  spp_load_total_actual_a
0   2026-04-01   1                    32440.0                  30110.0
1   2026-04-01   2                    31585.0                  31552.0
2   2026-04-01   3                    31124.0                  30860.0
3   2026-04-01   4                    30883.0                  30524.0
4   2026-04-01   5                    31120.0                  30709.0
5   2026-04-01   6                    32023.0                  31673.0
6   2026-04-01   7                    33790.0                  33342.0
7   2026-04-01   8                    35016.0                  34568.0
8   2026-04-01   9                    35513.0                  35212.0
9   2026-04-01  10                    35851.0                  35849.0
10  2026-04-01  11                    36356.0                  36323.0
11  2026-04-01  12                    36814.0                  36720.0
12  2026-04-01  13                    37247.0                  36997.0
13  2026-04-01  14                    37877.0                  37170.0
14  2026-04-01  15                    38289.0                  37311.0
15  2026-04-01  16                    38766.0                  37280.0
16  2026-04-01  17                    39267.0                      NaN
17  2026-04-01  18                    39499.0                      NaN
18  2026-04-01  19                    39288.0                      NaN
19  2026-04-01  20                    38807.0                      NaN
20  2026-04-01  21                    38370.0                      NaN
21  2026-04-01  22                    37430.0                      NaN
22  2026-04-01  23                    35670.0                      NaN
23  2026-04-01  24                    33618.0                      NaN

## 2. BAA Zonal Load (E and W)

In [3]:
df_baa = load.get_baa_zonal_load(START, END, baa_zones=BAA_ZONES, var_spec=['f', 'a'])
print(df_baa.shape)
df_baa

(48, 5)

,dt,hr,baa_zone,spp_baa_zonal_load_forecast_f,spp_baa_zonal_load_actual_a
0,2026-04-01,1,E,29713.0,27477.0
1,2026-04-01,1,W,2727.0,2633.0
2,2026-04-01,2,E,28966.0,29008.0
3,2026-04-01,2,W,2619.0,2544.0
4,2026-04-01,3,E,28563.0,28359.0
5,2026-04-01,3,W,2561.0,2501.0
6,2026-04-01,4,E,28340.0,28048.0
7,2026-04-01,4,W,2543.0,2476.0
8,2026-04-01,5,E,28571.0,28264.0
9,2026-04-01,5,W,2549.0,2445.0
10,2026-04-01,6,E,29422.0,29175.0
11,2026-04-01,6,W,2601.0,2498.0
12,2026-04-01,7,E,31084.0,30732.0
13,2026-04-01,7,W,2706.0,2610.0
14,2026-04-01,8,E,32134.0,31813.0
15,2026-04-01,8,W,2882.0,2755.0
16,2026-04-01,9,E,32550.0,32315.0
17,2026-04-01,9,W,2963.0,2897.0
18,2026-04-01,10,E,32893.0,32945.0
19,2026-04-01,10,W,2958.0,2904.0
20,2026-04-01,11,E,33413.0,33421.0
21,2026-04-01,11,W,2943.0,2902.0
22,2026-04-01,12,E,33870.0,33837.0
23,2026-04-01,12,W,2944.0,2883.0
24,2026-04-01,13,E,34342.0,34124.0
25,2026-04-01,13,W,2905.0,2873.0
26,2026-04-01,14,E,34992.0,34328.0
27,2026-04-01,14,W,2885.0,2842.0
28,2026-04-01,15,E,35380.0,34488.0
29,2026-04-01,15,W,2909.0,2823.0
30,2026-04-01,16,E,35858.0,34485.0
31,2026-04-01,16,W,2908.0,2795.0
32,2026-04-01,17,E,36311.0,NaN
33,2026-04-01,17,W,2956.0,NaN
34,2026-04-01,18,E,36494.0,NaN
35,2026-04-01,18,W,3005.0,NaN
36,2026-04-01,19,E,36215.0,NaN
37,2026-04-01,19,W,3073.0,NaN
38,2026-04-01,20,E,35684.0,NaN
39,2026-04-01,20,W,3123.0,NaN
40,2026-04-01,21,E,35193.0,NaN
41,2026-04-01,21,W,3177.0,NaN
42,2026-04-01,22,E,34270.0,NaN
43,2026-04-01,22,W,3160.0,NaN
44,2026-04-01,23,E,32611.0,NaN
45,2026-04-01,23,W,3059.0,NaN
46,2026-04-01,24,E,30799.0,NaN
47,2026-04-01,24,W,2819.0,NaN

## 3. Broadzonal Load

In [4]:
df_broadzonal = load.get_broadzonal_load(START, END, var_spec=['f', 'a'])
print(df_broadzonal.shape)
df_broadzonal

(72, 5)

,dt,hr,broadzone,spp_broadzonal_load_forecast_f,spp_broadzonal_load_actual_a
0,2026-04-01,1,NORTH,7650.74,7650.74
1,2026-04-01,1,SOUTH,21333.99,21333.99
2,2026-04-01,1,WEST,0.00,0.00
3,2026-04-01,2,NORTH,7579.01,7579.01
4,2026-04-01,2,SOUTH,20855.13,20855.13
...,...,...,...,...,...
67,2026-04-01,23,SOUTH,24017.62,NaN
68,2026-04-01,23,WEST,0.00,NaN
69,2026-04-01,24,NORTH,7796.01,NaN
70,2026-04-01,24,SOUTH,22593.36,NaN
71,2026-04-01,24,WEST,0.00,NaN

## 4. Zonal Load

In [5]:
df_zonal = load.get_zonal_load(START, END, var_spec=['f', 'a'])
print(df_zonal.shape)
df_zonal

/var/www/python/Prod/nighthawk/nighthawk/data/pipeline/common_functions/load.py:1588: UserWarning: No zonal load forecast available for zone(s) ['PSCO', 'WACM', 'WAUW']; using actual load as forecast.
  warnings.warn(

(480, 5)

             dt  hr  zone  spp_zonal_load_forecast_f  spp_zonal_load_actual_a
0    2026-04-01   1  CSWS                    4658.57                  4658.57
1    2026-04-01   1   EDE                     448.35                   448.35
2    2026-04-01   1  GRDA                     987.37                   987.37
3    2026-04-01   1  INDN                      79.79                    79.79
4    2026-04-01   1  KACY                     218.90                   218.90
..          ...  ..   ...                        ...                      ...
475  2026-04-01  24  WACM                        NaN                      NaN
476  2026-04-01  24  WAUE                    3911.98                      NaN
477  2026-04-01  24  WAUW                        NaN                      NaN
478  2026-04-01  24  WFEC                     977.51                      NaN
479  2026-04-01  24    WR                    3149.16                      NaN

[480 rows x 5 columns]

## 5. Reserve Zonal Load

In [6]:
df_res = load.get_res_zonal_load(START, END, var_spec=['f', 'a'])
print(df_res.shape)
df_res

(144, 5)

,dt,hr,ReserveZone,spp_res_zonal_load_forecast_f,spp_res_zonal_load_actual_a
0,2026-04-01,1,1,3660.03,3660.03
1,2026-04-01,1,2,657.00,657.00
2,2026-04-01,1,3,4096.22,4096.22
3,2026-04-01,1,4,16580.77,16580.77
4,2026-04-01,1,5,3990.71,3990.71
...,...,...,...,...,...
139,2026-04-01,24,2,680.42,NaN
140,2026-04-01,24,3,4173.73,NaN
141,2026-04-01,24,4,17739.21,NaN
142,2026-04-01,24,5,3911.98,NaN
143,2026-04-01,24,21,NaN,NaN

## 6. Load Error

In [7]:
df_load_error = load.get_load_error(START, END, var_spec=['f', 'a'])
print(df_load_error.shape)
df_load_error

(24, 4)

            dt  hr  spp_load_error_f  spp_load_error_a
0   2026-04-01   1        -158.31000           -2330.0
1   2026-04-01   2        -203.91600             -33.0
2   2026-04-01   3        -204.09600            -264.0
3   2026-04-01   4        -141.91500            -359.0
4   2026-04-01   5        -179.26300            -411.0
5   2026-04-01   6         143.59000            -350.0
6   2026-04-01   7         197.03500            -448.0
7   2026-04-01   8         131.98600            -448.0
8   2026-04-01   9          63.54950            -301.0
9   2026-04-01  10         -72.55100              -2.0
10  2026-04-01  11        -193.79400             -33.0
11  2026-04-01  12        -129.17100             -94.0
12  2026-04-01  13         -85.92140            -250.0
13  2026-04-01  14         -88.25000            -707.0
14  2026-04-01  15          37.18520            -978.0
15  2026-04-01  16           8.10015           -1486.0
16  2026-04-01  17         265.16700               NaN
17  2026-04-01  18         167.45300               NaN
18  2026-04-01  19         197.94100               NaN
19  2026-04-01  20         193.51700               NaN
20  2026-04-01  21          56.61560               NaN
21  2026-04-01  22          11.54570               NaN
22  2026-04-01  23          39.52530               NaN
23  2026-04-01  24        -150.98900               NaN

## 7. BAA Zonal Load Error (E and W)

In [8]:
df_baa_error = load.get_baa_zonal_load_error(START, END, baa_zones=BAA_ZONES, var_spec=['f', 'a'])
print(df_baa_error.shape)
df_baa_error

(48, 5)

/var/www/python/Prod/nighthawk/nighthawk/data/pipeline/common_functions/load.py:2150: UserWarning: No model-predicted BAA-zonal load error forecast available for zone(s) ['W']; using actual load error as forecast.
  warnings.warn(

,dt,hr,baa_zone,spp_baa_zonal_load_error_a,spp_baa_zonal_load_error_f
0,2026-04-01,1,E,-2236.0,-158.31000
1,2026-04-01,1,W,-94.0,-94.00000
2,2026-04-01,2,E,42.0,-203.91600
3,2026-04-01,2,W,-75.0,-75.00000
4,2026-04-01,3,E,-204.0,-204.09600
5,2026-04-01,3,W,-60.0,-60.00000
6,2026-04-01,4,E,-292.0,-141.91500
7,2026-04-01,4,W,-67.0,-67.00000
8,2026-04-01,5,E,-307.0,-179.26300
9,2026-04-01,5,W,-104.0,-104.00000
10,2026-04-01,6,E,-247.0,143.59000
11,2026-04-01,6,W,-103.0,-103.00000
12,2026-04-01,7,E,-352.0,197.03500
13,2026-04-01,7,W,-96.0,-96.00000
14,2026-04-01,8,E,-321.0,131.98600
15,2026-04-01,8,W,-127.0,-127.00000
16,2026-04-01,9,E,-235.0,63.54950
17,2026-04-01,9,W,-66.0,-66.00000
18,2026-04-01,10,E,52.0,-72.55100
19,2026-04-01,10,W,-54.0,-54.00000
20,2026-04-01,11,E,8.0,-193.79400
21,2026-04-01,11,W,-41.0,-41.00000
22,2026-04-01,12,E,-33.0,-129.17100
23,2026-04-01,12,W,-61.0,-61.00000
24,2026-04-01,13,E,-218.0,-85.92140
25,2026-04-01,13,W,-32.0,-32.00000
26,2026-04-01,14,E,-664.0,-88.25000
27,2026-04-01,14,W,-43.0,-43.00000
28,2026-04-01,15,E,-892.0,37.18520
29,2026-04-01,15,W,-86.0,-86.00000
30,2026-04-01,16,E,-1373.0,8.10015
31,2026-04-01,16,W,-113.0,-113.00000
32,2026-04-01,17,E,NaN,265.16700
33,2026-04-01,17,W,NaN,NaN
34,2026-04-01,18,E,NaN,167.45300
35,2026-04-01,18,W,NaN,NaN
36,2026-04-01,19,E,NaN,197.94100
37,2026-04-01,19,W,NaN,NaN
38,2026-04-01,20,E,NaN,193.51700
39,2026-04-01,20,W,NaN,NaN
40,2026-04-01,21,E,NaN,56.61560
41,2026-04-01,21,W,NaN,NaN
42,2026-04-01,22,E,NaN,11.54570
43,2026-04-01,22,W,NaN,NaN
44,2026-04-01,23,E,NaN,39.52530
45,2026-04-01,23,W,NaN,NaN
46,2026-04-01,24,E,NaN,-150.98900
47,2026-04-01,24,W,NaN,NaN

---
## WIND

### 8. Total Wind

In [3]:
df_wind_total = wind.get_total_wind(START, END, var_spec=['f', 'a'])
print(df_wind_total.shape)
df_wind_total

(24, 4)

            dt  hr  spp_wind_total_forecast_f  spp_wind_total_actual_a
0   2026-04-01   1                   19661.68                 17018.20
1   2026-04-01   2                   18941.02                 16073.57
2   2026-04-01   3                   18526.22                 15514.78
3   2026-04-01   4                   18392.06                 14693.56
4   2026-04-01   5                   18447.30                 13884.95
5   2026-04-01   6                   18251.26                 13138.94
6   2026-04-01   7                   17755.26                 12729.71
7   2026-04-01   8                   17281.17                 11809.35
8   2026-04-01   9                   16633.53                  9874.16
9   2026-04-01  10                   16403.86                  8009.48
10  2026-04-01  11                   17154.66                  7061.17
11  2026-04-01  12                   18484.05                  6885.44
12  2026-04-01  13                   20099.78                  7508.45
13  2026-04-01  14                   21484.89                  9344.62
14  2026-04-01  15                   22766.49                 11324.18
15  2026-04-01  16                   24159.63                 13980.73
16  2026-04-01  17                   25247.81                 15484.05
17  2026-04-01  18                   25709.12                 15125.89
18  2026-04-01  19                   25788.08                 15387.12
19  2026-04-01  20                   25905.19                 15893.35
20  2026-04-01  21                   26462.58                 16819.22
21  2026-04-01  22                   27181.59                 18486.04
22  2026-04-01  23                   28076.37                 18787.17
23  2026-04-01  24                   26422.09                 19292.60

### 9. BAA Zonal Wind (E and W)

In [4]:
df_wind_baa = wind.get_baa_zonal_wind(START, END, baa_zones=BAA_ZONES, var_spec=['f', 'a'])
print(df_wind_baa.shape)
df_wind_baa

(48, 5)

,dt,hr,baa_zone,spp_baa_zonal_wind_forecast_f,spp_baa_zonal_wind_actual_a
0,2026-04-01,1,E,18820.52,16197.00
1,2026-04-01,1,W,841.16,821.20
2,2026-04-01,2,E,18101.49,15325.80
3,2026-04-01,2,W,839.53,747.77
4,2026-04-01,3,E,17711.71,14835.12
5,2026-04-01,3,W,814.51,679.66
6,2026-04-01,4,E,17604.79,14035.19
7,2026-04-01,4,W,787.27,658.37
8,2026-04-01,5,E,17679.20,13225.89
9,2026-04-01,5,W,768.10,659.06
10,2026-04-01,6,E,17492.74,12491.20
11,2026-04-01,6,W,758.52,647.74
12,2026-04-01,7,E,17002.22,12092.82
13,2026-04-01,7,W,753.04,636.89
14,2026-04-01,8,E,16545.44,11198.60
15,2026-04-01,8,W,735.73,610.75
16,2026-04-01,9,E,15917.99,9254.99
17,2026-04-01,9,W,715.54,619.17
18,2026-04-01,10,E,15698.94,7438.47
19,2026-04-01,10,W,704.92,571.01
20,2026-04-01,11,E,16442.00,6474.50
21,2026-04-01,11,W,712.66,586.67
22,2026-04-01,12,E,17759.29,6322.80
23,2026-04-01,12,W,724.76,562.64
24,2026-04-01,13,E,19371.73,6936.46
25,2026-04-01,13,W,728.05,571.99
26,2026-04-01,14,E,20772.87,8806.61
27,2026-04-01,14,W,712.02,538.01
28,2026-04-01,15,E,22084.69,10817.26
29,2026-04-01,15,W,681.80,506.92
30,2026-04-01,16,E,23513.51,13465.08
31,2026-04-01,16,W,646.12,515.65
32,2026-04-01,17,E,24641.19,14990.82
33,2026-04-01,17,W,606.62,493.23
34,2026-04-01,18,E,25147.98,14659.22
35,2026-04-01,18,W,561.14,466.67
36,2026-04-01,19,E,25248.40,14964.64
37,2026-04-01,19,W,539.68,422.48
38,2026-04-01,20,E,25366.46,15505.78
39,2026-04-01,20,W,538.73,387.57
40,2026-04-01,21,E,25941.80,16492.95
41,2026-04-01,21,W,520.78,326.27
42,2026-04-01,22,E,26665.94,18233.11
43,2026-04-01,22,W,515.65,252.93
44,2026-04-01,23,E,27557.02,18631.62
45,2026-04-01,23,W,519.35,155.55
46,2026-04-01,24,E,25899.26,19162.22
47,2026-04-01,24,W,522.83,130.38

### 10. Reserve Zonal Wind

In [18]:
df_wind_res = wind.get_res_zonal_wind(START, END, var_spec=['f', 'a'])
display(df_wind_res.head(10))
df_wind_res

,dt,hr,ReserveZone,spp_res_zonal_wind_forecast_f,spp_res_zonal_wind_actual_a
0,2026-04-01,1,1,1907.53,1641.80
1,2026-04-01,1,2,3762.81,3894.99
2,2026-04-01,1,3,1125.62,921.67
3,2026-04-01,1,4,9296.98,7498.03
4,2026-04-01,1,5,2727.58,2160.04
5,2026-04-01,1,21,841.16,819.10
6,2026-04-01,2,1,1809.51,1570.33
7,2026-04-01,2,2,3436.82,3491.59
8,2026-04-01,2,3,995.66,591.17
9,2026-04-01,2,4,9127.73,7483.80

,dt,hr,ReserveZone,spp_res_zonal_wind_forecast_f,spp_res_zonal_wind_actual_a
0,2026-04-01,1,1,1907.53,1641.80
1,2026-04-01,1,2,3762.81,3894.99
2,2026-04-01,1,3,1125.62,921.67
3,2026-04-01,1,4,9296.98,7498.03
4,2026-04-01,1,5,2727.58,2160.04
...,...,...,...,...,...
139,2026-04-01,24,2,5785.92,4455.42
140,2026-04-01,24,3,2009.54,1653.04
141,2026-04-01,24,4,13878.44,9536.89
142,2026-04-01,24,5,2635.36,2611.94
143,2026-04-01,24,21,522.83,133.55

### 11. Wind Error

In [6]:
df_wind_error = wind.get_wind_error(START, END, var_spec=['f', 'a'])
print(df_wind_error.shape)
df_wind_error

(24, 4)

            dt  hr  spp_wind_error_f  spp_wind_error_a
0   2026-04-01   1          639.7140       2453.836674
1   2026-04-01   2          639.7140       2695.469547
2   2026-04-01   3          639.7140       2991.373332
3   2026-04-01   4          634.2130       3698.455000
4   2026-04-01   5          616.3100       4562.114167
5   2026-04-01   6          600.6570       5110.630000
6   2026-04-01   7          600.6570       5024.201667
7   2026-04-01   8          606.1580       5448.957501
8   2026-04-01   9          606.1580       6757.455000
9   2026-04-01  10          600.7200       8370.631667
10  2026-04-01  11          595.6800      10091.783333
11  2026-04-01  12          590.1790      11585.775000
12  2026-04-01  13          610.5930      12547.593332
13  2026-04-01  14          634.8350      12065.083332
14  2026-04-01  15          612.6970      11431.046667
15  2026-04-01  16          571.6480       9945.954993
16  2026-04-01  17          103.2400       9591.787496
17  2026-04-01  18           32.5311      10485.188336
18  2026-04-01  19           66.2004      10183.221673
19  2026-04-01  20          238.4210       9637.673344
20  2026-04-01  21          649.2300       8942.115859
21  2026-04-01  22          743.4560       6742.820020
22  2026-04-01  23          944.4660       6410.349963
23  2026-04-01  24          760.3070       3337.896738

### 12. BAA Zonal Wind Error (E and W)

In [7]:
df_wind_baa_error = wind.get_baa_zonal_wind_error(START, END, baa_zones=BAA_ZONES, var_spec=['f', 'a'])
print(df_wind_baa_error.shape)
df_wind_baa_error

(48, 5)

/var/www/python/Prod/nighthawk/nighthawk/data/pipeline/common_functions/wind.py:1593: UserWarning: No model-predicted BAA-zonal wind error forecast available for zone(s) ['W']; using actual wind error as forecast.
  warnings.warn(

,dt,hr,baa_zone,spp_baa_zonal_wind_error_a,spp_baa_zonal_wind_error_f
0,2026-04-01,1,E,2433.876674,639.714000
1,2026-04-01,1,W,19.960000,19.960000
2,2026-04-01,2,E,2614.815000,639.714000
3,2026-04-01,2,W,80.654546,80.654546
4,2026-04-01,3,E,2858.216667,639.714000
5,2026-04-01,3,W,133.156667,133.156667
6,2026-04-01,4,E,3569.600000,634.213000
7,2026-04-01,4,W,128.855000,128.855000
8,2026-04-01,5,E,4453.074167,616.310000
9,2026-04-01,5,W,109.040000,109.040000
10,2026-04-01,6,E,5000.228333,600.657000
11,2026-04-01,6,W,110.401667,110.401667
12,2026-04-01,7,E,4908.295000,600.657000
13,2026-04-01,7,W,115.906667,115.906667
14,2026-04-01,8,E,5346.840000,606.158000
15,2026-04-01,8,W,102.117501,102.117501
16,2026-04-01,9,E,6661.609167,606.158000
17,2026-04-01,9,W,95.845833,95.845833
18,2026-04-01,10,E,8258.920000,600.720000
19,2026-04-01,10,W,111.711666,111.711666
20,2026-04-01,11,E,9967.120833,595.680000
21,2026-04-01,11,W,124.662500,124.662500
22,2026-04-01,12,E,11428.370834,590.179000
23,2026-04-01,12,W,157.404167,157.404167
24,2026-04-01,13,E,12405.571666,610.593000
25,2026-04-01,13,W,142.021667,142.021667
26,2026-04-01,14,E,11901.989164,634.835000
27,2026-04-01,14,W,163.094167,163.094167
28,2026-04-01,15,E,11258.168334,612.697000
29,2026-04-01,15,W,172.878333,172.878333
30,2026-04-01,16,E,9816.422493,571.648000
31,2026-04-01,16,W,129.532500,129.532500
32,2026-04-01,17,E,9481.580007,103.240000
33,2026-04-01,17,W,110.207500,110.207500
34,2026-04-01,18,E,10394.310835,32.531100
35,2026-04-01,18,W,90.877500,90.877500
36,2026-04-01,19,E,10066.039160,66.200400
37,2026-04-01,19,W,117.182500,117.182500
38,2026-04-01,20,E,9489.516670,238.421000
39,2026-04-01,20,W,148.156667,148.156667
40,2026-04-01,21,E,8754.919183,649.230000
41,2026-04-01,21,W,187.196666,187.196666
42,2026-04-01,22,E,6480.100020,743.456000
43,2026-04-01,22,W,262.720000,262.720000
44,2026-04-01,23,E,6048.200110,944.466000
45,2026-04-01,23,W,362.150000,362.150000
46,2026-04-01,24,E,2948.744102,760.307000
47,2026-04-01,24,W,389.152500,389.152500

### 13. VER Curtailment

In [8]:
df_ver = wind.get_ver_curtailment(START, END, var_spec=['f', 'a'])
print(df_ver.shape)
df_ver

(24, 4)

,dt,hr,spp_ver_curtailments_forecast_f,spp_ver_curtailments_actual_a
0,2026-04-01,1,1811.040,189.643326
1,2026-04-01,2,1759.060,171.980453
2,2026-04-01,3,1525.740,20.066668
3,2026-04-01,4,1517.030,0.045000
4,2026-04-01,5,1510.380,0.235833
5,2026-04-01,6,1184.470,1.690000
6,2026-04-01,7,1122.280,1.348333
7,2026-04-01,8,1101.870,22.862499
8,2026-04-01,9,647.363,1.915000
9,2026-04-01,10,532.968,23.748333
10,2026-04-01,11,766.187,1.706667
11,2026-04-01,12,990.603,12.835000
12,2026-04-01,13,1160.860,43.736668
13,2026-04-01,14,1637.470,75.186668
14,2026-04-01,15,1896.170,11.263333
15,2026-04-01,16,2420.880,232.945007
16,2026-04-01,17,2434.320,171.972504
17,2026-04-01,18,2470.160,98.041664
18,2026-04-01,19,2509.170,217.738327
19,2026-04-01,20,2605.400,374.166656
20,2026-04-01,21,3927.390,701.244141
21,2026-04-01,22,4463.950,1952.729980
22,2026-04-01,23,6058.580,2878.850037
23,2026-04-01,24,6847.820,3791.593262

### 14. BAA Zonal VER Curtailment (E and W)

In [26]:
df_ver_baa = wind.get_baa_zonal_ver_curtailment('2026-04-03', '2026-04-03', baa_zones=BAA_ZONES, var_spec=['f', 'a'])
print(df_ver_baa.shape)
df_ver_baa

(24, 5)

/var/www/python/Prod/nighthawk/nighthawk/data/pipeline/common_functions/wind.py:1799: UserWarning: No BAA-zonal VER curtailment forecast available for zone(s) ['W']; using actual curtailment as forecast.
  warnings.warn(

,dt,hr,baa_zone,spp_baa_zonal_ver_curtailments_forecast_f,spp_baa_zonal_ver_curtailments_actual_a
0,2026-04-03,1,E,6153.24,NaN
1,2026-04-03,2,E,6430.88,NaN
2,2026-04-03,3,E,6702.76,NaN
3,2026-04-03,4,E,6808.07,NaN
4,2026-04-03,5,E,6626.88,NaN
5,2026-04-03,6,E,5765.97,NaN
6,2026-04-03,7,E,5497.78,NaN
7,2026-04-03,8,E,5065.83,NaN
8,2026-04-03,9,E,4994.91,NaN
9,2026-04-03,10,E,3866.38,NaN
10,2026-04-03,11,E,3776.04,NaN
11,2026-04-03,12,E,3629.12,NaN
12,2026-04-03,13,E,3004.48,NaN
13,2026-04-03,14,E,2119.15,NaN
14,2026-04-03,15,E,1635.34,NaN
15,2026-04-03,16,E,1612.35,NaN
16,2026-04-03,17,E,1552.89,NaN
17,2026-04-03,18,E,1503.65,NaN
18,2026-04-03,19,E,1084.86,NaN
19,2026-04-03,20,E,1090.95,NaN
20,2026-04-03,21,E,1443.53,NaN
21,2026-04-03,22,E,1759.99,NaN
22,2026-04-03,23,E,3047.26,NaN
23,2026-04-03,24,E,3906.19,NaN

---
## SOLAR

### 15. Total Solar

In [10]:
df_solar_total = solar.get_total_solar(START, END, var_spec=['f', 'a'])
print(df_solar_total.shape)
df_solar_total

(24, 4)

            dt  hr  spp_solar_total_forecast_f  spp_solar_total_actual_a
0   2026-04-01   1                        0.00                      0.60
1   2026-04-01   2                        0.00                      0.60
2   2026-04-01   3                        0.00                      0.60
3   2026-04-01   4                        0.00                      0.60
4   2026-04-01   5                        0.00                      0.60
5   2026-04-01   6                        0.00                      0.60
6   2026-04-01   7                        0.05                      0.60
7   2026-04-01   8                       53.81                     22.74
8   2026-04-01   9                      422.77                    363.38
9   2026-04-01  10                      827.84                    744.52
10  2026-04-01  11                     1040.28                    762.78
11  2026-04-01  12                     1231.59                    976.17
12  2026-04-01  13                     1346.48                   1173.30
13  2026-04-01  14                     1354.77                   1224.14
14  2026-04-01  15                     1277.63                   1211.61
15  2026-04-01  16                     1127.67                    965.83
16  2026-04-01  17                      931.52                    836.92
17  2026-04-01  18                      782.86                    559.63
18  2026-04-01  19                      520.74                    290.63
19  2026-04-01  20                      150.00                    113.35
20  2026-04-01  21                        5.79                     12.04
21  2026-04-01  22                        0.00                      0.01
22  2026-04-01  23                        0.00                      0.01
23  2026-04-01  24                        0.00                      0.00

### 16. BAA Zonal Solar (E and W)

In [11]:
df_solar_baa = solar.get_baa_zonal_solar(START, END, baa_zones=BAA_ZONES, var_spec=['f', 'a'])
print(df_solar_baa.shape)
df_solar_baa

(48, 5)

,dt,hr,baa_zone,spp_baa_zonal_solar_forecast_f,spp_baa_zonal_solar_actual_a
0,2026-04-01,1,E,0.60,0.60
1,2026-04-01,1,W,0.00,0.00
2,2026-04-01,2,E,0.60,0.60
3,2026-04-01,2,W,0.00,0.00
4,2026-04-01,3,E,0.60,0.60
5,2026-04-01,3,W,0.00,0.00
6,2026-04-01,4,E,0.60,0.60
7,2026-04-01,4,W,0.00,0.00
8,2026-04-01,5,E,0.60,0.60
9,2026-04-01,5,W,0.00,0.00
10,2026-04-01,6,E,0.60,0.60
11,2026-04-01,6,W,0.00,0.00
12,2026-04-01,7,E,0.05,0.60
13,2026-04-01,7,W,0.00,0.00
14,2026-04-01,8,E,52.76,22.62
15,2026-04-01,8,W,1.05,0.12
16,2026-04-01,9,E,385.00,335.76
17,2026-04-01,9,W,37.77,27.62
18,2026-04-01,10,E,685.76,660.14
19,2026-04-01,10,W,142.08,84.38
20,2026-04-01,11,E,799.30,619.88
21,2026-04-01,11,W,240.98,142.90
22,2026-04-01,12,E,908.31,767.67
23,2026-04-01,12,W,323.28,208.50
24,2026-04-01,13,E,977.99,792.99
25,2026-04-01,13,W,368.49,380.31
26,2026-04-01,14,E,960.44,848.17
27,2026-04-01,14,W,394.33,375.97
28,2026-04-01,15,E,877.78,802.78
29,2026-04-01,15,W,399.85,408.83
30,2026-04-01,16,E,748.08,545.89
31,2026-04-01,16,W,379.59,419.94
32,2026-04-01,17,E,597.14,423.29
33,2026-04-01,17,W,334.38,413.63
34,2026-04-01,18,E,466.37,241.52
35,2026-04-01,18,W,316.49,318.11
36,2026-04-01,19,E,243.19,142.71
37,2026-04-01,19,W,277.55,147.92
38,2026-04-01,20,E,38.57,42.42
39,2026-04-01,20,W,111.43,70.93
40,2026-04-01,21,E,0.19,1.09
41,2026-04-01,21,W,5.60,10.95
42,2026-04-01,22,E,0.00,0.00
43,2026-04-01,22,W,0.01,0.01
44,2026-04-01,23,E,0.00,0.00
45,2026-04-01,23,W,0.01,0.01
46,2026-04-01,24,E,0.00,0.00
47,2026-04-01,24,W,0.00,0.00

### 17. Reserve Zonal Solar

In [25]:
df_solar_res = solar.get_res_zonal_solar(START, END, var_spec=['f', 'a'])
print(df_solar_res.shape)
df_solar_res.sort_values(['dt','hr','ReserveZone'])[:10]

(144, 5)

,dt,hr,ReserveZone,spp_res_zonal_solar_forecast_f,spp_res_zonal_solar_actual_a
0,2026-04-01,1,1,0.0,0.00
24,2026-04-01,1,2,0.0,0.00
48,2026-04-01,1,3,0.0,-0.03
72,2026-04-01,1,4,0.0,0.60
96,2026-04-01,1,5,0.0,0.00
120,2026-04-01,1,21,0.0,0.00
1,2026-04-01,2,1,0.0,0.00
25,2026-04-01,2,2,0.0,0.00
49,2026-04-01,2,3,0.0,0.05
73,2026-04-01,2,4,0.0,0.60

---
## GEN OUTAGE

### 18. Gen Outage — Total SPP

In [13]:
df_genout_total = genout.get_genoutage_by_level(START, END, area_list=['SPP'], var_spec=['f', 'a'])
print(df_genout_total.shape)
df_genout_total

(24, 5)

            dt  hr baa_zone  spp_genoutage_forecast_f  spp_genoutage_actual_a
0   2026-04-01   1      SPP                   25715.9                 25197.9
1   2026-04-01   2      SPP                   25728.3                 25198.1
2   2026-04-01   3      SPP                   25878.9                 25348.7
3   2026-04-01   4      SPP                   25878.9                 25348.7
4   2026-04-01   5      SPP                   25712.9                 25182.7
5   2026-04-01   6      SPP                   25612.9                 25182.7
6   2026-04-01   7      SPP                   25897.1                 25171.9
7   2026-04-01   8      SPP                   25907.1                 25179.9
8   2026-04-01   9      SPP                   25907.1                 25180.5
9   2026-04-01  10      SPP                   25907.7                 25183.5
10  2026-04-01  11      SPP                   25182.9                 25794.4
11  2026-04-01  12      SPP                   25180.6                 25792.1
12  2026-04-01  13      SPP                   25258.3                 25888.2
13  2026-04-01  14      SPP                   25152.3                 25286.2
14  2026-04-01  15      SPP                   25272.4                 25314.3
15  2026-04-01  16      SPP                   25265.0                 25306.9
16  2026-04-01  17      SPP                   25264.8                 25306.7
17  2026-04-01  18      SPP                   25264.8                 25349.7
18  2026-04-01  19      SPP                   25805.3                 25882.4
19  2026-04-01  20      SPP                   25806.5                 25883.9
20  2026-04-01  21      SPP                   25753.5                 25830.9
21  2026-04-01  22      SPP                   25755.8                 25833.2
22  2026-04-01  23      SPP                   25713.0                 25790.4
23  2026-04-01  24      SPP                   25714.3                 25791.7

### 19. Gen Outage — BAA Zonal (E and W)

In [27]:
df_genout_baa = genout.get_genoutage_by_level('2026-04-03', '2026-04-03', area_list=['E', 'W'], var_spec=['f', 'a'])
print(df_genout_baa.shape)
df_genout_baa

(48, 5)

            dt  hr baa_zone  spp_genoutage_forecast_f  spp_genoutage_actual_a
0   2026-04-03   1        E                   25658.6                     NaN
1   2026-04-03   1        W                       NaN                     NaN
2   2026-04-03   2        E                   25658.8                     NaN
3   2026-04-03   2        W                       NaN                     NaN
4   2026-04-03   3        E                   25607.5                     NaN
5   2026-04-03   3        W                       NaN                     NaN
6   2026-04-03   4        E                   25607.5                     NaN
7   2026-04-03   4        W                       NaN                     NaN
8   2026-04-03   5        E                   25608.6                     NaN
9   2026-04-03   5        W                       NaN                     NaN
10  2026-04-03   6        E                   25608.6                     NaN
11  2026-04-03   6        W                       NaN                     NaN
12  2026-04-03   7        E                   25171.2                     NaN
13  2026-04-03   7        W                       NaN                     NaN
14  2026-04-03   8        E                   25171.2                     NaN
15  2026-04-03   8        W                       NaN                     NaN
16  2026-04-03   9        E                   25171.8                     NaN
17  2026-04-03   9        W                       NaN                     NaN
18  2026-04-03  10        E                   25171.2                     NaN
19  2026-04-03  10        W                       NaN                     NaN
20  2026-04-03  11        E                   26438.5                     NaN
21  2026-04-03  11        W                     928.3                     NaN
22  2026-04-03  12        E                   26437.0                     NaN
23  2026-04-03  12        W                     928.3                     NaN
24  2026-04-03  13        E                   26519.5                     NaN
25  2026-04-03  13        W                     928.3                     NaN
26  2026-04-03  14        E                   26570.1                     NaN
27  2026-04-03  14        W                     928.3                     NaN
28  2026-04-03  15        E                   26590.2                     NaN
29  2026-04-03  15        W                     928.3                     NaN
30  2026-04-03  16        E                   26589.8                     NaN
31  2026-04-03  16        W                     928.3                     NaN
32  2026-04-03  17        E                   26589.6                     NaN
33  2026-04-03  17        W                     928.3                     NaN
34  2026-04-03  18        E                   25397.6                     NaN
35  2026-04-03  18        W                     928.3                     NaN
36  2026-04-03  19        E                   25375.4                     NaN
37  2026-04-03  19        W                     928.3                     NaN
38  2026-04-03  20        E                   25376.9                     NaN
39  2026-04-03  20        W                     928.3                     NaN
40  2026-04-03  21        E                   25377.9                     NaN
41  2026-04-03  21        W                     928.3                     NaN
42  2026-04-03  22        E                   25380.2                     NaN
43  2026-04-03  22        W                     928.3                     NaN
44  2026-04-03  23        E                   25540.4                     NaN
45  2026-04-03  23        W                     928.3                     NaN
46  2026-04-03  24        E                   25540.9                     NaN
47  2026-04-03  24        W                     928.3                     NaN

---
## GEN MIX (FUEL TYPE)

### 20. Gen by Fuel Type (GenMixHourly — Hydro, Nuclear, NaturalGas)

In [29]:
df_fuel = fueltype.get_gen_fuel_type('2026-04-03', '2026-04-03', var_spec=['f', 'a'])
print(df_fuel.shape)
df_fuel

(24, 8)

,dt,hr,spp_fuelmix_hydro_forecast_f,spp_fuelmix_nuclear_forecast_f,spp_fuelmix_naturalgas_forecast_f,spp_fuelmix_hydro_actual_a,spp_fuelmix_nuclear_actual_a,spp_fuelmix_naturalgas_actual_a
0,2026-04-03,1,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-04-03,2,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-04-03,3,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-04-03,4,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-04-03,5,NaN,NaN,NaN,NaN,NaN,NaN
5,2026-04-03,6,NaN,NaN,NaN,NaN,NaN,NaN
6,2026-04-03,7,NaN,NaN,NaN,NaN,NaN,NaN
7,2026-04-03,8,NaN,NaN,NaN,NaN,NaN,NaN
8,2026-04-03,9,NaN,NaN,NaN,NaN,NaN,NaN
9,2026-04-03,10,NaN,NaN,NaN,NaN,NaN,NaN
10,2026-04-03,11,NaN,NaN,NaN,NaN,NaN,NaN
11,2026-04-03,12,NaN,NaN,NaN,NaN,NaN,NaN
12,2026-04-03,13,NaN,NaN,NaN,NaN,NaN,NaN
13,2026-04-03,14,NaN,NaN,NaN,NaN,NaN,NaN
14,2026-04-03,15,NaN,NaN,NaN,NaN,NaN,NaN
15,2026-04-03,16,NaN,NaN,NaN,NaN,NaN,NaN
16,2026-04-03,17,NaN,NaN,NaN,NaN,NaN,NaN
17,2026-04-03,18,NaN,NaN,NaN,NaN,NaN,NaN
18,2026-04-03,19,NaN,NaN,NaN,NaN,NaN,NaN
19,2026-04-03,20,NaN,NaN,NaN,NaN,NaN,NaN
20,2026-04-03,21,NaN,NaN,NaN,NaN,NaN,NaN
21,2026-04-03,22,NaN,NaN,NaN,NaN,NaN,NaN
22,2026-04-03,23,NaN,NaN,NaN,NaN,NaN,NaN
23,2026-04-03,24,NaN,NaN,NaN,NaN,NaN,NaN

### 21. Gen Outage by Fuel Type

In [28]:
df_outage_fuel = fueltype.get_genoutage_fuel_type('2026-04-02', '2026-04-02', var_spec=['f', 'a'])
print(df_outage_fuel.shape)
df_outage_fuel

(24, 14)

,dt,hr,spp_fuelmixoutage_coal_forecast_f,spp_fuelmixoutage_dieselfueloil_forecast_f,spp_fuelmixoutage_hydro_forecast_f,spp_fuelmixoutage_naturalgas_forecast_f,spp_fuelmixoutage_solar_forecast_f,spp_fuelmixoutage_wind_forecast_f,spp_fuelmixoutage_coal_actual_a,spp_fuelmixoutage_dieselfueloil_actual_a,spp_fuelmixoutage_hydro_actual_a,spp_fuelmixoutage_naturalgas_actual_a,spp_fuelmixoutage_solar_actual_a,spp_fuelmixoutage_wind_actual_a
0,2026-04-02,1,9024.8,212.0,890.0,13905.5,781.5,705.5,9025.8,212.0,890.0,13996.5,781.5,625.5
1,2026-04-02,2,9024.8,212.0,890.0,13905.5,781.5,705.5,9025.8,212.0,890.0,13996.5,781.5,625.5
2,2026-04-02,3,9024.8,212.0,890.0,13905.5,781.5,705.5,9025.8,212.0,890.0,13996.5,781.5,625.5
3,2026-04-02,4,9024.8,212.0,890.0,13905.5,781.5,705.5,9025.8,212.0,890.0,13996.5,781.5,625.5
4,2026-04-02,5,9025.8,212.0,890.0,13996.5,781.5,625.5,9125.8,280.1,1809.8,15021.6,970.5,564.5
5,2026-04-02,6,9025.8,212.0,890.0,13996.5,781.5,625.5,9125.8,280.1,1809.8,15021.6,970.5,564.5
6,2026-04-02,7,9025.8,212.0,890.0,14034.5,781.5,625.5,9125.8,280.1,1809.8,15021.6,970.5,564.5
7,2026-04-02,8,9025.8,212.0,890.0,14124.5,631.5,625.5,9025.8,277.0,1809.8,15111.6,820.5,564.5
8,2026-04-02,9,9025.8,212.0,890.0,14124.5,631.5,625.5,9025.8,299.0,1809.8,15030.6,820.5,564.5
9,2026-04-02,10,9025.8,212.0,890.0,14216.5,631.5,625.5,9025.8,302.8,1809.8,15030.6,820.5,564.5
10,2026-04-02,11,9025.8,212.0,890.0,14216.5,631.5,625.5,9025.8,302.8,1809.8,15030.6,820.5,564.5
11,2026-04-02,12,9025.8,212.0,890.0,14216.5,631.5,625.5,9025.8,302.8,1809.8,13838.6,820.5,564.5
12,2026-04-02,13,9025.8,212.0,890.0,14216.5,631.5,625.5,NaN,NaN,NaN,NaN,NaN,NaN
13,2026-04-02,14,9025.8,212.0,890.0,14216.5,631.5,625.5,NaN,NaN,NaN,NaN,NaN,NaN
14,2026-04-02,15,9025.8,212.0,890.0,14216.5,631.5,625.5,NaN,NaN,NaN,NaN,NaN,NaN
15,2026-04-02,16,9025.8,212.0,890.0,14171.5,631.5,625.5,NaN,NaN,NaN,NaN,NaN,NaN
16,2026-04-02,17,9025.8,212.0,890.0,14126.5,631.5,625.5,NaN,NaN,NaN,NaN,NaN,NaN
17,2026-04-02,18,9025.8,212.0,890.0,14117.5,631.5,625.5,NaN,NaN,NaN,NaN,NaN,NaN
18,2026-04-02,19,9025.8,212.0,779.0,14117.5,631.5,625.5,NaN,NaN,NaN,NaN,NaN,NaN
19,2026-04-02,20,9025.8,212.0,779.0,14117.5,631.5,625.5,NaN,NaN,NaN,NaN,NaN,NaN
20,2026-04-02,21,9025.8,212.0,779.0,14117.5,781.5,423.9,NaN,NaN,NaN,NaN,NaN,NaN
21,2026-04-02,22,9025.8,212.0,779.0,14117.5,781.5,423.9,NaN,NaN,NaN,NaN,NaN,NaN
22,2026-04-02,23,9025.8,212.0,779.0,14117.5,781.5,423.9,NaN,NaN,NaN,NaN,NaN,NaN
23,2026-04-02,24,9025.8,212.0,779.0,14117.5,781.5,423.9,NaN,NaN,NaN,NaN,NaN,NaN

---
## GEN MIX RAW TABLES

### 22. GenMix 5-min (spp_physical.GenMix)

In [9]:
df_genmix = sql_functions.download_df_from_sql_db(
    "SELECT IntervalEnd, GMTIntervalEnd, CoalTotal, WindTotal, SolarTotal, NaturalGasTotal, AverageActualLoad "
    "FROM spp_physical.GenMix "
    "WHERE DATE(IntervalEnd) = '2026-04-03' ORDER BY IntervalEnd")
print(df_genmix.shape)
# spot check: rows should be ~288 (5-min intervals * 24hr)
df_genmix.tail(10)

(108, 7)

,IntervalEnd,GMTIntervalEnd,CoalTotal,WindTotal,SolarTotal,NaturalGasTotal,AverageActualLoad
98,2026-04-03 08:10:00,2026-04-03 13:10:00,5456.2,20804.9,108.1,5611.3,33914.0
99,2026-04-03 08:15:00,2026-04-03 13:15:00,5513.1,20716.8,133.0,5740.2,34431.3
100,2026-04-03 08:20:00,2026-04-03 13:20:00,5541.2,20800.6,174.1,5700.4,34162.5
101,2026-04-03 08:25:00,2026-04-03 13:25:00,5633.1,20924.8,226.1,5633.5,34231.8
102,2026-04-03 08:30:00,2026-04-03 13:30:00,5689.0,20713.1,270.4,5768.1,34704.9
103,2026-04-03 08:35:00,2026-04-03 13:35:00,5768.0,20494.4,262.8,5922.1,34320.7
104,2026-04-03 08:40:00,2026-04-03 13:40:00,5804.2,20453.4,309.1,5830.4,34332.5
105,2026-04-03 08:45:00,2026-04-03 13:45:00,5828.2,20454.6,315.8,5910.4,34833.5
106,2026-04-03 08:50:00,2026-04-03 13:50:00,5830.0,20347.7,471.5,5949.8,34488.7
107,2026-04-03 08:55:00,2026-04-03 13:55:00,5804.3,20208.6,487.8,5969.1,34634.3

### 23. GenMixHourly (spp_physical.GenMixHourly)

In [11]:
df_genmixhr = sql_functions.download_df_from_sql_db(
    "SELECT dt, hr, CoalTotal, WindTotal, SolarTotal, NaturalGasTotal, AverageActualLoad "
    "FROM spp_physical.GenMixHourly "
    "WHERE dt = '2026-04-01' ORDER BY hr")
print(df_genmixhr.shape)
# spot check: 24 rows expected
df_genmixhr

(14, 7)

,dt,hr,CoalTotal,WindTotal,SolarTotal,NaturalGasTotal,AverageActualLoad
0,2026-04-01,10,8277.2,7332.9,772.8,14074.2,35172.4
1,2026-04-01,11,8448.3,7052.8,963.5,14188.4,35616.7
2,2026-04-01,12,8019.9,7547.7,1152.7,13116.7,35874.3
3,2026-04-01,13,7712.1,9298.3,1247.4,11788.0,36047.3
4,2026-04-01,14,7478.9,11275.6,1212.8,11707.5,36238.6
5,2026-04-01,15,7150.5,13926.5,991.6,9968.8,36344.5
6,2026-04-01,16,7259.8,15508.1,854.0,9644.6,36643.9
7,2026-04-01,17,7674.2,15249.4,607.3,9400.1,36818.3
8,2026-04-01,18,7579.6,15471.2,361.8,9109.9,36795.3
9,2026-04-01,19,7865.9,15949.2,118.0,9192.6,36578.6
10,2026-04-01,20,7997.3,16883.6,17.3,8646.0,36681.5
11,2026-04-01,21,7401.8,18233.7,0.2,7293.1,35910.5
12,2026-04-01,22,6157.5,18638.9,0.2,6865.2,34300.7
13,2026-04-01,23,5013.5,18955.1,0.3,6285.3,32663.4

### 24. BAAZonalGenMix (spp_physical.BAAZonalGenMix) — E and W

In [1]:
df_baa_genmix = sql_functions.download_df_from_sql_db(
    "SELECT IntervalEnd, BAA, CoalTotal, WindTotal, SolarTotal, NaturalGasTotal, AverageActualLoad\n",
    "FROM spp_physical.BAAZonalGenMix\n",
    "WHERE DATE(IntervalEnd) = '2026-04-01' ORDER BY IntervalEnd, BAA")
print(df_baa_genmix.shape)
# spot check: E + W rows; WindTotal_E + WindTotal_W should ≈ GenMix WindTotal
df_baa_genmix.head(10)

NameError: name 'sql_functions' is not defined

### 25. BAAZonalGenMixHourly (spp_physical.BAAZonalGenMixHourly) — E + W sum vs GenMixHourly

In [ ]:
df_baa_hr = sql_functions.download_df_from_sql_db(
    "SELECT dt, hr, BAA, WindTotal, SolarTotal, NaturalGasTotal, AverageActualLoad\n",
    "FROM spp_physical.BAAZonalGenMixHourly\n",
    "WHERE dt = '2026-04-01' ORDER BY hr, BAA")
print(df_baa_hr.shape)
# verify E+W sums match GenMixHourly
pivot = df_baa_hr.pivot_table(index=['dt','hr'], columns='BAA', values='WindTotal', aggfunc='sum')
pivot['total_EW'] = pivot.get('E', 0) + pivot.get('W', 0)
pivot = pivot.merge(df_genmixhr[['dt','hr','WindTotal']], on=['dt','hr'])
pivot['diff'] = pivot['total_EW'] - pivot['WindTotal']
print('Max E+W vs total diff (should be ~0):', pivot['diff'].abs().max())
pivot

---
## TIE FLOWS

### 26. TieFlows (spp_physical.TieFlows)

In [18]:
df_tieflow = sql_functions.download_df_from_sql_db(
    "SELECT * FROM spp_physical.TieFlows "
    "WHERE DATE(GMTTime) = '2026-04-01' ORDER BY MarketTime LIMIT 100")
print(df_tieflow.shape)
print('Columns:', df_tieflow.columns.tolist())
df_tieflow.head(10)

(100, 30)
Columns: ['MarketTime', 'GMTTime', 'SPPNSI', 'DPC', 'MCWEST', 'CLEC', 'SPC', 'AMRN', 'OTP', 'GRE', 'MDU', 'SOUC', 'SPA', 'SGE', 'AECI', 'ERCOTN', 'WAUE', 'EDDY', 'ERCOTE', 'BLKW', 'LAMAR', 'MEC', 'SPPNAI', 'RCEAST', 'EES', 'NSP', 'SCSE', 'ALTW', 'TVA', 'SIKE']

,MarketTime,GMTTime,SPPNSI,DPC,MCWEST,CLEC,SPC,AMRN,OTP,GRE,...,LAMAR,MEC,SPPNAI,RCEAST,EES,NSP,SCSE,ALTW,TVA,SIKE
0,2026-03-31 19:00:00,2026-04-01 00:00:00,398.6,31.5,20.6,80.9,-34.5,287.1,347.1,229.3,...,0.6,-934.2,389.4,102.7,253.6,-263.3,0.0,-123.4,-49.9,0.0
1,2026-03-31 19:01:00,2026-04-01 00:01:00,410.1,31.5,20.7,80.1,-27.5,284.2,350.1,229.9,...,0.4,-962.2,356.6,108.8,244.7,-265.5,0.0,-123.4,-49.5,0.0
2,2026-03-31 19:02:00,2026-04-01 00:02:00,435.5,31.5,20.4,75.6,-26.1,282.4,356.6,232.0,...,0.4,-977.9,334.9,114.9,213.4,-260.2,0.0,-120.8,-49.9,0.0
3,2026-03-31 19:03:00,2026-04-01 00:03:00,446.4,32.0,20.5,76.9,-20.6,279.8,370.2,234.4,...,0.6,-961.1,365.2,121.5,196.9,-264.2,0.0,-117.2,-49.5,0.0
4,2026-03-31 19:04:00,2026-04-01 00:04:00,464.0,32.1,20.6,74.0,-13.4,275.5,378.9,236.4,...,-0.1,-941.0,348.6,127.2,138.9,-261.8,0.0,-114.0,-48.8,0.0
5,2026-03-31 19:05:00,2026-04-01 00:05:00,489.5,32.4,20.5,71.8,-13.3,271.7,381.2,237.9,...,1.3,-971.8,349.8,133.6,137.9,-259.3,0.0,-111.7,-47.2,0.0
6,2026-03-31 19:06:00,2026-04-01 00:06:00,434.5,32.7,20.3,75.9,-22.3,267.5,388.6,238.4,...,0.6,-1004.6,298.4,134.0,141.4,-268.9,0.0,-112.5,-46.1,0.0
7,2026-03-31 19:07:00,2026-04-01 00:07:00,435.4,32.5,20.5,78.2,-39.7,265.0,387.8,238.2,...,0.9,-1108.9,141.3,134.0,118.6,-273.9,0.0,-114.1,-43.4,0.0
8,2026-03-31 19:08:00,2026-04-01 00:08:00,452.7,32.6,20.6,84.9,-55.1,266.5,396.2,238.6,...,0.6,-1092.5,239.5,134.0,174.1,-272.6,0.0,-117.7,-43.0,0.0
9,2026-03-31 19:09:00,2026-04-01 00:09:00,440.2,32.5,20.6,92.3,-50.2,274.6,399.2,247.7,...,0.4,-1071.1,302.6,134.0,193.4,-264.4,0.0,-115.1,-42.2,0.0

---
## RNU RATE

### 27. RNU Rate (spp_virtual.rnu_rate)

In [15]:
df_rnu = sql_functions.download_df_from_sql_db(
    "SELECT * FROM spp_virtual.rnu_rate "
    "ORDER BY dt DESC LIMIT 50")
print(df_rnu.shape)
df_rnu.head(10)

(50, 5)

           dt Run_Type  RT_RNU_Dist_Rate  RNU_Rate_Forecast      source
0  2026-04-07    Frcst           -0.4716            -0.4716  ForecastV1
1  2026-04-06    Frcst           -0.4716            -0.4716  ForecastV1
2  2026-04-05    Frcst           -0.4716            -0.4716  ForecastV1
3  2026-04-04    Frcst           -0.4716            -0.4716  ForecastV1
4  2026-04-03    Frcst           -0.4716            -0.4716  ForecastV1
5  2026-04-02    Frcst           -0.4716            -0.4716  ForecastV1
6  2026-04-01    Frcst           -0.4716            -0.4716  ForecastV1
7  2026-03-31    Frcst           -0.4716            -0.4716  ForecastV1
8  2026-03-30    Frcst           -0.4716            -0.4716  ForecastV1
9  2026-03-29    Frcst           -0.4716            -0.4716  ForecastV1

### 28. RNU Rate Detailed (spp_virtual.rnu_rate_detailed)

In [16]:
df_rnu_det = sql_functions.download_df_from_sql_db(
    "SELECT * FROM spp_virtual.rnu_rate_detailed "
    "ORDER BY dt DESC LIMIT 50")
print(df_rnu_det.shape)
df_rnu_det.head(10)

(50, 14)

,auto_id,dt,Run_Type,DA_Inadequacy,RT_Inadequacy,RT_Out_of_Merit,RT_Reg_Dep_ADJ,RT_JOA,RT_Net_Inadvertent,RT_Congestion,RT_RNU_Dist_Qty,RT_RNU_Dist_Rate,RT_RNU_Hrly_Amt,source
0,8936,2026-03-17,S7,35.39,-2434280.0,-235974.00,-48091.50,536581.0,5114.84,-2429240.0,2091530.0,-1.0431,2181670.0,ftp
1,8937,2026-03-16,S7,14.77,-166803.0,-29995.60,-11438.60,680046.0,27075.60,-139809.0,2081520.0,0.2267,-471884.0,ftp
2,8938,2026-03-15,S7,21.30,-1430000.0,-1044.56,-23408.40,772266.0,3073.29,-1427000.0,1915030.0,-0.3562,682137.0,ftp
3,8939,2026-03-14,S7,-45.05,-713455.0,-654.43,9132.07,335411.0,-6809.07,-720302.0,1781430.0,-0.2075,369636.0,ftp
4,8940,2026-03-13,S7,-16.25,378596.0,-952.92,-23912.30,205847.0,-579785.00,-201210.0,1797160.0,0.3114,-559623.0,ftp
5,8941,2026-03-12,S7,10.95,-455971.0,0.00,-26191.30,224016.0,11495.50,-444514.0,1959210.0,-0.1318,258230.0,ftp
6,8942,2026-03-11,S7,-26.16,-1970000.0,0.00,-12929.10,640875.0,-8588.67,-1978680.0,1941920.0,-0.6911,1342080.0,ftp
7,8901,2026-03-10,S7,2.74,-1023470.0,-39491.90,-19734.50,530062.0,827.45,-1022670.0,1912100.0,-0.2890,552619.0,ftp
8,8902,2026-03-09,S7,13.30,-549151.0,-12234.50,-37190.70,309633.0,19538.00,-529687.0,1800350.0,-0.1605,288942.0,ftp
9,8903,2026-03-08,S7,18.32,-635888.0,-1673.46,-2075.56,79495.2,-8633.87,-644632.0,1707120.0,-0.3281,560107.0,ftp

---
## OP CHARGES (MWP)

### 29. Op Reserve and Fees (spp_virtual.v3_op_reserve_and_fees)

In [17]:
df_opcharge = sql_functions.download_df_from_sql_db(
    "SELECT * FROM spp_virtual.v3_op_reserve_and_fees "
    "ORDER BY dt DESC LIMIT 50")
print(df_opcharge.shape)
print('Columns:', df_opcharge.columns.tolist())
df_opcharge.head(10)

(50, 4)
Columns: ['dt', 'daMwpDistRate', 'rtMwpDistRate', 'source']

           dt  daMwpDistRate  rtMwpDistRate      source
0  2026-04-08         0.5302         1.0057  forecastV2
1  2026-04-07         0.4272         0.9656  forecastV2
2  2026-04-06         0.2148         1.0180  forecastV2
3  2026-04-05         0.1601         1.0818  forecastV2
4  2026-04-04         0.3102         0.8351  forecastV2
5  2026-04-03         0.4005         1.0808  forecastV2
6  2026-04-02         0.3155         0.9194  forecastV2
7  2026-04-01         0.3386         1.0200  forecastV2
8  2026-03-31         0.4006         0.9613  forecastV2
9  2026-03-30         0.3880         0.9131  forecastV2