In [1]:
# Get daily constraint ranked by the abs RT - DA 
import sys
sys.path.append('/var/www/python/Prod/nighthawk/')

import pandas as pd
from nighthawk.data import Constraint

In [2]:
now = pd.Timestamp.now(tz='US/Central')
days_ahead = 2 if now.hour >= 10 else 1
bid_dt = (now + pd.Timedelta(days=days_ahead)).strftime('%Y-%m-%d')
print(bid_dt)

2026-06-03

# Daily RT DA Spike Analysis

In [3]:
# give a date and returns to me the hourly metrics at that hour, wind/load/temperature/gas/wind ramp/genoutage

In [4]:
from nighthawk.data.pipeline.common_functions.wind import Wind
from nighthawk.data.pipeline.common_functions.load import Load
from nighthawk.data.pipeline.common_functions.gas import Gas
from nighthawk.data.pipeline.common_functions.genoutage import GenOutage
from nighthawk.data.pipeline.common_functions.weather import Weather
from nighthawk.data.network.node import Node

SPP_HUB_NODES = {636:'south_hub'}
SPP_CITIES =[ ('Kansas City', 'MO'), ('Oklahoma City', 'OK')]


def get_hourly_snapshot(date: str, hour: int):
    assert 1 <= hour <= 24, "hour must be between 1 and 24"
    dt      = date
    dt_prev = (pd.Timestamp(dt) - pd.Timedelta(days=1)).strftime('%Y-%m-%d')

    wind_df = Wind('SPP').get_total_wind(dt_prev, dt, var_spec=['f'])
    load_df = Load('SPP').get_total_load(dt_prev, dt, var_spec=['f'])

    gas_raw = Gas('SPP').get_daily_gas_price(['Henry'], dt_prev, dt, pivot=False)
    gas_df  = (gas_raw[gas_raw['hub_name'] == 'Henry'][['dt', 'gas_price']]
               .rename(columns={'gas_price': 'henry_gas_price'}))

    go_raw = GenOutage('SPP').get_genoutage_by_level(dt_prev, dt, var_spec=['f'], area_list=['SPP'])
    go_df  = go_raw[go_raw['baa_zone'] == 'SPP'][['dt', 'hr', 'spp_genoutage_forecast_f']]

    weather_obj = Weather('SPP')
    city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()
    temp_raw    = weather_obj.get_citylevel_temperature_for_ve(dt_prev, dt, city_ids, pivot=False)
    temp_df     = (temp_raw.groupby(['dt', 'hr'])['temperature_degf']
                           .mean().reset_index()
                           .rename(columns={'temperature_degf': 'avg_temp_f'}))

    price_raw = Node(list(SPP_HUB_NODES.keys()), 'SPP').get_price(
        dt, dt, component=['Slack'], type=['DA', 'RT'], granularity='hourly'
    )
    price_raw['dt'] = price_raw['dt'].astype(str)
    price_raw['hr'] = price_raw['hr'].astype(int)

    for df in [wind_df, load_df, go_df, temp_df]:
        df['dt'] = df['dt'].astype(str)
        df['hr'] = df['hr'].astype(int)
    gas_df['dt'] = gas_df['dt'].astype(str)

    base = (
        wind_df[['dt', 'hr', 'spp_wind_total_forecast_f']]
        .merge(load_df[['dt', 'hr', 'spp_load_total_forecast_f']], on=['dt', 'hr'], how='outer')
        .merge(go_df,   on=['dt', 'hr'], how='left')
        .merge(temp_df, on=['dt', 'hr'], how='left')
        .merge(gas_df,  on='dt',         how='left')
        .sort_values(['dt', 'hr']).reset_index(drop=True)
    )
    base['B_wind_ramp'] = base['spp_wind_total_forecast_f'].diff()
    base['B_load_ramp'] = base['spp_load_total_forecast_f'].diff()
    base['B_wind_ramp_2'] = base['spp_wind_total_forecast_f'].diff(2)
    base['B_load_ramp_2'] = base['spp_load_total_forecast_f'].diff(2)

    row       = base[(base['dt'] == dt) & (base['hr'] == hour)]
    price_row = price_raw[(price_raw['dt'] == dt) & (price_raw['hr'] == hour)].copy()
    price_row['hub'] = price_row['node_num'].map(SPP_HUB_NODES)

    if row.empty:
        print(f"No data found for {dt} hour {hour}")
        return None

    r   = row.iloc[0]
    rec = {
        'dt':               dt,
        'hr':               hour,
        'wind_f (MW)':      round(r['spp_wind_total_forecast_f'], 1),
        'load_f (MW)':      round(r['spp_load_total_forecast_f'], 1),
        'genoutage_f (MW)': round(r['spp_genoutage_forecast_f'],  1),
        'avg_temp (°F)':    round(r['avg_temp_f'],                1),
        'henry_gas ($/MMBtu)': round(r['henry_gas_price'],        3),
        'wind_ramp (MW/hr)': round(r['B_wind_ramp'],                1),
        'load_ramp (MW/hr)': round(r['B_load_ramp'],                1),
        'wind_ramp_2 (MW/hr)': round(r['B_wind_ramp_2'],                1),
        'load_ramp_2 (MW/hr)': round(r['B_load_ramp_2'],                1),
    }

    for _, pr in price_row.sort_values('node_num').iterrows():
        hub = pr['hub']
        rec[f'{hub}_da_slack']  = round(pr.get('da_slack', float('nan')), 2)
        rec[f'{hub}_rt_slack']  = round(pr.get('rt_slack', float('nan')), 2)

    display(pd.DataFrame([rec]))
    return pd.DataFrame([rec])


# ── Example ───────────────────────────────────────────────
get_hourly_snapshot('2022-12-23', 18)

/tmp/ipykernel_211633/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),south_hub_da_slack,south_hub_rt_slack
0,2022-12-23,18,10722.4,40623.0,11765.4,10.3,7.28,-930.1,1710.0,-2080.7,2397.0,149.7,1395.17

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),south_hub_da_slack,south_hub_rt_slack
0,2022-12-23,18,10722.4,40623.0,11765.4,10.3,7.28,-930.1,1710.0,-2080.7,2397.0,149.7,1395.17

In [5]:
import sys
sys.path.append('/var/www/python/Prod/nighthawk/')
import pandas as pd
from nighthawk.util.bigquery_functions import download_df_from_bq

PNL_COLS = ['clear_mw', 'profit_total', 'profit_congestion', 'profit_slack']

def _fetch_pnl(start_dt: str, end_dt: str) -> pd.DataFrame:
    query = f"""
        SELECT dt, hr, incdec, strategy, rep_zone, broad_zone,
               SUM(clear_mw)          AS clear_mw,
               SUM(profit_total)      AS profit_total,
               SUM(profit_congestion) AS profit_congestion,
               SUM(profit_slack)      AS profit_slack
        FROM `movetocloud-999.virtual_financials.segment_portfolio_details_SPP`
        WHERE dt BETWEEN '{start_dt}' AND '{end_dt}'
        GROUP BY dt, hr, incdec, strategy, rep_zone, broad_zone
        ORDER BY dt, hr
    """
    df = download_df_from_bq(query)
    df['dt'] = pd.to_datetime(df['dt']).dt.strftime('%Y-%m-%d')
    df['hr'] = df['hr'].astype(int)
    return df


def get_spp_pnl(start_dt: str, end_dt: str, group_by: str = 'daily') -> pd.DataFrame:
    """
    Fetch SPP virtual portfolio PnL summed across all strategies.

    group_by: 'daily'  — one row per dt
              'hourly' — one row per dt x hr
              'raw'    — full detail (strategy / rep_zone / incdec)
    """
    assert group_by in ('daily', 'hourly', 'raw')
    df = _fetch_pnl(start_dt, end_dt)
    if group_by == 'daily':
        return df.groupby('dt', as_index=False)[PNL_COLS].sum()
    elif group_by == 'hourly':
        return df.groupby(['dt', 'hr'], as_index=False)[PNL_COLS].sum()
    return df


def get_pnl_snapshot(date: str, hour: int) -> pd.DataFrame:
    """Return a single-row DataFrame with total PnL for one specific date and hour."""
    df = _fetch_pnl(date, date)
    row = df[df['hr'] == hour][PNL_COLS].sum()
    result = pd.DataFrame([{'dt': date, 'hr': hour, **{c: round(row[c], 2) for c in PNL_COLS}}])
    display(result)
    return result


# Daily PnL (summed across all strategies, one row per dt)
daily = get_spp_pnl('2026-05-01', '2026-05-12', group_by='daily')
display(daily)

# Hourly PnL (one row per dt x hr)
hourly = get_spp_pnl('2026-05-01', '2026-05-12', group_by='hourly')
display(hourly)

# Single dt + hour snapshot
get_pnl_snapshot('2022-12-23', 18)

            dt     clear_mw  profit_total  profit_congestion  profit_slack
0   2026-05-01  1314.123994  10346.707933       -1462.969181  10884.276826
1   2026-05-02  1652.635993  -7083.557217      -12633.139192     21.284947
2   2026-05-03  3990.475993   7572.335125      -11842.373297  16723.520420
3   2026-05-04  2913.842014  -3192.139128       -4567.698330    114.950350
4   2026-05-05  4434.162016  16118.681327        8296.839209   4425.614313
5   2026-05-06  3987.468992  -6386.306198      -23104.017113   -674.526433
6   2026-05-07  3755.137000  15738.199106       19953.350274  -7964.616577
7   2026-05-08  4304.602005  67259.501733       29093.770899  32013.608437
8   2026-05-09  3716.091997  16205.688033        1858.715909  16642.058252
9   2026-05-10  4435.628995   3100.265405        2119.289315    206.546872
10  2026-05-11  2445.745995  15801.618050       31015.130184 -21331.629859
11  2026-05-12  3894.887007  10758.093735       -4994.136422   3146.404895

             dt  hr    clear_mw  profit_total  profit_congestion  profit_slack
0    2026-05-01   1    0.000000      0.000000           0.000000      0.000000
1    2026-05-01   2  159.647999    516.767106           1.068651    278.250245
2    2026-05-01   3  155.144999    466.455470           3.612927    239.142706
3    2026-05-01   4  192.359999    508.910930          14.164024    324.564199
4    2026-05-01   5   55.928000     88.684027           1.266369     90.660056
..          ...  ..         ...           ...                ...           ...
283  2026-05-12  20  303.584000   4922.006249       -1673.332169   6052.511373
284  2026-05-12  21  139.781999    222.990298       -1267.729583   1051.766621
285  2026-05-12  22  178.310000  -2155.851849       -1877.787045   -597.293858
286  2026-05-12  23  148.264000   -763.514208        -667.330491   -334.509082
287  2026-05-12  24  148.011001   -707.721846        -666.170698   -444.299891

[288 rows x 6 columns]

           dt  hr  clear_mw  profit_total  profit_congestion  profit_slack
0  2022-12-23  18      7.09       5328.41             493.17       4666.42

           dt  hr  clear_mw  profit_total  profit_congestion  profit_slack
0  2022-12-23  18      7.09       5328.41             493.17       4666.42

In [8]:
import os
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler

SAVE_PATH   = '/mnt/disks/filedisk1/SPP/VE/spp_hourly_fundamentals.csv'
RF_FEATURES = [
    'wind_f (MW)', 'load_f (MW)', 'genoutage_f (MW)', 'avg_temp (°F)',
    'henry_gas ($/MMBtu)', 'wind_ramp (MW/hr)', 'load_ramp (MW/hr)',
    'wind_ramp_2 (MW/hr)', 'load_ramp_2 (MW/hr)',
]
TARGET = 'SHub_rt_slack'


def find_similar_hours(date: str, hour: int, k: int = 10,
                        dataset_path: str = SAVE_PATH,
                        n_estimators: int = 200) -> pd.DataFrame:
    """
    Train a RandomForest on (fundamentals -> SHub_rt_slack) using all history
    strictly before the given dt/hr, then rank historical hours by RF proximity
    (fraction of trees where a historical row shares the same leaf as the query).

    Returns top-k most similar rows sorted by rf_proximity descending,
    with the query row prepended (rf_proximity = 1.0).
    """
    df = pd.read_csv(dataset_path)
    df['dt'] = df['dt'].astype(str)
    df['hr'] = df['hr'].astype(int)

    # --- strict past-only filter ---
    cutoff    = pd.Timestamp(date) + pd.Timedelta(hours=hour - 1)
    df['_ts'] = pd.to_datetime(df['dt']) + pd.to_timedelta(df['hr'] - 1, unit='h')
    hist      = df[df['_ts'] < cutoff].drop(columns='_ts').reset_index(drop=True)

    # --- query row ---
    query_rows = df[(df['dt'] == date) & (df['hr'] == hour)].drop(columns='_ts', errors='ignore')
    if query_rows.empty:
        print('Query dt/hr not in dataset, fetching live...')
        query_row = get_hourly_snapshot(date, hour)
    else:
        query_row = query_rows.iloc[[0]]

    # --- feature matrix ---
    feat_cols = [c for c in RF_FEATURES if c in hist.columns and c in query_row.columns]
    train_mask = hist[feat_cols].notna().all(axis=1) & hist[TARGET].notna()
    hist_clean = hist[train_mask].reset_index(drop=True)

    X_train = hist_clean[feat_cols].values
    y_train = hist_clean[TARGET].values
    X_query = query_row[feat_cols].fillna(0).values

    # --- train RF ---
    rf = RandomForestRegressor(n_estimators=n_estimators, random_state=42,
                               n_jobs=-1, max_features='sqrt')
    rf.fit(X_train, y_train)

    print(f'RF trained on {len(X_train)} rows | '
          f'top features: {sorted(zip(rf.feature_importances_, feat_cols), reverse=True)[:3]}')

    # --- RF proximity: fraction of trees sharing the same leaf ---
    # apply() returns shape (n_samples, n_estimators) — leaf index per tree
    hist_leaves  = rf.apply(X_train)          # (n_hist, n_trees)
    query_leaves = rf.apply(X_query)          # (1,      n_trees)
    proximity    = (hist_leaves == query_leaves).mean(axis=1)  # (n_hist,)

    # --- top k by proximity ---
    k = min(k, len(hist_clean))
    top_idx  = np.argsort(proximity)[::-1][:k]
    neighbours = hist_clean.iloc[top_idx].copy()
    neighbours.insert(0, 'rf_proximity', proximity[top_idx].round(4))
    neighbours = neighbours.sort_values('rf_proximity', ascending=False).reset_index(drop=True)

    # --- remove any row from the query date before prepending query row ---
    neighbours = neighbours[neighbours['dt'] != date].sort_values('rf_proximity',ascending=False)
    # neighbours = neighbours.sort_values('SHub_rt_slack', ascending=False).groupby('dt').head(3).sort_values('SHub_rt_slack', ascending=False)
    # --- prepend query row ---
    q = query_row.copy()
    q.insert(0, 'rf_proximity', 1.0)
    result = pd.concat([q, neighbours], ignore_index=True)
    return result


# ── Example ───────────────────────────────────────────────
find_similar_hours('2026-02-05', 17, k=20)

RF trained on 53458 rows | top features: [(np.float64(0.2462259813613005), 'avg_temp (°F)'), (np.float64(0.15052681429048678), 'genoutage_f (MW)'), (np.float64(0.1383914165600613), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-02-05,17,14289.63,32834.0,10650.1,59.500000,6.43,-1461.28,295.0,-2410.89,11.0,28.1054,404.1851,206.440001,-62365.938848,387.063636,-65353.675389
1,0.170,2022-07-01,6,14438.65,30901.0,8863.1,73.166667,6.46,-1117.83,138.0,-2486.89,-172.0,30.8206,45.4116,23.939000,-40.729554,74.293929,-263.847374
2,0.075,2022-08-16,6,13548.89,32258.0,6419.1,74.166667,8.55,-1221.32,342.0,-2240.43,31.0,40.2045,55.4238,103.304000,957.512408,908.283454,-579.449514
3,0.045,2022-07-25,6,14579.86,33429.0,7723.6,75.833333,8.24,-1078.63,420.0,-2080.29,51.0,36.4565,49.6445,61.907000,-192.575932,-491.847419,-21.042240
4,0.045,2022-04-13,19,14265.99,29406.0,21813.5,52.333333,6.56,-1165.66,-29.0,-2153.31,-81.0,50.7048,44.5023,109.996001,1498.184027,1851.563093,-600.867565
5,0.045,2022-09-29,10,14386.65,28338.0,16650.0,59.000000,6.60,-1142.15,482.0,-1888.43,831.0,40.2965,62.2358,156.316001,244.029452,3065.127021,-3467.083809
6,0.040,2022-04-25,12,14301.43,28245.0,24450.6,52.333333,6.55,-1507.18,-42.0,-2526.24,126.0,41.8679,24.2558,117.336000,5086.091929,5225.552505,-458.295572
7,0.040,2022-12-19,12,13647.13,34908.0,14665.5,40.500000,6.59,-1428.13,-398.0,-3147.18,-656.0,62.9655,55.5540,54.907000,259.616920,177.717612,-65.472462
8,0.040,2022-06-18,8,13801.18,30728.0,9573.1,75.500000,7.34,-1470.64,1218.0,-2445.80,1102.0,39.2255,47.2523,39.387000,893.380030,880.272826,-203.056099
9,0.035,2022-07-01,5,15556.48,30763.0,8863.1,73.500000,6.46,-1369.06,-310.0,-2613.74,-958.0,23.0436,47.1452,22.901000,-197.759024,-1.283994,-348.660561
10,0.030,2022-08-07,8,16373.07,33141.0,5924.3,77.500000,8.19,-1391.65,535.0,-2421.34,193.0,29.0272,23.2598,102.561000,647.493528,1043.151296,-679.204912
11,0.030,2026-02-02,4,12089.31,34458.0,10458.9,32.500000,7.26,-515.10,244.0,-1044.88,90.0,44.7348,55.4103,158.435000,2209.953290,2426.908601,-704.036636
12,0.030,2022-05-21,18,14249.01,29408.0,16884.5,59.000000,7.97,-182.99,-44.0,-730.14,10.0,65.8837,15.3695,54.521000,-2419.236447,-259.294732,-2246.256111
13,0.030,2022-07-11,6,14259.17,31124.0,7016.0,72.000000,6.39,-562.91,368.0,-970.77,-9.0,25.5683,35.4123,91.864999,943.127660,501.868524,373.694140
14,0.025,2022-11-30,3,12682.94,28838.0,17411.3,27.500000,6.03,-990.99,142.0,-2195.50,30.0,38.2431,41.2625,59.715001,-399.727139,-498.464306,64.347863
15,0.025,2022-02-03,17,12894.79,37047.0,9851.6,15.666667,6.44,-390.24,329.0,-703.59,91.0,62.8924,26.9385,17.856000,127.536238,542.122922,-423.234842
16,0.020,2022-11-30,2,13673.93,28696.0,17411.3,28.500000,6.03,-1204.51,-112.0,-2623.53,-732.0,35.2499,35.2607,42.746001,-337.122906,-311.007940,-82.342793
17,0.020,2022-05-25,19,14982.28,29109.0,13435.6,59.833333,8.77,-1504.48,-181.0,-2137.42,-224.0,49.5568,13.9227,89.243001,2249.082716,1682.893954,402.486540
18,0.020,2022-11-19,10,14273.60,33620.0,21417.1,29.000000,6.06,-1700.89,-183.0,-2992.81,93.0,59.8727,53.3778,82.652000,2827.808927,2822.942930,-154.877035

In [7]:
dt_hr_list = [(bid_dt, hr) for hr in range(1, 25)]

all_results = {}
avg_rt_slack_list = []
dangerous_hours = []
avg_da_slack_list=[]

for dt, hr in dt_hr_list:
    print(f'\n=== {dt} hr {hr} ===')
    result = find_similar_hours(dt, hr, k=20)
    all_results[(dt, hr)] = result
    display(result[:5])

    neighbours = result[result['dt'] != dt]
    avg_slack = neighbours['SHub_rt_slack'].mean()
    avg_rt_slack_list.append({'dt': dt, 'hr': hr, 'avg_rt_slack': round(avg_slack, 2)})
    avg_slack = neighbours['SHub_da_slack'].mean()
    avg_da_slack_list.append({'dt': dt, 'hr': hr, 'avg_da_slack': round(avg_slack, 2)})
    

    if (neighbours['SHub_rt_slack'] > 150).any():
        dangerous_hours.append({'dt': dt, 'hr': hr, 'avg_rt_slack': round(avg_slack, 2)})

print('\n=== Avg RT Slack by Hour ===')
display(pd.DataFrame(avg_rt_slack_list))
print('\n=== Avg DA Slack by Hour ===')
display(pd.DataFrame(avg_da_slack_list))

print('\n=== Dangerous Hours (similar dates with rt_slack > 150) ===')
display(pd.DataFrame(dangerous_hours) if dangerous_hours else 'None')

=== 2026-06-03 hr 1 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_211633/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-03,1,17698.0,35429.0,15601.5,72.5,NaN,52.8,-2359.0,-268.3,-4678.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-03,1,17698.00,35429.0,15601.5,72.5,NaN,52.80,-2359.0,-268.30,-4678.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.080,2020-06-17,23,16658.23,35741.0,7417.4,79.5,1.38,268.09,-2448.0,561.65,-3884.0,10.9125,51.6478,131.629001,6493.896078,3793.897973,2677.228862
2,0.060,2020-06-29,24,17333.53,35751.0,11633.3,80.5,1.40,860.42,-2545.0,1407.37,-4828.0,10.4575,11.2824,122.645000,356.468878,249.497889,85.680459
3,0.055,2020-09-06,23,15854.72,35420.0,14960.1,79.5,1.90,369.93,-2339.0,1228.91,-4388.0,11.9773,13.3604,189.027001,1141.323347,1147.425919,-223.950903
4,0.050,2024-06-13,24,17377.41,36554.0,13345.1,78.0,2.80,-505.68,-2464.0,16.93,-4920.0,18.6009,15.3462,246.319000,2369.639807,2796.939673,-463.617311

=== 2026-06-03 hr 2 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_211633/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-03,2,17323.4,34031.0,15161.5,71.5,NaN,-374.6,-1398.0,-321.8,-3757.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-03,2,17323.40,34031.0,15161.5,71.500000,NaN,-374.60,-1398.0,-321.80,-3757.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.055,2020-06-17,23,16658.23,35741.0,7417.4,79.500000,1.38,268.09,-2448.0,561.65,-3884.0,10.9125,51.6478,131.629001,6493.896078,3793.897973,2677.228862
2,0.050,2020-06-29,2,17485.91,30838.0,12284.3,78.500000,1.40,-63.32,-1567.0,0.81,-3576.0,9.1607,8.5902,94.424000,-306.792115,-262.177537,-52.148996
3,0.045,2020-06-29,1,17549.23,32405.0,12217.3,79.666667,1.40,64.13,-2009.0,942.86,-4236.0,11.2900,9.1970,107.036000,473.839470,644.455086,-181.483986
4,0.035,2020-06-28,24,17485.10,34414.0,12203.3,82.000000,1.40,878.73,-2227.0,1168.54,-4334.0,8.3081,7.9859,155.691001,597.776491,650.793699,-87.281239

=== 2026-06-03 hr 3 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_211633/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-03,3,16610.2,33034.0,15162.1,70.5,NaN,-713.2,-997.0,-1087.7,-2395.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-03,3,16610.20,33034.0,15162.1,70.500000,NaN,-713.20,-997.0,-1087.70,-2395.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.125,2024-09-22,20,16625.17,33416.0,17537.7,65.000000,2.21,-798.38,-1045.0,-1382.92,-1916.0,41.7323,21.8364,156.533000,-343.919279,-913.300017,403.717983
2,0.040,2024-04-16,22,22084.99,31462.0,28834.2,70.000000,1.36,-645.58,-1060.0,-1540.17,-1320.0,22.6781,172.9243,137.047000,5474.022897,-1046.576958,6394.340755
3,0.040,2020-09-08,21,15642.74,33167.0,16489.0,64.833333,1.90,103.56,-746.0,238.83,-1989.0,15.8571,12.8775,145.629001,60.595456,1.952443,-55.391382
4,0.035,2020-06-17,23,16658.23,35741.0,7417.4,79.500000,1.38,268.09,-2448.0,561.65,-3884.0,10.9125,51.6478,131.629001,6493.896078,3793.897973,2677.228862

=== 2026-06-03 hr 4 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_211633/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-03,4,16052.8,32429.0,15161.5,68.5,NaN,-557.5,-605.0,-1270.6,-1602.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-03,4,16052.80,32429.0,15161.5,68.500000,NaN,-557.50,-605.0,-1270.60,-1602.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.045,2020-09-08,21,15642.74,33167.0,16489.0,64.833333,1.90,103.56,-746.0,238.83,-1989.0,15.8571,12.8775,145.629001,60.595456,1.952443,-55.391382
2,0.045,2024-09-22,21,15780.26,32643.0,17522.7,64.000000,2.21,-844.91,-773.0,-1643.29,-1818.0,36.2911,19.8033,92.909000,-2440.503241,-2627.891017,69.129572
3,0.035,2023-05-27,19,14950.42,33088.0,15392.9,78.333333,1.88,416.96,-632.0,756.69,-672.0,25.9438,16.1454,195.998000,-5123.112350,-5675.576486,380.552717
4,0.030,2020-06-17,1,16281.38,30668.0,6876.7,75.333333,1.38,71.89,-2457.0,17.59,-4625.0,8.4333,42.3382,109.418000,278.623401,1973.925927,-1767.833007

=== 2026-06-03 hr 5 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_211633/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-03,5,15566.4,32343.0,15161.5,67.5,NaN,-486.4,-86.0,-1043.9,-691.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-03,5,15566.40,32343.0,15161.5,67.500000,NaN,-486.40,-86.0,-1043.90,-691.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.055,2020-01-17,20,15762.57,32146.0,15103.2,41.333333,2.07,-324.06,-270.0,-515.94,115.0,15.8663,24.0565,154.157998,-607.665791,-149.324927,-592.715987
2,0.040,2023-05-27,19,14950.42,33088.0,15392.9,78.333333,1.88,416.96,-632.0,756.69,-672.0,25.9438,16.1454,195.998000,-5123.112350,-5675.576486,380.552717
3,0.035,2024-03-14,12,13163.18,30046.0,14072.0,65.833333,1.24,-560.11,1.0,-1233.66,40.0,16.7893,24.5489,154.706999,-1206.915718,-1965.273452,782.629688
4,0.030,2020-06-09,22,14928.56,32025.0,9475.1,72.666667,1.66,-469.43,-1465.0,-831.77,-2995.0,15.8119,68.5866,55.367000,-739.858321,-420.121857,-389.261414

=== 2026-06-03 hr 6 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_211633/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-03,6,14890.2,32996.0,15245.0,66.5,NaN,-676.2,653.0,-1162.6,567.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-03,6,14890.20,32996.0,15245.0,66.500000,NaN,-676.20,653.0,-1162.60,567.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.060,2024-03-14,10,14396.84,30006.0,14179.0,62.500000,1.24,-549.84,103.0,-753.59,428.0,16.9708,40.4109,185.182998,1874.402675,-478.804409,2382.192152
2,0.035,2020-09-08,10,14915.16,32237.0,16533.0,68.166667,1.90,-160.71,1186.0,-570.73,2233.0,17.3456,20.6568,134.623001,354.100874,506.264614,-272.600508
3,0.030,2024-03-14,11,13723.29,30045.0,14072.0,64.500000,1.24,-673.55,39.0,-1223.39,142.0,16.2759,19.1457,199.121998,1200.809918,874.547635,367.525719
4,0.030,2024-11-09,18,12581.32,29183.0,22944.5,58.000000,1.23,-920.76,679.0,-2686.82,799.0,36.5459,21.8617,33.436000,-9.517795,367.007724,-408.544614

=== 2026-06-03 hr 7 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_211633/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-03,7,14150.9,34274.0,15247.7,66.5,NaN,-739.2,1278.0,-1415.4,1931.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-03,7,14150.90,34274.0,15247.7,66.500000,NaN,-739.20,1278.0,-1415.40,1931.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.075,2024-06-03,10,11296.99,33509.0,17146.0,71.000000,1.77,-460.47,1323.0,-1468.61,2560.0,24.4436,39.7845,84.386000,-4664.276902,-5383.600322,623.357266
2,0.060,2020-09-08,12,14403.67,34756.0,16556.0,70.166667,1.90,-271.87,1205.0,-511.49,2519.0,21.4101,28.4293,120.726000,147.251861,294.053137,-272.198576
3,0.045,2020-01-22,8,14354.50,34450.0,14870.0,35.333333,1.95,-604.32,1249.0,-1193.25,3388.0,21.9363,19.1500,155.647002,29.071546,56.476195,-155.752601
4,0.045,2020-06-29,9,14570.49,34210.0,12177.1,76.833333,1.40,-614.52,1960.0,-1683.16,3749.0,15.9461,11.6229,120.824001,-275.260248,83.704235,-377.492602

=== 2026-06-03 hr 8 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_211633/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-03,8,12988.8,35513.0,15374.2,65.5,NaN,-1162.1,1239.0,-1901.3,2517.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-03,8,12988.80,35513.0,15374.2,65.500000,NaN,-1162.10,1239.0,-1901.30,2517.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.050,2024-06-03,10,11296.99,33509.0,17146.0,71.000000,1.77,-460.47,1323.0,-1468.61,2560.0,24.4436,39.7845,84.386000,-4664.276902,-5383.600322,623.357266
2,0.050,2020-09-08,13,14346.00,35849.0,16533.0,71.333333,1.90,-57.67,1093.0,-329.54,2298.0,22.9006,39.7547,132.395001,949.037923,1150.215185,-365.725333
3,0.045,2020-02-26,8,12101.74,34596.0,14814.0,30.333333,1.90,-759.83,1211.0,-1648.02,3670.0,19.8113,34.1743,41.681000,452.125756,593.087588,-209.721766
4,0.030,2020-02-07,8,11000.77,36066.0,11820.6,28.333333,1.87,-794.55,1161.0,-1320.01,3415.0,24.8713,24.1586,155.949001,-4531.679491,-4436.523593,-147.021505

=== 2026-06-03 hr 9 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_211633/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-03,9,12310.7,36585.0,15587.1,67.5,NaN,-678.1,1072.0,-1840.2,2311.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-03,9,12310.70,36585.0,15587.1,67.500000,NaN,-678.10,1072.0,-1840.20,2311.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.045,2020-02-26,8,12101.74,34596.0,14814.0,30.333333,1.90,-759.83,1211.0,-1648.02,3670.0,19.8113,34.1743,41.681000,452.125756,593.087588,-209.721766
2,0.045,2024-06-03,10,11296.99,33509.0,17146.0,71.000000,1.77,-460.47,1323.0,-1468.61,2560.0,24.4436,39.7845,84.386000,-4664.276902,-5383.600322,623.357266
3,0.035,2020-09-08,13,14346.00,35849.0,16533.0,71.333333,1.90,-57.67,1093.0,-329.54,2298.0,22.9006,39.7547,132.395001,949.037923,1150.215185,-365.725333
4,0.030,2024-03-18,9,7721.25,33754.0,21007.4,29.833333,1.37,-837.24,235.0,-493.43,2050.0,39.9352,96.9710,40.551000,2454.986555,195.235383,2319.393444

=== 2026-06-03 hr 10 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_211633/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-03,10,12527.6,37793.0,15579.0,70.5,NaN,216.9,1208.0,-461.2,2280.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-03,10,12527.60,37793.0,15579.0,70.500000,NaN,216.90,1208.0,-461.20,2280.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.075,2024-06-03,13,10451.27,37406.0,17173.3,76.500000,1.77,-63.50,1161.0,-405.88,2464.0,34.4529,27.5416,54.652000,-1143.226660,-1058.494714,-167.012813
2,0.060,2020-06-29,11,14036.64,38109.0,12207.1,79.500000,1.40,-86.16,1950.0,-533.85,3899.0,18.7869,14.9713,136.546001,-339.695378,51.154934,-430.813431
3,0.055,2024-06-03,14,10768.65,38732.0,17173.3,77.000000,1.77,317.38,1326.0,253.88,2487.0,34.6058,41.5247,72.655000,716.852241,562.260999,47.981797
4,0.045,2020-09-08,13,14346.00,35849.0,16533.0,71.333333,1.90,-57.67,1093.0,-329.54,2298.0,22.9006,39.7547,132.395001,949.037923,1150.215185,-365.725333

=== 2026-06-03 hr 11 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_211633/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-03,11,12465.9,39034.0,15494.8,74.0,NaN,-61.7,1241.0,155.1,2449.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-03,11,12465.90,39034.0,15494.8,74.000000,NaN,-61.70,1241.0,155.10,2449.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.125,2024-06-03,14,10768.65,38732.0,17173.3,77.000000,1.77,317.38,1326.0,253.88,2487.0,34.6058,41.5247,72.655000,716.852241,562.260999,47.981797
2,0.065,2020-06-29,11,14036.64,38109.0,12207.1,79.500000,1.40,-86.16,1950.0,-533.85,3899.0,18.7869,14.9713,136.546001,-339.695378,51.154934,-430.813431
3,0.065,2024-06-03,13,10451.27,37406.0,17173.3,76.500000,1.77,-63.50,1161.0,-405.88,2464.0,34.4529,27.5416,54.652000,-1143.226660,-1058.494714,-167.012813
4,0.060,2020-06-29,12,14471.11,39922.0,12207.1,81.166667,1.40,434.47,1813.0,348.31,3763.0,20.3780,15.3287,175.490001,-556.769021,111.728708,-741.018258

=== 2026-06-03 hr 12 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_211633/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-03,12,12165.8,40458.0,15494.5,76.0,NaN,-300.0,1424.0,-361.8,2665.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-03,12,12165.80,40458.0,15494.5,76.0,NaN,-300.00,1424.0,-361.80,2665.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.060,2024-06-03,14,10768.65,38732.0,17173.3,77.0,1.77,317.38,1326.0,253.88,2487.0,34.6058,41.5247,72.655,716.852241,562.260999,47.981797
2,0.045,2024-06-03,11,10857.15,34942.0,17173.3,73.5,1.77,-439.84,1433.0,-900.31,2756.0,27.4565,19.8844,43.530,-903.639543,-840.255091,-140.990201
3,0.045,2024-06-03,13,10451.27,37406.0,17173.3,76.5,1.77,-63.50,1161.0,-405.88,2464.0,34.4529,27.5416,54.652,-1143.226660,-1058.494714,-167.012813
4,0.035,2024-06-03,12,10514.77,36245.0,17173.3,76.0,1.77,-342.38,1303.0,-782.22,2736.0,29.5716,29.1970,93.342,-10272.222429,-10277.770919,-151.049798

=== 2026-06-03 hr 13 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_211633/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-03,13,12089.9,41780.0,15444.6,78.0,NaN,-75.9,1322.0,-375.9,2746.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-03,13,12089.90,41780.0,15444.6,78.000000,NaN,-75.90,1322.0,-375.90,2746.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.055,2020-06-29,13,14602.47,41598.0,12192.1,82.833333,1.40,131.36,1676.0,565.83,3489.0,22.1771,18.3351,176.058001,-770.453649,-285.414281,-549.819153
2,0.050,2024-06-03,14,10768.65,38732.0,17173.3,77.000000,1.77,317.38,1326.0,253.88,2487.0,34.6058,41.5247,72.655000,716.852241,562.260999,47.981797
3,0.035,2024-06-03,13,10451.27,37406.0,17173.3,76.500000,1.77,-63.50,1161.0,-405.88,2464.0,34.4529,27.5416,54.652000,-1143.226660,-1058.494714,-167.012813
4,0.035,2020-06-29,11,14036.64,38109.0,12207.1,79.500000,1.40,-86.16,1950.0,-533.85,3899.0,18.7869,14.9713,136.546001,-339.695378,51.154934,-430.813431

=== 2026-06-03 hr 14 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_211633/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-03,14,12363.7,43063.0,15444.6,80.0,NaN,273.7,1283.0,197.8,2605.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-03,14,12363.70,43063.0,15444.6,80.000000,NaN,273.70,1283.0,197.80,2605.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.100,2020-06-29,14,14895.66,43191.0,12192.1,84.500000,1.40,293.19,1593.0,424.55,3269.0,24.7701,16.5931,144.205001,-957.366555,-139.653833,-867.169818
2,0.050,2020-06-29,12,14471.11,39922.0,12207.1,81.166667,1.40,434.47,1813.0,348.31,3763.0,20.3780,15.3287,175.490001,-556.769021,111.728708,-741.018258
3,0.040,2024-06-03,14,10768.65,38732.0,17173.3,77.000000,1.77,317.38,1326.0,253.88,2487.0,34.6058,41.5247,72.655000,716.852241,562.260999,47.981797
4,0.035,2020-06-27,14,9906.63,38972.0,10546.9,82.500000,1.40,479.97,1423.0,844.86,3146.0,26.3375,18.2447,195.133001,-845.477008,-83.446956,-771.878911

=== 2026-06-03 hr 15 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_211633/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-03,15,12989.0,43979.0,15444.6,81.0,NaN,625.3,916.0,899.1,2199.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-03,15,12989.00,43979.0,15444.6,81.0,NaN,625.30,916.0,899.10,2199.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.050,2024-06-03,15,11425.04,39659.0,17173.3,78.5,1.77,656.39,927.0,973.77,2253.0,36.5486,20.9846,98.150000,891.036792,1171.870027,-389.791326
2,0.045,2020-06-29,16,15523.53,45270.0,12177.1,87.5,1.40,253.39,893.0,627.87,2079.0,29.8974,24.5909,350.439000,-2542.616521,-963.072578,-1631.577601
3,0.045,2024-06-03,16,12273.90,40432.0,17173.3,81.0,1.77,848.86,773.0,1505.25,1700.0,37.3132,32.5731,139.617000,1718.836814,1922.387046,-404.601203
4,0.040,2020-06-29,14,14895.66,43191.0,12192.1,84.5,1.40,293.19,1593.0,424.55,3269.0,24.7701,16.5931,144.205001,-957.366555,-139.653833,-867.169818

=== 2026-06-03 hr 16 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_211633/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-03,16,13773.7,44756.0,14681.1,82.0,NaN,784.7,777.0,1410.0,1693.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-03,16,13773.70,44756.0,14681.1,82.0,NaN,784.70,777.0,1410.00,1693.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.055,2024-06-03,17,13296.02,40973.0,17173.3,82.0,1.77,1022.12,541.0,1870.98,1314.0,37.7773,45.9286,160.942,1952.916968,1296.179348,359.473619
2,0.050,2024-06-03,16,12273.90,40432.0,17173.3,81.0,1.77,848.86,773.0,1505.25,1700.0,37.3132,32.5731,139.617,1718.836814,1922.387046,-404.601203
3,0.045,2024-06-03,19,14843.83,40693.0,16853.3,82.5,1.77,673.48,-466.0,1547.81,-280.0,34.2513,27.1114,196.177,1284.614484,2311.408174,-1329.636567
4,0.040,2020-06-27,15,10465.00,40177.0,10376.9,83.5,1.40,558.37,1205.0,1038.34,2628.0,26.0193,19.3204,249.581,-1612.895584,-346.126517,-1281.844181

=== 2026-06-03 hr 17 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_211633/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-03,17,14428.9,45040.0,14683.3,83.0,NaN,655.2,284.0,1439.9,1061.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-03,17,14428.90,45040.0,14683.3,83.0,NaN,655.20,284.0,1439.90,1061.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.060,2024-06-03,19,14843.83,40693.0,16853.3,82.5,1.77,673.48,-466.0,1547.81,-280.0,34.2513,27.1114,196.177,1284.614484,2311.408174,-1329.636567
2,0.050,2020-06-29,16,15523.53,45270.0,12177.1,87.5,1.40,253.39,893.0,627.87,2079.0,29.8974,24.5909,350.439,-2542.616521,-963.072578,-1631.577601
3,0.045,2020-06-27,15,10465.00,40177.0,10376.9,83.5,1.40,558.37,1205.0,1038.34,2628.0,26.0193,19.3204,249.581,-1612.895584,-346.126517,-1281.844181
4,0.040,2024-06-03,18,14170.35,41159.0,17173.3,80.5,1.77,874.33,186.0,1896.45,727.0,38.1990,35.1413,107.345,471.822144,624.904045,-308.666080

=== 2026-06-03 hr 18 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_211633/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-03,18,14967.3,44916.0,14675.6,82.3,NaN,538.4,-124.0,1193.6,160.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-03,18,14967.30,44916.0,14675.6,82.3,NaN,538.40,-124.0,1193.60,160.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.075,2024-06-03,19,14843.83,40693.0,16853.3,82.5,1.77,673.48,-466.0,1547.81,-280.0,34.2513,27.1114,196.177000,1284.614484,2311.408174,-1329.636567
2,0.055,2020-06-27,19,11987.99,41580.0,10376.9,84.5,1.40,528.31,-614.0,936.35,-352.0,23.8872,16.2477,333.123001,-2308.387010,-53.053704,-2295.744190
3,0.040,2020-06-29,16,15523.53,45270.0,12177.1,87.5,1.40,253.39,893.0,627.87,2079.0,29.8974,24.5909,350.439000,-2542.616521,-963.072578,-1631.577601
4,0.035,2023-05-31,18,13562.43,39804.0,14267.4,81.0,2.10,315.13,-250.0,1061.12,71.0,43.5394,25.7858,317.749000,-3088.854650,1383.017405,-4548.431508

=== 2026-06-03 hr 19 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_211633/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-03,19,15418.6,44338.0,14668.2,81.7,NaN,451.3,-578.0,989.7,-702.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-03,19,15418.60,44338.0,14668.2,81.7,NaN,451.30,-578.0,989.70,-702.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.080,2024-09-09,19,15130.40,39669.0,14728.5,83.0,2.10,246.31,-584.0,393.44,-621.0,35.3967,23.2046,124.665000,525.414797,651.707518,-354.846734
2,0.060,2024-06-03,20,15243.08,39587.0,16853.3,80.0,1.77,399.25,-1106.0,1072.73,-1572.0,31.0614,34.1942,227.672000,3960.839026,3469.021661,118.057624
3,0.055,2020-06-27,19,11987.99,41580.0,10376.9,84.5,1.40,528.31,-614.0,936.35,-352.0,23.8872,16.2477,333.123001,-2308.387010,-53.053704,-2295.744190
4,0.050,2024-06-03,19,14843.83,40693.0,16853.3,82.5,1.77,673.48,-466.0,1547.81,-280.0,34.2513,27.1114,196.177000,1284.614484,2311.408174,-1329.636567

=== 2026-06-03 hr 20 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_211633/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-03,20,15961.1,43195.0,14468.5,81.0,NaN,542.5,-1143.0,993.8,-1721.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-03,20,15961.10,43195.0,14468.5,81.0,NaN,542.50,-1143.0,993.80,-1721.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.105,2024-06-03,20,15243.08,39587.0,16853.3,80.0,1.77,399.25,-1106.0,1072.73,-1572.0,31.0614,34.1942,227.672000,3960.839026,3469.021661,118.057624
2,0.095,2020-06-27,20,12443.84,40294.0,10376.9,84.0,1.40,455.85,-1286.0,984.16,-1900.0,20.0700,22.6626,309.007001,572.406597,-109.733283,610.232913
3,0.055,2020-06-28,20,16126.39,41351.0,11982.3,86.5,1.40,-121.71,-1218.0,-32.11,-1810.0,18.9481,15.0072,248.390002,-76.036407,779.663710,-940.931840
4,0.045,2020-06-28,22,16316.56,38748.0,12203.3,83.5,1.40,180.39,-1032.0,190.17,-2603.0,14.9893,17.0964,142.889000,922.976155,686.719877,205.581899

=== 2026-06-03 hr 21 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_211633/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-03,21,16315.1,41935.0,14469.9,78.7,NaN,354.0,-1260.0,896.5,-2403.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-03,21,16315.10,41935.0,14469.9,78.700000,NaN,354.00,-1260.0,896.50,-2403.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.090,2024-06-03,21,16192.63,38246.0,16853.3,79.000000,1.77,949.55,-1341.0,1348.80,-2447.0,24.9642,40.5561,204.333000,4298.307340,2655.510552,1386.304909
2,0.080,2020-06-28,22,16316.56,38748.0,12203.3,83.500000,1.40,180.39,-1032.0,190.17,-2603.0,14.9893,17.0964,142.889000,922.976155,686.719877,205.581899
3,0.060,2020-06-29,22,15926.16,40579.0,11633.3,83.333333,1.40,406.09,-1243.0,513.19,-3088.0,16.9032,14.2374,151.989000,-77.085782,239.311972,-368.966509
4,0.055,2020-06-27,20,12443.84,40294.0,10376.9,84.000000,1.40,455.85,-1286.0,984.16,-1900.0,20.0700,22.6626,309.007001,572.406597,-109.733283,610.232913

=== 2026-06-03 hr 22 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_211633/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-03,22,16933.2,40625.0,14470.1,76.3,NaN,618.1,-1310.0,972.0,-2570.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-03,22,16933.20,40625.0,14470.1,76.3,NaN,618.10,-1310.0,972.00,-2570.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.075,2020-06-28,22,16316.56,38748.0,12203.3,83.5,1.40,180.39,-1032.0,190.17,-2603.0,14.9893,17.0964,142.889000,922.976155,686.719877,205.581899
2,0.060,2024-06-03,21,16192.63,38246.0,16853.3,79.0,1.77,949.55,-1341.0,1348.80,-2447.0,24.9642,40.5561,204.333000,4298.307340,2655.510552,1386.304909
3,0.060,2020-09-07,20,16889.80,38969.0,15806.1,84.5,1.90,525.89,-1697.0,948.08,-2686.0,19.1788,34.9728,226.737001,4656.759094,2543.616002,1895.756064
4,0.055,2024-06-03,22,17900.84,36930.0,16973.3,75.0,1.77,1708.21,-1316.0,2657.76,-2657.0,21.6346,66.3793,143.362000,2101.114714,2521.142990,-540.864869

=== 2026-06-03 hr 23 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_211633/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-03,23,17650.4,38605.0,14542.9,74.0,NaN,717.2,-2020.0,1335.3,-3330.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-03,23,17650.40,38605.0,14542.9,74.000000,NaN,717.20,-2020.0,1335.30,-3330.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.110,2020-06-29,23,16473.11,38296.0,11633.3,81.500000,1.4,546.95,-2283.0,953.04,-3526.0,14.3818,13.3372,146.039001,298.939463,408.703899,-141.733138
2,0.075,2020-09-06,22,15484.79,37759.0,14960.1,81.833333,1.9,858.98,-2049.0,1768.58,-3376.0,15.8326,15.0719,205.901001,1200.049830,1076.119250,-112.004884
3,0.040,2024-06-13,23,17883.09,39018.0,13345.1,80.500000,2.8,522.61,-2456.0,1382.29,-4156.0,23.0530,21.7452,242.287000,1692.226389,1868.156557,-220.553556
4,0.035,2020-09-07,21,17537.89,37657.0,15806.1,82.000000,1.9,648.09,-1312.0,1173.98,-3009.0,17.6289,44.6758,197.177001,2364.667217,880.509265,1219.916093

=== 2026-06-03 hr 24 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_211633/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-03,24,17907.9,36349.0,14542.9,74.0,NaN,257.5,-2256.0,974.7,-4276.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-03,24,17907.90,36349.0,14542.9,74.0,NaN,257.50,-2256.0,974.70,-4276.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.085,2020-06-17,23,16658.23,35741.0,7417.4,79.5,1.38,268.09,-2448.0,561.65,-3884.0,10.9125,51.6478,131.629001,6493.896078,3793.897973,2677.228862
2,0.065,2020-09-06,23,15854.72,35420.0,14960.1,79.5,1.90,369.93,-2339.0,1228.91,-4388.0,11.9773,13.3604,189.027001,1141.323347,1147.425919,-223.950903
3,0.065,2024-06-03,23,19492.27,34756.0,16973.3,74.0,1.77,1591.43,-2174.0,3299.64,-3490.0,15.4898,53.3588,118.791000,-868.415489,-648.672931,-372.542701
4,0.060,2020-06-28,23,16606.37,36641.0,12203.3,82.0,1.40,289.81,-2107.0,470.20,-3139.0,11.7955,11.8024,158.616000,742.323036,745.994189,-42.503689

=== Avg RT Slack by Hour ===

            dt  hr  avg_rt_slack
0   2026-06-03   1         38.61
1   2026-06-03   2         50.07
2   2026-06-03   3         49.27
3   2026-06-03   4         49.39
4   2026-06-03   5         56.88
5   2026-06-03   6         34.21
6   2026-06-03   7         28.95
7   2026-06-03   8         29.84
8   2026-06-03   9         38.31
9   2026-06-03  10         27.07
10  2026-06-03  11         31.66
11  2026-06-03  12         28.53
12  2026-06-03  13         24.04
13  2026-06-03  14         27.17
14  2026-06-03  15         31.94
15  2026-06-03  16         45.88
16  2026-06-03  17         28.71
17  2026-06-03  18         25.20
18  2026-06-03  19         31.29
19  2026-06-03  20         25.50
20  2026-06-03  21         28.64
21  2026-06-03  22         29.39
22  2026-06-03  23         34.28
23  2026-06-03  24         40.42

=== Avg DA Slack by Hour ===

            dt  hr  avg_da_slack
0   2026-06-03   1         12.97
1   2026-06-03   2         14.19
2   2026-06-03   3         19.49
3   2026-06-03   4         18.70
4   2026-06-03   5         19.87
5   2026-06-03   6         19.44
6   2026-06-03   7         22.15
7   2026-06-03   8         26.53
8   2026-06-03   9         32.18
9   2026-06-03  10         27.35
10  2026-06-03  11         28.03
11  2026-06-03  12         27.19
12  2026-06-03  13         28.93
13  2026-06-03  14         27.12
14  2026-06-03  15         30.40
15  2026-06-03  16         36.43
16  2026-06-03  17         28.42
17  2026-06-03  18         28.95
18  2026-06-03  19         28.27
19  2026-06-03  20         26.63
20  2026-06-03  21         23.99
21  2026-06-03  22         22.77
22  2026-06-03  23         23.00
23  2026-06-03  24         13.15

=== Dangerous Hours (similar dates with rt_slack > 150) ===

           dt  hr  avg_rt_slack
0  2026-06-03   1         12.97
1  2026-06-03   2         14.19
2  2026-06-03   3         19.49
3  2026-06-03   4         18.70
4  2026-06-03   5         19.87
5  2026-06-03   6         19.44
6  2026-06-03  16         36.43
7  2026-06-03  24         13.15