In [1]:
# Get daily constraint ranked by the abs RT - DA 
from functions import (
    get_recent_constraint_mvalue,
    get_node_dfax_from_constraint_num,
    get_hourly_mvalue_for_constraint_num,
    get_constraint_node_prices_from_constraint_num,
    get_constraints_node_price,
    get_metrics_for_nodes,
    get_recent_direction_accuracy,
    get_weather_date,
    predict_tomorrow_percentile,
    analyze_constraint_by_zone,
    plot_constraint_seasonality,
    plot_recent_hourly_distribution,
)
import pandas as pd

In [3]:
now = pd.Timestamp.now(tz='US/Central')
days_ahead = 2 if now.hour >= 10 else 1
bid_dt = (now + pd.Timedelta(days=days_ahead)).strftime('%Y-%m-%d')
print(bid_dt)

2026-06-04

In [4]:
dt = '2026-06-03'
mvalue= get_recent_constraint_mvalue(dt, dt)
dfax= get_node_dfax_from_constraint_num(mvalue)
hourly_mvalue = get_hourly_mvalue_for_constraint_num(mvalue)
fundamentals = get_weather_date(hourly_mvalue, dt)

start_dt: 2026-06-03, end_dt: 2026-06-03, Market: SPP
Fetching RT mvalues...
Fetching DA mvalues...
RT constraints: 0, DA constraints: 58
Fetching constraint details...

   oops_constraint_num  rt_total   da_total      rt_da  abs_rt_da_diff            monitored                       contingency
0               625778         0 -2441.9582  2441.9582       2441.9582  lnfirstcrk-roanrdge      kcpl:nashuahawthorn:345:1:11
1               776592         0 -1615.9204  1615.9204       1615.9204    xfmrduncan-duncan  wfec:anadarkofletch3comanch2:138
2               509581         0 -1413.1246  1413.1246       1413.1246          lngord-maiz               wr:wichbent:345:1:8
3               680789         0 -1345.5913  1345.5913       1345.5913      lnweav-tallgras               wr:bentmidi:138:1:5

RT active constraint-days: 0
DA active constraint-days: 424
   oops_constraint_num          dt  hr  rt_mvalue  da_mvalue     rt_da
0               509581  2024-06-07  14          0  -150.6535  150.6535
1               509581  2024-06-07  15          0  -124.7079  124.7079
2               509581  2024-06-07  16          0  -111.3417  111.3417
3               509581  2024-06-07  17          0   -84.7992   84.7992
4               509581  2024-06-07  18          0    -2.8752    2.8752

Merged hourly rows: 3907

      oops_constraint_num          dt  hr  rt_mvalue  da_mvalue     rt_da          monitored                       contingency
0                  509581  2024-06-07  14          0  -150.6535  150.6535        lngord-maiz               wr:wichbent:345:1:8
1                  509581  2024-06-07  15          0  -124.7079  124.7079        lngord-maiz               wr:wichbent:345:1:8
2                  509581  2024-06-07  16          0  -111.3417  111.3417        lngord-maiz               wr:wichbent:345:1:8
3                  509581  2024-06-07  17          0   -84.7992   84.7992        lngord-maiz               wr:wichbent:345:1:8
4                  509581  2024-06-07  18          0    -2.8752    2.8752        lngord-maiz               wr:wichbent:345:1:8
...                   ...         ...  ..        ...        ...       ...                ...                               ...
3902               776592  2026-06-01  20          0  -179.0772  179.0772  xfmrduncan-duncan  wfec:anadarkofletch3comanch2:138
3903               776592  2026-06-01  21          0  -178.9095  178.9095  xfmrduncan-duncan  wfec:anadarkofletch3comanch2:138
3904               776592  2026-06-01  22          0  -204.7144  204.7144  xfmrduncan-duncan  wfec:anadarkofletch3comanch2:138
3905               776592  2026-06-01  23          0  -215.4419  215.4419  xfmrduncan-duncan  wfec:anadarkofletch3comanch2:138
3906               776592  2026-06-01  24          0  -246.1899  246.1899  xfmrduncan-duncan  wfec:anadarkofletch3comanch2:138

[3907 rows x 8 columns]

Reserve zones available: [1, 2, 3, 4, 5, 21]
Wind cols: ['rz1_spp_res_zonal_wind_forecast_f', 'rz2_spp_res_zonal_wind_forecast_f', 'rz3_spp_res_zonal_wind_forecast_f', 'rz4_spp_res_zonal_wind_forecast_f', 'rz5_spp_res_zonal_wind_forecast_f', 'rz21_spp_res_zonal_wind_forecast_f']
Load cols: ['rz1_spp_res_zonal_load_forecast_f', 'rz2_spp_res_zonal_load_forecast_f', 'rz3_spp_res_zonal_load_forecast_f', 'rz4_spp_res_zonal_load_forecast_f', 'rz5_spp_res_zonal_load_forecast_f', 'rz21_spp_res_zonal_load_forecast_f']

In [ ]:
from IPython.display import display, HTML
row_counts = hourly_mvalue.groupby('monitored').size().sort_values()
print(row_counts.to_string())

for name in row_counts.index:
    display(HTML(f'''
    <hr style="border: 3px solid black; margin: 30px 0;">
    <h1 style="background:#2c3e50; color:white; padding:12px 20px; border-radius:6px; font-family:monospace;">
        {name} &nbsp;<span style="font-size:0.6em; color:#aaa;">({row_counts[name]:,} rows)</span>
    </h1>
    <hr style="border: 1px solid #aaa; margin-bottom: 20px;">
    '''))

    analyze_constraint_by_zone(fundamentals, hourly_mvalue, name, 4, 95)
    plot_constraint_seasonality(hourly_mvalue, name)
    plot_recent_hourly_distribution(hourly_mvalue, name, bid_dt, days=10)
    table = get_constraints_node_price(hourly_mvalue, dfax, [name])
    get_metrics_for_nodes(table)

In [ ]:
# name = 'lnraun-tekamho'
# zone= 1
# analyze_constraint_by_zone(fundamentals, hourly_mvalue, name, zone, 90)
# plot_constraint_seasonality(hourly_mvalue, name)
# table = get_constraints_node_price(hourly_mvalue, dfax, [name])
# get_metrics_for_nodes(table)

In [5]:
fundamentals = get_weather_date(hourly_mvalue,'2026-06-04')

Reserve zones available: [1, 2, 3, 4, 5, 21]
Wind cols: ['rz1_spp_res_zonal_wind_forecast_f', 'rz2_spp_res_zonal_wind_forecast_f', 'rz3_spp_res_zonal_wind_forecast_f', 'rz4_spp_res_zonal_wind_forecast_f', 'rz5_spp_res_zonal_wind_forecast_f', 'rz21_spp_res_zonal_wind_forecast_f']
Load cols: ['rz1_spp_res_zonal_load_forecast_f', 'rz2_spp_res_zonal_load_forecast_f', 'rz3_spp_res_zonal_load_forecast_f', 'rz4_spp_res_zonal_load_forecast_f', 'rz5_spp_res_zonal_load_forecast_f', 'rz21_spp_res_zonal_load_forecast_f']

In [15]:
tomorrow_pct = predict_tomorrow_percentile(fundamentals, '2026-06-04')

--- Zone 1 ---

    hr  wind_value  wind_pct  load_value  load_pct
0    1      2033.0      66.3      4096.6      91.3
1    2      1950.9      65.2      3956.4      92.4
2    3      1810.3      59.8      3892.5      92.4
3    4      1663.8      53.3      3844.6      89.1
4    5      1511.0      43.5      3851.0      80.4
5    6      1374.2      41.3      4048.3      82.6
6    7      1385.4      44.6      4343.4      89.1
7    8      1423.2      48.9      4534.9      94.6
8    9      1429.2      53.3      4651.1      94.6
9   10      1475.0      65.2      4730.3      92.4
10  11      1417.9      63.0      4939.3      95.7
11  12      1424.5      60.9      5003.2      94.6
12  13      1498.6      63.0      5022.4      93.5
13  14      1535.9      64.1      5020.5      90.2
14  15      1614.3      65.2      5093.0      90.2
15  16      1710.8      67.4      5163.2      90.2
16  17      1716.5      66.3      5175.2      89.1
17  18      1736.5      67.4      5278.5      91.3
18  19      1627.3      62.0      5284.2      91.3
19  20      1447.1      58.7      5236.7      93.5
20  21      1588.7      58.7      5083.6      93.5
21  22      1810.6      62.0      4843.6      92.4
22  23      1832.4      60.9      4518.6      94.6
23  24      1805.5      62.0      4344.4      95.7

--- Zone 2 ---

    hr  wind_value  wind_pct  load_value  load_pct
0    1      4372.1      42.4       659.0      70.7
1    2      4308.8      42.4       647.5      63.0
2    3      4182.9      44.6       631.1      34.8
3    4      4048.9      43.5       637.1      43.5
4    5      3970.0      44.6       642.5      44.6
5    6      3870.7      44.6       673.5      71.7
6    7      3678.8      41.3       715.5      70.7
7    8      3476.2      41.3       727.1      68.5
8    9      3691.6      50.0       747.2      95.7
9   10      4175.3      65.2       757.4      92.4
10  11      4466.9      75.0       772.7      92.4
11  12      4633.5      80.4       802.3      93.5
12  13      4700.0      80.4       827.6      94.6
13  14      4762.1      78.3       857.9      94.6
14  15      4838.6      78.3       881.2      97.8
15  16      4864.5      78.3       892.9      97.8
16  17      4927.2      78.3       894.2      95.7
17  18      5004.5      78.3       885.6      95.7
18  19      5067.3      78.3       884.0      95.7
19  20      5214.8      79.3       870.7      96.7
20  21      5413.9      78.3       846.9      98.9
21  22      5650.5      77.2       784.2      95.7
22  23      5863.1      81.5       737.5      95.7
23  24      5973.2      82.6       709.3      96.7

--- Zone 3 ---

    hr  wind_value  wind_pct  load_value  load_pct
0    1      1070.6       9.8      4089.4      42.4
1    2       923.5       7.6      3972.3      15.2
2    3       906.0      12.0      3929.4      12.0
3    4       875.6      14.1      3927.7      12.0
4    5       740.4      10.9      3930.2       5.4
5    6       614.5      10.9      3940.1       2.2
6    7       529.4      12.0      4023.2      10.9
7    8       452.4      10.9      4078.9      16.3
8    9       399.6      13.0      4123.4      19.6
9   10       424.5      19.6      4179.0      30.4
10  11       467.2      22.8      4261.7      62.0
11  12       476.8      26.1      4405.3      76.1
12  13       504.5      30.4      4541.5      84.8
13  14       552.7      30.4      4612.1      79.3
14  15       625.9      31.5      4686.2      78.3
15  16       727.5      34.8      4695.9      76.1
16  17       843.3      35.9      4754.9      75.0
17  18       941.8      39.1      4793.6      73.9
18  19      1045.2      38.0      4804.9      80.4
19  20      1057.3      33.7      4813.2      84.8
20  21      1127.2      28.3      4702.0      84.8
21  22      1323.7      30.4      4574.0      80.4
22  23      1473.3      33.7      4472.8      81.5
23  24      1523.8      34.8      4414.9      89.1

--- Zone 4 ---

    hr  wind_value  wind_pct  load_value  load_pct
0    1      8309.1      32.6     17924.5      84.8
1    2      8080.5      33.7     17189.7      82.6
2    3      7851.1      34.8     16713.9      82.6
3    4      7753.0      35.9     16443.5      80.4
4    5      7631.4      37.0     16616.9      79.3
5    6      7490.3      35.9     17339.7      81.5
6    7      7324.2      34.8     18276.1      79.3
7    8      6995.9      32.6     19051.6      82.6
8    9      6858.3      35.9     19990.9      91.3
9   10      7460.1      43.5     21096.8      94.6
10  11      8142.0      47.8     22372.9      95.7
11  12      8655.1      50.0     23563.6      95.7
12  13      8968.2      55.4     24721.8      95.7
13  14      9178.3      54.3     25585.0      93.5
14  15      9499.6      54.3     26246.8      93.5
15  16      9796.8      57.6     26623.8      93.5
16  17     10000.6      56.5     26640.4      93.5
17  18     10205.3      56.5     25709.0      90.2
18  19     10535.0      56.5     24852.2      87.0
19  20     10745.1      55.4     24347.5      91.3
20  21     11233.6      54.3     23269.3      92.4
21  22     11937.0      55.4     22377.6      91.3
22  23     12462.6      54.3     21067.3      90.2
23  24     12859.1      56.5     19854.2      90.2

--- Zone 5 ---

    hr  wind_value  wind_pct  load_value  load_pct
0    1      1084.0      13.0      3768.4      53.3
1    2      1056.9      13.0      3672.1      43.5
2    3       964.5      10.9      3604.4      35.9
3    4       887.1       9.8      3604.8      35.9
4    5       843.0       9.8      3633.8      30.4
5    6       770.0       9.8      3659.8      27.2
6    7       673.6       7.6      3804.8      28.3
7    8       512.4       7.6      3940.2      35.9
8    9       404.3       5.4      4008.7      42.4
9   10       391.5       5.4      4065.8      55.4
10  11       422.8       7.6      4131.2      68.5
11  12       450.3       8.7      4186.2      83.7
12  13       479.7       8.7      4226.9      92.4
13  14       523.1       7.6      4324.5      97.8
14  15       581.0       8.7      4338.2      97.8
15  16       638.7      12.0      4393.0      97.8
16  17       643.9       9.8      4400.7      98.9
17  18       641.5       9.8      4369.8      96.7
18  19       721.2      14.1      4330.8      95.7
19  20       748.0      14.1      4270.1      95.7
20  21       757.0      10.9      4180.8      87.0
21  22       893.6      13.0      4086.1      76.1
22  23      1015.4      14.1      4012.7      77.2
23  24      1000.1      10.9      3892.8      62.0

--- Zone 21 ---

    hr  wind_value  wind_pct  load_value  load_pct
0    1       693.7      67.2      2688.8      51.4
1    2       660.4      59.4      2585.3      50.0
2    3       629.1      56.2      2506.5      33.3
3    4       577.7      54.7      2466.1      31.9
4    5       522.8      46.9      2453.5      25.0
5    6       459.0      42.2      2455.2      20.8
6    7       387.5      31.2      2463.8       8.3
7    8       328.7      26.6      2433.0       2.8
8    9       287.6      29.7      2468.2       1.4
9   10       251.1      32.8      2526.8       4.2
10  11       239.0      28.1      2560.9       8.3
11  12       267.0      29.7      2587.8      12.5
12  13       298.7      34.4      2633.6      19.4
13  14       309.4      37.5      2705.5      38.9
14  15       319.3      34.4      2774.1      50.0
15  16       327.9      35.9      2830.4      54.2
16  17       356.0      39.1      2961.5      63.9
17  18       398.1      39.1      3093.5      66.7
18  19       453.8      45.3      3201.3      72.2
19  20       546.9      62.5      3257.7      76.4
20  21       613.6      71.9      3239.2      76.4
21  22       677.5      76.6      3158.1      75.0
22  23       732.7      81.2      3072.6      73.6
23  24       762.0      76.6      2897.4      66.7

--- Summary (median pct by zone / peak) ---
1: ow: 62, fw: 56, ol: 92, fl: 90
2: ow: 78, fw: 44, ol: 95, fl: 66
3: ow: 30, fw: 11, ol: 77, fl: 12
4: ow: 54, fw: 35, ol: 92, fl: 82
5: ow: 9, fw: 10, ol: 89, fl: 35
21: ow: 36, fw: 55, ol: 52, fl: 32