In [1]:
# Get daily constraint ranked by the abs RT - DA 
from functions import (
    get_recent_constraint_mvalue,
    get_node_dfax_from_constraint_num,
    get_hourly_mvalue_for_constraint_num,
    get_constraint_node_prices_from_constraint_num,
    get_constraints_node_price,
    get_metrics_for_nodes,
    get_recent_direction_accuracy,
    get_weather_date,
    predict_tomorrow_percentile,
    analyze_constraint_by_zone,
    plot_constraint_seasonality,
    plot_recent_hourly_distribution,
)
import pandas as pd

/opt/gk-py314/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
now = pd.Timestamp.now(tz='US/Central')
days_ahead = 2 if now.hour >= 10 else 1
bid_dt = (now + pd.Timedelta(days=days_ahead)).strftime('%Y-%m-%d')
print(bid_dt)

2026-07-29

In [3]:
dt = (pd.Timestamp(bid_dt) - pd.Timedelta(days=1)).strftime('%Y-%m-%d')
mvalue= get_recent_constraint_mvalue(dt, dt, threshold=500)
dfax= get_node_dfax_from_constraint_num(mvalue)
hourly_mvalue = get_hourly_mvalue_for_constraint_num(mvalue)
fundamentals = get_weather_date(hourly_mvalue, dt)

start_dt: 2026-07-28, end_dt: 2026-07-28, Market: SPP
Fetching RT mvalues...
Fetching DA mvalues...
RT constraints: 15, DA constraints: 70

Fetching constraint details...

    oops_constraint_num   rt_total   da_total      rt_da  abs_rt_da_diff                monitored                       contingency
0                895163     0.0000 -3520.3940  3520.3940       3520.3940        lnst_joe-avectytp     nppdmps:cooperst_joe:345:1:11
1                554091     0.0000 -3199.2795  3199.2795       3199.2795        lnnebrcty-sub3456       oppd:sub3740sub3455:345:1:9
2                523079     0.0000 -2707.7204  2707.7204       2707.7204      lnt_brmghm-lbrtyst5    aeciindn:mo_cityeckles:161:1:4
3                626867     0.0000 -2315.1607  2315.1607       2315.1607          ln29eveng3-29ga               wr:hoytjeff:345:1:6
4                649753     0.0000 -1508.5137  1508.5137       1508.5137         lnrussett-sbrown   okge:brown2bodlecaney1:138:7:34
5                801901 -1338.1280     0.0000 -1338.1280       1338.1280         lnmonett-aur1241     aeci:jasper7blackbry:345:1:12
6                776006     0.0000 -1106.7813  1106.7813       1106.7813          lnmarshal3-knob       seci:elm_crkconcor3:230:1:9
7                648887     0.0000 -1064.3099  1064.3099       1064.3099        lnsnakeck-aliance      waue:waysid_wstegall:230:2:8
8                568166     0.0000 -1046.3452  1046.3452       1046.3452    lnmain1-batfld5_rev23  sprmaeci:junctn5brook_ln:161:1:1
9                680789     0.0000 -1035.0585  1035.0585       1035.0585          lnweav-tallgras               wr:bentmidi:138:1:5
10               653411 -1027.4585     0.0000 -1027.4585       1027.4585         lnrussett-sbrown   okge:brown2bodlecaney1:138:7:34
11               899212     0.0000 -1015.5091  1015.5091       1015.5091  lnanta_tp-exirawa_rev23         csws:kiowapittsb9:345:1:8
12               801513     0.0000  -880.7272   880.7272        880.7272         lnmonett-aur1241     aeci:jasper7blackbry:345:1:12
13                  609     0.0000  -831.5008   831.5008        831.5008        xfmrozrk_b-ozrk_b                              base
14               566845     0.0000  -637.6132   637.6132        637.6132  lnaliance-snakeck_rev23  nppd:dunlapboxbutechadron:115:2:
15               290952     0.0000  -607.9368   607.9368        607.9368        lnfulton_c-pat_wx       csws:nwtexarturk_pp:345:1:8
18               829721     0.0000  -372.7802   372.7802        372.7802          lnmarshal3-knob       seci:concor3clifto1:115:1:9
20               524987  -331.1494     0.0000  -331.1494        331.1494      lnt_brmghm-lbrtyst5    aeciindn:mo_cityeckles:161:1:4
28               892112     0.0000  -185.3107   185.3107        185.3107        lnfulton_c-pat_wx        csws:wilkeslongwoo:345:1:9
32               550088  -157.8321     0.0000  -157.8321        157.8321        lnnebrcty-sub3456       oppd:sub3740sub3455:345:1:9
57               707084   -39.1737     0.0000   -39.1737         39.1737          lnmarshal3-knob       seci:elm_crkconcor3:230:1:9

RT active constraint-days: 625
DA active constraint-days: 2243
   oops_constraint_num          dt  hr  rt_mvalue  da_mvalue    rt_da
0                  609  2024-07-30   8        0.0    -3.1417   3.1417
1                  609  2024-07-30   9        0.0   -10.2431  10.2431
2                  609  2024-07-30  10        0.0   -11.5700  11.5700
3                  609  2024-07-30  11        0.0    -2.5718   2.5718
4                  609  2024-07-30  12        0.0    -9.4942   9.4942

Merged hourly rows: 25736

       oops_constraint_num          dt  hr  rt_mvalue  da_mvalue     rt_da                monitored                contingency
0                      609  2024-07-30   8        0.0    -3.1417    3.1417        xfmrozrk_b-ozrk_b                       base
1                      609  2024-07-30   9        0.0   -10.2431   10.2431        xfmrozrk_b-ozrk_b                       base
2                      609  2024-07-30  10        0.0   -11.5700   11.5700        xfmrozrk_b-ozrk_b                       base
3                      609  2024-07-30  11        0.0    -2.5718    2.5718        xfmrozrk_b-ozrk_b                       base
4                      609  2024-07-30  12        0.0    -9.4942    9.4942        xfmrozrk_b-ozrk_b                       base
...                    ...         ...  ..        ...        ...       ...                      ...                        ...
25731               899212  2026-07-28  19        0.0  -119.0713  119.0713  lnanta_tp-exirawa_rev23  csws:kiowapittsb9:345:1:8
25732               899212  2026-07-28  20        0.0  -121.4201  121.4201  lnanta_tp-exirawa_rev23  csws:kiowapittsb9:345:1:8
25733               899212  2026-07-28  21        0.0   -78.1150   78.1150  lnanta_tp-exirawa_rev23  csws:kiowapittsb9:345:1:8
25734               899212  2026-07-28  22        0.0   -45.2815   45.2815  lnanta_tp-exirawa_rev23  csws:kiowapittsb9:345:1:8
25735               899212  2026-07-28  23        0.0   -25.4347   25.4347  lnanta_tp-exirawa_rev23  csws:kiowapittsb9:345:1:8

[25736 rows x 8 columns]

Reserve zones available: [1, 2, 3, 4, 5, 21]
Wind cols: ['rz1_spp_res_zonal_wind_forecast_f', 'rz2_spp_res_zonal_wind_forecast_f', 'rz3_spp_res_zonal_wind_forecast_f', 'rz4_spp_res_zonal_wind_forecast_f', 'rz5_spp_res_zonal_wind_forecast_f', 'rz21_spp_res_zonal_wind_forecast_f']
Load cols: ['rz1_spp_res_zonal_load_forecast_f', 'rz2_spp_res_zonal_load_forecast_f', 'rz3_spp_res_zonal_load_forecast_f', 'rz4_spp_res_zonal_load_forecast_f', 'rz5_spp_res_zonal_load_forecast_f', 'rz21_spp_res_zonal_load_forecast_f']

In [4]:
# from IPython.display import display, HTML
# row_counts = hourly_mvalue.groupby('monitored').size().sort_values()
# print(row_counts.to_string())

# for name in row_counts.index:
#     display(HTML(f'''
#     <hr style="border: 3px solid black; margin: 30px 0;">
#     <h1 style="background:#2c3e50; color:white; padding:12px 20px; border-radius:6px; font-family:monospace;">
#         {name} &nbsp;<span style="font-size:0.6em; color:#aaa;">({row_counts[name]:,} rows)</span>
#     </h1>
#     <hr style="border: 1px solid #aaa; margin-bottom: 20px;">
#     '''))

#     analyze_constraint_by_zone(fundamentals, hourly_mvalue, name, 4, 95)
#     plot_constraint_seasonality(hourly_mvalue, name)
#     plot_recent_hourly_distribution(hourly_mvalue, name, bid_dt, days=10)
#     table = get_constraints_node_price(hourly_mvalue, dfax, [name])
#     get_metrics_for_nodes(table)

In [5]:
# name = 'lnraun-tekamho'
# zone= 1
# analyze_constraint_by_zone(fundamentals, hourly_mvalue, name, zone, 90)
# plot_constraint_seasonality(hourly_mvalue, name)
# table = get_constraints_node_price(hourly_mvalue, dfax, [name])
# get_metrics_for_nodes(table)

In [6]:
fundamentals = get_weather_date(hourly_mvalue, bid_dt)

Reserve zones available: [1, 2, 3, 4, 5, 21]
Wind cols: ['rz1_spp_res_zonal_wind_forecast_f', 'rz2_spp_res_zonal_wind_forecast_f', 'rz3_spp_res_zonal_wind_forecast_f', 'rz4_spp_res_zonal_wind_forecast_f', 'rz5_spp_res_zonal_wind_forecast_f', 'rz21_spp_res_zonal_wind_forecast_f']
Load cols: ['rz1_spp_res_zonal_load_forecast_f', 'rz2_spp_res_zonal_load_forecast_f', 'rz3_spp_res_zonal_load_forecast_f', 'rz4_spp_res_zonal_load_forecast_f', 'rz5_spp_res_zonal_load_forecast_f', 'rz21_spp_res_zonal_load_forecast_f']

In [7]:
tomorrow_pct = predict_tomorrow_percentile(fundamentals, bid_dt)

--- Zone 1 ---

    hr  wind_value  wind_pct  load_value  load_pct
0    1       656.1      13.3      5980.6      86.7
1    2       657.7      13.3      5825.1      86.7
2    3       655.1      16.7      5525.7      86.7
3    4       616.9      23.3      5422.1      86.7
4    5       562.2      16.7      5532.9      86.7
5    6       501.4      16.7      5599.3      93.3
6    7       453.1      16.7      5705.8      86.7
7    8       398.4      20.0      5738.3      86.7
8    9       295.4      26.7      5987.7      83.3
9   10       225.8      26.7      6138.2      73.3
10  11       260.0      26.7      6451.6      73.3
11  12       324.6      36.7      6932.4      80.0
12  13       372.0      43.3      7169.0      86.7
13  14       427.8      50.0      7254.2      80.0
14  15       499.3      53.3      7332.8      83.3
15  16       571.6      60.0      7467.4      86.7
16  17       656.5      66.7      7512.9      86.7
17  18       751.7      73.3      7486.2      86.7
18  19       841.4      70.0      7328.1      80.0
19  20       899.4      66.7      7224.5      83.3
20  21       981.0      63.3      7122.8      86.7
21  22      1089.5      60.0      6689.8      83.3
22  23      1163.0      46.7      6490.7      86.7
23  24      1204.2      53.3      6152.0      83.3

--- Zone 2 ---

    hr  wind_value  wind_pct  load_value  load_pct
0    1      2961.1      20.0       913.0      93.3
1    2      2733.5      20.0       877.9      90.0
2    3      2499.6      20.0       862.0      90.0
3    4      2329.6      20.0       845.2      90.0
4    5      2066.3      20.0       847.2      93.3
5    6      1719.4      23.3       853.9      93.3
6    7      1388.1      20.0       881.0      93.3
7    8      1103.7      20.0       890.6      93.3
8    9       891.0      30.0       930.6      93.3
9   10       732.3      30.0       969.1      90.0
10  11       638.5      16.7       995.7      86.7
11  12       638.2      23.3      1032.2      83.3
12  13       714.6      23.3      1064.8      76.7
13  14       845.9      26.7      1102.9      83.3
14  15      1006.5      33.3      1138.9      86.7
15  16      1114.3      33.3      1159.4      93.3
16  17      1186.1      33.3      1170.9      93.3
17  18      1348.0      30.0      1171.3      93.3
18  19      1616.1      26.7      1163.3      93.3
19  20      1879.4      23.3      1147.9      93.3
20  21      2171.1      30.0      1127.9      90.0
21  22      2666.2      26.7      1071.1      93.3
22  23      3132.0      26.7      1039.7      96.7
23  24      3341.2      30.0       943.1      83.3

--- Zone 3 ---

    hr  wind_value  wind_pct  load_value  load_pct
0    1      1865.6      70.0      5207.8     100.0
1    2      1738.9      56.7      5123.9      93.3
2    3      1595.9      50.0      5104.0      96.7
3    4      1364.2      43.3      5028.6      96.7
4    5      1010.1      33.3      4933.7      93.3
5    6       715.5      30.0      4911.4      93.3
6    7       567.4      26.7      4909.1      93.3
7    8       457.0      26.7      4926.1      93.3
8    9       326.6      26.7      5012.9     100.0
9   10       252.9      30.0      5230.6     100.0
10  11       229.2      33.3      5411.2      93.3
11  12       182.8      20.0      5656.2      93.3
12  13       174.5      13.3      5915.7      96.7
13  14       213.0      13.3      6088.8      96.7
14  15       280.8      20.0      6100.8      93.3
15  16       356.1      20.0      6147.4      93.3
16  17       454.2      26.7      6156.2     100.0
17  18       605.9      36.7      6142.1      93.3
18  19       784.6      40.0      6100.7      93.3
19  20       962.6      36.7      6074.2      93.3
20  21      1223.1      43.3      5984.2      96.7
21  22      1560.7      63.3      5738.1      93.3
22  23      1803.2      70.0      5616.2      96.7
23  24      1899.0      73.3      5462.9      93.3

--- Zone 4 ---

    hr  wind_value  wind_pct  load_value  load_pct
0    1      8703.1      43.3     25980.6      93.3
1    2      8435.3      36.7     24920.6      93.3
2    3      7878.2      36.7     23989.0      93.3
3    4      7392.8      36.7     23348.0      93.3
4    5      6862.6      36.7     23050.5      93.3
5    6      6093.6      36.7     23235.0      90.0
6    7      5392.3      36.7     23574.7      90.0
7    8      4557.1      36.7     24291.2      90.0
8    9      3443.3      36.7     25753.8      90.0
9   10      2630.7      40.0     27393.5      86.7
10  11      2337.4      40.0     29409.5      86.7
11  12      2226.3      36.7     31011.2      86.7
12  13      2220.8      40.0     32474.6      86.7
13  14      2404.5      40.0     33316.1      83.3
14  15      2744.5      40.0     33839.7      83.3
15  16      3097.7      40.0     34327.8      90.0
16  17      3499.4      40.0     34393.5      96.7
17  18      4119.2      40.0     34158.6      90.0
18  19      4883.7      40.0     33001.2      80.0
19  20      5615.5      40.0     32667.8      83.3
20  21      6620.0      43.3     31637.1      83.3
21  22      7856.7      40.0     30360.5      86.7
22  23      8765.3      40.0     28777.2      86.7
23  24      9130.3      50.0     27160.8      86.7

--- Zone 5 ---

    hr  wind_value  wind_pct  load_value  load_pct
0    1      1614.3      46.7      4006.4      56.7
1    2      1655.2      46.7      3900.0      56.7
2    3      1638.5      50.0      3867.9      60.0
3    4      1619.9      53.3      3841.2      63.3
4    5      1574.6      53.3      3852.6      66.7
5    6      1471.5      53.3      3934.2      80.0
6    7      1327.6      50.0      4005.0      73.3
7    8      1189.3      46.7      4168.9      70.0
8    9       979.6      46.7      4312.6      86.7
9   10       774.1      43.3      4446.6      76.7
10  11       730.1      43.3      4558.8      83.3
11  12       782.5      43.3      4680.2      83.3
12  13       828.7      46.7      4730.6      83.3
13  14       856.6      50.0      4761.5      73.3
14  15       904.5      50.0      4767.1      76.7
15  16       975.6      53.3      4771.2      73.3
16  17      1070.3      53.3      4774.1      70.0
17  18      1179.0      53.3      4783.4      80.0
18  19      1316.9      56.7      4792.3      86.7
19  20      1455.3      66.7      4767.5      86.7
20  21      1617.5      66.7      4716.2      86.7
21  22      1827.0      73.3      4540.9      63.3
22  23      1967.5      66.7      4389.6      63.3
23  24      2054.9      63.3      4244.5      63.3

--- Zone 21 ---

    hr  wind_value  wind_pct  load_value  load_pct
0    1       267.2       6.7      3688.0      83.3
1    2       218.5       3.3      3482.8      83.3
2    3       210.0       3.3      3308.4      83.3
3    4       201.6       3.3      3165.5      83.3
4    5       179.1       3.3      3064.3      83.3
5    6       149.4       3.3      3128.9      86.7
6    7       132.7       6.7      3099.2      73.3
7    8       125.0       6.7      3109.1      66.7
8    9       101.1       6.7      3258.3      70.0
9   10        83.5      10.0      3359.6      66.7
10  11        92.1      16.7      3605.3      86.7
11  12       110.5      23.3      3863.6      86.7
12  13       140.3      30.0      4114.8      86.7
13  14       182.4      43.3      4325.2      86.7
14  15       231.0      46.7      4488.4      86.7
15  16       276.1      46.7      4605.7      86.7
16  17       322.3      50.0      4676.4      86.7
17  18       370.4      50.0      4732.7      86.7
18  19       372.9      40.0      4704.5      80.0
19  20       360.1      23.3      4598.9      70.0
20  21       355.6      16.7      4433.4      60.0
21  22       345.3      10.0      4397.8      80.0
22  23       405.9      20.0      4286.2      86.7
23  24       426.2      23.3      4050.8      86.7

--- Summary (median pct by zone / peak) ---
1: ow: 51, fw: 16, ol: 83, fl: 86
2: ow: 26, fw: 20, ol: 93, fl: 91
3: ow: 28, fw: 46, ol: 93, fl: 93
4: ow: 40, fw: 36, ol: 86, fl: 93
5: ow: 51, fw: 51, ol: 78, fl: 63
21: ow: 23, fw: 3, ol: 86, fl: 83