In [1]:
# Get daily constraint ranked by the abs RT - DA 
import sys
sys.path.append('/var/www/python/Prod/nighthawk/')

import pandas as pd
from nighthawk.data import Constraint

In [3]:
now = pd.Timestamp.now(tz='US/Central')
days_ahead = 2 if now.hour >= 10 else 1
bid_dt = (now + pd.Timedelta(days=days_ahead)).strftime('%Y-%m-%d')
print(bid_dt)

2026-06-05

# Daily RT DA Spike Analysis

In [4]:
# give a date and returns to me the hourly metrics at that hour, wind/load/temperature/gas/wind ramp/genoutage

In [5]:
from nighthawk.data.pipeline.common_functions.wind import Wind
from nighthawk.data.pipeline.common_functions.load import Load
from nighthawk.data.pipeline.common_functions.gas import Gas
from nighthawk.data.pipeline.common_functions.genoutage import GenOutage
from nighthawk.data.pipeline.common_functions.weather import Weather
from nighthawk.data.network.node import Node

SPP_HUB_NODES = {636:'south_hub'}
SPP_CITIES =[ ('Kansas City', 'MO'), ('Oklahoma City', 'OK')]


def get_hourly_snapshot(date: str, hour: int):
    assert 1 <= hour <= 24, "hour must be between 1 and 24"
    dt      = date
    dt_prev = (pd.Timestamp(dt) - pd.Timedelta(days=1)).strftime('%Y-%m-%d')

    wind_df = Wind('SPP').get_total_wind(dt_prev, dt, var_spec=['f'])
    load_df = Load('SPP').get_total_load(dt_prev, dt, var_spec=['f'])

    gas_raw = Gas('SPP').get_daily_gas_price(['Henry'], dt_prev, dt, pivot=False)
    gas_df  = (gas_raw[gas_raw['hub_name'] == 'Henry'][['dt', 'gas_price']]
               .rename(columns={'gas_price': 'henry_gas_price'}))

    go_raw = GenOutage('SPP').get_genoutage_by_level(dt_prev, dt, var_spec=['f'], area_list=['SPP'])
    go_df  = go_raw[go_raw['baa_zone'] == 'SPP'][['dt', 'hr', 'spp_genoutage_forecast_f']]

    weather_obj = Weather('SPP')
    city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()
    temp_raw    = weather_obj.get_citylevel_temperature_for_ve(dt_prev, dt, city_ids, pivot=False)
    temp_df     = (temp_raw.groupby(['dt', 'hr'])['temperature_degf']
                           .mean().reset_index()
                           .rename(columns={'temperature_degf': 'avg_temp_f'}))

    price_raw = Node(list(SPP_HUB_NODES.keys()), 'SPP').get_price(
        dt, dt, component=['Slack'], type=['DA', 'RT'], granularity='hourly'
    )
    price_raw['dt'] = price_raw['dt'].astype(str)
    price_raw['hr'] = price_raw['hr'].astype(int)

    for df in [wind_df, load_df, go_df, temp_df]:
        df['dt'] = df['dt'].astype(str)
        df['hr'] = df['hr'].astype(int)
    gas_df['dt'] = gas_df['dt'].astype(str)

    base = (
        wind_df[['dt', 'hr', 'spp_wind_total_forecast_f']]
        .merge(load_df[['dt', 'hr', 'spp_load_total_forecast_f']], on=['dt', 'hr'], how='outer')
        .merge(go_df,   on=['dt', 'hr'], how='left')
        .merge(temp_df, on=['dt', 'hr'], how='left')
        .merge(gas_df,  on='dt',         how='left')
        .sort_values(['dt', 'hr']).reset_index(drop=True)
    )
    base['B_wind_ramp'] = base['spp_wind_total_forecast_f'].diff()
    base['B_load_ramp'] = base['spp_load_total_forecast_f'].diff()
    base['B_wind_ramp_2'] = base['spp_wind_total_forecast_f'].diff(2)
    base['B_load_ramp_2'] = base['spp_load_total_forecast_f'].diff(2)

    row       = base[(base['dt'] == dt) & (base['hr'] == hour)]
    price_row = price_raw[(price_raw['dt'] == dt) & (price_raw['hr'] == hour)].copy()
    price_row['hub'] = price_row['node_num'].map(SPP_HUB_NODES)

    if row.empty:
        print(f"No data found for {dt} hour {hour}")
        return None

    r   = row.iloc[0]
    rec = {
        'dt':               dt,
        'hr':               hour,
        'wind_f (MW)':      round(r['spp_wind_total_forecast_f'], 1),
        'load_f (MW)':      round(r['spp_load_total_forecast_f'], 1),
        'genoutage_f (MW)': round(r['spp_genoutage_forecast_f'],  1),
        'avg_temp (°F)':    round(r['avg_temp_f'],                1),
        'henry_gas ($/MMBtu)': round(r['henry_gas_price'],        3),
        'wind_ramp (MW/hr)': round(r['B_wind_ramp'],                1),
        'load_ramp (MW/hr)': round(r['B_load_ramp'],                1),
        'wind_ramp_2 (MW/hr)': round(r['B_wind_ramp_2'],                1),
        'load_ramp_2 (MW/hr)': round(r['B_load_ramp_2'],                1),
    }

    for _, pr in price_row.sort_values('node_num').iterrows():
        hub = pr['hub']
        rec[f'{hub}_da_slack']  = round(pr.get('da_slack', float('nan')), 2)
        rec[f'{hub}_rt_slack']  = round(pr.get('rt_slack', float('nan')), 2)

    display(pd.DataFrame([rec]))
    return pd.DataFrame([rec])


# ── Example ───────────────────────────────────────────────
get_hourly_snapshot('2022-12-23', 18)

/tmp/ipykernel_103950/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),south_hub_da_slack,south_hub_rt_slack
0,2022-12-23,18,10722.4,40623.0,11765.4,10.3,7.28,-930.1,1710.0,-2080.7,2397.0,149.7,1395.17

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),south_hub_da_slack,south_hub_rt_slack
0,2022-12-23,18,10722.4,40623.0,11765.4,10.3,7.28,-930.1,1710.0,-2080.7,2397.0,149.7,1395.17

In [6]:
import sys
sys.path.append('/var/www/python/Prod/nighthawk/')
import pandas as pd
from nighthawk.util.bigquery_functions import download_df_from_bq

PNL_COLS = ['clear_mw', 'profit_total', 'profit_congestion', 'profit_slack']

def _fetch_pnl(start_dt: str, end_dt: str) -> pd.DataFrame:
    query = f"""
        SELECT dt, hr, incdec, strategy, rep_zone, broad_zone,
               SUM(clear_mw)          AS clear_mw,
               SUM(profit_total)      AS profit_total,
               SUM(profit_congestion) AS profit_congestion,
               SUM(profit_slack)      AS profit_slack
        FROM `movetocloud-999.virtual_financials.segment_portfolio_details_SPP`
        WHERE dt BETWEEN '{start_dt}' AND '{end_dt}'
        GROUP BY dt, hr, incdec, strategy, rep_zone, broad_zone
        ORDER BY dt, hr
    """
    df = download_df_from_bq(query)
    df['dt'] = pd.to_datetime(df['dt']).dt.strftime('%Y-%m-%d')
    df['hr'] = df['hr'].astype(int)
    return df


def get_spp_pnl(start_dt: str, end_dt: str, group_by: str = 'daily') -> pd.DataFrame:
    """
    Fetch SPP virtual portfolio PnL summed across all strategies.

    group_by: 'daily'  — one row per dt
              'hourly' — one row per dt x hr
              'raw'    — full detail (strategy / rep_zone / incdec)
    """
    assert group_by in ('daily', 'hourly', 'raw')
    df = _fetch_pnl(start_dt, end_dt)
    if group_by == 'daily':
        return df.groupby('dt', as_index=False)[PNL_COLS].sum()
    elif group_by == 'hourly':
        return df.groupby(['dt', 'hr'], as_index=False)[PNL_COLS].sum()
    return df


def get_pnl_snapshot(date: str, hour: int) -> pd.DataFrame:
    """Return a single-row DataFrame with total PnL for one specific date and hour."""
    df = _fetch_pnl(date, date)
    row = df[df['hr'] == hour][PNL_COLS].sum()
    result = pd.DataFrame([{'dt': date, 'hr': hour, **{c: round(row[c], 2) for c in PNL_COLS}}])
    display(result)
    return result


# Daily PnL (summed across all strategies, one row per dt)
daily = get_spp_pnl('2026-05-01', '2026-05-12', group_by='daily')
display(daily)

# Hourly PnL (one row per dt x hr)
hourly = get_spp_pnl('2026-05-01', '2026-05-12', group_by='hourly')
display(hourly)

# Single dt + hour snapshot
get_pnl_snapshot('2022-12-23', 18)

            dt     clear_mw  profit_total  profit_congestion  profit_slack
0   2026-05-01  1314.123994  10346.707933       -1462.969181  10884.276826
1   2026-05-02  1652.635993  -7083.557217      -12633.139192     21.284947
2   2026-05-03  3990.475993   7572.335125      -11842.373297  16723.520420
3   2026-05-04  2913.842014  -3192.139128       -4567.698330    114.950350
4   2026-05-05  4434.162016  16118.681327        8296.839209   4425.614313
5   2026-05-06  3987.468992  -6386.306198      -23104.017113   -674.526433
6   2026-05-07  3755.137000  15738.199106       19953.350274  -7964.616577
7   2026-05-08  4304.602005  67259.501733       29093.770899  32013.608437
8   2026-05-09  3716.091997  16205.688033        1858.715909  16642.058252
9   2026-05-10  4435.628995   3100.265405        2119.289315    206.546872
10  2026-05-11  2445.745995  15801.618050       31015.130184 -21331.629859
11  2026-05-12  3894.887007  10758.093735       -4994.136422   3146.404895

             dt  hr    clear_mw  profit_total  profit_congestion  profit_slack
0    2026-05-01   1    0.000000      0.000000           0.000000      0.000000
1    2026-05-01   2  159.647999    516.767106           1.068651    278.250245
2    2026-05-01   3  155.144999    466.455470           3.612927    239.142706
3    2026-05-01   4  192.359999    508.910930          14.164024    324.564199
4    2026-05-01   5   55.928000     88.684027           1.266369     90.660056
..          ...  ..         ...           ...                ...           ...
283  2026-05-12  20  303.584000   4922.006249       -1673.332169   6052.511373
284  2026-05-12  21  139.781999    222.990298       -1267.729583   1051.766621
285  2026-05-12  22  178.310000  -2155.851849       -1877.787045   -597.293858
286  2026-05-12  23  148.264000   -763.514208        -667.330491   -334.509082
287  2026-05-12  24  148.011001   -707.721846        -666.170698   -444.299891

[288 rows x 6 columns]

           dt  hr  clear_mw  profit_total  profit_congestion  profit_slack
0  2022-12-23  18      7.09       5328.41             493.17       4666.42

           dt  hr  clear_mw  profit_total  profit_congestion  profit_slack
0  2022-12-23  18      7.09       5328.41             493.17       4666.42

In [7]:
import os
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler

SAVE_PATH   = '/mnt/disks/filedisk1/SPP/VE/spp_hourly_fundamentals.csv'
RF_FEATURES = [
    'wind_f (MW)', 'load_f (MW)', 'genoutage_f (MW)', 'avg_temp (°F)',
    'henry_gas ($/MMBtu)', 'wind_ramp (MW/hr)', 'load_ramp (MW/hr)',
    'wind_ramp_2 (MW/hr)', 'load_ramp_2 (MW/hr)',
]
TARGET = 'SHub_rt_slack'


def find_similar_hours(date: str, hour: int, k: int = 10,
                        dataset_path: str = SAVE_PATH,
                        n_estimators: int = 200) -> pd.DataFrame:
    """
    Train a RandomForest on (fundamentals -> SHub_rt_slack) using all history
    strictly before the given dt/hr, then rank historical hours by RF proximity
    (fraction of trees where a historical row shares the same leaf as the query).

    Returns top-k most similar rows sorted by rf_proximity descending,
    with the query row prepended (rf_proximity = 1.0).
    """
    df = pd.read_csv(dataset_path)
    df['dt'] = df['dt'].astype(str)
    df['hr'] = df['hr'].astype(int)

    # --- strict past-only filter ---
    cutoff    = pd.Timestamp(date) + pd.Timedelta(hours=hour - 1)
    df['_ts'] = pd.to_datetime(df['dt']) + pd.to_timedelta(df['hr'] - 1, unit='h')
    hist      = df[df['_ts'] < cutoff].drop(columns='_ts').reset_index(drop=True)

    # --- query row ---
    query_rows = df[(df['dt'] == date) & (df['hr'] == hour)].drop(columns='_ts', errors='ignore')
    if query_rows.empty:
        print('Query dt/hr not in dataset, fetching live...')
        query_row = get_hourly_snapshot(date, hour)
    else:
        query_row = query_rows.iloc[[0]]

    # --- feature matrix ---
    feat_cols = [c for c in RF_FEATURES if c in hist.columns and c in query_row.columns]
    train_mask = hist[feat_cols].notna().all(axis=1) & hist[TARGET].notna()
    hist_clean = hist[train_mask].reset_index(drop=True)

    X_train = hist_clean[feat_cols].values
    y_train = hist_clean[TARGET].values
    X_query = query_row[feat_cols].fillna(0).values

    # --- train RF ---
    rf = RandomForestRegressor(n_estimators=n_estimators, random_state=42,
                               n_jobs=-1, max_features='sqrt')
    rf.fit(X_train, y_train)

    print(f'RF trained on {len(X_train)} rows | '
          f'top features: {sorted(zip(rf.feature_importances_, feat_cols), reverse=True)[:3]}')

    # --- RF proximity: fraction of trees sharing the same leaf ---
    # apply() returns shape (n_samples, n_estimators) — leaf index per tree
    hist_leaves  = rf.apply(X_train)          # (n_hist, n_trees)
    query_leaves = rf.apply(X_query)          # (1,      n_trees)
    proximity    = (hist_leaves == query_leaves).mean(axis=1)  # (n_hist,)

    # --- top k by proximity ---
    k = min(k, len(hist_clean))
    top_idx  = np.argsort(proximity)[::-1][:k]
    neighbours = hist_clean.iloc[top_idx].copy()
    neighbours.insert(0, 'rf_proximity', proximity[top_idx].round(4))
    neighbours = neighbours.sort_values('rf_proximity', ascending=False).reset_index(drop=True)

    # --- remove any row from the query date before prepending query row ---
    neighbours = neighbours[neighbours['dt'] != date].sort_values('rf_proximity',ascending=False)
    # neighbours = neighbours.sort_values('SHub_rt_slack', ascending=False).groupby('dt').head(3).sort_values('SHub_rt_slack', ascending=False)
    # --- prepend query row ---
    q = query_row.copy()
    q.insert(0, 'rf_proximity', 1.0)
    result = pd.concat([q, neighbours], ignore_index=True)
    return result

In [8]:
dt_hr_list = [(bid_dt, hr) for hr in range(1, 25)]

all_results = {}
avg_rt_slack_list = []
dangerous_hours = []
avg_da_slack_list=[]

for dt, hr in dt_hr_list:
    print(f'\n=== {dt} hr {hr} ===')
    result = find_similar_hours(dt, hr, k=20)
    all_results[(dt, hr)] = result
    display(result[:5])

    neighbours = result[result['dt'] != dt]
    avg_slack = neighbours['SHub_rt_slack'].mean()
    avg_rt_slack_list.append({'dt': dt, 'hr': hr, 'avg_rt_slack': round(avg_slack, 2)})
    avg_slack = neighbours['SHub_da_slack'].mean()
    avg_da_slack_list.append({'dt': dt, 'hr': hr, 'avg_da_slack': round(avg_slack, 2)})
    

    if (neighbours['SHub_rt_slack'] > 150).any():
        dangerous_hours.append({'dt': dt, 'hr': hr, 'avg_rt_slack': round(avg_slack, 2)})

print('\n=== Avg RT Slack by Hour ===')
display(pd.DataFrame(avg_rt_slack_list))
print('\n=== Avg DA Slack by Hour ===')
display(pd.DataFrame(avg_da_slack_list))

print('\n=== Dangerous Hours (similar dates with rt_slack > 150) ===')
display(pd.DataFrame(dangerous_hours) if dangerous_hours else 'None')

=== 2026-06-05 hr 1 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_103950/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-05,1,23842.2,35797.0,15193.1,74.0,NaN,243.4,-1329.0,186.5,-3259.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-05,1,23842.20,35797.0,15193.1,74.0,NaN,243.40,-1329.0,186.50,-3259.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.075,2024-07-28,1,23908.07,34806.0,10323.0,75.5,1.99,389.84,-2156.0,657.86,-3481.0,8.9916,4.9176,96.712000,20.030640,-27.202406,-76.587555
2,0.075,2024-06-02,22,23247.69,34324.0,17355.9,77.5,1.77,-170.83,-1156.0,-652.53,-2244.0,20.8818,10.9252,113.208000,1521.720514,856.501306,362.806360
3,0.070,2024-07-28,2,24197.19,33374.0,10323.0,74.5,1.99,289.12,-1432.0,678.96,-3588.0,5.9384,3.9635,109.713000,-209.974182,-343.135688,-38.759386
4,0.065,2024-07-29,2,24565.08,35780.0,10259.0,80.0,1.99,-111.36,-1469.0,106.20,-3171.0,8.6045,7.4053,101.070002,2376.590667,2293.171551,-0.846813

=== 2026-06-05 hr 2 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_103950/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-05,2,23637.9,34408.0,15195.1,74.0,NaN,-204.3,-1389.0,39.1,-2718.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-05,2,23637.90,34408.0,15195.1,74.0,NaN,-204.30,-1389.0,39.10,-2718.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.185,2024-06-02,22,23247.69,34324.0,17355.9,77.5,1.77,-170.83,-1156.0,-652.53,-2244.0,20.8818,10.9252,113.208,1521.720514,856.501306,362.806360
2,0.075,2024-06-02,23,23347.12,32644.0,17355.9,76.5,1.77,99.43,-1680.0,-71.40,-2836.0,15.9145,4.7601,78.346,-40.358512,-64.850546,-154.755464
3,0.060,2024-08-14,2,23205.48,34687.0,8332.5,76.5,2.14,-144.51,-1420.0,-50.89,-2910.0,9.5849,0.0755,66.279,258.003286,369.503596,-192.110060
4,0.055,2024-08-24,2,25088.22,34058.0,9093.7,78.5,1.82,27.35,-1482.0,279.59,-2909.0,8.4887,15.0528,180.796,-4176.842253,-4398.497948,-129.337058

=== 2026-06-05 hr 3 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_103950/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-05,3,23241.4,33484.0,15195.1,73.0,NaN,-396.5,-924.0,-600.8,-2313.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-05,3,23241.40,33484.0,15195.1,73.0,NaN,-396.50,-924.0,-600.80,-2313.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.110,2024-06-02,22,23247.69,34324.0,17355.9,77.5,1.77,-170.83,-1156.0,-652.53,-2244.0,20.8818,10.9252,113.208,1521.720514,856.501306,362.806360
2,0.065,2024-07-13,4,23333.37,33090.0,9579.0,77.0,2.15,-822.52,-920.0,-1281.61,-2214.0,6.9798,-1.4326,126.279,-2749.435154,-3266.257012,349.315564
3,0.060,2024-06-02,21,23418.52,35480.0,17235.9,81.0,1.77,-481.70,-1088.0,-640.21,-2071.0,25.1112,14.5383,135.721,2322.447028,1723.115212,274.394088
4,0.050,2024-08-14,3,22967.51,33711.0,8332.5,76.5,2.14,-237.97,-976.0,-382.48,-2396.0,6.0352,-4.7444,56.146,-383.276315,-162.827800,-287.572004

=== 2026-06-05 hr 4 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_103950/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-05,4,22878.7,32926.0,15197.7,72.0,NaN,-362.7,-558.0,-759.2,-1482.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-05,4,22878.70,32926.0,15197.7,72.0,NaN,-362.70,-558.0,-759.20,-1482.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.070,2024-07-28,5,23711.92,31034.0,10539.0,72.0,1.99,-377.35,-524.0,-584.17,-1291.0,2.9954,2.2733,103.258001,-448.717761,-492.664062,-118.041809
2,0.045,2024-04-30,21,21447.62,33063.0,25282.0,74.5,1.55,-251.26,-555.0,-631.57,-1232.0,29.3054,21.4776,202.103999,3430.428156,4694.438614,-1560.458518
3,0.040,2024-08-24,4,24419.82,32336.0,9093.7,77.0,1.82,-422.12,-708.0,-668.40,-1722.0,4.3021,2.6016,169.393000,-598.958275,-422.613249,-334.835187
4,0.040,2024-08-14,4,22436.67,33015.0,8332.5,76.0,2.14,-530.84,-696.0,-768.81,-1672.0,4.3414,-0.4849,33.400000,784.030015,837.720448,-91.003993

=== 2026-06-05 hr 5 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_103950/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-05,5,22349.5,32820.0,15197.1,72.0,NaN,-529.2,-106.0,-891.9,-664.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-05,5,22349.50,32820.0,15197.1,72.0,NaN,-529.20,-106.0,-891.90,-664.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.080,2024-04-16,21,22730.57,32522.0,28834.2,73.5,1.36,-894.59,-260.0,-1630.40,-733.0,32.5289,40.8944,151.728000,1827.535524,1709.283935,-185.825732
2,0.065,2024-08-24,6,23336.52,31920.0,10638.2,76.5,1.82,-592.47,-24.0,-1083.30,-416.0,6.7522,6.1314,101.708000,-749.799330,-712.148324,-145.840158
3,0.050,2024-04-16,22,22084.99,31462.0,28834.2,70.0,1.36,-645.58,-1060.0,-1540.17,-1320.0,22.6781,172.9243,137.047000,5474.022897,-1046.576958,6394.340755
4,0.040,2024-07-28,7,22472.41,30594.0,10539.0,72.0,1.99,-722.29,-143.0,-1239.51,-440.0,4.1718,2.1107,81.151001,-376.570047,-496.825089,-8.343750

=== 2026-06-05 hr 6 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_103950/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-05,6,21642.0,33415.0,15197.8,72.0,NaN,-707.5,595.0,-1236.7,489.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-05,6,21642.00,33415.0,15197.8,72.0,NaN,-707.50,595.0,-1236.70,489.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.075,2024-07-28,8,21592.81,31243.0,10539.0,71.5,1.99,-879.60,649.0,-1601.89,506.0,9.6307,6.0147,112.466,217.274098,-70.925457,104.788194
2,0.055,2024-08-24,8,22262.21,32583.0,10568.2,76.0,1.82,-591.94,491.0,-1074.31,663.0,7.2557,6.0082,115.753,-422.606356,-464.575673,-230.737002
3,0.040,2024-08-14,6,21126.82,33280.0,9698.3,74.5,2.14,-595.23,485.0,-1309.85,265.0,8.5042,5.8938,35.431,-381.658720,-338.044131,-83.540510
4,0.040,2024-07-29,6,22160.43,34105.0,9073.0,77.0,1.99,-708.06,378.0,-1354.44,161.0,10.2357,15.6164,50.723,837.198408,825.765448,-16.777438

=== 2026-06-05 hr 7 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_103950/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-05,7,20709.0,34540.0,15193.1,72.0,NaN,-933.1,1125.0,-1640.6,1720.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-05,7,20709.00,34540.0,15193.1,72.000000,NaN,-933.10,1125.0,-1640.60,1720.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.075,2024-07-28,9,20874.44,33054.0,10539.0,73.000000,1.99,-718.37,1811.0,-1597.97,2460.0,15.3481,9.5559,93.068,417.850922,110.143254,158.856044
2,0.075,2024-07-29,7,21381.13,35168.0,8628.0,76.500000,1.99,-779.30,1063.0,-1487.36,1441.0,12.0410,14.2086,42.899,994.934485,964.697363,7.390105
3,0.075,2024-03-26,8,20706.90,33988.0,22143.6,32.000000,1.46,-1001.06,1496.0,-1677.29,3608.0,40.8138,194.0007,80.383,-1548.661361,-8930.308868,7753.578152
4,0.070,2024-03-26,9,19709.67,34204.0,22443.6,32.333333,1.46,-997.23,216.0,-1998.29,1712.0,50.2313,20.6898,54.865,840.119536,1545.551982,-768.819930

=== 2026-06-05 hr 8 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_103950/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-05,8,19509.3,35895.0,15441.3,70.0,NaN,-1199.7,1355.0,-2132.7,2480.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-05,8,19509.30,35895.0,15441.3,70.000000,NaN,-1199.70,1355.0,-2132.70,2480.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.110,2024-07-29,8,20262.60,36637.0,8673.0,75.500000,1.99,-1118.53,1469.0,-1897.83,2532.0,16.0313,14.5200,28.933,-1708.731993,-1713.315501,-23.254568
2,0.065,2024-08-14,8,19529.63,35476.0,9698.3,74.000000,2.14,-891.15,1226.0,-1597.19,2196.0,15.8933,0.1964,76.579,448.654177,-97.539410,471.297386
3,0.065,2024-03-26,8,20706.90,33988.0,22143.6,32.000000,1.46,-1001.06,1496.0,-1677.29,3608.0,40.8138,194.0007,80.383,-1548.661361,-8930.308868,7753.578152
4,0.060,2024-03-26,9,19709.67,34204.0,22443.6,32.333333,1.46,-997.23,216.0,-1998.29,1712.0,50.2313,20.6898,54.865,840.119536,1545.551982,-768.819930

=== 2026-06-05 hr 9 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_103950/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-05,9,18192.7,37258.0,15505.3,73.0,NaN,-1316.6,1363.0,-2516.3,2718.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-05,9,18192.70,37258.0,15505.3,73.0,NaN,-1316.60,1363.0,-2516.30,2718.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.070,2024-08-14,9,18386.12,37112.0,8997.3,75.5,2.14,-1143.51,1636.0,-2034.66,2862.0,19.7888,4.1957,105.388,1499.496242,351.249431,1052.919125
2,0.040,2024-09-19,9,17639.13,35077.0,16232.3,74.0,2.33,-1396.91,985.0,-2413.57,2018.0,21.9458,20.4653,42.117,272.340867,264.072884,-124.087241
3,0.035,2024-09-18,10,18469.70,35266.0,16299.5,75.0,2.33,-337.74,1333.0,-1082.05,2230.0,21.6358,19.5420,41.623,246.238809,217.936668,-47.570405
4,0.035,2024-03-01,8,18256.30,33731.0,14256.9,36.5,1.66,-1053.53,1189.0,-2041.47,3087.0,21.6179,15.0075,136.673,2279.437630,1985.642945,151.432407

=== 2026-06-05 hr 10 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_103950/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-05,10,17162.5,38874.0,15502.3,74.0,NaN,-1030.2,1616.0,-2346.8,2979.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-05,10,17162.50,38874.0,15502.3,74.0,NaN,-1030.20,1616.0,-2346.80,2979.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.055,2024-09-19,11,15328.33,38657.0,16092.3,79.5,2.33,-848.07,2054.0,-2310.80,3580.0,29.1460,30.0429,73.002000,-9.101037,-121.974882,-39.851950
2,0.045,2024-09-18,12,17799.98,38870.0,16001.5,81.0,2.33,-695.02,1826.0,-669.72,3604.0,33.0924,35.9610,71.649000,157.201617,202.736695,-161.881621
3,0.035,2024-08-22,13,17153.27,40296.0,9110.6,77.0,2.12,-958.60,1788.0,-1709.23,3600.0,26.7644,20.3831,107.487000,-1048.104032,-888.713251,-258.187446
4,0.030,2020-06-29,11,14036.64,38109.0,12207.1,79.5,1.40,-86.16,1950.0,-533.85,3899.0,18.7869,14.9713,136.546001,-339.695378,51.154934,-430.813431

=== 2026-06-05 hr 11 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_103950/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-05,11,16132.3,40701.0,15502.1,77.5,NaN,-1030.2,1827.0,-2060.4,3443.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-05,11,16132.30,40701.0,15502.1,77.500000,NaN,-1030.20,1827.0,-2060.40,3443.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.085,2024-09-19,12,14213.52,40898.0,16092.3,82.500000,2.33,-1114.81,2241.0,-1962.88,4295.0,41.6057,46.9705,39.437000,740.054847,499.445601,84.442026
2,0.060,2024-09-19,11,15328.33,38657.0,16092.3,79.500000,2.33,-848.07,2054.0,-2310.80,3580.0,29.1460,30.0429,73.002000,-9.101037,-121.974882,-39.851950
3,0.055,2020-06-29,13,14602.47,41598.0,12192.1,82.833333,1.40,131.36,1676.0,565.83,3489.0,22.1771,18.3351,176.058001,-770.453649,-285.414281,-549.819153
4,0.045,2020-06-29,11,14036.64,38109.0,12207.1,79.500000,1.40,-86.16,1950.0,-533.85,3899.0,18.7869,14.9713,136.546001,-339.695378,51.154934,-430.813431

=== 2026-06-05 hr 12 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_103950/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-05,12,14906.6,42422.0,15483.3,80.0,NaN,-1225.7,1721.0,-2255.9,3548.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-05,12,14906.60,42422.0,15483.3,80.000000,NaN,-1225.70,1721.0,-2255.90,3548.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.070,2020-06-29,14,14895.66,43191.0,12192.1,84.500000,1.40,293.19,1593.0,424.55,3269.0,24.7701,16.5931,144.205001,-957.366555,-139.653833,-867.169818
2,0.065,2020-06-29,13,14602.47,41598.0,12192.1,82.833333,1.40,131.36,1676.0,565.83,3489.0,22.1771,18.3351,176.058001,-770.453649,-285.414281,-549.819153
3,0.065,2024-09-19,12,14213.52,40898.0,16092.3,82.500000,2.33,-1114.81,2241.0,-1962.88,4295.0,41.6057,46.9705,39.437000,740.054847,499.445601,84.442026
4,0.050,2024-08-22,14,16411.25,42050.0,9110.6,80.500000,2.12,-742.02,1754.0,-1700.62,3542.0,27.8273,23.6574,108.485000,-613.140173,-369.650407,-346.731278

=== 2026-06-05 hr 13 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_103950/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-05,13,14019.3,44090.0,15727.9,82.0,NaN,-887.3,1668.0,-2113.0,3389.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-05,13,14019.30,44090.0,15727.9,82.000000,NaN,-887.30,1668.0,-2113.00,3389.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.075,2020-06-29,14,14895.66,43191.0,12192.1,84.500000,1.40,293.19,1593.0,424.55,3269.0,24.7701,16.5931,144.205001,-957.366555,-139.653833,-867.169818
2,0.060,2020-06-29,13,14602.47,41598.0,12192.1,82.833333,1.40,131.36,1676.0,565.83,3489.0,22.1771,18.3351,176.058001,-770.453649,-285.414281,-549.819153
3,0.045,2024-09-19,14,11886.62,45138.0,16107.3,89.500000,2.33,-978.49,2064.0,-2326.90,4240.0,69.4872,89.2851,54.033000,206.426710,-168.464269,179.238826
4,0.040,2024-09-19,13,12865.11,43074.0,16092.3,86.500000,2.33,-1348.41,2176.0,-2463.22,4417.0,55.5438,88.0590,44.174000,-364.584894,-420.282706,-57.340948

=== 2026-06-05 hr 14 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_103950/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-05,14,13859.4,45674.0,15727.9,84.0,NaN,-159.9,1584.0,-1047.2,3252.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-05,14,13859.40,45674.0,15727.9,84.000000,NaN,-159.90,1584.0,-1047.20,3252.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.090,2020-06-29,14,14895.66,43191.0,12192.1,84.500000,1.40,293.19,1593.0,424.55,3269.0,24.7701,16.5931,144.205001,-957.366555,-139.653833,-867.169818
2,0.040,2020-06-29,13,14602.47,41598.0,12192.1,82.833333,1.40,131.36,1676.0,565.83,3489.0,22.1771,18.3351,176.058001,-770.453649,-285.414281,-549.819153
3,0.040,2024-09-19,14,11886.62,45138.0,16107.3,89.500000,2.33,-978.49,2064.0,-2326.90,4240.0,69.4872,89.2851,54.033000,206.426710,-168.464269,179.238826
4,0.035,2020-06-29,18,15707.96,45699.0,12177.1,88.333333,1.40,53.67,-200.0,184.43,429.0,26.7113,18.6166,460.385000,-1411.092498,1964.246379,-3498.534541

=== 2026-06-05 hr 15 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_103950/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-05,15,14204.1,46930.0,15732.4,86.5,NaN,344.7,1256.0,184.8,2840.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-05,15,14204.10,46930.0,15732.4,86.500000,NaN,344.70,1256.0,184.80,2840.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.140,2020-06-29,15,15270.14,44377.0,12177.1,86.000000,1.40,374.48,1186.0,667.67,2779.0,26.9279,24.9918,144.598001,-631.399460,-479.908777,-221.955014
2,0.065,2020-06-29,16,15523.53,45270.0,12177.1,87.500000,1.40,253.39,893.0,627.87,2079.0,29.8974,24.5909,350.439000,-2542.616521,-963.072578,-1631.577601
3,0.055,2020-06-29,17,15654.29,45899.0,12177.1,89.000000,1.40,130.76,629.0,384.15,1522.0,29.3383,18.6100,413.604000,-2128.930823,1799.785158,-4023.623622
4,0.045,2020-06-30,15,12757.36,46486.0,10749.9,90.166667,1.66,280.69,1082.0,314.76,2788.0,29.1036,22.5019,235.034001,-1780.278391,-450.001901,-1448.637697

=== 2026-06-05 hr 16 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_103950/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-05,16,14685.1,47736.0,15669.9,86.5,NaN,481.0,806.0,825.7,2062.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-05,16,14685.10,47736.0,15669.9,86.500000,NaN,481.00,806.0,825.70,2062.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.105,2020-06-29,16,15523.53,45270.0,12177.1,87.500000,1.40,253.39,893.0,627.87,2079.0,29.8974,24.5909,350.439000,-2542.616521,-963.072578,-1631.577601
2,0.050,2020-06-29,15,15270.14,44377.0,12177.1,86.000000,1.40,374.48,1186.0,667.67,2779.0,26.9279,24.9918,144.598001,-631.399460,-479.908777,-221.955014
3,0.050,2020-06-29,17,15654.29,45899.0,12177.1,89.000000,1.40,130.76,629.0,384.15,1522.0,29.3383,18.6100,413.604000,-2128.930823,1799.785158,-4023.623622
4,0.050,2020-06-30,16,13072.42,47432.0,10761.9,91.833333,1.66,315.06,946.0,595.75,2028.0,32.5554,20.9041,186.208001,-852.454879,961.292694,-1949.643559

=== 2026-06-05 hr 17 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_103950/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-05,17,15281.7,48140.0,15672.1,86.5,NaN,596.6,404.0,1077.6,1210.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-05,17,15281.70,48140.0,15672.1,86.500000,NaN,596.60,404.0,1077.60,1210.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.045,2020-09-07,17,15423.56,41636.0,15818.1,87.000000,1.90,664.65,561.0,1576.06,1671.0,27.6527,27.9903,103.310001,1213.983468,1188.937375,-100.421688
2,0.040,2024-09-20,17,12776.77,48489.0,16971.6,94.500000,2.21,1197.98,380.0,2671.23,1350.0,113.5029,124.1824,85.616001,1427.682322,1507.960329,-537.683885
3,0.040,2024-09-20,18,13354.15,47878.0,16971.6,93.500000,2.21,577.38,-611.0,1775.36,-231.0,104.3930,139.6214,85.682000,2473.411209,4230.342609,-2286.026425
4,0.040,2020-09-07,18,15941.72,41655.0,15818.1,86.166667,1.90,518.16,19.0,1182.81,580.0,27.0898,29.6984,106.914000,973.110005,983.132333,-116.248614

=== 2026-06-05 hr 18 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_103950/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-05,18,15985.4,47996.0,15627.9,87.5,NaN,703.7,-144.0,1300.3,260.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-05,18,15985.40,47996.0,15627.9,87.500000,NaN,703.70,-144.0,1300.30,260.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.055,2020-09-07,18,15941.72,41655.0,15818.1,86.166667,1.90,518.16,19.0,1182.81,580.0,27.0898,29.6984,106.914000,973.110005,983.132333,-116.248614
2,0.055,2024-09-20,18,13354.15,47878.0,16971.6,93.500000,2.21,577.38,-611.0,1775.36,-231.0,104.3930,139.6214,85.682000,2473.411209,4230.342609,-2286.026425
3,0.035,2020-09-07,19,16363.91,40666.0,15806.1,85.333333,1.90,422.19,-989.0,940.35,-970.0,21.3842,29.0427,171.093001,2312.655619,1467.788810,725.944360
4,0.030,2020-06-28,19,16248.10,42569.0,11982.3,87.666667,1.40,89.60,-592.0,303.71,-418.0,22.4945,15.8077,228.595001,-221.864877,1084.375600,-1393.646793

=== 2026-06-05 hr 19 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_103950/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-05,19,17000.3,47150.0,15262.5,85.5,NaN,1014.9,-846.0,1718.6,-990.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-05,19,17000.30,47150.0,15262.5,85.500000,NaN,1014.90,-846.0,1718.60,-990.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.080,2024-07-27,19,17361.78,44149.0,10444.0,85.500000,1.99,969.82,-621.0,1753.41,-663.0,30.9147,45.7805,195.114000,4148.750623,3655.312503,162.379225
2,0.070,2020-09-07,19,16363.91,40666.0,15806.1,85.333333,1.90,422.19,-989.0,940.35,-970.0,21.3842,29.0427,171.093001,2312.655619,1467.788810,725.944360
3,0.035,2024-09-16,19,18133.15,42247.0,16885.9,84.500000,2.21,864.14,-809.0,2082.47,-1080.0,44.4120,111.6393,217.353000,6251.888686,11639.773445,-6152.360313
4,0.035,2020-06-28,19,16248.10,42569.0,11982.3,87.666667,1.40,89.60,-592.0,303.71,-418.0,22.4945,15.8077,228.595001,-221.864877,1084.375600,-1393.646793

=== 2026-06-05 hr 20 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_103950/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-05,20,18197.2,45734.0,14998.7,85.0,NaN,1196.9,-1416.0,2211.8,-2262.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-05,20,18197.20,45734.0,14998.7,85.0,NaN,1196.90,-1416.0,2211.80,-2262.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.080,2024-08-23,20,18839.30,45578.0,9925.1,88.5,1.91,1391.80,-1415.0,3036.40,-2237.0,34.8340,22.8764,127.987,1769.775777,2541.468490,-830.222609
2,0.045,2024-07-26,20,14869.25,45041.0,9908.1,88.0,2.00,1127.27,-1439.0,2062.77,-2342.0,29.9815,34.5285,155.610,1275.559607,643.806448,462.496372
3,0.045,2020-09-05,20,10633.78,39118.0,16153.6,85.0,1.90,1268.27,-1571.0,2063.07,-2352.0,22.5736,61.8642,127.091,-154.726609,71.798504,-370.125619
4,0.040,2024-07-27,20,18400.78,42946.0,10444.0,84.5,1.99,1039.00,-1203.0,2008.82,-1824.0,26.7076,21.0634,211.558,3242.799405,3248.967277,-301.580183

=== 2026-06-05 hr 21 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_103950/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-05,21,19626.6,44214.0,15000.1,83.0,NaN,1429.5,-1520.0,2626.4,-2936.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.00,2026-06-05,21,19626.60,44214.0,15000.1,83.0,NaN,1429.50,-1520.0,2626.40,-2936.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.09,2024-08-23,21,20368.05,43963.0,9794.1,86.0,1.91,1528.75,-1615.0,2920.55,-3030.0,36.4488,20.4474,158.945000,2226.933281,2257.925764,-77.121581
2,0.08,2024-07-27,21,19771.84,41409.0,10444.0,82.5,1.99,1371.06,-1537.0,2410.06,-2740.0,22.7734,19.7125,220.324000,2075.487961,1918.157821,-147.612922
3,0.05,2024-08-28,22,19640.59,44180.0,10267.5,82.5,1.91,2119.80,-1887.0,3992.41,-3434.0,25.1602,10.2547,206.160000,1725.574109,445.618956,985.072122
4,0.05,2024-09-11,20,17021.36,40406.0,13635.8,83.0,2.12,1468.39,-1276.0,2502.57,-2034.0,25.2057,50.8105,233.379999,-673.393417,-1380.796048,452.619225

=== 2026-06-05 hr 22 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_103950/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-05,22,21054.1,42829.0,15000.4,81.0,NaN,1427.4,-1385.0,2856.9,-2905.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-05,22,21054.10,42829.0,15000.4,81.0,NaN,1427.40,-1385.0,2856.90,-2905.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.075,2024-08-22,21,21058.85,41955.0,9110.6,80.5,2.12,1136.35,-1445.0,1895.29,-2775.0,28.8750,22.9688,206.149,402.583666,-720.605755,821.206817
2,0.065,2024-06-12,22,20576.97,40024.0,13797.7,81.0,2.71,1714.79,-1502.0,2884.19,-3381.0,24.1143,22.4778,225.217,6132.886131,6365.426237,-318.274225
3,0.055,2024-07-27,21,19771.84,41409.0,10444.0,82.5,1.99,1371.06,-1537.0,2410.06,-2740.0,22.7734,19.7125,220.324,2075.487961,1918.157821,-147.612922
4,0.045,2025-09-11,21,22344.39,42534.0,10422.1,83.0,2.89,2036.14,-1360.0,3424.87,-2826.0,26.6048,27.7924,157.439,1738.791977,1719.435295,-137.274161

=== 2026-06-05 hr 23 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_103950/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-05,23,21767.9,40912.0,14996.1,79.0,NaN,713.9,-1917.0,2141.3,-3302.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-05,23,21767.90,40912.0,14996.1,79.0,NaN,713.90,-1917.0,2141.30,-3302.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.085,2024-09-17,22,24030.46,38550.0,16828.1,78.5,2.20,843.16,-1826.0,1474.06,-3041.0,29.6789,63.0937,93.666,-584.011665,-1034.066089,371.144231
2,0.060,2024-09-18,22,23179.93,39747.0,16918.0,81.0,2.33,1099.80,-1945.0,1832.01,-3139.0,38.9015,23.8067,62.033,127.680830,167.146229,-114.118446
3,0.045,2024-09-11,22,20477.01,37349.0,13470.2,76.0,2.12,1476.35,-1834.0,3455.65,-3057.0,13.1783,42.8394,127.040,-8934.230240,-6951.935834,-2093.386920
4,0.040,2024-08-28,22,19640.59,44180.0,10267.5,82.5,1.91,2119.80,-1887.0,3992.41,-3434.0,25.1602,10.2547,206.160,1725.574109,445.618956,985.072122

=== 2026-06-05 hr 24 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_103950/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-06-05,24,22090.1,38707.0,15253.1,79.0,NaN,322.2,-2205.0,1036.1,-4122.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-06-05,24,22090.10,38707.0,15253.1,79.0,NaN,322.20,-2205.0,1036.10,-4122.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.095,2024-09-17,22,24030.46,38550.0,16828.1,78.5,2.20,843.16,-1826.0,1474.06,-3041.0,29.6789,63.0937,93.666,-584.011665,-1034.066089,371.144231
2,0.075,2024-08-28,24,21159.79,38751.0,10267.5,80.5,1.91,249.46,-2805.0,1519.20,-5429.0,13.6953,-1.9788,154.479,4323.313608,2329.629209,1776.040867
3,0.075,2024-09-20,23,18288.71,38791.0,17286.7,81.5,2.21,1163.85,-2124.0,2311.17,-4051.0,31.7475,46.9883,73.314,-1578.052084,-1223.949283,-574.005874
4,0.070,2024-09-17,23,24260.57,36317.0,17126.1,77.5,2.20,230.11,-2233.0,1073.27,-4059.0,17.8351,25.1067,40.102,228.427155,182.884145,16.480555

=== Avg RT Slack by Hour ===

            dt  hr  avg_rt_slack
0   2026-06-05   1          9.66
1   2026-06-05   2          8.04
2   2026-06-05   3         12.15
3   2026-06-05   4         23.49
4   2026-06-05   5         25.51
5   2026-06-05   6         18.79
6   2026-06-05   7         32.61
7   2026-06-05   8         21.98
8   2026-06-05   9         32.16
9   2026-06-05  10         26.75
10  2026-06-05  11         25.13
11  2026-06-05  12         28.41
12  2026-06-05  13         59.97
13  2026-06-05  14         50.75
14  2026-06-05  15         57.92
15  2026-06-05  16         56.54
16  2026-06-05  17         63.63
17  2026-06-05  18         50.49
18  2026-06-05  19         53.55
19  2026-06-05  20         34.36
20  2026-06-05  21         36.43
21  2026-06-05  22         35.31
22  2026-06-05  23         31.23
23  2026-06-05  24         27.26

=== Avg DA Slack by Hour ===

            dt  hr  avg_da_slack
0   2026-06-05   1         13.29
1   2026-06-05   2         13.53
2   2026-06-05   3         10.99
3   2026-06-05   4         15.39
4   2026-06-05   5         14.62
5   2026-06-05   6         18.20
6   2026-06-05   7         21.69
7   2026-06-05   8         21.30
8   2026-06-05   9         23.85
9   2026-06-05  10         24.35
10  2026-06-05  11         25.80
11  2026-06-05  12         26.68
12  2026-06-05  13         49.20
13  2026-06-05  14         37.11
14  2026-06-05  15         39.87
15  2026-06-05  16         46.17
16  2026-06-05  17         57.58
17  2026-06-05  18         46.18
18  2026-06-05  19         37.51
19  2026-06-05  20         28.56
20  2026-06-05  21         33.46
21  2026-06-05  22         24.81
22  2026-06-05  23         24.26
23  2026-06-05  24         23.43

=== Dangerous Hours (similar dates with rt_slack > 150) ===

            dt  hr  avg_rt_slack
0   2026-06-05   3         10.99
1   2026-06-05   4         15.39
2   2026-06-05   5         14.62
3   2026-06-05   6         18.20
4   2026-06-05   7         21.69
5   2026-06-05   8         21.30
6   2026-06-05   9         23.85
7   2026-06-05  13         49.20
8   2026-06-05  14         37.11
9   2026-06-05  15         39.87
10  2026-06-05  16         46.17
11  2026-06-05  17         57.58
12  2026-06-05  19         37.51