In [1]:
# Get daily constraint ranked by the abs RT - DA 
from functions import (
    get_recent_constraint_mvalue,
    get_node_dfax_from_constraint_num,
    get_hourly_mvalue_for_constraint_num,
    get_constraint_node_prices_from_constraint_num,
    get_constraints_node_price,
    get_metrics_for_nodes,
    get_recent_direction_accuracy,
    get_weather_date,
    predict_tomorrow_percentile,
    analyze_constraint_by_zone,
    plot_constraint_seasonality,
    plot_recent_hourly_distribution,
)
import pandas as pd

In [2]:
now = pd.Timestamp.now(tz='US/Central')
days_ahead = 2 if now.hour >= 10 else 1
bid_dt = (now + pd.Timedelta(days=days_ahead)).strftime('%Y-%m-%d')
print(bid_dt)

2026-06-05

In [4]:
dt = '2026-06-04'
mvalue= get_recent_constraint_mvalue(dt, dt)
dfax= get_node_dfax_from_constraint_num(mvalue)
hourly_mvalue = get_hourly_mvalue_for_constraint_num(mvalue)
fundamentals = get_weather_date(hourly_mvalue, dt)

start_dt: 2026-06-04, end_dt: 2026-06-04, Market: SPP
Fetching RT mvalues...
Fetching DA mvalues...
RT constraints: 0, DA constraints: 73
Fetching constraint details...

   oops_constraint_num  rt_total   da_total      rt_da  abs_rt_da_diff            monitored                       contingency
0               680789         0 -2885.2280  2885.2280       2885.2280      lnweav-tallgras               wr:bentmidi:138:1:5
1               791481         0 -2823.2031  2823.2031       2823.2031  lnosage_og-webbtap4  grdaokge:clevlnd7whtetail:345:1:
2               776592         0 -2462.4758  2462.4758       2462.4758    xfmrduncan-duncan  wfec:anadarkofletch3comanch2:138
3               441249         0 -1922.2396  1922.2396       1922.2396     lnaur1241-rdspg5   cswsspa:eurekaspeurk_spabeaver1
4               435448         0 -1824.9752  1824.9752       1824.9752    lnnwtexar-nnewbos        csws:welshnwtexar:345:1:11
5               794129         0 -1623.9426  1623.9426       1623.9426          lnmidi-butl              wr:butlweav:138:2:12
6               549568         0 -1560.6434  1560.6434       1560.6434    xfmrsub975-sub975      oppd:sub1280sub1263:161:1:10
7               878969         0 -1330.6068  1330.6068       1330.6068    lnlenexa-shwnmsn5         kcpl:pflumm5craig:161:1:7

RT active constraint-days: 0
DA active constraint-days: 805
   oops_constraint_num          dt  hr  rt_mvalue  da_mvalue     rt_da
0               435448  2024-06-05  23          0    -3.0569    3.0569
1               435448  2024-06-05  24          0   -38.1945   38.1945
2               435448  2024-06-06   1          0  -174.6787  174.6787
3               435448  2024-06-06   2          0  -193.7479  193.7479
4               435448  2024-06-06   3          0  -210.6007  210.6007

Merged hourly rows: 7440

      oops_constraint_num          dt  hr  rt_mvalue  da_mvalue     rt_da          monitored                 contingency
0                  435448  2024-06-05  23          0    -3.0569    3.0569  lnnwtexar-nnewbos  csws:welshnwtexar:345:1:11
1                  435448  2024-06-05  24          0   -38.1945   38.1945  lnnwtexar-nnewbos  csws:welshnwtexar:345:1:11
2                  435448  2024-06-06   1          0  -174.6787  174.6787  lnnwtexar-nnewbos  csws:welshnwtexar:345:1:11
3                  435448  2024-06-06   2          0  -193.7479  193.7479  lnnwtexar-nnewbos  csws:welshnwtexar:345:1:11
4                  435448  2024-06-06   3          0  -210.6007  210.6007  lnnwtexar-nnewbos  csws:welshnwtexar:345:1:11
...                   ...         ...  ..        ...        ...       ...                ...                         ...
7435               878969  2026-05-29  20          0   -45.9775   45.9775  lnlenexa-shwnmsn5   kcpl:pflumm5craig:161:1:7
7436               878969  2026-05-29  21          0   -69.8495   69.8495  lnlenexa-shwnmsn5   kcpl:pflumm5craig:161:1:7
7437               878969  2026-05-29  22          0   -25.5453   25.5453  lnlenexa-shwnmsn5   kcpl:pflumm5craig:161:1:7
7438               878969  2026-05-31  23          0   -10.8162   10.8162  lnlenexa-shwnmsn5   kcpl:pflumm5craig:161:1:7
7439               878969  2026-05-31  24          0   -48.7183   48.7183  lnlenexa-shwnmsn5   kcpl:pflumm5craig:161:1:7

[7440 rows x 8 columns]

Reserve zones available: [1, 2, 3, 4, 5, 21]
Wind cols: ['rz1_spp_res_zonal_wind_forecast_f', 'rz2_spp_res_zonal_wind_forecast_f', 'rz3_spp_res_zonal_wind_forecast_f', 'rz4_spp_res_zonal_wind_forecast_f', 'rz5_spp_res_zonal_wind_forecast_f', 'rz21_spp_res_zonal_wind_forecast_f']
Load cols: ['rz1_spp_res_zonal_load_forecast_f', 'rz2_spp_res_zonal_load_forecast_f', 'rz3_spp_res_zonal_load_forecast_f', 'rz4_spp_res_zonal_load_forecast_f', 'rz5_spp_res_zonal_load_forecast_f', 'rz21_spp_res_zonal_load_forecast_f']

In [ ]:
from IPython.display import display, HTML
row_counts = hourly_mvalue.groupby('monitored').size().sort_values()
print(row_counts.to_string())

for name in row_counts.index:
    display(HTML(f'''
    <hr style="border: 3px solid black; margin: 30px 0;">
    <h1 style="background:#2c3e50; color:white; padding:12px 20px; border-radius:6px; font-family:monospace;">
        {name} &nbsp;<span style="font-size:0.6em; color:#aaa;">({row_counts[name]:,} rows)</span>
    </h1>
    <hr style="border: 1px solid #aaa; margin-bottom: 20px;">
    '''))

    analyze_constraint_by_zone(fundamentals, hourly_mvalue, name, 4, 95)
    plot_constraint_seasonality(hourly_mvalue, name)
    plot_recent_hourly_distribution(hourly_mvalue, name, bid_dt, days=10)
    table = get_constraints_node_price(hourly_mvalue, dfax, [name])
    get_metrics_for_nodes(table)

In [ ]:
# name = 'lnraun-tekamho'
# zone= 1
# analyze_constraint_by_zone(fundamentals, hourly_mvalue, name, zone, 90)
# plot_constraint_seasonality(hourly_mvalue, name)
# table = get_constraints_node_price(hourly_mvalue, dfax, [name])
# get_metrics_for_nodes(table)

In [5]:
fundamentals = get_weather_date(hourly_mvalue, bid_dt)

Reserve zones available: [1, 2, 3, 4, 5, 21]
Wind cols: ['rz1_spp_res_zonal_wind_forecast_f', 'rz2_spp_res_zonal_wind_forecast_f', 'rz3_spp_res_zonal_wind_forecast_f', 'rz4_spp_res_zonal_wind_forecast_f', 'rz5_spp_res_zonal_wind_forecast_f', 'rz21_spp_res_zonal_wind_forecast_f']
Load cols: ['rz1_spp_res_zonal_load_forecast_f', 'rz2_spp_res_zonal_load_forecast_f', 'rz3_spp_res_zonal_load_forecast_f', 'rz4_spp_res_zonal_load_forecast_f', 'rz5_spp_res_zonal_load_forecast_f', 'rz21_spp_res_zonal_load_forecast_f']

In [6]:
tomorrow_pct = predict_tomorrow_percentile(fundamentals, bid_dt)

--- Zone 1 ---

    hr  wind_value  wind_pct  load_value  load_pct
0    1       778.0      29.0      4207.6      93.5
1    2       709.5      19.4      4082.9      93.5
2    3       674.7      29.0      4026.8      93.5
3    4       688.4      29.0      3988.6      96.8
4    5       669.3      29.0      3990.6      93.5
5    6       618.6      25.8      4086.0      90.3
6    7       588.6      32.3      4297.0      87.1
7    8       545.8      35.5      4601.9      96.8
8    9       505.3      35.5      4789.0      96.8
9   10       492.2      35.5      4907.9      93.5
10  11       451.3      29.0      5068.0      96.8
11  12       392.8      25.8      5213.4      96.8
12  13       363.1      22.6      5322.2      93.5
13  14       349.3      16.1      5436.7      90.3
14  15       341.4      12.9      5502.2      90.3
15  16       343.1      12.9      5542.5      87.1
16  17       335.1      12.9      5576.4      83.9
17  18       344.3      16.1      5537.1      83.9
18  19       343.9       9.7      5525.4      83.9
19  20       325.1       9.7      5374.6      87.1
20  21       458.4      12.9      5253.0      93.5
21  22       527.4      12.9      4957.5      93.5
22  23       447.4       6.5      4727.9      96.8
23  24       448.9       3.2      4528.8      96.8

--- Zone 2 ---

    hr  wind_value  wind_pct  load_value  load_pct
0    1      5913.3      93.5       684.2      90.3
1    2      5916.4      90.3       661.7      83.9
2    3      5888.8      90.3       653.7      83.9
3    4      5864.7      90.3       646.2      83.9
4    5      5778.6      83.9       648.0      83.9
5    6      5683.3      83.9       676.4      80.6
6    7      5520.1      83.9       715.5      80.6
7    8      5160.7      83.9       725.6      83.9
8    9      4782.4      80.6       754.1     100.0
9   10      4575.4      80.6       800.3     100.0
10  11      4370.5      80.6       838.5      96.8
11  12      4104.9      80.6       857.5      96.8
12  13      3836.2      80.6       881.0      96.8
13  14      3570.6      83.9       892.1      93.5
14  15      3487.3      74.2       913.2      96.8
15  16      3495.6      64.5       914.8      96.8
16  17      3572.6      67.7       920.4      96.8
17  18      3694.0      71.0       916.5      96.8
18  19      3950.5      71.0       906.2      93.5
19  20      4444.8      87.1       891.5     100.0
20  21      4862.4      83.9       867.2     100.0
21  22      5084.9      80.6       820.1      96.8
22  23      5208.8      74.2       796.9     100.0
23  24      5092.7      74.2       753.0     100.0

--- Zone 3 ---

    hr  wind_value  wind_pct  load_value  load_pct
0    1      1551.8      38.7      4225.6      58.1
1    2      1546.0      48.4      4075.8      25.8
2    3      1550.4      54.8      3992.1      16.1
3    4      1502.7      54.8      3936.5       9.7
4    5      1380.6      58.1      3946.7      12.9
5    6      1254.6      58.1      4004.4      19.4
6    7      1158.0      58.1      4095.8      29.0
7    8      1029.4      61.3      4141.2      41.9
8    9       846.0      61.3      4260.9      61.3
9   10       770.5      64.5      4388.6      74.2
10  11       746.7      61.3      4487.2      77.4
11  12       665.6      58.1      4604.1      74.2
12  13       606.3      48.4      4746.0      83.9
13  14       648.8      51.6      4874.1      80.6
14  15       714.4      54.8      5014.7      77.4
15  16       789.5      48.4      5054.2      80.6
16  17       957.4      51.6      5059.2      74.2
17  18      1148.9      58.1      5028.8      71.0
18  19      1258.7      61.3      4953.4      61.3
19  20      1413.2      61.3      4858.9      61.3
20  21      1522.0      64.5      4680.7      58.1
21  22      1505.0      48.4      4582.0      54.8
22  23      1461.7      32.3      4469.1      54.8
23  24      1339.6      25.8      4381.5      67.7

--- Zone 4 ---

    hr  wind_value  wind_pct  load_value  load_pct
0    1     14540.0      90.3     18803.7      77.4
1    2     14389.3      90.3     18132.2      87.1
2    3     14187.0      90.3     17715.4      87.1
3    4     14021.4      93.5     17439.6      87.1
4    5     13764.2      93.5     17591.7      87.1
5    6     13364.1      90.3     17986.6      87.1
6    7     12862.4      87.1     18839.6      87.1
7    8     12454.2      80.6     19767.7      90.3
8    9     12273.2      83.9     20594.1      90.3
9   10     11915.5      80.6     21422.4      90.3
10  11     11196.2      77.4     22465.3      90.3
11  12     10481.7      77.4     23381.2      80.6
12  13      9910.4      74.2     24273.3      74.2
13  14      9533.3      67.7     25071.0      74.2
14  15      9664.1      74.2     25506.3      74.2
15  16     10073.4      74.2     25855.9      71.0
16  17     10536.4      74.2     26609.6      80.6
17  18     11114.0      74.2     26454.8      80.6
18  19     11818.4      77.4     26270.2      87.1
19  20     12228.7      77.4     25320.6      93.5
20  21     12439.4      77.4     24281.2      93.5
21  22     12626.7      77.4     23069.8      90.3
22  23     12672.1      77.4     21835.8      90.3
23  24     12360.4      74.2     20712.0      90.3

--- Zone 5 ---

    hr  wind_value  wind_pct  load_value  load_pct
0    1       937.2      19.4      3730.5      90.3
1    2       859.4      19.4      3609.8      74.2
2    3       781.2       9.7      3555.6      61.3
3    4       724.5       9.7      3558.3      58.1
4    5       673.8       6.5      3568.1      58.1
5    6       628.6       9.7      3603.7      41.9
6    7       552.2      12.9      3703.3      38.7
7    8       452.6       9.7      3878.1      61.3
8    9       395.2       9.7      3980.1      87.1
9   10       320.4       6.5      4055.4      90.3
10  11       287.4       6.5      4136.1     100.0
11  12       337.3       9.7      4191.9     100.0
12  13       362.2       9.7      4221.2      96.8
13  14       327.7       6.5      4241.9      90.3
14  15       350.9       3.2      4275.2      93.5
15  16       383.1       6.5      4273.3      90.3
16  17       386.3       3.2      4249.1      77.4
17  18       366.4       3.2      4218.2      77.4
18  19       328.8       0.0      4220.4      80.6
19  20       344.4       0.0      4173.0      80.6
20  21       443.5       6.5      4140.2      80.6
21  22       599.0       6.5      4050.8      77.4
22  23       811.3       6.5      4015.7     100.0
23  24      1058.9      22.6      3874.6      93.5

--- Zone 21 ---

    hr  wind_value  wind_pct  load_value  load_pct
0    1       740.8      80.6      2710.8      45.2
1    2       754.7      83.9      2567.2      38.7
2    3       764.2      83.9      2482.0      19.4
3    4       768.1      77.4      2403.2       6.5
4    5       758.9      74.2      2364.7       6.5
5    6       754.8      80.6      2392.1       6.5
6    7       731.9      80.6      2461.8       6.5
7    8       690.1      71.0      2550.3      29.0
8    9       628.5      61.3      2639.8      29.0
9   10       567.0      58.1      2688.8      29.0
10  11       514.7      54.8      2703.2      32.3
11  12       434.5      48.4      2760.7      41.9
12  13       338.1      32.3      2804.3      48.4
13  14       245.8      22.6      2868.5      48.4
14  15       183.9      16.1      2919.7      54.8
15  16       150.2       9.7      2973.9      54.8
16  17       152.3       9.7      2987.6      54.8
17  18       176.8      12.9      3046.2      48.4
18  19       226.6      12.9      3116.6      48.4
19  20       302.2      32.3      3146.4      51.6
20  21       421.1      35.5      3125.4      51.6
21  22       575.3      58.1      3081.5      48.4
22  23       674.8      67.7      3026.8      51.6
23  24       722.0      77.4      2893.2      48.4

--- Summary (median pct by zone / peak) ---
1: ow: 14, fw: 29, ol: 93, fl: 93
2: ow: 80, fw: 87, ol: 96, fl: 83
3: ow: 58, fw: 54, ol: 72, fl: 22
4: ow: 77, fw: 90, ol: 88, fl: 87
5: ow: 6, fw: 11, ol: 88, fl: 59
21: ow: 33, fw: 80, ol: 48, fl: 12