In [1]:
# Get daily constraint ranked by the abs RT - DA 
import sys
sys.path.append('/var/www/python/Prod/nighthawk/')

import pandas as pd
from nighthawk.data import Constraint

In [2]:
now = pd.Timestamp.now(tz='US/Central')
days_ahead = 2 if now.hour >= 10 else 1
bid_dt = (now + pd.Timedelta(days=days_ahead)).strftime('%Y-%m-%d')
print(bid_dt)

2026-05-30

# Daily RT DA Spike Analysis

In [3]:
# give a date and returns to me the hourly metrics at that hour, wind/load/temperature/gas/wind ramp/genoutage

In [4]:
from nighthawk.data.pipeline.common_functions.wind import Wind
from nighthawk.data.pipeline.common_functions.load import Load
from nighthawk.data.pipeline.common_functions.gas import Gas
from nighthawk.data.pipeline.common_functions.genoutage import GenOutage
from nighthawk.data.pipeline.common_functions.weather import Weather
from nighthawk.data.network.node import Node

SPP_HUB_NODES = {636:'south_hub'}
SPP_CITIES =[ ('Kansas City', 'MO'), ('Oklahoma City', 'OK')]


def get_hourly_snapshot(date: str, hour: int):
    assert 1 <= hour <= 24, "hour must be between 1 and 24"
    dt      = date
    dt_prev = (pd.Timestamp(dt) - pd.Timedelta(days=1)).strftime('%Y-%m-%d')

    wind_df = Wind('SPP').get_total_wind(dt_prev, dt, var_spec=['f'])
    load_df = Load('SPP').get_total_load(dt_prev, dt, var_spec=['f'])

    gas_raw = Gas('SPP').get_daily_gas_price(['Henry'], dt_prev, dt, pivot=False)
    gas_df  = (gas_raw[gas_raw['hub_name'] == 'Henry'][['dt', 'gas_price']]
               .rename(columns={'gas_price': 'henry_gas_price'}))

    go_raw = GenOutage('SPP').get_genoutage_by_level(dt_prev, dt, var_spec=['f'], area_list=['SPP'])
    go_df  = go_raw[go_raw['baa_zone'] == 'SPP'][['dt', 'hr', 'spp_genoutage_forecast_f']]

    weather_obj = Weather('SPP')
    city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()
    temp_raw    = weather_obj.get_citylevel_temperature_for_ve(dt_prev, dt, city_ids, pivot=False)
    temp_df     = (temp_raw.groupby(['dt', 'hr'])['temperature_degf']
                           .mean().reset_index()
                           .rename(columns={'temperature_degf': 'avg_temp_f'}))

    price_raw = Node(list(SPP_HUB_NODES.keys()), 'SPP').get_price(
        dt, dt, component=['Slack'], type=['DA', 'RT'], granularity='hourly'
    )
    price_raw['dt'] = price_raw['dt'].astype(str)
    price_raw['hr'] = price_raw['hr'].astype(int)

    for df in [wind_df, load_df, go_df, temp_df]:
        df['dt'] = df['dt'].astype(str)
        df['hr'] = df['hr'].astype(int)
    gas_df['dt'] = gas_df['dt'].astype(str)

    base = (
        wind_df[['dt', 'hr', 'spp_wind_total_forecast_f']]
        .merge(load_df[['dt', 'hr', 'spp_load_total_forecast_f']], on=['dt', 'hr'], how='outer')
        .merge(go_df,   on=['dt', 'hr'], how='left')
        .merge(temp_df, on=['dt', 'hr'], how='left')
        .merge(gas_df,  on='dt',         how='left')
        .sort_values(['dt', 'hr']).reset_index(drop=True)
    )
    base['B_wind_ramp'] = base['spp_wind_total_forecast_f'].diff()
    base['B_load_ramp'] = base['spp_load_total_forecast_f'].diff()
    base['B_wind_ramp_2'] = base['spp_wind_total_forecast_f'].diff(2)
    base['B_load_ramp_2'] = base['spp_load_total_forecast_f'].diff(2)

    row       = base[(base['dt'] == dt) & (base['hr'] == hour)]
    price_row = price_raw[(price_raw['dt'] == dt) & (price_raw['hr'] == hour)].copy()
    price_row['hub'] = price_row['node_num'].map(SPP_HUB_NODES)

    if row.empty:
        print(f"No data found for {dt} hour {hour}")
        return None

    r   = row.iloc[0]
    rec = {
        'dt':               dt,
        'hr':               hour,
        'wind_f (MW)':      round(r['spp_wind_total_forecast_f'], 1),
        'load_f (MW)':      round(r['spp_load_total_forecast_f'], 1),
        'genoutage_f (MW)': round(r['spp_genoutage_forecast_f'],  1),
        'avg_temp (°F)':    round(r['avg_temp_f'],                1),
        'henry_gas ($/MMBtu)': round(r['henry_gas_price'],        3),
        'wind_ramp (MW/hr)': round(r['B_wind_ramp'],                1),
        'load_ramp (MW/hr)': round(r['B_load_ramp'],                1),
        'wind_ramp_2 (MW/hr)': round(r['B_wind_ramp_2'],                1),
        'load_ramp_2 (MW/hr)': round(r['B_load_ramp_2'],                1),
    }

    for _, pr in price_row.sort_values('node_num').iterrows():
        hub = pr['hub']
        rec[f'{hub}_da_slack']  = round(pr.get('da_slack', float('nan')), 2)
        rec[f'{hub}_rt_slack']  = round(pr.get('rt_slack', float('nan')), 2)

    display(pd.DataFrame([rec]))
    return pd.DataFrame([rec])


# ── Example ───────────────────────────────────────────────
get_hourly_snapshot('2022-12-23', 18)

/tmp/ipykernel_3362251/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),south_hub_da_slack,south_hub_rt_slack
0,2022-12-23,18,10722.4,40623.0,11765.4,10.3,7.28,-930.1,1710.0,-2080.7,2397.0,149.7,1395.17

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),south_hub_da_slack,south_hub_rt_slack
0,2022-12-23,18,10722.4,40623.0,11765.4,10.3,7.28,-930.1,1710.0,-2080.7,2397.0,149.7,1395.17

In [5]:
import sys
sys.path.append('/var/www/python/Prod/nighthawk/')
import pandas as pd
from nighthawk.util.bigquery_functions import download_df_from_bq

PNL_COLS = ['clear_mw', 'profit_total', 'profit_congestion', 'profit_slack']

def _fetch_pnl(start_dt: str, end_dt: str) -> pd.DataFrame:
    query = f"""
        SELECT dt, hr, incdec, strategy, rep_zone, broad_zone,
               SUM(clear_mw)          AS clear_mw,
               SUM(profit_total)      AS profit_total,
               SUM(profit_congestion) AS profit_congestion,
               SUM(profit_slack)      AS profit_slack
        FROM `movetocloud-999.virtual_financials.segment_portfolio_details_SPP`
        WHERE dt BETWEEN '{start_dt}' AND '{end_dt}'
        GROUP BY dt, hr, incdec, strategy, rep_zone, broad_zone
        ORDER BY dt, hr
    """
    df = download_df_from_bq(query)
    df['dt'] = pd.to_datetime(df['dt']).dt.strftime('%Y-%m-%d')
    df['hr'] = df['hr'].astype(int)
    return df


def get_spp_pnl(start_dt: str, end_dt: str, group_by: str = 'daily') -> pd.DataFrame:
    """
    Fetch SPP virtual portfolio PnL summed across all strategies.

    group_by: 'daily'  — one row per dt
              'hourly' — one row per dt x hr
              'raw'    — full detail (strategy / rep_zone / incdec)
    """
    assert group_by in ('daily', 'hourly', 'raw')
    df = _fetch_pnl(start_dt, end_dt)
    if group_by == 'daily':
        return df.groupby('dt', as_index=False)[PNL_COLS].sum()
    elif group_by == 'hourly':
        return df.groupby(['dt', 'hr'], as_index=False)[PNL_COLS].sum()
    return df


def get_pnl_snapshot(date: str, hour: int) -> pd.DataFrame:
    """Return a single-row DataFrame with total PnL for one specific date and hour."""
    df = _fetch_pnl(date, date)
    row = df[df['hr'] == hour][PNL_COLS].sum()
    result = pd.DataFrame([{'dt': date, 'hr': hour, **{c: round(row[c], 2) for c in PNL_COLS}}])
    display(result)
    return result


# Daily PnL (summed across all strategies, one row per dt)
daily = get_spp_pnl('2026-05-01', '2026-05-12', group_by='daily')
display(daily)

# Hourly PnL (one row per dt x hr)
hourly = get_spp_pnl('2026-05-01', '2026-05-12', group_by='hourly')
display(hourly)

# Single dt + hour snapshot
get_pnl_snapshot('2022-12-23', 18)

            dt     clear_mw  profit_total  profit_congestion  profit_slack
0   2026-05-01  1314.123994  10346.707933       -1462.969181  10884.276826
1   2026-05-02  1652.635993  -7083.557217      -12633.139192     21.284947
2   2026-05-03  3990.475993   7572.335125      -11842.373297  16723.520420
3   2026-05-04  2913.842014  -3192.139128       -4567.698330    114.950350
4   2026-05-05  4434.162016  16118.681327        8296.839209   4425.614313
5   2026-05-06  3987.468992  -6386.306198      -23104.017113   -674.526433
6   2026-05-07  3755.137000  15738.199106       19953.350274  -7964.616577
7   2026-05-08  4304.602005  67259.501733       29093.770899  32013.608437
8   2026-05-09  3716.091997  16205.688033        1858.715909  16642.058252
9   2026-05-10  4435.628995   3100.265405        2119.289315    206.546872
10  2026-05-11  2445.745995  15801.618050       31015.130184 -21331.629859
11  2026-05-12  3894.887007  10758.093735       -4994.136422   3146.404895

             dt  hr    clear_mw  profit_total  profit_congestion  profit_slack
0    2026-05-01   1    0.000000      0.000000           0.000000      0.000000
1    2026-05-01   2  159.647999    516.767106           1.068651    278.250245
2    2026-05-01   3  155.144999    466.455470           3.612927    239.142706
3    2026-05-01   4  192.359999    508.910930          14.164024    324.564199
4    2026-05-01   5   55.928000     88.684027           1.266369     90.660056
..          ...  ..         ...           ...                ...           ...
283  2026-05-12  20  303.584000   4922.006249       -1673.332169   6052.511373
284  2026-05-12  21  139.781999    222.990298       -1267.729583   1051.766621
285  2026-05-12  22  178.310000  -2155.851849       -1877.787045   -597.293858
286  2026-05-12  23  148.264000   -763.514208        -667.330491   -334.509082
287  2026-05-12  24  148.011001   -707.721846        -666.170698   -444.299891

[288 rows x 6 columns]

           dt  hr  clear_mw  profit_total  profit_congestion  profit_slack
0  2022-12-23  18      7.09       5328.41             493.17       4666.42

           dt  hr  clear_mw  profit_total  profit_congestion  profit_slack
0  2022-12-23  18      7.09       5328.41             493.17       4666.42

In [6]:
import os
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler

SAVE_PATH   = '/mnt/disks/filedisk1/SPP/VE/spp_hourly_fundamentals.csv'
RF_FEATURES = [
    'wind_f (MW)', 'load_f (MW)', 'genoutage_f (MW)', 'avg_temp (°F)',
    'henry_gas ($/MMBtu)', 'wind_ramp (MW/hr)', 'load_ramp (MW/hr)',
    'wind_ramp_2 (MW/hr)', 'load_ramp_2 (MW/hr)',
]
TARGET = 'SHub_rt_slack'


def find_similar_hours(date: str, hour: int, k: int = 20,
                        dataset_path: str = SAVE_PATH,
                        n_estimators: int = 200) -> pd.DataFrame:
    """
    Train a RandomForest on (fundamentals -> SHub_rt_slack) using all history
    strictly before the given dt/hr, then rank historical hours by RF proximity
    (fraction of trees where a historical row shares the same leaf as the query).

    Returns top-k most similar rows sorted by rf_proximity descending,
    with the query row prepended (rf_proximity = 1.0).
    """
    df = pd.read_csv(dataset_path)
    df['dt'] = df['dt'].astype(str)
    df['hr'] = df['hr'].astype(int)

    # --- strict past-only filter ---
    cutoff    = pd.Timestamp(date) + pd.Timedelta(hours=hour - 1)
    df['_ts'] = pd.to_datetime(df['dt']) + pd.to_timedelta(df['hr'] - 1, unit='h')
    hist      = df[df['_ts'] < cutoff].drop(columns='_ts').reset_index(drop=True)

    # --- query row ---
    query_rows = df[(df['dt'] == date) & (df['hr'] == hour)].drop(columns='_ts', errors='ignore')
    if query_rows.empty:
        print('Query dt/hr not in dataset, fetching live...')
        query_row = get_hourly_snapshot(date, hour)
    else:
        query_row = query_rows.iloc[[0]]

    # --- feature matrix ---
    feat_cols = [c for c in RF_FEATURES if c in hist.columns and c in query_row.columns]
    train_mask = hist[feat_cols].notna().all(axis=1) & hist[TARGET].notna()
    hist_clean = hist[train_mask].reset_index(drop=True)

    X_train = hist_clean[feat_cols].values
    y_train = hist_clean[TARGET].values
    X_query = query_row[feat_cols].fillna(0).values

    # --- train RF ---
    rf = RandomForestRegressor(n_estimators=n_estimators, random_state=42,
                               n_jobs=-1, max_features='sqrt')
    rf.fit(X_train, y_train)

    print(f'RF trained on {len(X_train)} rows | '
          f'top features: {sorted(zip(rf.feature_importances_, feat_cols), reverse=True)[:3]}')

    # --- RF proximity: fraction of trees sharing the same leaf ---
    # apply() returns shape (n_samples, n_estimators) — leaf index per tree
    hist_leaves  = rf.apply(X_train)          # (n_hist, n_trees)
    query_leaves = rf.apply(X_query)          # (1,      n_trees)
    proximity    = (hist_leaves == query_leaves).mean(axis=1)  # (n_hist,)

    # --- top k by proximity ---
    k = min(k, len(hist_clean))
    top_idx  = np.argsort(proximity)[::-1][:k]
    neighbours = hist_clean.iloc[top_idx].copy()
    neighbours.insert(0, 'rf_proximity', proximity[top_idx].round(4))
    neighbours = neighbours.sort_values('rf_proximity', ascending=False).reset_index(drop=True)

    # --- remove any row from the query date before prepending query row ---
    neighbours = neighbours[neighbours['dt'] != date].sort_values('rf_proximity',ascending=False)
    # neighbours = neighbours.sort_values('SHub_rt_slack', ascending=False).groupby('dt').head(3).sort_values('SHub_rt_slack', ascending=False)
    # --- prepend query row ---
    q = query_row.copy()
    q.insert(0, 'rf_proximity', 1.0)
    result = pd.concat([q, neighbours], ignore_index=True)
    return result


# ── Example ───────────────────────────────────────────────
find_similar_hours('2026-02-05', 17, k=20)

RF trained on 53458 rows | top features: [(np.float64(0.2462259813613005), 'avg_temp (°F)'), (np.float64(0.15052681429048678), 'genoutage_f (MW)'), (np.float64(0.1383914165600613), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-02-05,17,14289.63,32834.0,10650.1,59.500000,6.43,-1461.28,295.0,-2410.89,11.0,28.1054,404.1851,206.440001,-62365.938848,387.063636,-65353.675389
1,0.170,2022-07-01,6,14438.65,30901.0,8863.1,73.166667,6.46,-1117.83,138.0,-2486.89,-172.0,30.8206,45.4116,23.939000,-40.729554,74.293929,-263.847374
2,0.075,2022-08-16,6,13548.89,32258.0,6419.1,74.166667,8.55,-1221.32,342.0,-2240.43,31.0,40.2045,55.4238,103.304000,957.512408,908.283454,-579.449514
3,0.045,2022-07-25,6,14579.86,33429.0,7723.6,75.833333,8.24,-1078.63,420.0,-2080.29,51.0,36.4565,49.6445,61.907000,-192.575932,-491.847419,-21.042240
4,0.045,2022-04-13,19,14265.99,29406.0,21813.5,52.333333,6.56,-1165.66,-29.0,-2153.31,-81.0,50.7048,44.5023,109.996001,1498.184027,1851.563093,-600.867565
5,0.045,2022-09-29,10,14386.65,28338.0,16650.0,59.000000,6.60,-1142.15,482.0,-1888.43,831.0,40.2965,62.2358,156.316001,244.029452,3065.127021,-3467.083809
6,0.040,2022-04-25,12,14301.43,28245.0,24450.6,52.333333,6.55,-1507.18,-42.0,-2526.24,126.0,41.8679,24.2558,117.336000,5086.091929,5225.552505,-458.295572
7,0.040,2022-12-19,12,13647.13,34908.0,14665.5,40.500000,6.59,-1428.13,-398.0,-3147.18,-656.0,62.9655,55.5540,54.907000,259.616920,177.717612,-65.472462
8,0.040,2022-06-18,8,13801.18,30728.0,9573.1,75.500000,7.34,-1470.64,1218.0,-2445.80,1102.0,39.2255,47.2523,39.387000,893.380030,880.272826,-203.056099
9,0.035,2022-07-01,5,15556.48,30763.0,8863.1,73.500000,6.46,-1369.06,-310.0,-2613.74,-958.0,23.0436,47.1452,22.901000,-197.759024,-1.283994,-348.660561
10,0.030,2022-08-07,8,16373.07,33141.0,5924.3,77.500000,8.19,-1391.65,535.0,-2421.34,193.0,29.0272,23.2598,102.561000,647.493528,1043.151296,-679.204912
11,0.030,2026-02-02,4,12089.31,34458.0,10458.9,32.500000,7.26,-515.10,244.0,-1044.88,90.0,44.7348,55.4103,158.435000,2209.953290,2426.908601,-704.036636
12,0.030,2022-05-21,18,14249.01,29408.0,16884.5,59.000000,7.97,-182.99,-44.0,-730.14,10.0,65.8837,15.3695,54.521000,-2419.236447,-259.294732,-2246.256111
13,0.030,2022-07-11,6,14259.17,31124.0,7016.0,72.000000,6.39,-562.91,368.0,-970.77,-9.0,25.5683,35.4123,91.864999,943.127660,501.868524,373.694140
14,0.025,2022-11-30,3,12682.94,28838.0,17411.3,27.500000,6.03,-990.99,142.0,-2195.50,30.0,38.2431,41.2625,59.715001,-399.727139,-498.464306,64.347863
15,0.025,2022-02-03,17,12894.79,37047.0,9851.6,15.666667,6.44,-390.24,329.0,-703.59,91.0,62.8924,26.9385,17.856000,127.536238,542.122922,-423.234842
16,0.020,2022-11-30,2,13673.93,28696.0,17411.3,28.500000,6.03,-1204.51,-112.0,-2623.53,-732.0,35.2499,35.2607,42.746001,-337.122906,-311.007940,-82.342793
17,0.020,2022-05-25,19,14982.28,29109.0,13435.6,59.833333,8.77,-1504.48,-181.0,-2137.42,-224.0,49.5568,13.9227,89.243001,2249.082716,1682.893954,402.486540
18,0.020,2022-11-19,10,14273.60,33620.0,21417.1,29.000000,6.06,-1700.89,-183.0,-2992.81,93.0,59.8727,53.3778,82.652000,2827.808927,2822.942930,-154.877035

In [7]:
dt_hr_list = [(bid_dt, hr) for hr in range(1, 25)]

all_results = {}
avg_rt_slack_list = []
dangerous_hours = []
avg_da_slack_list=[]

for dt, hr in dt_hr_list:
    print(f'\n=== {dt} hr {hr} ===')
    result = find_similar_hours(dt, hr, k=20)
    all_results[(dt, hr)] = result
    display(result[:5])

    neighbours = result[result['dt'] != dt]
    avg_slack = neighbours['SHub_rt_slack'].mean()
    avg_rt_slack_list.append({'dt': dt, 'hr': hr, 'avg_rt_slack': round(avg_slack, 2)})
    avg_slack = neighbours['SHub_da_slack'].mean()
    avg_da_slack_list.append({'dt': dt, 'hr': hr, 'avg_da_slack': round(avg_slack, 2)})
    

    if (neighbours['SHub_rt_slack'] > 150).any():
        dangerous_hours.append({'dt': dt, 'hr': hr, 'avg_rt_slack': round(avg_slack, 2)})

print('\n=== Avg RT Slack by Hour ===')
display(pd.DataFrame(avg_rt_slack_list))
print('\n=== Avg DA Slack by Hour ===')
display(pd.DataFrame(avg_da_slack_list))

print('\n=== Dangerous Hours (similar dates with rt_slack > 150) ===')
display(pd.DataFrame(dangerous_hours) if dangerous_hours else 'None')

=== 2026-05-30 hr 1 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_3362251/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-05-30,1,21145.5,35370.0,19284.4,73.0,3.08,417.4,-1232.0,1056.7,-3148.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-05-30,1,21145.50,35370.0,19284.4,73.000000,3.08,417.40,-1232.0,1056.70,-3148.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.085,2025-05-13,22,20853.97,35508.0,24553.5,76.500000,3.20,1566.82,-1334.0,2402.55,-2413.0,25.0701,21.9729,161.866999,635.894937,956.971858,-508.317751
2,0.050,2023-10-02,22,21228.98,35677.0,19357.1,77.333333,2.69,1097.94,-1957.0,2367.00,-3311.0,29.9795,18.1064,112.285000,483.600030,573.010788,-331.028958
3,0.045,2025-05-19,21,21439.77,34490.0,22357.5,74.000000,3.07,156.55,-868.0,605.56,-1729.0,30.9905,81.6022,372.362998,-1669.889618,14152.079328,-16638.365290
4,0.040,2025-06-03,20,21845.35,34961.0,15166.1,70.500000,2.98,-1208.81,-1006.0,-1864.07,-1752.0,35.4129,11.0790,291.797999,2562.438037,1516.252697,863.983577

=== 2026-05-30 hr 2 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_3362251/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-05-30,2,21406.3,33969.0,19442.8,72.5,3.08,260.8,-1401.0,678.2,-2633.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-05-30,2,21406.30,33969.0,19442.8,72.5,3.08,260.80,-1401.0,678.20,-2633.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.095,2025-05-19,21,21439.77,34490.0,22357.5,74.0,3.07,156.55,-868.0,605.56,-1729.0,30.9905,81.6022,372.362998,-1669.889618,14152.079328,-16638.365290
2,0.045,2025-05-19,22,21232.27,33660.0,22357.5,73.0,3.07,-207.50,-830.0,-50.95,-1698.0,27.4351,68.3160,297.474999,4275.088005,11953.410664,-8220.268594
3,0.045,2026-03-17,13,19970.17,34924.0,21591.2,41.5,3.11,-348.82,-1177.0,-639.76,-2409.0,17.5197,15.2619,283.751000,2373.080138,1826.012130,-509.784756
4,0.040,2025-05-19,23,20940.11,31857.0,22357.5,70.5,3.07,-292.16,-1803.0,-499.66,-2633.0,23.5623,14.5322,282.942999,2938.618358,2041.385566,643.776425

=== 2026-05-30 hr 3 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_3362251/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-05-30,3,21107.7,33065.0,19443.4,71.5,3.08,-298.6,-904.0,-37.8,-2305.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-05-30,3,21107.70,33065.0,19443.4,71.5,3.08,-298.60,-904.0,-37.80,-2305.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.115,2025-05-19,22,21232.27,33660.0,22357.5,73.0,3.07,-207.50,-830.0,-50.95,-1698.0,27.4351,68.3160,297.474999,4275.088005,11953.410664,-8220.268594
2,0.050,2025-05-19,23,20940.11,31857.0,22357.5,70.5,3.07,-292.16,-1803.0,-499.66,-2633.0,23.5623,14.5322,282.942999,2938.618358,2041.385566,643.776425
3,0.045,2026-03-17,15,20095.42,33377.0,21593.7,47.5,3.11,134.66,-935.0,125.25,-1547.0,12.4108,11.6713,216.240000,3375.324659,3216.436296,-618.680702
4,0.045,2025-05-19,21,21439.77,34490.0,22357.5,74.0,3.07,156.55,-868.0,605.56,-1729.0,30.9905,81.6022,372.362998,-1669.889618,14152.079328,-16638.365290

=== 2026-05-30 hr 4 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_3362251/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-05-30,4,20769.2,32432.0,19442.8,71.5,3.08,-338.6,-633.0,-637.2,-1537.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-05-30,4,20769.20,32432.0,19442.8,71.500000,3.08,-338.60,-633.0,-637.20,-1537.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.080,2023-03-20,12,21234.05,32304.0,18771.0,47.000000,2.41,-164.63,-799.0,-608.83,-1577.0,20.1633,18.4780,179.801000,758.462674,704.679132,-444.215968
2,0.060,2023-05-11,20,19867.70,32849.0,22221.1,72.500000,2.12,-271.87,-614.0,-419.59,-1029.0,20.2786,16.9470,170.268001,1225.994794,1241.702158,-329.271170
3,0.055,2023-05-10,22,20858.55,32160.0,20443.4,72.833333,2.21,554.41,-912.0,1146.49,-1496.0,21.0144,18.9236,111.058000,729.668497,718.909141,-78.164489
4,0.045,2023-05-11,21,19574.92,32388.0,22221.1,71.166667,2.12,-292.78,-461.0,-564.65,-1075.0,19.7557,20.4043,154.352001,-531.463738,-533.055834,-299.481374

=== 2026-05-30 hr 5 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_3362251/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-05-30,5,20614.1,32136.0,19443.4,69.5,3.08,-155.0,-296.0,-493.6,-929.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-05-30,5,20614.10,32136.0,19443.4,69.500000,3.08,-155.00,-296.0,-493.60,-929.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.045,2026-03-17,17,19768.40,32835.0,21496.9,52.500000,3.11,-224.59,-20.0,-327.02,-542.0,16.1107,9.9967,379.122000,3876.487100,1518.872827,904.626159
2,0.045,2023-05-11,21,19574.92,32388.0,22221.1,71.166667,2.12,-292.78,-461.0,-564.65,-1075.0,19.7557,20.4043,154.352001,-531.463738,-533.055834,-299.481374
3,0.035,2023-05-11,20,19867.70,32849.0,22221.1,72.500000,2.12,-271.87,-614.0,-419.59,-1029.0,20.2786,16.9470,170.268001,1225.994794,1241.702158,-329.271170
4,0.030,2025-03-17,13,20741.22,30359.0,24291.1,65.000000,3.92,193.32,-353.0,-961.40,-900.0,17.5209,18.6959,78.996000,5174.591104,5173.223136,-157.676205

=== 2026-05-30 hr 6 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_3362251/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-05-30,6,20321.0,32171.0,19441.1,69.5,3.08,-293.1,35.0,-448.1,-261.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-05-30,6,20321.00,32171.0,19441.1,69.5,3.08,-293.10,35.0,-448.10,-261.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.075,2026-03-17,17,19768.40,32835.0,21496.9,52.5,3.11,-224.59,-20.0,-327.02,-542.0,16.1107,9.9967,379.122000,3876.487100,1518.872827,904.626159
2,0.030,2023-05-11,19,20139.57,33463.0,22422.8,73.5,2.12,-147.72,-415.0,86.41,-311.0,21.1160,13.3699,109.796000,-71.522428,75.762839,-329.370143
3,0.030,2024-11-26,21,20338.87,32013.0,20025.9,42.5,2.77,-26.47,-299.0,282.63,-451.0,22.8602,29.0636,271.100999,3095.753156,3872.116992,-1084.954717
4,0.025,2025-03-04,11,20118.01,31821.0,16148.4,57.0,3.81,-342.03,-75.0,-654.84,-93.0,24.1964,24.4119,127.709001,-192.653949,-166.937850,-178.739233

=== 2026-05-30 hr 7 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_3362251/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-05-30,7,19805.9,32373.0,19606.0,69.5,3.08,-515.1,202.0,-808.2,237.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-05-30,7,19805.90,32373.0,19606.0,69.5,3.08,-515.10,202.0,-808.20,237.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.125,2026-03-17,18,19218.35,33031.0,21498.2,52.5,3.11,-550.05,196.0,-774.64,176.0,24.2560,13.6251,384.205000,5162.634029,1176.767878,2445.776570
2,0.085,2025-11-17,17,19689.71,32925.0,26268.3,70.5,3.49,-1198.86,234.0,-1180.46,249.0,34.4902,17.1797,176.733000,1841.969783,477.974627,1011.713987
3,0.050,2025-11-17,13,20341.47,32290.0,26506.5,65.0,3.49,-67.03,210.0,-480.35,321.0,18.1261,15.8000,337.730000,148.374964,77.170677,-631.733881
4,0.030,2025-05-20,18,18756.07,34499.0,22045.6,73.0,3.01,-1000.34,39.0,-1368.18,513.0,35.7979,27.3081,289.108999,6256.390638,5110.715691,808.870732

=== 2026-05-30 hr 8 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_3362251/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-05-30,8,18787.2,33063.0,19605.6,68.5,3.08,-1018.7,690.0,-1533.8,892.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.00,2026-05-30,8,18787.20,33063.0,19605.6,68.5,3.08,-1018.70,690.0,-1533.80,892.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.14,2026-03-17,19,18461.36,33572.0,21589.7,52.5,3.11,-756.99,541.0,-1307.04,737.0,36.9194,22.0042,285.520000,4246.060220,-220.073154,3209.022804
2,0.07,2025-05-20,18,18756.07,34499.0,22045.6,73.0,3.01,-1000.34,39.0,-1368.18,513.0,35.7979,27.3081,289.108999,6256.390638,5110.715691,808.870732
3,0.06,2025-10-03,9,16714.61,32409.0,19378.7,67.0,3.32,-969.08,890.0,-1317.49,1868.0,25.8990,31.6845,140.657000,-7537.946516,-7178.894969,-443.820839
4,0.05,2025-11-17,18,18693.43,33317.0,26447.6,70.0,3.49,-996.28,392.0,-2195.14,626.0,47.5189,21.5685,136.899000,3376.581799,1525.880469,1568.252149

=== 2026-05-30 hr 9 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_3362251/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-05-30,9,17435.9,34496.0,19647.9,70.5,3.08,-1351.4,1433.0,-2370.0,2123.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-05-30,9,17435.90,34496.0,19647.9,70.5,3.08,-1351.40,1433.0,-2370.00,2123.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.065,2025-06-17,9,16435.09,34487.0,13603.0,75.0,2.89,-1591.71,1514.0,-2717.07,2907.0,29.9533,41.4444,89.274,1081.871045,361.077527,686.304685
2,0.055,2024-09-19,9,17639.13,35077.0,16232.3,74.0,2.33,-1396.91,985.0,-2413.57,2018.0,21.9458,20.4653,42.117,272.340867,264.072884,-124.087241
3,0.050,2025-06-25,8,17315.61,34955.0,11935.4,74.0,3.31,-1275.73,1640.0,-1970.06,2706.0,25.4239,38.2817,68.416,1340.455561,1094.766467,108.472835
4,0.045,2026-03-13,8,17466.51,34121.0,18662.8,46.0,3.27,-1764.09,1367.0,-3951.92,3283.0,26.3724,18.4812,59.707,-299.745541,66.337912,-354.230078

=== 2026-05-30 hr 10 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_3362251/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-05-30,10,16841.9,36307.0,19459.0,73.0,3.08,-594.0,1811.0,-1945.3,3244.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-05-30,10,16841.90,36307.0,19459.0,73.0,3.08,-594.00,1811.0,-1945.30,3244.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.075,2024-12-12,7,16432.38,36296.0,17160.3,29.0,3.11,-832.72,2104.0,-1471.94,3417.0,61.8378,101.1410,106.572,-3390.261137,-2899.118039,-676.781806
2,0.060,2025-06-17,10,15541.71,36164.0,13331.0,77.0,2.89,-893.38,1677.0,-2485.09,3191.0,31.6574,35.2415,65.054,332.372418,103.344187,154.716161
3,0.055,2025-06-25,9,16492.44,36832.0,12226.9,76.5,3.31,-823.17,1877.0,-2098.90,3517.0,30.9393,22.3843,54.254,565.451854,780.006043,-320.834620
4,0.045,2023-09-29,11,18340.42,34433.0,17962.6,78.0,2.74,-741.86,1871.0,-2269.73,3296.0,43.6087,23.8357,37.430,188.298133,344.798803,-247.112827

=== 2026-05-30 hr 11 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_3362251/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-05-30,11,16876.4,38128.0,19458.8,77.5,3.08,34.5,1821.0,-559.5,3632.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-05-30,11,16876.40,38128.0,19458.8,77.500000,3.08,34.50,1821.0,-559.50,3632.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.065,2025-06-17,11,15486.10,37976.0,13146.0,80.000000,2.89,-55.61,1812.0,-948.99,3489.0,34.2428,20.2489,69.594,-256.917058,589.812758,-933.248660
2,0.060,2025-06-25,10,16979.16,38687.0,11687.9,79.000000,3.31,486.72,1855.0,-336.45,3732.0,31.8452,26.0422,103.364,701.340457,1026.057769,-517.312232
3,0.050,2025-10-01,13,13211.90,38072.0,17067.9,82.000000,3.13,-23.04,1844.0,245.73,3640.0,38.2981,33.8262,187.505,7978.465623,7989.460850,-562.006943
4,0.050,2023-09-29,12,18418.14,36430.0,17962.6,81.333333,2.74,77.72,1997.0,-664.14,3868.0,52.5397,45.9226,41.553,-22.011553,52.698753,-187.378563

=== 2026-05-30 hr 12 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_3362251/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-05-30,12,17021.6,39866.0,19458.8,79.5,3.08,145.2,1738.0,179.7,3559.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-05-30,12,17021.60,39866.0,19458.8,79.5,3.08,145.20,1738.0,179.70,3559.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.115,2025-06-17,12,15708.49,39615.0,13146.0,82.0,2.89,222.39,1639.0,166.78,3451.0,37.0512,22.1603,95.328,-879.831040,239.297845,-1252.065148
2,0.055,2025-10-01,14,12825.78,39793.0,17088.9,83.0,3.13,-386.12,1721.0,-409.16,3565.0,43.6920,28.2171,149.949,-967.983492,139.979746,-1431.378541
3,0.055,2025-06-25,10,16979.16,38687.0,11687.9,79.0,3.31,486.72,1855.0,-336.45,3732.0,31.8452,26.0422,103.364,701.340457,1026.057769,-517.312232
4,0.045,2024-09-17,13,15415.16,39308.0,19071.1,80.0,2.20,354.41,1709.0,599.26,3374.0,37.4499,48.5630,125.500,-3925.520009,-3024.443993,-1140.655845

=== 2026-05-30 hr 13 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_3362251/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-05-30,13,17824.3,41521.0,19457.2,81.5,3.08,802.7,1655.0,947.9,3393.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-05-30,13,17824.30,41521.0,19457.2,81.5,3.08,802.70,1655.0,947.90,3393.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.090,2024-09-17,14,16093.66,40991.0,19071.1,83.0,2.20,678.50,1683.0,1032.91,3392.0,50.9574,55.9685,191.599000,-15780.246918,-15286.611659,-687.234066
2,0.060,2025-10-03,14,16340.89,41337.0,19207.2,86.0,3.32,885.96,1937.0,2059.02,3929.0,49.7306,46.5662,180.693000,-1386.505926,-1727.969982,171.480421
3,0.045,2025-07-04,12,18594.78,38880.0,8282.7,81.5,3.22,1093.39,1512.0,2032.57,3278.0,24.8181,16.7490,211.888999,2216.713104,2789.246519,-806.620575
4,0.045,2025-06-17,14,16807.11,42561.0,13148.8,84.5,2.89,747.64,1402.0,1098.62,2946.0,47.5643,47.6506,127.593000,285.201057,191.626271,-73.755821

=== 2026-05-30 hr 14 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_3362251/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-05-30,14,19471.9,42969.0,19457.5,83.0,3.08,1647.6,1448.0,2450.3,3103.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-05-30,14,19471.90,42969.0,19457.5,83.0,3.08,1647.60,1448.0,2450.30,3103.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.070,2024-09-17,17,19621.67,43979.0,18719.1,87.5,2.20,1379.55,510.0,2551.40,1595.0,51.3352,71.4958,181.187000,-24408.138697,-23050.732673,-1473.534075
2,0.065,2024-06-07,15,19506.25,41520.0,16455.5,87.0,2.29,1904.88,1241.0,4022.84,2751.0,30.2775,32.4663,416.697001,2127.616515,1807.974280,268.941524
3,0.060,2025-07-04,13,19712.19,40253.0,8186.9,82.0,3.22,1117.41,1373.0,2210.80,2885.0,26.6874,19.5068,312.082999,2156.592553,3022.648764,-1126.634510
4,0.045,2024-09-17,16,18242.12,43469.0,19071.1,86.5,2.20,1171.85,1085.0,2148.46,2478.0,51.8059,65.9981,176.270000,-26064.404112,-25237.133964,-915.190049

=== 2026-05-30 hr 15 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_3362251/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-05-30,15,21571.9,44054.0,19457.5,85.5,3.08,2100.0,1085.0,3747.5,2533.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-05-30,15,21571.90,44054.0,19457.5,85.5,3.08,2100.00,1085.0,3747.50,2533.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.070,2024-09-17,16,18242.12,43469.0,19071.1,86.5,2.20,1171.85,1085.0,2148.46,2478.0,51.8059,65.9981,176.270,-26064.404112,-25237.133964,-915.190049
2,0.065,2024-06-07,16,20979.84,42677.0,16455.5,88.5,2.29,1473.59,1157.0,3378.47,2398.0,33.1195,28.8975,346.131,21.957537,-140.941858,148.971535
3,0.060,2024-09-17,17,19621.67,43979.0,18719.1,87.5,2.20,1379.55,510.0,2551.40,1595.0,51.3352,71.4958,181.187,-24408.138697,-23050.732673,-1473.534075
4,0.055,2024-09-17,18,20940.43,43711.0,18719.1,88.0,2.20,1318.76,-268.0,2698.31,242.0,50.7958,52.5002,193.401,-19249.648714,-19196.748608,-312.497222

=== 2026-05-30 hr 16 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_3362251/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-05-30,16,23357.3,44888.0,19395.0,86.5,3.08,1785.4,834.0,3885.4,1919.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-05-30,16,23357.30,44888.0,19395.0,86.5,3.08,1785.40,834.0,3885.40,1919.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.080,2026-04-16,17,24655.55,41682.0,28900.4,85.0,2.75,1827.78,775.0,3984.28,1664.0,30.3039,11.8526,144.643001,-1002.938848,-332.941097,-691.420923
2,0.075,2025-06-02,16,24987.39,42166.0,15033.4,86.0,2.81,998.89,930.0,2077.74,2103.0,32.9216,19.0466,162.027000,-545.288576,146.643457,-851.088083
3,0.060,2024-09-17,17,19621.67,43979.0,18719.1,87.5,2.20,1379.55,510.0,2551.40,1595.0,51.3352,71.4958,181.187000,-24408.138697,-23050.732673,-1473.534075
4,0.060,2024-09-18,17,20602.30,45663.0,16132.5,91.0,2.33,1244.15,644.0,2505.35,1764.0,63.6249,98.1731,70.217000,372.237698,373.244698,-4.136410

=== 2026-05-30 hr 17 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_3362251/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-05-30,17,24354.1,45405.0,19397.2,86.5,3.08,996.8,517.0,2782.2,1351.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-05-30,17,24354.10,45405.0,19397.2,86.5,3.08,996.80,517.0,2782.20,1351.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.130,2025-06-02,16,24987.39,42166.0,15033.4,86.0,2.81,998.89,930.0,2077.74,2103.0,32.9216,19.0466,162.027000,-545.288576,146.643457,-851.088083
2,0.115,2025-06-02,17,25507.83,42660.0,15034.4,86.5,2.81,520.44,494.0,1519.33,1424.0,37.7623,22.9375,115.319998,-234.609616,89.889119,-456.764998
3,0.050,2025-10-03,18,20005.37,43536.0,18963.2,87.5,3.32,939.38,-553.0,1862.13,-216.0,44.1098,34.5335,135.085000,-1876.841135,-1736.579337,-332.099593
4,0.050,2024-09-17,17,19621.67,43979.0,18719.1,87.5,2.20,1379.55,510.0,2551.40,1595.0,51.3352,71.4958,181.187000,-24408.138697,-23050.732673,-1473.534075

=== 2026-05-30 hr 18 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_3362251/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-05-30,18,24777.9,45399.0,19343.7,86.5,3.08,423.8,-6.0,1420.6,511.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.00,2026-05-30,18,24777.90,45399.0,19343.7,86.5,3.08,423.80,-6.0,1420.60,511.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.11,2025-06-02,18,25783.08,42494.0,15034.4,87.0,2.81,275.25,-166.0,795.69,328.0,36.6053,25.5101,91.209998,365.297398,345.075723,-92.167249
2,0.11,2025-06-02,17,25507.83,42660.0,15034.4,86.5,2.81,520.44,494.0,1519.33,1424.0,37.7623,22.9375,115.319998,-234.609616,89.889119,-456.764998
3,0.07,2025-10-03,18,20005.37,43536.0,18963.2,87.5,3.32,939.38,-553.0,1862.13,-216.0,44.1098,34.5335,135.085000,-1876.841135,-1736.579337,-332.099593
4,0.04,2025-10-03,17,19065.99,44089.0,18998.7,89.0,3.32,922.75,337.0,1855.16,1368.0,51.5755,40.3911,201.066000,4521.475365,3365.427803,881.039384

=== 2026-05-30 hr 19 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_3362251/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-05-30,19,25024.1,44777.0,19346.0,85.5,3.08,246.2,-622.0,670.0,-628.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-05-30,19,25024.10,44777.0,19346.0,85.5,3.08,246.20,-622.0,670.00,-628.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.110,2025-06-02,19,25853.29,41785.0,15034.4,86.0,2.81,70.21,-709.0,345.46,-875.0,36.4404,26.9812,64.277999,715.942587,728.503709,-42.364940
2,0.075,2025-10-04,18,26262.13,40525.0,21497.7,86.0,3.21,160.32,-233.0,544.68,152.0,40.1982,23.6715,292.073001,13621.119303,11521.180597,1272.036359
3,0.070,2025-06-02,18,25783.08,42494.0,15034.4,87.0,2.81,275.25,-166.0,795.69,328.0,36.6053,25.5101,91.209998,365.297398,345.075723,-92.167249
4,0.060,2025-10-03,18,20005.37,43536.0,18963.2,87.5,3.32,939.38,-553.0,1862.13,-216.0,44.1098,34.5335,135.085000,-1876.841135,-1736.579337,-332.099593

=== 2026-05-30 hr 20 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_3362251/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-05-30,20,25009.2,43506.0,19346.3,83.5,3.08,-14.8,-1271.0,231.3,-1893.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-05-30,20,25009.20,43506.0,19346.3,83.5,3.08,-14.80,-1271.0,231.30,-1893.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.095,2025-06-02,20,25713.01,40480.0,15034.4,85.0,2.81,-140.28,-1305.0,-70.07,-2014.0,34.5581,27.6878,85.855999,331.765911,259.269697,56.744388
2,0.080,2025-10-04,19,26272.55,39321.0,21497.7,84.0,3.21,10.42,-1204.0,170.74,-1437.0,32.4101,25.9689,186.966000,4438.292255,3842.701246,138.467794
3,0.050,2026-04-14,19,25985.56,41530.0,27705.8,83.0,2.78,-212.58,-643.0,-247.57,-901.0,36.7525,66.9642,166.146000,18687.305438,15541.991901,2868.664920
4,0.040,2024-07-01,20,25557.14,45624.0,9727.9,87.5,2.39,66.08,-1246.0,647.60,-1633.0,32.6021,26.4888,271.115000,-508.417511,-227.409606,-401.674121

=== 2026-05-30 hr 21 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_3362251/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-05-30,21,25401.3,42311.0,19347.7,81.5,3.08,392.1,-1195.0,377.3,-2466.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-05-30,21,25401.30,42311.0,19347.7,81.5,3.08,392.10,-1195.0,377.30,-2466.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.115,2024-09-17,21,23187.30,40376.0,16828.1,82.0,2.20,630.90,-1215.0,1234.21,-2579.0,38.8606,81.5361,122.490000,-10331.753252,-9036.388445,-1547.757929
2,0.055,2025-10-04,20,26670.31,37941.0,21751.2,81.0,3.21,397.76,-1380.0,408.18,-2584.0,25.6994,21.1200,230.560000,2145.822510,1733.381097,-89.736413
3,0.045,2025-06-17,22,18513.27,39695.0,12669.3,78.5,2.89,344.57,-1213.0,472.80,-2661.0,35.0513,24.7797,74.916000,1181.839833,775.458753,352.669888
4,0.040,2026-04-14,20,25921.05,40660.0,27706.0,80.5,2.78,-64.51,-870.0,-277.09,-1513.0,41.3023,25.0294,145.843999,13352.596421,14019.185457,-1119.869334

=== 2026-05-30 hr 22 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_3362251/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-05-30,22,26333.0,41076.0,19347.9,79.5,3.08,931.6,-1235.0,1323.7,-2430.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-05-30,22,26333.00,41076.0,19347.9,79.5,3.08,931.60,-1235.0,1323.70,-2430.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.105,2024-09-17,21,23187.30,40376.0,16828.1,82.0,2.20,630.90,-1215.0,1234.21,-2579.0,38.8606,81.5361,122.490,-10331.753252,-9036.388445,-1547.757929
2,0.060,2025-06-02,22,26239.94,37796.0,15064.4,80.0,2.81,447.84,-1344.0,526.93,-2684.0,25.7313,23.2716,131.487,323.704336,320.183705,-69.253462
3,0.055,2025-10-04,20,26670.31,37941.0,21751.2,81.0,3.21,397.76,-1380.0,408.18,-2584.0,25.6994,21.1200,230.560,2145.822510,1733.381097,-89.736413
4,0.055,2026-04-16,20,28126.53,40549.0,28804.8,82.0,2.75,863.44,-898.0,1893.91,-1349.0,30.1897,27.4001,154.722,-221.971204,-512.127717,24.066569

=== 2026-05-30 hr 23 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_3362251/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-05-30,23,26949.2,39350.0,19348.2,77.5,3.08,616.2,-1726.0,1547.8,-2961.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-05-30,23,26949.20,39350.0,19348.2,77.5,3.08,616.20,-1726.0,1547.80,-2961.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.125,2024-09-17,22,24030.46,38550.0,16828.1,78.5,2.20,843.16,-1826.0,1474.06,-3041.0,29.6789,63.0937,93.666000,-584.011665,-1034.066089,371.144231
2,0.115,2025-05-14,22,23644.72,38673.0,24013.6,82.0,3.26,1128.31,-1617.0,1889.67,-3013.0,31.9246,33.2309,159.813001,-1478.625174,-1431.288223,-267.927145
3,0.075,2025-10-04,20,26670.31,37941.0,21751.2,81.0,3.21,397.76,-1380.0,408.18,-2584.0,25.6994,21.1200,230.560000,2145.822510,1733.381097,-89.736413
4,0.075,2025-10-03,21,25337.01,38685.0,19144.9,79.0,3.32,2076.64,-1595.0,4042.01,-3247.0,20.4478,9.7465,292.722000,-4264.913698,-4212.654713,-310.826982

=== 2026-05-30 hr 24 ===
Query dt/hr not in dataset, fetching live...

/tmp/ipykernel_3362251/756036728.py:28: DeprecationWarning: Call to deprecated function get_city_details.
  city_ids    = weather_obj.get_city_details(SPP_CITIES)['CityId'].tolist()

,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr)
0,2026-05-30,24,27248.1,37385.0,19348.2,77.5,3.08,298.9,-1965.0,915.1,-3691.0

RF trained on 55781 rows | top features: [(np.float64(0.2546404443089726), 'avg_temp (°F)'), (np.float64(0.1473164504894639), 'genoutage_f (MW)'), (np.float64(0.13547095455338448), 'henry_gas ($/MMBtu)')]

,rf_proximity,dt,hr,wind_f (MW),load_f (MW),genoutage_f (MW),avg_temp (°F),henry_gas ($/MMBtu),wind_ramp (MW/hr),load_ramp (MW/hr),wind_ramp_2 (MW/hr),load_ramp_2 (MW/hr),SHub_da_slack,SHub_rt_slack,clear_mw,profit_total,profit_congestion,profit_slack
0,1.000,2026-05-30,24,27248.10,37385.0,19348.2,77.5,3.08,298.90,-1965.0,915.10,-3691.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.125,2026-04-13,23,27975.87,37386.0,28463.8,76.0,2.65,473.21,-1976.0,839.95,-3277.0,17.3617,-5.2879,152.994,-1047.422193,1367.021455,-2609.924799
2,0.095,2025-10-03,22,26669.70,36871.0,19147.3,77.5,3.32,1332.69,-1814.0,3409.33,-3409.0,11.1566,5.7860,235.424,-4068.576720,-3863.586947,-383.071162
3,0.065,2025-10-04,21,27447.46,36508.0,22011.5,76.5,3.21,777.15,-1433.0,1174.91,-2813.0,18.3630,12.7331,204.488,2534.179784,2017.540602,90.894866
4,0.060,2025-06-21,1,30380.72,37531.0,9695.1,83.0,3.10,80.46,-1985.0,100.14,-3668.0,10.7740,2.2417,67.489,593.780068,316.112492,168.133218

=== Avg RT Slack by Hour ===

            dt  hr  avg_rt_slack
0   2026-05-30   1         21.28
1   2026-05-30   2         20.24
2   2026-05-30   3         19.06
3   2026-05-30   4         23.63
4   2026-05-30   5         24.23
5   2026-05-30   6         21.54
6   2026-05-30   7         33.55
7   2026-05-30   8         19.20
8   2026-05-30   9         26.91
9   2026-05-30  10         65.76
10  2026-05-30  11         33.02
11  2026-05-30  12         35.14
12  2026-05-30  13         42.51
13  2026-05-30  14         42.80
14  2026-05-30  15         33.09
15  2026-05-30  16         39.89
16  2026-05-30  17         42.23
17  2026-05-30  18         33.62
18  2026-05-30  19         36.12
19  2026-05-30  20         35.58
20  2026-05-30  21         35.19
21  2026-05-30  22         35.12
22  2026-05-30  23         21.12
23  2026-05-30  24         10.95

=== Avg DA Slack by Hour ===

            dt  hr  avg_da_slack
0   2026-05-30   1         21.86
1   2026-05-30   2         18.15
2   2026-05-30   3         17.46
3   2026-05-30   4         22.70
4   2026-05-30   5         23.97
5   2026-05-30   6         24.12
6   2026-05-30   7         23.00
7   2026-05-30   8         26.75
8   2026-05-30   9         29.16
9   2026-05-30  10         39.80
10  2026-05-30  11         39.03
11  2026-05-30  12         40.78
12  2026-05-30  13         44.03
13  2026-05-30  14         39.26
14  2026-05-30  15         39.31
15  2026-05-30  16         42.27
16  2026-05-30  17         41.67
17  2026-05-30  18         43.28
18  2026-05-30  19         40.32
19  2026-05-30  20         38.20
20  2026-05-30  21         36.61
21  2026-05-30  22         31.56
22  2026-05-30  23         21.89
23  2026-05-30  24         15.84

=== Dangerous Hours (similar dates with rt_slack > 150) ===

           dt  hr  avg_rt_slack
0  2026-05-30   7          23.0
1  2026-05-30  10          39.8